### ISSUE TITLE
Trezor plugin is disabled when default wallet already exists

### ISSUE THREAD

**Issue by specto** [spesmilo/electrum#1016]
1. Start Electrum for the first time 
2. Create standard wallet
3. Exit
4. Connect Trezor device
5. Start Electrum again

Result: Trezor plugin is disabled in the plugin settings dialog.

Expected Result: Some kind of message informing that the current wallet cannot be used with Trezor.

After moving the default_wallet file the plugin is detected and works just fine.

Electrum version: 2.0b2, OS: Mac OS 10.10.2

**Comment by ecdsa** [comment]
I see no reason to activate the trezor plugin if the current walet file is not a trezor wallet.
or shall we also activate btchip?

**Comment by specto** [comment]
Whenever you connect a device and the software that should work with it is not recognizing it you assume there is something wrong.

I don't know how other hardware wallets behave but it should be the same for them.

**Comment by dabura667** [comment]
@ecdsa I think he is asking for a message to detect Trezor plugged into USB and say "Hey, you can't use Trezor with a non-trezor wallet. Please create a new trezor wallet in order to use it."

Maybe inserting code like this to check for Trezor, and sending a pop-up could be possible...
http://stackoverflow.com/questions/8110310/simple-way-to-query-connected-usb-devices-info-in-python

@specto however, tbh the current flow is easy to understand. No one should think "oh, I can just magically use Trezor with a wallet that I created without Trezor and has nothing to do with Trezor."... anyone who even vaguely understands what Trezor does will think "ok, I need to create a new wallet to work with Trezor..." which will lead them to the new wallet creation screen, where they will be able to set up and enable the Trezor.

**Comment by ecdsa** [comment]
I understand, but that sounds like a bad design. 
we cannot activate all plugins by default, just because one of them might be useful at that moment.

**Comment by specto** [comment]
@dabura667 Thank you for clarifiying.

I was only trying to point out it is bad user experience. If it's hard to implement of course you have all the reasons to ignore this request. Most probably you have more important things to focus on.
