### ISSUE TITLE
Electrum BIP32 key derivation?

### ISSUE THREAD

**Issue by olalonde** [spesmilo/electrum#1145]
I've been trying to generate addresses from my wallet using the master public key from my Electrum 2.0.4 wallet (xpub....). After entering the xpub string into http://www.bip32.org, it is not generating addresses that are listed in my addresses tab. How does Electrum does key generation?

**Comment by olalonde** [comment]
Ooops, just had to use this custom path: `m/0/0`

**Comment by Sroose** [comment]
Hi, I have a similar question: Electrum generated a seed for my example wallet: "kit zebra shiver emotion decade enlist pigeon space foster cost mesh library".
The attached xprv is xprv9s21ZrQH143K255hxTDneZyLL3ZhpMEX1gTurQViqcCsLc6YKCTc8kUqLHSUuH9bnNdrJdjSbfk1EAiYNnQwGwwFphR2DNBcEDLwgWruVEd

When I put the phrase in bip32.org, I get totally different values, hence also different addresses. Is this due to a different standard?

My main concern is I would like to have a 12-words phrase that later can be recovered regardless of tooling.
