### ISSUE TITLE
blockchain unconfirmed.

### ISSUE THREAD

**Issue by AidPearce** [spesmilo/electrum#1352]
Hi all

Again some trouble. For some reason it already more than a day, the two transactions are displayed as unconfirmed.
What could it be?

![sc-1](https://cloud.githubusercontent.com/assets/12866261/8579136/7a88c128-25bb-11e5-881f-8bd015db365c.png)

![sc-2](https://cloud.githubusercontent.com/assets/12866261/8579138/820497b0-25bb-11e5-9303-f4fd8c506af3.png)

**Comment by CodingAnarchy** [comment]
https://bitcoin.org/en/alert/2015-07-04-spv-mining

**Comment by AidPearce** [comment]
Looked and read the links, and all the same and have not understood, wait for confirmation, or these funds are lost forever?

Yet who have a file header last blockchain, on Electrum?

**Comment by AidPearce** [comment]
A couple of hours ago, all funds that were unconfirmed returned to. In blockchain displayed as if these transactions (unconfirmed) was not, and the entire amount of on a purse. Now I go again to blockchain, transaction data appeared again (unconfirmed).
On Electrum wallet for all this time so nothing has changed. How transactions were pending, and so they remain.

**Comment by dabura667** [comment]
I have no clue what you're saying... I'm sorry.

Basically, right now a lot of people are sending transactions, so Bitcoin is very slow.

If you want to send a transaction, set a higher fee in preferences. 0.001 BTC should be enough.

**Comment by dabura667** [comment]
https://blockchain.info/ja/tx/e18abdafae85ea85d532169aea98bd63eb20ae913d95bad8cd97c4e2ff73bf5d

This transaction has a low fee. Due to recent network congestion, this fee might be ignored due to spam filters some miners are adding.

https://blockchain.info/ja/tx/6e1a983158d8fbc1959a46f670466795dc74cf00d4da42ed6e9914b3addf7d00

This transaction uses the first transaction as an input, so it can not confirm until both confirm.

looking at the other trailing transactions, you have 4 chained unconfirms @ 2139 bytes with a total of all 4 fees of 36000 satoshis. Which comes to a total of 16800 satoshis per kB in fees.

This is below eligius CPFP fee rules, so I might suggest chaining another transaction with a large fee, like 0.001 BTC and that should get the chain of transactions picked up by some pool using CPFP.

**Comment by AidPearce** [comment]
Yes, I have nothing to send. Funds themselves go (the ones that I just posted, but they did not go), hang pending confirmation blockchain for a day or two, then back again to the purse, then do go and everything is repeated.

**Comment by AidPearce** [comment]
dabura667, what do you propose to do?

**Comment by ecdsa** [comment]
switch to another server that was rebooted recently (no-ip.org reboots everyday iirc)

**Comment by AidPearce** [comment]
Switchable...

![not connected](https://cloud.githubusercontent.com/assets/12866261/8595275/54dcbcf4-2651-11e5-8030-b974c24c46b4.png)

![not connected1](https://cloud.githubusercontent.com/assets/12866261/8595278/5b9b2b34-2651-11e5-99ad-8808c2968187.png)

![not connected2](https://cloud.githubusercontent.com/assets/12866261/8595283/6229bcfe-2651-11e5-9650-3908bc23ece3.png)

On the other servers...

![not connected3](https://cloud.githubusercontent.com/assets/12866261/8595368/8a674434-2651-11e5-9d22-bbbfa7f6a5ab.png)

![not connected4](https://cloud.githubusercontent.com/assets/12866261/8595371/8edfe5a2-2651-11e5-892b-626d23d0973f.png)

![not connected5](https://cloud.githubusercontent.com/assets/12866261/8595399/93fde20a-2651-11e5-8e9b-b73cf000c934.png)

**Comment by AidPearce** [comment]
![block](https://cloud.githubusercontent.com/assets/12866261/8595644/8e8c88f2-2652-11e5-8a21-f8ee3318e91e.png)

**Comment by AidPearce** [comment]
All matter is closed.
Gone are transaction.
