### ISSUE TITLE
Electrum try to synchronize since 4 days

### ISSUE THREAD

**Issue by FilestormGER** [spesmilo/electrum#1454]
Hey guys,

![screenshot - 19_09](https://cloud.githubusercontent.com/assets/14361368/9976847/0d5693e0-5ef1-11e5-80fc-1984f665479c.png)
since 4 days Electrum try to synchronize but nothing happens! Status over hours and hours ist still "synchronisize".
also since 4 days i have one "pending-transfer" in my wallet with a amount from 0,0 - at Blockchain details to this transfer says: "Transaction rejected by our node. Reason: Transaction was previously accepted but has been pruned from our database."
Maybe this will be the issue for the error..!?

A few of transfers are missing since 4 days also!

**Comment by kyuupichan** [comment]
Have you tried closing and restarting?  One cause of this is fixed in electrum in git and will be in 2.5.

**Comment by FilestormGER** [comment]
of course, i´ve tried to restart, but nothing changed. elecrtrum still try to synchronize but no data-transfer over 2 hours.

**Comment by ecdsa** [comment]
try using another server

**Comment by FilestormGER** [comment]
hey ecdsa,
i´ve tried every single server, nothing happens :-(  electrum still try to sync/connect

**Comment by FilestormGER** [comment]
no more ideas guys??? 
i gonna delete the prog and say goodbye to my btc´s - Thank you !

**Comment by ecdsa** [comment]
there might be a problem with your configuration file.
you could try to delete it.
also, use the latest version, not 2.3.2

**Comment by gubatron** [comment]
same thing started happening over here since yesterday.
Electrum 2.4.4, running on Mac.

is there a blocking call when opening the network dialog that could be done instead on a background thread, when electrum is in this state I cannot attempt to change the server as the UI thread stops responding indefinitely. For me, the only way to open the Network dialog now, is to completly disconnect my computer from the internet to trigger the "Not connected" state, and then I can proceed to open the network dialog, this probably shouldn't be the case.

I bet an expert in the codebase could fix possible freeze quickly.

**Comment by FilestormGER** [comment]
Hi,
after trying to update to a new version a few times, now it seem that´s all worked fine!
THX!

File
