### ISSUE TITLE
Store contacts in wallet file

### ISSUE THREAD

**Issue by leafcutterant** [spesmilo/electrum#1482]
It would make more sense, rather than having all wallets (at times, all users...) display the same contacts. What do you think?

**Comment by ecdsa** [comment]
why?

**Comment by murder77** [comment]
refeer to me with ideas ... or n'´t stans

2015-10-16 2:35 GMT-05:00 ThomasV <notifications@github.com>:

**Comment by leafcutterant** [comment]
@ecdsa Because it's more convenient. To move around one's data, it's logical to move the wallet file. Furthermore, contacts are personal. It makes no sense to use the same contacts with every wallet, that's like displaying the same e-mail contacts for every person who uses a computer for sending e-mails.

But even if it's just one person with multiple wallets, those wallets are created for different purposes. It would feel strange e.g. to store your grandma's address and your darknet market deposit address at the same place. Compartmentalization means more security in this case, I can't see why contacts should be shared.

**Comment by ecdsa** [comment]
anyone else thinks that it's more convenient?

**Comment by dabura667** [comment]
tbh I think the "contacts" function just encourages address re-use and increases the chance that a user will send to an address that no longer works (like when bitstamp's deposit addresses were compromised.)

I would be all for including contacts in the individual wallet file once BIP47 payment codes and ECDH keypair generation is implemented. (Wishful thinking) But that is primarily due to the fact that the contact's address generation would require knowledge of the private key of your wallet.

As for storing the current contacts feature in the wallet file... I'd say super low priority ACK, If it can be done relatively easily and someone wants to take the time to do it, it couldn't hurt I don't think. It does seem like a marginal improvement of UX. (though the feature itself is not something I like: see above)

**Comment by ecdsa** [comment]
Maybe this could be part of a broader change.
I am currently experimenting with the idea of merging 'contacts' and 'invoices'. I will try that in the kivy/android GUI
