### ISSUE TITLE
Cannot install electrum without root priviledges with `pip --user`

### ISSUE THREAD

**Issue by a3nm** [spesmilo/electrum#1486]
I'm trying to install electrum locally as an unpriviledged user, without using root. However, running `pip install --user` fails because it tries to write to `/usr/share/applications/`.

To reproduce, run:

    pip install --user https://download.electrum.org/Electrum-2.5.tar.gz

After some steps, it fails as follows:

    copying electrum.desktop -> /usr/share/applications/
    error: [Errno 13] Permission denied: '/usr/share/applications/electrum.desktop'

I think this should be fixed: it's good policy to allow users to install electrum if they don't have root priviledges (or don't want to use them).

**Comment by miohtama** [comment]
This happens because Electrum's Python package installer tries to touch system files.

https://github.com/spesmilo/electrum/blob/master/setup.py#L19

`sudo pip install` is very unreliable way to install packages or applications and is discouraged by Python community. Furthermore it has been (rightfully) disabled on latest OSXs on operating system level by Apple:

* Python packaging guide: https://packaging.python.org/en/latest/installing.html

* http://stackoverflow.com/a/33004920/315168

Generally, this kind of files should not be installed with setup.py run. Python packages are meant to be safe to use in any kind of Python installations, including on-system wide installations and virtualenvs. Creating system icons should be left to operating system native package manager, like Deb (Ubuntu) or whatever you download from App Store on OSX.

**Comment by ecdsa** [comment]
I cannot reproduce that issue; ``` pip install --user ``` works for me.
could this be caused by a different version of pip?

**Comment by miohtama** [comment]
`/usr/share/applications/` should not be writable by a user. Either you are using different operating system, you have changed the default permissions of your operating system folders or you are running as root.

**Comment by abitfan** [comment]
@ecdsa you are probably using a virtual env
The problem seems to be with sys.prefix, removing that correctly installs the app file in ~/.local/share/applications however when installed as root the file will be added to /usr/local/share/applications

**Comment by ecdsa** [comment]
I am not using a virtualenv
```pip install --user``` installs in ```~/.local/lib/python2.7/site-packages/```

**Comment by a3nm** [comment]
I was using:

    pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

(from Debian testing: 1.5.6-7)

I manually installed pip 7.1.2 and the install went smoothly.

So indeed it looks like my problem was just caused by an outdated pip. I don't know whether things could be improved by failing with a more useful error message when the pip being used is too old, but otherwise my bug report could just be closed.

Thanks for your insights!
