### ISSUE TITLE
Reenable TLS 1.1 and 1.2 support

### ISSUE THREAD

**Issue by mithrandi** [spesmilo/electrum#1503]
In 4731418af9d47084a2b88dad38bf2d279c392d9b, the OpenSSL method was changed from `PROTOCOL_SSLv23` to `PROTOCOL_TLSv1`. This has the effect of disabling TLS 1.1 and 1.2 protocol support, forcing the protocol version to TLS 1.0 only. I'm not sure if this was done because of a misunderstanding of what `PROTOCOL_SSLv23` does (contrary to the name, it has nothing specifically to do with SSLv2 or SSLv3, and in fact both of those protocols are disabled by default in OpenSSL these days; rather it causes OpenSSL to negotiate the protocol version between client and server, selecting an acceptable version based on the OP_NO_* flags set), or due to some compatibility issue. If the former, then I think the change should be reverted; if the latter, then I think this should at least be well-documented, and some kind of plan devised whereby TLS 1.2 support can be restored.

**Comment by EagleTM** [comment]
PR was #1381
It references https://docs.python.org/2/library/ssl.html
Specifically the table showing which versions in a client (down the side) can connect to which versions in a server (along the top).

Indeed TLS 1.1 and 1.2 are not supported by this. What we really want is to disable SSLv2 and SSLv3 (because v3 is not available on newer openssl on the server side, but clients are requesting it and SSLv2 is way too old). 

Is there an easy way to tell the client to use SSLv23 but to disable SSLv2 / SSLv3?

**Comment by EagleTM** [comment]
Oh OK i see in in the referenced doc "The ciphers parameter sets the available ciphers for this SSL object. It should be a string in the OpenSSL cipher list format." It would be good to have sample code at the relevant section or a PR which recommended ciphers at this time.

**Comment by mithrandi** [comment]
I don't think you can select protocol version by controlling cihpres. To explictly disable SSLv2 and SSLv3, you would do this by constructing a context and adjusting the option flags:
```
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.options |= ssl.OP_NO_SSLv2
context.options |= ssl.OP_NO_SSLv3
sock = context.wrap_socket(sock, ...)
```
This would make sure that SSLv2/3 are disabled even when using an older Python / OpenSSL where this is not the default.

**Comment by ecdsa** [comment]
reverted in 614f3df4b83bf197e60a510269e71f5a32b36661

**Comment by ecdsa** [comment]
ssl.SSSLContext requires python 2.7.9
I will not add it for now, because it would break too many installations.

**Comment by EagleTM** [comment]
From the reference page above:
"The ciphers parameter sets the available ciphers for this SSL object. It should be a string in the OpenSSL cipher list format." 

Can't we make use of "ciphers" or is that a 2.7.9 thing too?

Another thing that'd be important to check: Does this break connectivity for clients which want to use SSLv3 but the server does not support it (because of openssl) or will the connection gracefully upgrade to TLS 1.0?

**Comment by ecdsa** [comment]
I am not sure if the traceback in #1381 is caused by that.. 
I think it's not an Electrum issue, but more a Python issue.
Let's run the risk for now

**Comment by mithrandi** [comment]
`ciphers` controls the available ciphers; while you could disable all SSLv3 ciphers (as certain ciphers are version-specific), if you do this but still allow negotiating SSLv3 protocol version, this will just cause a connection failure due to no acceptable ciphers being negotiated.

Regarding the traceback in #1381, I'm pretty sure this was due to a much older version of this code using `PROTOCOL_SSLv3` (*not* `PROTOCOL_SSLv23`).

**Comment by ecdsa** [comment]
I too think it was a version of the code using `PROTOCOL_SSLv3`
