### ISSUE TITLE
Dust threshold changed in 0.11.1

### ISSUE THREAD

**Issue by torusJKL** [spesmilo/electrum#1550]
If the remaining bitcoins of a payment are considered to be dust then we get the error 64:dust.
This is not user friendly and can confuse new users.

The scenario could be as follow::
- 2700 satosohi is considered to be dust
- the input addresses sum to the amount of 1.00002000 BTC
- the payment is 1 BTC
- the output address (change) would be 0.00002000

Instead of giving the dust error Electrum would ask the user to increase the fee by the amount of the remaining dust (e.g. 0.00002 BTC).
The user can accept it or cancel the payment.

If he accepts than the dust will be automatically added to the fee so that the remainder will be 0.

This does not cover the scenario when a user wants to send an amount that by itself is already dust.

**Comment by ecdsa** [comment]
Electrum already adds dust outputs to the fee.
the dust threashold is 546 satoshis in the current version.
does it need to be changed?

**Comment by torusJKL** [comment]
I added this request from what I understood in the recent forum threads.
e.g. https://bitcointalk.org/index.php?topic=1247379.0
I will try to reproduce it myself.

**Comment by ecdsa** [comment]
Either the OP uses an outdated version of Electrum, or the electrum server has a different definition of dust (unlikely, because 546 has been the norm for a long time).

**Comment by ecdsa** [comment]
apparently it changed again: https://bitcointalk.org/index.php?topic=1214993.0

**Comment by ecdsa** [comment]
best thing will be to add a new RPC
in the short term, I will increase min_relay_fee in the client.

**Comment by ecdsa** [comment]
ok, version 2.5.4 is released, with a higher threshold

**Comment by Anynomouss** [comment]
Dust is managed very crappy in Electrum IMO. 
My transaction includes one large Bitcoin output and one smaller one of 1 Satoshi. In the first place, what is the freedom of money/Bitcoin if you cannot transact it freely. If I am willing to spend dollars for a single dust output I should have that freedom.
Secondly, If 1 Satoshi output are not allowed by any Electrum network, why does the wallet itself allow me set 1 Satoshi as value for an output to begin with. Thirdly, the other output is clearly large, so why does the network reject the transaction, all outputs should be considered, not just one.  Because of this shitty rule/implementation I have to repeat the dance of a large MultiSig wasting a lot peoples time
