### ISSUE TITLE
Feature suggestion: Add encryption for public keys too

### ISSUE THREAD

**Issue by someone235** [spesmilo/electrum#1601]
Let's say I want no one to see which addresses I posses, it would be nice if I'll have an option to encrypt the whole wallet, and not only its private keys.

**Comment by ecdsa** [comment]
this has already been discussed ad nauseam.
If the whole wallet is encrypted, the password must be stored in memory during the whole session, which makes it vulnerable.
If it is a separate password, there will be a large fraction of users who will use the same password for the wallet file and for their private keys/seed, or even no password at all for their seed.

**Comment by ecdsa** [comment]
btw, I am simply following the recommendaions of Bitcoin Core on this.

**Comment by someone235** [comment]
Can you please reference me to a discussion about this?
I don't really get why it's bad that some users will use the same password for the encryption of the private and public key.

**Comment by ecdsa** [comment]
It's bad because the password has to stay in memory for a long time, which makes it much easier for other processes to read it.

People have requested this a few times here on github, just search though past issues. In the end, I wrote a FAQ item in order to have less of them: 
http://docs.electrum.org/en/latest/faq.html#why-can-i-open-the-wallet-without-entering-my-password

Let me know if you have any suggestion to improve the FAQ or to make this info more visible.
