### ISSUE TITLE
BIP44 wallet

### ISSUE THREAD

**Issue by the9ull** [spesmilo/electrum#1604]
I think that Electrum should support BIP44 in the future. I think that interoperability among wallets is important. I imagine a future where I could import my seed in every wallet.
Moreover this multi-account is a great feature too.
Did you discussed in the past about BIP44 and BIP39 implementation? I guess yes. What are the central points?
I think that introduce BIP39 at this point it is not easy for backward compatibility reasons; and for BIP44?
Thank you

**Comment by ecdsa** [comment]
I already discussed BIP44 and BIP39; I do not like them. The authors of BIP39 initially listed me as a co-author of the BIP, and I had to ask to have my name removed from it.

BIP44 creates multiple accounts with hardened derivations.
Here is what I don't like about it:
1. multiple accounts create a more difficult user interface and user experience. I prefer to keep Electrum simple.
2. Electrum already allows you to create multiple wallet files. This covers the functionality of accounts, although with a different seed each time. 
3. If multiple seeds is a problem, we can add support for multiple wallets that share the same seed, using a password protected derivation.
4. if we supported multiple wallet files AND wallets with multiple accounts, we would have a two levels of hierarchy. This would make the user experience much more complex, with no obvious benefit.
5. when people use the same wallet on several devices, a wallet with multiple accounts cannot synchronize itself with other instances without the password. Of course the wallet could detect that a new account is funded, but then it would need to request the password in order to create the next account. I do not feel comfortable with software that requests the users password without the user initiating any action; this seems prone to attacks.

**Comment by ecdsa** [comment]
and concerning BIP39, I believe it was written by monkeys. 
you can listen to my interview for details:

**Comment by ecdsa** [comment]
Note on interoperability: Multibit does not support multiple accounts in BIP44, see https://multibit.org/en/help/hd0.1/how-spv-works.html

**Comment by kyuupichan** [comment]
I agree with ThomasV here.  However restoring a hardware wallet essentially gives you what you want, but we don't want to encourage people to create BIP44 wallets.

**Comment by kyuupichan** [comment]
I'll close this given ThomasV's views.

**Comment by bsbits** [comment]
I would like to re-open this issue.

I will be using Electrum on a server (Linux), and need to generate millions of btc addresses.
A single wallet will not handle that many, can you add an option to create multiple accounts that share the same seed / xpub ?

**Comment by dabura667** [comment]
A single account can hold over 2 billion addresses.

**Comment by bsbits** [comment]
@dabura667 won't it be an issue for a single electrum wallet to manage a very high amount of bitcoin addresses ?

Assuming I restore the wallet on my computer, it won't find the btc till I regenerate the millions of addresses, and this will consume time and resources.

**Comment by dabura667** [comment]
> Assuming I restore the wallet on my computer, it won't find the btc till I regenerate the millions of addresses, and this will consume time and resources.

Which is how the current wallet works. In order to create separate accounts you need to create separate wallet files.

This issue is about creating multiple accounts in one big wallet file which is the same thing effectively as generating a bunch of addresses in one account.

Your issue is wanting multiple wallet files, which is already possible.

**Comment by bsbits** [comment]
Sounds fair, I never thought using BIP44 will consume the same resources as a single wallet.

**Comment by seanc-1** [comment]
Yes I will see about.  The. Upgrade. And if. I was. Inform.  Early. On.  The.  I'm would. Dwelt. With the situation.   As.  Seen. Fit.

**Comment by TayaAfi** [comment]
Hello, tell me. The BIP 44 protocol makes it possible to use 1 recovery phrase for any wallets that support this protocol, right? those wallets of different services such as Blockchain.info and BTC.com can be absolutely independent of each other and have different passwords, but open with the same recovery phrase? Really looking forward to your reply.

**Comment by Transisto** [comment]
Use different derivation paths, problem solved.
