### ISSUE TITLE
Vote for the fork with your wallet and transactions

### ISSUE THREAD

**Issue by HostFat** [spesmilo/electrum#1684]
> I think the last and definitive word about the fork will be uttered by the users. My suggestion is this, to make users count and express their opinions: Wallet developers (mainly SPV wallets) should allow a way to tip miners that support a particular fork (today 2 MB, tomorrow everything put at a vote).
> My suggestion is to include a feature in SPV wallets that allow the user to automatically tip a determined sum (say 1 cent) or percent (10%-100%) of the fee to the last block with a valid vote for the fork (say the last block in the last 1000 blocks).

https://www.reddit.com/r/btc/comments/471jqg/vote_for_the_fork_with_your_wallet_and/

**Comment by corsaro1** [comment]
excellent idea

**Comment by filchef** [comment]
If you like to vote use full node wallet to support a particular fork.

**Comment by ecdsa** [comment]
the idea of voting for the fork is interesting, but I don't think it makes sense to implement this in each wallet separately. why don't you setup a website that lets wallet user vote on their favorite fork? 
that would work on all wallets.

**Comment by HostFat** [comment]
While a website can be a good idea, and there are already some possibilities, the proposed idea is full decentralized.

Someone is already making the code here :)
https://github.com/santiagorp/electrum/tree/classic_miner_tip

**Comment by painlord2k** [comment]
I wrote something on BitcoinTalk about my idea and the rationales of it:

https://bitcointalk.org/index.php?topic=1376093.msg14010357#msg14010357

I copy & paste it here

It should go to the coinbase address of the last block mined with Version 805306368  BIP109.
I don't know how it will manage some borderline cases like multiple payment addresses in the coinbase transaction; 


I just had the basic idea. The developer of the Electrum fork working on it stated it will be converted in a plug in the the near future to increase the chances to be included in the main release.

My idea is a way to manage a political process allowing the users, the people affected by the decisions made by others, to make their voices heard thru their wallets and their transactions.

It is just a decentralised, market driven and market based, way to buy larger blocks for the users benefitting from larger blocks.

In my opinion, it is a better solution than donating to mining operators to mine blocks with the desired version in it:

we reward the last block mined with BIP109 of the last 1000

This have a few advantages:
1) The miner is rewarded only after he has mined the block
2) If he is the only miner mining, he get all the tips (this incentive the first miners to risk and get out with the first block ASAP, even if someone will try to DDoS him)
3) More miners divide the tips and the burden of the DDoS and other niceties of opponents.
4) The tips form a  continue stream of coins entering in the pocket of the supporting miners
5) The stream is semi-automatic and people should increase the tips as the fees they pay increase because of lack of space in the blocks; the miners supporting the increase of the blocks would receive double fees compared to the miners not supporting it.
6) The people paying the fees could be counted and the support to the fork gauged by the miners and everyone else (E.G. If half of the transactions actively support larger blocks, miners would have a difficult time to dismiss them)
7) It is a decentralized action, so opponents would be in a difficult position to stop it, censor it and so on.



This idea could be, in the near future, generalized as a way to gauge the support of users to future forks of the blockchain and manage political processes in general.

E.G. Think about a community of individuals using bitcoin to pay and be paid: they live on an island and there is a ferry connecting it to the mainland. Some individuals propose to build a bridge, someone else oppose the idea (mainly the ferry boat owners, his employees and his shareholders) and stall the decision. The community, in a very decentralized way, could finance the building of the bridge paying a tip proportional to the fee they pay for the service of the ferry. No one is forced to pay what he oppose to, no one can prevent every individual to pay for what he want.

**Comment by ecdsa** [comment]
it's fine with me to add this as a plugin. However, do not expect me to maintain such a plugin; I do not have time for that, and I keep thinking it is very inefficient to build this feature into every wallet.
