### ISSUE TITLE
Adjust nLockTime (custom locktime)

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1685]
As an advanced feature (hidden from regular use), it would be cool if the nLockTime could be adjusted.
The broadcast button should probably stay disabled for such transactions.

**Comment by Rspigler** [comment]
I was just about to write my own Issue under this same principle in order to enable Electrum users to activate what is often referred to as (and often requested for) a Dead Man's Switch.  I could be wrong, but all that would really be required is a GUI for nLockTime (possibly only enable this under advance settings, as suggested by @ulrichard)

As far as I can tell, Electrum would be the first wallet to enable this feature.

**Comment by Rspigler** [comment]
See (https://github.com/spesmilo/electrum/issues/2401) for updated issue/feature request with bounty attached.

**Comment by ysangkok** [comment]
@Rspigler Does the bounty apply to this issue too?

**Comment by Rspigler** [comment]
@ysangkok, my apologies for the late response.

This issue should probably be closed; @bauerj wrote a great implementation in PR https://github.com/spesmilo/electrum/pull/2405. While this wasn't merged due to @ecdsa believing that the use case wasn't common enough to confuse users with, the work has already been done, and the payment has been sent.  

This can be confirmed here:  https://btc.blockr.io/tx/info/2f9e763141efaa405dccfa4d5b9ea8ec5c9e5eae02d081917e3f20df67a2e05b.

**Comment by botweb** [comment]
I would love to have this feature. @ecdsa Wouldn't it be an option to allow such advanced features through a new tab in settings? That way power users and newbies get served.
