### ISSUE TITLE
Last word in seed almost always starts with “ab” or “ac”

### ISSUE THREAD

**Issue by izischein** [spesmilo/electrum#1733]
When creating standard wallet, almost always (in 25 from out of my 27 last tries) the last word of the seed starts with “ab” or “ac”. (absurd, absorb, acid, etc...)

Tested with Electrum 2.6.1, 2.6.2, 2.6.3 on linux mint 17.3 mate X64, and on windows 7 sp1 X64  from 3 different PCs

**Comment by ecdsa** [comment]
this is because of the checksum I guess

**Comment by izischein** [comment]
Please explain. Does something is wrong with my PCs? This is the way it should work always? Does the other 12 words are random with no limiting pattern?

**Comment by ecdsa** [comment]
There's nothing wrong with your PC.
Standard Electrum seeds have 128 bits of entropy, plus 8 extra bits for checksum and seed version.
Mycelium uses BIP39, which does not include a seed version.

When the 136-bits seed is converted to words, with the current English wordlist, you may get 12 or 13 words. If you have 13 words, that word will be one of the first in the sorted wordlist.

I guess we should increase the size of the wordlist, so that seeds always have 12 words.

**Comment by izischein** [comment]
How many words we get from 8 bits random? I guess 256, but it seems that the 13th word randoms from 8, or, at most, 16 words.

**Comment by dabura667** [comment]
4 bits, so 16 words. You are getting the first 16 words.

**Comment by IntegersOfK** [comment]
Are there plans to propose a real BIP for the 13-word seed format? It seems like the reasoning behind using it is sound, so shouldn't we codify that? Or maybe that's already the case, but I see it referred to as "Electrum seed" everywhere and I wonder if we could formalise it into more than that.

**Comment by dabura667** [comment]
BIP39 is the winner in the phrase wars. (even though it is inferior technically)

Creating a new BIP would just serve to further fragment and confuse people when every wallet supports only one or the other etc.

Electrum having its own derivation method unique only to it is fine imo.

**Comment by ecdsa** [comment]
@IntegersOfK Electrum's seed format is not a "13 words seed format". 
When I find time, I will add words to the list, so that standard seeds have 12 words.

**Comment by dermoth** [comment]
Why not use bip39 instead so that wallet is portable between applications?

Also based on it, it seems like with 2048 words, 12 words is the minimum, going up to 24 for the highest entropy. Would it be possible to support higher entropy too?

**Comment by dabura667** [comment]
BIP39 has so many problems. It's a shame that it was rushed through so hastily so that they could hurry up and start selling the Trezor.

I live SatoshiLabs and my Trezor... But BIP39 was hastily slapped together and not given the time and care all the other aspects of the Trezor got.

I mean, if you read the BIP, you'll see it self-contradicts on two major points.

1. Since the seed is a hash of the phrase, the wallet need not know the wordlist!
2. The checksum is based off the entropy fed into the wordlist to generate the phrase, so you need to know the wordlist to check the checksum.

While it doesn't require that you check the checksum...

What do you think a developer does when there's a checksum? Checks it.

Bam, there goes one "feature" it claims to have but really doesn't.

Etc. etc...

Plus, seed portability is bad for security.

If you're importing your seed into 100000 devices just to "try it out" you're eventually going to enter it into malware.

**Comment by ecdsa** [comment]
@dermoth you can create Electrum seeds with higher entropy with the command line.
Using BIP39 is too dangerous, it's a risk I am not willing to take.

**Comment by IntegersOfK** [comment]
@dabura667 I don't agree that we need to be concerned with malware infested tools people choose to put their seed into, that's kind of their own problem; it's not going to help those people by making a more complex seed derivation process and they're probably already a lost cause if they're sharing their seed around willy nilly. Beyond the regular disclaimers ('hide yo seed!') I do not believe educating people on malware or making hurdles as protection from people's own incompetence should be part of the scope of this project.

I know I've already brought this up, but I _really_ think electrum as a project could codify the 'better' convention formally with a BIP for the wider community. There have been so many discussions between projects on the best way to deal with this specific problem and as far as I can tell the only disadvantage to the electrum approach is itself the lack of cross-compatibility (and I suppose the relative ease of creating a defacto brain wallet is also a legitimate criticism). I'm shocked it's not more obvious to people that requiring a wordlist to decode a BIP39 seed is a terribly inconvenient requirement. My point is that we've got alt-coins attention now (Monero using the format/checksum concept?) and if we expect people to continue using electrum (and bitcoin in general if I'm being dramatic) we're going to have to get other people on board with the better ideas that we're pushing.

I don't think people feel satisfied or comfortable with this response that electrum is a unique snowflake and will always have a different way of deriving seeds; it feels rogue. You can see the constant confusion on the forums, on stack exchange, here literally in this issue tracker... the response so far is "we'll make it look like a BIP39 seed by adding more words" as though that somehow helps us get rid of BIP39. Shouldn't we, as pioneers and early stakeholders in Bitcoin as a project, try to get BIP39 naturally deprecated? We all agree BIP39 sucks (except its adoption), and I believe the only way we can secure electrum as a quality option for years to come is if we express these logical electrum-style benefits in a formal document so developers have all the information in an official format to feel good about their mnemonic implementation.

This is the last I'll comment here on the matter, thank you for letting me participate in this discussion and for considering my points.

**Comment by ecdsa** [comment]
fixed in 569a3b4fab68a61db8c0e6f2362728dd5850c3f5
this commit makes sure that the last seed word is uniformly distributed, and default seeds are now 12 words.
