### ISSUE TITLE
Add features "Auto-Update" and "Check for Updates"

### ISSUE THREAD

**Issue by iostonykraft** [spesmilo/electrum#1741]
I'd like features that lets users automatically update the app and check for updates

**Comment by dabura667** [comment]
Auto-updates no. This is dangerous.

Check for updates button that allows the user to press a button to update, yes. Would be nice, but also could be dangerous for people who blindly download binaries without checking the signatures.

**Comment by RustyNomad** [comment]
Will it not be possible to code it into Electrum to check the signatures of any update against those as published in order to make sure that the download is a 'valid' download?

User can then click on the update after which a screen/window will be shown to either verify the download and or to show a warning if the signatures does not match which should then also not allow the update to continue.

**Comment by ecdsa** [comment]
I do not know what to do with this.
A lot of users value privacy, and detecting updates goes against that.

**Comment by iostonykraft** [comment]
Sure, i get that. Not a big deal, you can leave it out. 

Wednesday, September 28, 2016, 6:53 AM -0400 from ThomasV  <notifications@github.com>:

**Comment by lupa18** [comment]
give user the possibility of choose. 

If you think it's against privacy, it could be default disabled 

sometimes is very important due a security update for example, and security could be compromised without an update

**Comment by ecdsa** [comment]
this was added to version 3.3.3
