### ISSUE TITLE
Signing a message doesn't ask for TOTP

### ISSUE THREAD

**Issue by nicexe** [spesmilo/electrum#1768]
I am using the latest (as of now) release of Electrum (version: ~~2.6.3~~ 2.6.4) on OSX 10.10.5
I made a new wallet as Electrum prompted me on it's initial start and I also enabled two-factor authentication using Google's totp algorithm.
The problem is that when I try to use one of the receiving addresses to sign a message, I get prompted to enter my password but never for Google's totp.
It gives me an error: cannot sign message.

**Comment by ecdsa** [comment]
what is the expected behavior of sign/verify with multisig addresses?
in order to verify the signature, if we only have an address then we need to know all the pubkeys

**Comment by dabura667** [comment]
Nope.

No wallets support it, because the "derive pubkey from signature" trick does not work if m is less than n.

ie... If you have a 2 of 2, I could derive both pubkeys from the sigs and try both orders of pubkeys to see if either is your address, but if it is 2 of 3, I need to know the 3rd pubkey somehow.

Either they need to include the redeemscript (which is a little much, UX-wise) or force n == m

That is probably why no one is supporting it.

**Comment by nicexe** [comment]
I forgot to mention that I can spend from those receiving addresses. When I try to spend then I'm asked for both my password and totp.

**Comment by ecdsa** [comment]
ok, I disabled that for multisig
