### ISSUE TITLE
All translations are not updated.

### ISSUE THREAD

**Issue by kevlarsefirot** [spesmilo/electrum#1874]
https://bitcointalk.org/index.php?topic=1555887.msg15676230#msg15676230

This problem persists please a detailed examination of the problem!

**Comment by dabura667** [comment]
The problem is that no one has built the translations.

Someone with manager access must run the build translations command, otherwise downloading the project zip file will only return translations from the last time.

@ecdsa if you log in to crowdin, and click build project in the management menu, this problem should be solved.

Whoever is making the builds for release should have the crowdin api key file, otherwise they will not package the most recent translations.

**Comment by kevlarsefirot** [comment]
dabura667: Thank you very much (That's exactly what I'm trying to say)

**Comment by ecdsa** [comment]
@dabura667 thank for the explanation, I just did ir
