### ISSUE TITLE
This wallet is watching-only dialog ...

### ISSUE THREAD

**Issue by eriksank** [spesmilo/electrum#1893]
Would it be possible to have checkbox in that dialog saying "[x] stop telling me this. I know now!" The dialog shows up every time I start the wallet, and demands an "Ok" click. Maybe it would be better to show it somewhere next to the balance: (read-only wallet). It would spare the user from having to incessantly click the Ok button.

Another small problem. I have a wallet for which all transactions remain in "status: -1 confirmations". Is there a way to get the wallet to download the transaction details anyway?

**Comment by gits7r** [comment]
The warning is useful, maybe it's annoying for some users.

Why do they remain in status -1 confirmations? Is there anything special with these transactions? If they are confirmed but yet remain with -1 confirmations because of an error you could restore the wallet from seed and see if it works.

**Comment by eriksank** [comment]
> The warning is useful, maybe it's annoying for some users.

It is useful the first time you see it! ;-)

After that, it is just repeating the obvious.

> Is there anything special with these transactions?

Actually, no, thanks. They got flagged confirmed in the meanwhile. It just took a lot of time to verify this, because these transactions were really old ...

Thanks for your help!

**Comment by transmitthis** [comment]
Arrive here specifically because I searched for a way to stop the annoying warning. 
I know it's watching - I made it watching!  
Really don't need this warning - just have a icon, or a different colour wallet boarder, anything except annoying users with sound and notification and a OK dialogue step.

Even a console command that can disable this would do...
Programmers - not understanding Users or design here...
