### ISSUE TITLE
amodem broken on windows

### ISSUE THREAD

**Issue by norill** [spesmilo/electrum#1924]
audio modem doesn't work on windows. an exception is thrown when clicking plugin toggle in 

```
plugins\audio_modem\qt.py", line 36, in __init__
    }[platform.system()]
```

**Comment by norill** [comment]
also in standalone electrum the toggle is always grayed out, even if amodem is installed

**Comment by romanz** [comment]
Since my workstation runs Linux, I haven't specified the correct DLL to load for Windows machines:
https://github.com/spesmilo/electrum/blob/master/plugins/audio_modem/qt.py#L35

But you may try PortAudio port for Windows (see https://github.com/romanz/amodem/issues/3#issuecomment-71191377) - and if it works for you, please send a pull request to Electrum :)

**Comment by bauerj** [comment]
The plugin toggle is now disabled if it's not available, which is slightly better.

To use it on Windows, you need to run Electrum from source and install amodem from [PyPi](https://pypi.org/project/amodem/).
