### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by freezi** [spesmilo/electrum#1954]
it gives me this error when trying to send or when trying to export private keys

**Comment by faithinvw** [comment]
I've been getting this error aswell today, I get it when trying to do Anything in my account that requires me to input my password. I was able to receive BTC today but unable to send it out. I've emailed their support team and will let you know what they say when they get back to me

**Comment by ecdsa** [comment]
does it show something more in the console?

**Comment by freezi** [comment]
no it doesnt say anything in the console

**Comment by ecdsa** [comment]
which version /OS are you running?

**Comment by freezi** [comment]
2.7.1 & win10

**Comment by ecdsa** [comment]
are you able to show your seed or to update your password?

**Comment by freezi** [comment]
no. its gives me that error when trying to do almost anything in the wallet menu

**Comment by ecdsa** [comment]
does it give that too if you enter a wrong password?

**Comment by freezi** [comment]
no, it says invalid password.

**Comment by ecdsa** [comment]
ok, if you restore your wallet from seed, does the new wallet have the same issue?

**Comment by freezi** [comment]
the balance stays at 0.00 when restored but not on the original

**Comment by ecdsa** [comment]
that suggests you're not restoring with the correct seed. 
do the wallets have the same addresses?

**Comment by freezi** [comment]
no idk how

**Comment by ecdsa** [comment]
@faithinvw can you try to restore from seed in another file, and report if it works?

**Comment by freezi** [comment]
it did

**Comment by ecdsa** [comment]
@freezi please explain what you mean by "it did"

**Comment by freezi** [comment]
i restored from another files seed and the addresses matched up. but when i restore from the seed in the original wallet it doesnt match

**Comment by ecdsa** [comment]
can you send me an email to electrumdev@gmail.com ?

**Comment by freezi** [comment]
emailed you

**Comment by ecdsa** [comment]
see https://bitcointalk.org/index.php?topic=1637501.0

**Comment by faithinvw** [comment]
I made a new wallet with my seed and the issue was resolved. Thanks for the advice/help!

**Comment by ecdsa** [comment]
@faithinvw please also upgrade Electrum, the issue is fixed in recent versions

**Comment by SomberNight** [comment]
User "jmoney" on IRC reported this today. He claimed to be user [jb0y3 from bitcointalk](https://bitcointalk.org/index.php?topic=1798751.0).

He had originally set up a 2fa wallet using 2.7.0, probably encountered this bug there, and then subsequently upgraded to 2.7.18 and 3.0.3 keeping the same wallet file.
He had lost his seed words unfortunately, but he had this erroneous wallet file and also access to one time password through Google Auth. He also knew what the password for the wallet file was supposed to be.

The trace for the error, using the in-app QT console:
```
>> wallet.keystore.check_password("correctpassword")
Traceback (most recent call last):
File "site-packages\electrum-3.0.3-py3.5.egg\electrum\bitcoin.py", line 935, in deserialize_xprv
File "site-packages\electrum-3.0.3-py3.5.egg\electrum\bitcoin.py", line 915, in deserialize_xkey
TypeError: object of type 'NoneType' has no len()
```

I asked him to run this command in the console:
```
bitcoin.pw_decode(wallet.keystore.xprv, "correctpassword")
```
The output looked like an encrypted xprv.
He then modified his wallet file so that `"x1/"`>`"xprv"` now contained the output of above command.

Also, Electrum thought that the wallet file did not have a password, so he changed `"use_encryption"` to be `true`.

After this, he was able to send the coins out of this wallet.
