### ISSUE TITLE
Running a Server

### ISSUE THREAD

**Issue by andrewtoth** [spesmilo/electrum#2030]
I was looking at electrum.org for an answer to why and what resources we will expend to run an Electrum server. On the site it has no mention of this, even in the FAQ http://docs.electrum.org/en/latest/faq.html titled How does Electrum work. That question should be updated IMO. However, I am interested in running an Electrum server, and my question is does this benefit the ecosystem or not and what resource limits would I expect to hit if I were to run one. Thanks.

**Comment by dabura667** [comment]
https://github.com/spesmilo/electrum-server/blob/master/INSTALL

This is how you install it. It must be installed on a Linux system with bitcoind installed running with txindex=1 (please set up txindex=1 before syncing the blockchain)

Then you can set up SSL and IRC. setting up SSL and IRC will allow random people to connect to your server.

If you don't setup IRC, you will be the only one who will know of your server. Unless you tell someone its IP address. I suggest setting up SSL though, as if you don't all your balance info will traverse the internet in plain text (unencrypted)

**Comment by davidkaufman** [comment]
And so... I'm still curious... does it help the Electrum ecosystem for more Electrum users to run Electrum servers?  Does the project need/want more servers in the pool?  Are the current servers particularly busy?  Would additional servers alleviate the load or reduce the burden of time or cost for those currently running Electrum servers?

I also wondered about Andrew's other questions: what resources should the server have? Can I expect my Electrum server to require a lot of: 

A. Bandwidth?  How much?  In or out?  Just when "downloading the Foundry"?

B. CPU, Will a quad core or higher be required/recommended, or just a low-end ec2 t2 (~ dual core) be sufficient?

C. RAM?  I noticed the note at the end of the INSTALL page:

  https://github.com/spesmilo/electrum-server/blob/master/INSTALL

where "if your [electrum] server of bitcoind is killed because it uses too much memory" -- but again, how much RAM is required/recommended to avoid such problems?

D. Storage.  I see I have to run a full bitcoind node, so I know I need (um https://blockchain.info/charts/blocks-size) at least 90 GB just for that.  Plus  -- how big is that Foundry thing again? 

Also, issues like: Are more Electrum servers needed/wanted on Tor.  Would running on an onion addresses help the forces of financial freedom worldwide? 

I assume if Andrew was wondering about all this, and i was wondering the same things -- and if the project would benefit from from more users running more servers, then answering all these sorts of questions, perhaps in a Gentle Introduction to Running an Electrum Sever page on the electrum.org website, would certainly help those of us who've considered it, to decide whether or not we have (or can afford) enough server power to do so!

Thanks!

-dave

**Comment by dabura667** [comment]
A. You need enough throughput for a bitcoind instance (aka. however many connections you want to have; at least 8) and the queries from Electrum clients. (If you're publicly advertising your server, random Electrum clients will connect to you asking for kilobytes or megabytes of data in one go.)

B. bitcoind is made to use as much CPU as it can. I would recommend at least a dual core to help with threading the processes for bitcoind and Electrum-server

C. As much as you can. This changes drastically depending on network conditions, but I've had 4GB RAM nodes crash recently with bitcoind only, so I'd say 8GB just to be safe, or at the very least 4GB + 10GB of swap disk.

D. 500GB should be fine for a while. That will hold blockchain, Electrum stuff, swap disk space, and OS stuff for a good while.

If you're looking for the bare minimums, your Electrum server will start crashing in a few weeks/months, so the answer to everything is "as much as possible." but the biggest cause of crashes is RAM, so don't skimp if you can afford it.

**Comment by dabura667** [comment]
To answer the "does Electrum need it?" the answer will always be yes. The more Electrum servers participate, the less resources are required for each one, which helps out.

To answer the Tor question, that is also always a yes. The more people can access via Tor, the better.

**Comment by kyuupichan** [comment]
I'm writing a more lightweight electrum server here:

  https://github.com/kyuupichan/electrumx/

It works well enough for personal use right now.  It will be ready for public use in a month or two.

It requires about 18GB for the database.  It takes about 10-20hrs to sync depending on hardware from genesis block.  You can decide how much memory to use during sync (see the docs) but it defaults to using about 2.5GB.  Once synced memory usage is minimal.  The database format will change as I improve it obsoleting older ones.  Please read the notes and be aware it is experimental.
