### ISSUE TITLE
Low Fee - Unconfirmed Paerent

### ISSUE THREAD

**Issue by spadventure89** [spesmilo/electrum#2056]
Hey guys been reading a lot about this and it seemed to happen to me.

I have two transactions stuck one at low fee and the other unconfirmed parent.

Its been one week now and still hasnt been dropped out of the block chain.

Can anyone help me out please...

https://blockchain.info/tx/4a5e0447e3ef2106c8770b692873829820ac42711a6adcaa8eca2377e493c91b

https://blockchain.info/tx/82b4d086dfd816986e3a4ecc910ab7a7493f01c35345361dfaea8b4793702778

**Comment by ecdsa** [comment]
you can try to find an electrum server that does not have these transactions in its memory pool, and spend from there with a higher fee.

**Comment by spadventure89** [comment]
Hey T,

Really appreciate your reply ! 

Do you mean by going through all the different servers in Electrum ?

**Comment by ecdsa** [comment]
yes. if there is none, you will have to wait.

**Comment by dabura667** [comment]
82b4d086dfd816986e3a4ecc910ab7a7493f01c35345361dfaea8b4793702778 should be gone now. Try again.

As for 4a5e0447e3ef2106c8770b692873829820ac42711a6adcaa8eca2377e493c91b:

is 1C6Q1javcVaS5rrkj22RAD4WMYfncAgTq5 or 15B14PXK2tFMZVveuEm16hsXCugirmkRwk one of your change addresses?

If so, you can spend the coin from that transaction, and send it to yourself with a very high fee. 0.0004294 BTC fee should be enough.

The miners will see that the total fees of your stuck transaction AND the transaction you sent from that change add up to a high enough fee to pay for both transactions and both will get confirmed. (most likely)

**Comment by spadventure89** [comment]
Thanks for the reply guys ! 

Everything went through

**Comment by JazzTp** [comment]
@dabura667 Hi, most evidently I still have a superficial understanding of how transactions work, could you please confirm if I did the correct steps in order to follow your suggestion?

I have an unconfirmed transaction (although it was created with dynamic fees). For privacy, I sent the ID by PM to the main developer a few hours ago (his answer concerned another of the three questions I had included in my message). 

Later, I tried the following:

In Electrum, I went to the "Receive" tab, copied the address, then went to the "Coins" tab, right-clicked on the address which was *apparently* the change address of the unconfirmed transaction, and chose "spend" in order to send that amount to myself as you suggested, that is to my receive address, and I created the transaction with dynamic fees ON and the fees cursor to the maximum. I signed and broadcast the originated transaction although it showed "Sent amount: 0. mBTC", thinking that I might be some rounding/display problem, or something related to the "Unconfirmed" status of the previous transaction and that both thing would be solved together by adding these fees to the previous ones by mean of this "send to yourself change coins" trick, which I might very well have misunderstood.

In the history window, that last transaction appears below the previous Unconfirmed one (as older?!), with a yellow triangle with "!" inside, "Unconfirmed parent". The amount -0.192 mBTC is reflected in the balance column (probably just the fees I spent to send change coins or actually 0 mBTC to myself).

After broadcasting the payment, I have in the History window the situation visible in the attached image:

The previously unconfirmed transaction is still "Unconfirmed".


**Thanks!**

**Comment by JazzTp** [comment]
@dabura667 Both transactions went through, both have 40 confirmations at the moment.

It would be quite interesting to me to know if what I did in order to follow your suggestion was correct or not.
In my previous post I forgot to mention that the transaction that first stayed "Unconfirmed" was a "pay to many" one, pay to two actually. Maybe (?) miners consider that fees per kByte should be higher in case of "pay to many" transactions, but even if that was the case I'd expect Electrum to take care of it with the "dynamic fees" option active. For now, I probably need to remember to slide that cursor to the right in case of "pay to many" transactions (I actually *had*, I never meant to be stingy with fees, but I got various "error: Server did not answer" messages and in order to exclude that it might depend on fees I had brought that cursor back to the middle).

Talking about "pay to many" transactions... one question the main developer did not answer is: at what address does Electrum Technologies receive BTC donations? Or: what server do they run directly (so I could get the address through the "donate to server" menu item). My modest donation alone won't change their balance of course but I believe it's a must, the Electrum + server software clearly demand a constant huge effort.
