### ISSUE TITLE
Missing icon and launcher

### ISSUE THREAD

**Issue by ntilotta** [spesmilo/electrum#2117]
Debian / Testing GNOME 3 - KDE Plasma 5

**Comment by bauerj** [comment]
How did you install it? Using pip?

**Comment by ntilotta** [comment]
@bauerj yes

**Comment by ysangkok** [comment]
Did the issue persist?

**Comment by bauerj** [comment]
Can pip even do that?

**Comment by ysangkok** [comment]
Well, `setup.py` could. But I think it would be confusing since usually PIP installed programs do not add launchers. So I say we close this, WONTFIX?

**Comment by ysangkok** [comment]
Okay, I talked to Thomas about this. So, we don't want add code for all desktop environments, since it varies too much between distributions. Downstream packagers should add launcher icons in the appropriate places for the difference desktop environments. Pull requests are accepted if you know some XDG standardized way of storing launcher icons, you would of course need to remove the launcher during uninstall also.
