### ISSUE TITLE
Not Connected. Ever. v2.7.9 on Tails v2.10

### ISSUE THREAD

**Issue by radbradsdad** [spesmilo/electrum#2146]
Electrum 2.7.9 doesn't seem to want to connect despite various config changes. I've tried auto-select server as well as:

Server: 56ckl5obj37gypcu.onion:50002
SSL Enabled
Socks 5, localhost:9050

OS: Tails v2.10

Regardless, the message in the bottom just says "Not connected"

Any help would be appreciated. I sent some btc into the wallet, and there are currently 10 confirmations via blockchain. But nothing in my Electrum wallet.

**Comment by ecdsa** [comment]
maybe the server is not online anymore?
either disable TOR, or find another .onion server
https://1209k.com/bitcoin-eye/ele.php

**Comment by JazzTp** [comment]
Seen your message, I have checked out Electrum 2.7.9 with Tails 2.10, and
it connects and syncs fine here (2.7.9 is the version coming with Tails).

I'm using it through *Tor*, the network configuration is the default one
for Electrum in Tails:

Select server automatically: check (= activated, do it automatically)

Use SSL: check (activated)

Proxy: SOCKS5 localhost 9050

*Be sure to wait a few seconds after booting and logging in, until Tails
tells you that Tor is ready to use.* If that does not happen, the problem
is elsewhere. You might have to look into Tails docs and troubleshoot your
connection and/or Tor setup.
It always ran straightforward here, so I have no idea what you might need
to change.



At present, I'm actually using Electrum 2.7.18 (*) on Tails 2.10 and it
works fine too (just a few messages on the terminal window from which I
launch, but it connects and syncs very fast and I can receive and send
coins).

I had tried previous Electrum versions (2.6.3, 2.6.4, 2.7.12, 2.7.17) on
previous Tails versions, always through Tor, I haven't made many
transactions yet but I can tell you that so far I never had one single
connection/sync problem.



(*) The online part: I boot Tails from DVD, then launch a script I
prepared, which eliminates the .electrum folder and replaces it from a
backed up one (**), it extracs Electrum from a password protected archive,
enters its folder and launches it from within (otherwise the Electrum
version coming with Tails would be launched) with the appropiate wallet.
When Electrum exits, the script offers to backup the .electrum folder. I
can launch again and then launch another script which only does that backup
(or trivially launch tar myself).

The offline part: I boot from pendrive, Persistence is active but just to
avoid a second pendrive. I launch a script similar to the other one, the
only thing which changes is that the wallet is the cold storage one.

So, not modifying anything in Tails nor relying on Persistence more than
that, I can switch rather quickly to a new Tails/Electrum version.

Actually, .electrum here is a sym link to something like .electrum_2.7.18,
so I can keep different backups and try a previous Electrum version any
time.


(**) Upon first launch, I only leave the blockchain_headers file in the
.electrum folder [or nothing at all], and let Electrum recreate the rest,
and reconfigure Network and Preferences.
