### ISSUE TITLE
unconfirmed transaction

### ISSUE THREAD

**Issue by quest00** [spesmilo/electrum#2153]
I have several transactions that are sitting unconfirmed.  How can we push them thru or kick them out of the mempool.  It has been nearly 48 hours.  Anyone please help. I am using electrum 2.6.4.  I believe the issue may have to do with the fee size which was set at the default 0.5 mBTC/kB.  Is there a way to get the transactions completed or kicked back asap.  I have 4 transfers in this state.  One of them is listed below.  Please help!!!!

1A3M8bK7r2PNB4XMEo6tFgKAaW4Hx6Z3ZE

transaction ID
8dcc58b7f5f8ab1496057a52824471041c9303609221d817dcd598044785a14b

**Comment by shsmith** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by quest00** [comment]
How long before the funds are kicked back?  I dont really understand how to perform a child pays for parent.  Can someone walk me thru this step by step?

**Comment by shsmith** [comment]
The idea is to spend the "change" in the tx back to yourself, but with a much higher fee. 
This higher fee will speed up the original tx. 

See these discussions on the topic:
https://bitcointalk.org/index.php?topic=1118563.0
https://bitcoinmagazine.com/articles/what-to-do-if-your-bitcoin-transaction-gets-stuck-1481042383/

I had a look at the TX you quoted, and it appears your change to 1BoczPR4HC85c4Hm9WtjkYienYmvNM9XsY is already spent, so this may not be possible. It is an input to another tx you likely did to 1MmCX4XQ9rqDdbdLF4EFsTsx6rBUKZbKV3 with another change address of 1As2RHPhGNfgjwsdzhQ3DJay6VzGU1z7iv. That second change address is also spent in a tx to 1MmCX4XQ9rqDdbdLF4EFsTsx6rBUKZbKV3 with an unspent change address of 1MX2mAZhDMcEwFoDqDk4RAVogsMmUtfWva.  If 1MX2mAZhDMcEwFoDqDk4RAVogsMmUtfWva is an address in your wallet, then spending that to yourself with a 8x fee may be enough to get the whole chain of txs unstuck.

In the long term, I recommend you update to the latest electrum (2.7.18) and then turn on "Enable replace by fee" and always check "Replaceable" when you send new txs. That will make it very easy and reliable to increase fees when needed without resorting to spending change addresses.

**Comment by JazzTp** [comment]
A way to do a "child pays for parent" transaction was - I believe - suggested by @dabura667 in issue #2056 (disclaimer: I'm a newbie in the constant process of getting better documented (following these issues hopefully gives a deeper understanding of how things work). 

I tried that and described there (see issue #2056) the precise steps I had performed, asking if those were the correct steps, with no answer so far.
That transaction (and the supposedly CPFP one) had gone through when I checked very few hours later, however I don't know if that was a coincidence or if my steps were the correct ones.

@shsmith if you could check out #2056 and confirm whether those steps were correct or not, that would be great.

Also, noted down after that episode, @quest00 and I will keep the "replace by fee" option enabled.

**Comment by quest00** [comment]
If i update will that change any of my wallet?  can I then select replace by fee?  The 1MX2mAZhDMcEwFoDqDk4RAVogsMmUtfWva I do not think is mine.  Ive read those articles and still do not understand exactly how to perform the parent pays for child.  How long before the mempool kicks all these out and back to the sender?

**Comment by quest00** [comment]
shsmith or anyone else who may know.... even though that last address may not be mine, If I spend to that wallet would that clear all the other stuff underneath it?

**Comment by quest00** [comment]
can you walk me through a spend change?  As this is all new to me and im not entirely sure all the steps, I greatly appreciate your help with this issue.  You think it will be longer then a week?  How much you recommend to set the fee at mBTC/kB?  or use another method?  Can i update the electrum without loosing anything?

**Comment by shsmith** [comment]
@JazzTp thank you for the links. It seems likely that you did successfully speed up your tx with this technique. It is my understanding that the developers are adding an automated way of doing this into the GUI so that it will be much less confusing. Not sure when we will see that update, but most likely in the next few weeks.

**Comment by shsmith** [comment]
@quest00 Go to preferences and set "Set transaction fees manually".
Find the change address (probably in the "change" section of your "addresses" tab).
Right-click on it and choose "spend from".
Pick another empty address in your walled as the "to" address.
Put a very small value in the "amount" field and put the whole change value 0.000703 in the "fee" field.
This will spent the whole $0.75 of change as a "fee" to all the parent transactions.

**Comment by JazzTp** [comment]
@shsmith Thank you.

**Comment by quest00** [comment]
can I make it even more enticing and place more then 0.000703?  that is the same as 7.03 mBTC right?

**Comment by shsmith** [comment]
@quest00 Yes, you can pay even more. But because you are using "spend from" it may not allow more than the balance of that address you are spending from. It may be possible to control-click the change address plus some other address with a balance and "spend from" the pair.

@JazzTp The "coins" tab was just recently added. In the older version @quest00 is using it is all done from the "addresses" tab.  

Somebody should make a youtube video showing step by step how to do this...

**Comment by JazzTp** [comment]
@shsmith Roger that, "Coins" tab recently added.

@quest00 About your question related to upgrading:

I beleve 2.6.4 used an older seed type, not only it has no option to extend the seed with your own custom words, but also (if I understood correctly words of the main developer in another issue) it generates uncompressed transactions, meaning that you would pay **less fees** if you now created a **new wallet with a new seed, with a recent Electrum version**, and from the old wallet you sent all the funds to the new wallet (I'd double check the "dynamic fees" option ON, and I'd slide that fees cursor somewhere to the right).

**Comment by quest00** [comment]
@shsmith 

 I have other stuck transactions.  I just need to find the change address and send that to myself again?  I noticed the fees arnt that high 0.000703.  Will that be high enough to clear the funds?  Also, I just got funds sent to my wallet for lower fees then those that are stuck.  Why would the those original transactions get stuck?  Thanks

**Comment by quest00** [comment]
@shsmith 

I tried to send the funds like you explained.  I got an error that it was rejected due to network rules... Why is that?  What did I do wrong?

**Comment by shsmith** [comment]
The fees are based "per kb" of tx data. Your first tx had 5 inputs and 2 outputs, making the whole tx 816 bytes. That requires a much higher fee than a minimal tx of 1 input with 2 outputs (usually 225 bytes). Most likely the tx that went through had a higher fee/kb but since the kb was smaller, the total fee was smaller.

One final trick is that if you know the person on the receiving end of the tx, they can also try to spend the unconfirmed tx using a higher fee, and just like spending change, it will make the original tx confirm faster.

**Comment by quest00** [comment]
@shsmith 

Do you know why im getting an error?  'transaction was rejected by network rules.(64:dust)

how do I make my tx with 1 input and 2 outputs?

what fee setting should i set my wallet for?

**Comment by shsmith** [comment]
64:dust means that part of the tx had too small a value to be considered a valid amount. I'm not sure of the exact rule for what is considered dust, but if you make all the outputs larger you should avoid that.

When you spend from a single input that has more than the amount you want to send, you will get a 1 in + 2 out tx. In the case of your original tx, none of your original coins were enough so it had to gather up 5 different inputs in order to reach the total you wanted to send. Normally you don't need to worry to much about it, unless you are getting a lot of micro payments (eg. from faucets). Micro payments are expensive to spend and in some cases cost more in fees than they are worth. That causes them to be considered "dust" to avoid filling up the blockchain without adding value.

In the future (after you upgrade to the latest electrum) you should check "enable replace by fee" and when you send you should always check "replaceable". Once you start doing that, you can try a low fee, and if you get impatient you can easily increase the fee right from the transactions list.

**Comment by quest00** [comment]
This is driving me crazy.... I have another transaction, which is much larger on hold too.  Is there a way I can send you private messages?

**Comment by quest00** [comment]
finally got it sent but its sitting unconfirmed... wonderful...

4774a2298c4e9d2602f10093ec1bbfb40b15607ad03d203dd4fd3da3188ae678

**Comment by JazzTp** [comment]
The transaction in which I spent to myself the change coins of the previous
unconfirmed one was at first apparently stuck, too, "unconfirmed parent",
but when I checked again a few hours later both had gone through and
already had more than 40 confirmations.

**Comment by quest00** [comment]
everything cleared!!!  YEAH!!!  think it was just time or what we tried?

**Comment by quest00** [comment]
Thank you all!!!!

**Comment by JazzTp** [comment]
You are welcome.

I believe the Child Pays For Parent transaction speeds it up as expected.

But, better, let's follow recommendations, @shsmith nicely and clearly
summarized them here, I add my thanks to him.

**Comment by electrumwallet123** [comment]
@shsmith you say me all the process is listen here about how to make CPFP with electrum wallet!!! but as i see many people still does not understand the process!!! like me still not understand what i need to do.
My transaction is stuck for 3 days :|, if someone can help me i even pay for help me make my transaction confirmed and i will never ever use electrum wallet in my life
It's so hard to describe step by step how people can make CPFP for unconfirmed transaction with low fee.

You simply put a link: http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
Well either there is nothing detailed how to make CPFP i think because of those problem electrum will lose a lot of users and because the support does not know how to explain more detailed for newbie users.

**Comment by shsmith** [comment]
Keep reading. There are several questions and answers in this topic. 

You might be better off joining the IRC channel so you can live chat.
https://webchat.freenode.net/

**Comment by leopoldtenny** [comment]
With thousands of people flocking into investing their money in cryptocurrency, the bitcoin block size reaches its limit that leads to severely crowded bitcoin network, failing to include all the transactions in time. As a result of the crowded bitcoin server, thousands of transactions are delayed or stuck and are all waiting for confirmation. For this reason, when you are sending a bitcoin transaction to someone else it's showing that "**[unconfirmed bitcoins transaction](http://www.speedupmybitcointransaction.com/)**" or " bitcoin transaction unconfirmed". It's very worrying situation. You can use free bitcoin transaction accelerator to boost your unconfirmed transaction. Unconfirmed transaction accelerator is also best for people who have low fees set on their bitcoin wallet for their transactions to be confirmed faster.
