### ISSUE TITLE
Problem not solved: pending transaction

### ISSUE THREAD

**Issue by CharlotteStuttgart** [spesmilo/electrum#2194]
Hi,

Four days ago I wrote about my transaction with transaction ID 6870684550f148fbe58d6b4ca055d00189358e2214c8311ae97b7b73eba9586a
It is still unconfirmed but as said I only have limited time.
I tried to do the CPFP but as I can not set the sent from address in my electrum 2.7.18 wallet I was unsuccessfull. The transaction has a fee of 50.147 sat/B which I read is standard.
Can someone please assist as the documentation of Electrum is poor in describing how to speed up a transaction.

Thanks in advance!

Charlotte

**Comment by JazzTp** [comment]
Hi,

Answering a bit in a hurry admittedly (I'm rather a newbie myself anyway).

In issue #2153 I had mentioned issue #2056, you should see both here:
https://github.com/spesmilo/electrum/issues?utf8=%E2%9C%93&q=%232056

In #2056 I had described step by step what I had done to create a CPFP transaction (which was apparently successful) , in #2153 user @shsmith kindly confirmed that those steps were correct steps. 

**However, after seeing your transaction, I am unable to give you precise advise on spending change coins.**

**I read that the person to whom you are sending your payment can also try to spend the coins of the unconfirmed incoming transaction, in order to create a CPFP transaction** (the person will be paying fees).

In #2153 @shsmith analyzed a transaction by its ID... let me see how the ping command works, maybe he can help:

ping @shsmith 


Whenever I  had a critical time frame to send a payment, I slided the fees/kB cursor to the rightmost position. I understand a SEPA wired transfer is only 1 EUR (some banks charge 4), and that today's Bitcoins network fees can be higher, but with Bitcoins you don't pay a fixed monthly fee to any bank, so **I'd really go the safe side with fees when delivery time frame is critical**.

Also, in issue #2153, @shsmith also reminded us, for the future, to **leave the option "enable replace by fee" active and to mark "replaceable" on any outgoing transaction. That allows to simply and reliably increase fees for unconfirmed transactions**.

**Comment by ecdsa** [comment]
you can spend from the same address, open the coins tab.
