### ISSUE TITLE
FEE!!!!

### ISSUE THREAD

**Issue by auralarch** [spesmilo/electrum#2212]
I know, I already see others reporting this issue.  But  IT NEEDS TO BE DEALT WITH & FIXED!!!
Yes, I AM yelling!  Because this is absolutely infuriating!  This delay is going to end up being quite expensive for me.  I would have gladly paid WHATEVER fee was needed to get my transaction processed and now my coins are stuck and my fee is in potentially PERMANENT limbo- and for what?!

Literally, I am asking...  What is the purpose of this?!  Are you really trying to save me twenty cents or whatever the heck it is?!

This isn't the first time this has happened to me (and obviously if I was dumb as dog poop I would never have used this pathetic software again).  But I thought that I could correct for the problem...      
Not only did I set the BS flexible fee up to the max so see how much it was.  Then, just to be safe (so I thought!) I QUADRUPLED the fee.  And yet, it turns out that was still only 70 satoshis per byte.  Are you SERIOUS?!  WTF?!?!?!
So whoever made this software is capable of coding for all these complex encryption algorithms, but you can't calculate a simple fee?   Come on!

This is absurd- you guys should be embarrassed and ashamed of yourselves.

Check it out; there's a site that tells you how much of a fee you need to keep a transaction from getting stuck for as long as infinity (literally!)  and that's where mine ended up AFTER quadrupling the already HIGHEST fee the program would've attached to my transaction using its settings.

There is absolutely NO excuse for this nonsense!!!!

**Comment by ecdsa** [comment]
come back when you are able to make a useful report

**Comment by JazzTp** [comment]
Hi,

I leave dynamic fees activated,

AND

when delivery time frame is critical I slide the fees cursor to the right,

AND

I have the option "enable replace by fee" active, and mark any outgoing
transaction as replaceable

(before learning this, I did have an unconfirmed transaction and could
successfully create a "child pays for parent" transaction to speed it up, I
checked 2-3 hours later and both had already more than 40 confirmation).

I read an article weeks ago where an important developer/miner said, about
the infamous backlog, that a 5 USD fee is always enough, and that stuck
transactions are usually very small amounts with very small fees.

Of course you're not happy to transfer 1 or 10 dollars and pay 5 for the
transaction...

There's quite a debate going on about this and other aspects of Bitcoin,
and different propositions for its future...

Satoshi himself allegedly proposed the enlargement of the block size, and
said that the Bitcoin network CAN be put in conditions to process many
transactions, at VISA level, and  at small fees, with no need for a
secondary layer like "Lightening" would be... Well, there's much to read on
the web. I'm positive they will be able to grab the best of each position
and finally unanimously have the Bitcoin network evolve to the best.

ON THE OTHER HAND...

Sending a wired transfer in Europe, from one bank account to another
(SEPA), costs 1 to 4 EUR as for I know...

To receive it, the cost goes from zero up to a percentage of the sum.

You also pay monthly and yearly for your bank account.

If you make many payments, the 1 EUR to send, zero to receive situation is
obviously cheaper than those 5 USD "suggested" with Bitcoin, even
considering fixed bank account fees.

Just comparing.

Other crypto coins will be competing on this, and other features... or will
be suggesting alternatives that Bitcoin will be able to adopt.

Some proof of stake algorithm instead of proof of work might make the whole
blockchain cheaper.

**Comment by JazzTp** [comment]
You might want to see if

http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

and

#2153 and #2056

can add any useful information.
