### ISSUE TITLE
unconfirmed parent 

### ISSUE THREAD

**Issue by HarmanBose** [spesmilo/electrum#2225]
hello! i have issue with my electrum wallet, transaction de97a854b9db8953413a097f3f262398583e678c7a2f6ea4f93cf86b448dc4f3 48 or above hrs in that status
how to fix it? help pls!!!

**Comment by JazzTp** [comment]
Hi, yesterday's issue #2219 might give you useful information.

**Comment by HarmanBose** [comment]
thanks for your reply!

**Comment by JazzTp** [comment]
You're welcome.

**Comment by HarmanBose** [comment]
i am a noob in these technical moments, pls can you give me a step-by-step guide?

**Comment by HarmanBose** [comment]
help wanted, whoever makes this transaction valid - Ill pay 50usd

**Comment by JazzTp** [comment]
I'm also a newbie, I'm following these issues to better document myself.

By checking out the issue #2219 I pointed you to, you'd find my comment
there (copied below), in turn pointing to:

1) Electrum documentation explaining "child pays for parent" transactions,

2) two previous issues, in one of which I made a step by step description
you might want to check out, which was later confirmed to be correct, by a
more knowledgeable user in the other issue mentioned there, where he also
suggested a procedure for older Electrum versions lacking the Coins tab.

That user also suggested someone made a video...

Well, I hadn't directly copied here my comment on yesterday's issue because
I'm on my cell phone at the moment, having to take care of other things,
anyways here it goes:

----------...

Hi, newbie here.

Unconfirmed parent: maybe you tried to spend coins from an unconfirmed
transaction.

Low fee: I suggest you keep the "dynamic fees" option active, as well as
"enable replace by fee",  and mark any outgoing transaction as replaceable,
so you will be able to easily raise the associated fee in case your
transaction remains unconfirmed longer than you can wait for it to go
through.

Also, you might want to check out

http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

and previous issues

#2153 and #2056

...----------

**Comment by JazzTp** [comment]
(I doubt anybody around would accept your compensation.)

See if you can identify a change address in your transaction, then check
#2056 there's a step by step description....

Otherwise the person to whom you sent that payment can create a "child pays
for parent" transaction by selecting the coins from your unconfirmed
transaction and trying to spend them (he can send them to himself).

In both cases, an "unconfirmed parent" error should appear, but miners will
be able to associate transactions and sum fees, so later both transactions
should go through, if fees sum up OK for miners.

TO PREVENT having to create"child pays for parent" transactions:

In the console of the Electrum GUI:

setconfig('max_fee_rate', 200000)

and restart electrum (as per issue #2181)

In Electrum preferences:

Dynamic fees active, "enable replace by fee" active, mark any outgoing
transaction as replaceable, move the fees/kB slider to the right.

Earlier today on yet another similar issue somebody pasted a useful link:

https://bitcoinfees.21.co/

**Comment by JazzTp** [comment]
(On my PC now.)

I don't see any change address in your transaction (I can't rule out that a more knowledgeable user would).

**See my previous comment: "... the person to whom you sent that payment can create a "child pays for parent" transaction by selecting the coins from your unconfirmed transaction and trying to spend them (he can send them to himself)" and what follows.**

-----

**Another suggestion I've read from one of the main developers here, but I've _never tried_:**

1) make another transaction which sends **the same coins** to the same person, with a higher fee.

_See recommendations in my previous comment to PREVENT facing this kind of situations, especially when delivery time frame is critical._

**THEN:**

2) try connecting to different Electrum servers and broadcast the new transaction until you find one server that doesn't give you an error for having already spent those coins (that server doesn't have your stuck transaction in its memory pool). It's not granted that you'll find one.

**Comment by HarmanBose** [comment]
ok man, thanks A LOT! you give me a lot of info i should had learn

**Comment by HarmanBose** [comment]
but i cannot understand why noone wanrs to get that easy money?

**Comment by JazzTp** [comment]
Sorry I can't figure out how to do more, the best thing is to learn how to _prevent_, I _had_ to, rather recently, myself.

**Comment by HarmanBose** [comment]
I have found video tuto!)) thnks to everyone

**Comment by JazzTp** [comment]
**Share the link to the tutorial please.**

(I'm sure more than one would help if he was reading and in condition to stay on it... as I said, I doubt anybody around would accept your compensation.)

**Comment by HarmanBose** [comment]
https://github.com/spesmilo/electrum/issues/2225#issuecomment-283799662 here is video
guys can you help me with understanding of this:
the big one, TRID, de97a854b9db8953413a097f3f262398583e678c7a2f6ea4f93cf86b448dc4f3
small one: e37fdf2c20a28ba15dcb477a6b522fafd53d99b564177fcc3c75d619ee19be55
I do not understand which one of them is broken, pls help

**Comment by HarmanBose** [comment]
dam sorry https://www.youtube.com/watch?v=ycq7O48aPvQ
