### ISSUE TITLE
Paymentsending  says "low fee" on electrum.... Help!!

### ISSUE THREAD

**Issue by mgkeel** [spesmilo/electrum#2237]
bassically sent btc to an addresss and now my funds are un-usable.... its been 3 days now and i need to resolve this issue asap.. Thanks

**Comment by ecdsa** [comment]
enable dynamic fees and read http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

**Comment by dabura667** [comment]
We should enable dynamic fees by default and remove the GUI for setting your own fee.

People who want to do such things can use the console / CLI anyways

**Comment by ecdsa** [comment]
dynamic fees are already enabled by default.
these are users who inherited the previous setting

**Comment by dabura667** [comment]
Perhaps change the name of the dynamic fee usage setting so that older wallets will be switched to dynamic fees automatically once.

Then remove the option to disable dynamic fees from the GUI.

That way old and new users will need to go into the CLI or console to change the setting.

imo, already users are shown their fee before sending, so it's not like you'd be forcing large fees on them, they would have to agree.

**Comment by ecdsa** [comment]
this was missing: 83e925c0cd31e31c467343c39fba0f889157f21a

**Comment by kyuupichan** [comment]
@dabura667 I like the ability to set a fee; I'll be quite upset if it goes from the GUI.  Make it hard to enable or something, but please don't remove it.

**Comment by ecdsa** [comment]
I'm not going to remove it. I think the fix we have now is sufficient.

**Comment by dabura667** [comment]
@kyuupichan @ecdsa

imo in the same way we don't let a newbie user modify their gap limit with a slider bar because the educated enough to fiddle with every option and take a stab at what it means but still uneducated newbie will just see "oh, number of addresses? MOARRRR!" and shoot themselves in the foot...

we should also not allow the newbie who is just smart enough to poke around, but ignorant of fee dynamics and how they affect confirmation, and they say "ooooh, I can send bitcoin for a super low fee! Yay!"

I can change my gap limit with a 10 character easy to remember command in the console tab.

It could be "wallet.disable_dyn_fees()" or something and BAM, your wallet is just like you want it... but Mr. Noseypants can't get himself in trouble.

FYI this was my justification in my head.
