### ISSUE TITLE
Max fee is too low

### ISSUE THREAD

**Issue by AlbertoDL** [spesmilo/electrum#2250]
The scrollbar allows you to set a max fee = 1mBTC. It's too low to get tx confirmed in this period.
Without the need of using the console, users should be allowed to set a higher amount, while a "bump fee" button would be great (expecially if dynamically adjusted to the market fluctuation)...

**Comment by bauerj** [comment]
Enable "Use dynamic fees" in the options.

Also, to be able to bump fees, enable RBF.

**Comment by JazzTp** [comment]
In the console type: setconfig('max_fee_rate', 200000)

or 300000

Then restart Electrum.

**Comment by JazzTp** [comment]
Don't type "or 300000" in the console, I meant you might want to replace
200000 with an higher value.

**Comment by JazzTp** [comment]
https://bitcoinfees.21.co/

https://support.21.co/bitcoin/transactions-and-fees/how-do-i-calculate-my-transaction-fee

**Comment by bauerj** [comment]
How is that better than using dynamic fees?

**Comment by JazzTp** [comment]
I have dynamic fees active, too.
And "enable replace by fee", and I mark as replaceable any outgoing
transaction.

Kind of newbie here so I'm unable to give you a precise answer.

I got a stuck unconfirmed transaction only once for a few hours, although I
had dynamic fees active. That was before learning about the "enable replace
by fee" option (to speed up the transaction, I could do a "child pays for
parent" transaction because there was a change address in that transaction).

**Comment by AlbertoDL** [comment]
Yeah thank you guys and sorry, this thread should be closed. My newbieness makes me blind. I just noticed the possibility to enable RBF and dynamic fees

**Comment by JazzTp** [comment]
You're welcome.
