### ISSUE TITLE
Electrum wallet 1.x Not connected

### ISSUE THREAD

**Issue by Nickmelb** [spesmilo/electrum#2323]
Hi,

I have not upgraded my Electrum wallet version 1.x for a while and it was working fine. Recently it shows not connected with a red button on the bottom right hand corner. How can fix this ?

 I did attempt to upgrade to latest Electrum wallet however nothing happend when running the new wallet.

Regards

Nick

**Comment by ecdsa** [comment]
you should definitely upgrade.
In electrum 1.x, open the seed dialog and write down your seed.
then rename  your default_wallet file to a different name.
then start Electrum 2.8, and restore your wallet from seed.

**Comment by Nickmelb** [comment]
Hi,


I have loaded Electrum to my android phone and have recovered all my coins. When i attempt to use the camera to take a photo of a QR code the camera does not work. Is there a setting i am missing to get the camera to work?


Regards


Nick


________________________________

**Comment by ecdsa** [comment]
from the play store: "Important: In order to scan QR codes, this app uses the ZXing QR Scanner app. If you experience issues with the camera button, please make sure that you have installed the original QR Scanner app by ZXing; many phones are distributed with custom QR scanner applications that are not 100% compatible with ZXing."
