### ISSUE TITLE
Send only confirmed coins ?

### ISSUE THREAD

**Issue by bsbits** [spesmilo/electrum#2395]
I would like to know if it is possible to send coins from confirmed parent transactions only and exclude unconfirmed ones.

If it is possible, how can I do it via command line ?

**Comment by dabura667** [comment]
Electrum already prioritizes confirmed utxos over all else.

You mean you want it to return an error and fail sending if the send amount is over the total of confirmed utxos amounts?

**Comment by bsbits** [comment]
Correct.

Also if there is a way to get the confirmed bitcoins then send them all while excluding unconfirmed transaction.

**Comment by dabura667** [comment]
I took a peek at the source code, and it's doable. You would need to pass an boolean arg through like 5 nested methods, but it's doable.

Currently the source can not do as you ask via CLI.

In GUI mode you can use coin control to manually select the utxos.

**Comment by bsbits** [comment]
I will actually use the GUI to spend coins.

So the solution is enabling coin table and select the address / addresses to spend from ?

**Comment by bsbits** [comment]
The only solution I came up with is using command line to list an export addresses with no pending transactions and use the GUI to select them

**Comment by ecdsa** [comment]
reopening. I think it would be useful to have that as an option.

**Comment by janhn** [comment]
In my recent experience, Electrum picked coins from an unconfirmed transaction with priority. It would be good to have some control over this.

**Comment by bsbits** [comment]
If @ecdsa can craft us something on the next release, it will be perfect.

**Comment by ecdsa** [comment]
currently, miners do not take coin age into account in order to decide transaction priority. Thus, the only reason not to use the 'privacy' policy is that it uses unconfirmed inputs. The correct way to fix that is to have a single policy, that prioritizes confirmed inputs and then behaves like the current privacy coin chooser.

**Comment by ecdsa** [comment]
then we can remove the policy selector from the GUI, and replace it with an option to send only confirmed inputs.

**Comment by ptilancelot** [comment]
Since all the manipulations I made .... I understand nothing more, while I
start with the criptomonnaie which I begin to understand wallet, bitcoin,
ether, and the only Euro that I changed into bitcoin to try. ..... It's
been almost 2 months, I have to hazar choose to change them to Ether. I
chose hazar in your home ... then more ways to know who? I understood
well?????
Since everybody attacks me by message in all languages ​​... with words
that I do not understand the meaning ..... just some numbers and number ...
that does not correspond to anything to change ...
First I want to know if it is good at you that I put the bitcoin to change
in ethereum ?????
That I understand why I have everyone on the back ..
Then as if I was 11 years old, explain to me that I have been doing for 3
days without sleeping between work on pc, and accountants in front of me
who talk to me about numbers the only time of year when all citotyen even
The accountants without laughing ... Vienna in a bad mood ... So that I
recheck all their tax returns on the income of 2016 ... Imagine me all
derrierer with my pc, all min my ding messaging, And Hop I lost the son of
my mails, in the middle of a hundred mail, in all languages, and
nationality.All as inconprehensible as the others ... Go.year days, .I will
wash a good coffee, today I'm on holiday xd ... Come on, in one hour, with
the webcam for example ... will be easier to make yourself understand,
I will have at least the pleasure of seeing a sacred boy who put me, like
never people in an Olympic shit.
Say thomas thank you to you too for your patience, at the same time you
know what you are talking about, but with a deaf frankly I had no time
between messages, my clients in front of me, talking money and accounting
WHA, in this story, you will see me will be the loser ...
But at least I will have known you ... Thank you


2017-07-01 9:09 GMT+02:00 ThomasV <notifications@github.com>:

**Comment by ptilancelot** [comment]
Ah finally I begin to understand ..... there is mining too.
C like me it at 2 months the ETHER was at 80e the bitcoin at about 900e
Look frankly at his days, he has something to cheer
Bitcoin

                                       LOOKS IT HAS WHAT PT THE PLOMBS.
AH YES LOOKS AS SEE I WRITE ON COINBASE


Ethereum Transaction Delays
We're currently working through a backlog of Ethereum withdrawals. Recent
or new outbound transactions may remain pending longer than expected.
Bitcoin
·
2 188,99 €
Ethereum
·
238,49 €
Litecoin
·
34,58 €
1H
1D
1W
1M
1Y
ALL
34,58 €
LITECOIN PRICE
+9,50 €
SINCE LAST MONTH (EUR)
+37.88%
SINCE LAST MONTH (%)

2017-07-01 9:28 GMT+02:00 pti lancelot <pti.lancelot@gmail.com>:

**Comment by ecdsa** [comment]
I added the option, but I did not remove the coin selection policy choice; 
the privacy policy must first be fixed, so that it prioritizes confirmed inputs, when the option is disabled.
