### ISSUE TITLE
Signing message with multisig wallet

### ISSUE THREAD

**Issue by RCasatta** [spesmilo/electrum#2408]
Hi,
I would like to sign message from a multisig wallet.

Ideal solution would be using the multisig "3" address and passing the partially signed message around cosigner (the sameway transaction are signed)

Less ideal solution would be to sign with a single sig address "1" derived from every cosigner xpub.
I tried to derive /0/0 from my xpub but when I try to sign a text message with that address I receive "Address not in wallet"

Is it somehow possible to sign text messages with a multisig wallet?

**Comment by dabura667** [comment]
I know of no standard library for doing such a thing. So if it were implemented in Electrum, only Electrum would be able to verify it until every other wallet supported it.

**Comment by ecdsa** [comment]
you do not sign a message with an address, but with a public key.

**Comment by fresheneesz** [comment]
How can you easily verify your multisig wallet partner still has access to their keys? I was hoping the signature interface would allow me to sign something with the individual private key of one party, in such a way that the other party could verify it. Is that not possible?

**Comment by SomberNight** [comment]
@fresheneesz There is currently no way in the GUI/CLI to sign/verify a message with a privkey/pubkey; only "with" an address. If someone implements this, it could get merged, most certainly for the CLI. It does not look difficult to do; you need to implement a way in the wallet to find the corresponding privkey for a pubkey, everything else is trivial.

If you want a workaround right now, you can encrypt a message to your cosigner's pubkey, and if they can decrypt it and tell you the contents, they still have the key.

**Comment by fresheneesz** [comment]
That sounds like a reasonable workaround. Doesn't look like an intuitive workflow tho. In particular, I'm seeing the following usability issues:

* There's no indication of which cosigner key is yours (ie the corresponding private key is held by this wallet) and which one is from an outside cosigner. 
* The encrypt/decryption UI is unnecessarily confusing, where if you're doing decryption, you put the encrypted message in the bottom field, and if you're doing encryption you put it in the top field. I can see this being useful in testing that the feature works correctly, but its an odd interface to use an input field as an output field (and vice versa) in different cases.
* Where in a normal wallet, you can right click on an address and use it to either sign or encrypt/decrypt, in a multisig wallet, that option is gone. Using one of the master public keys doesn't work here (brings up an error). Using one of the public keys in the details of an address brings up the incomprehensible message "m 1, n 66" seemingly no matter which public key I use. 

The last problem there is the biggest blocker, since at this point I don't know how to encrypt something with this multisig wallet.

**Comment by SomberNight** [comment]
@fresheneesz 

> Using one of the public keys in the details of an address brings up the incomprehensible message "m 1, n 66" seemingly no matter which public key I use.

I see. That's a bug. Please open a separate issue for it.

**Comment by fresheneesz** [comment]
https://github.com/spesmilo/electrum/issues/5856
