### ISSUE TITLE
Electrum Fees

### ISSUE THREAD

**Issue by jeremy4d** [spesmilo/electrum#2483]
Hi. I'm trying to send .5 BTC of which I have available in this wallet. However, it's saying I can only send ,413 BTC and charging a fee of over .08 BTC. Any ideas why this is the case? I'm currently running version 2.7.13. Thanks.

**Comment by dabura667** [comment]
You have a lot of inputs. There's nothing you can do, really, except send at a lower fee and hope that it confirms (it probably won't).

**Comment by jeremy4d** [comment]
Thank you. I haven't sent BTC in a few months. Last time the fee was .004. Have the fees gone up this much in the past few months? A .08 fee on a .5 transfer equals a 16% fee. Thank you, again for your help!

**Comment by gits7r** [comment]
@jeremy4d it depends. If your .5 is comprised of one input, 16% fee is of course huge. But my guess is that your .5 is comprised of many small inputs, case in which the fee can be high yes, because the fee depends on the size of the transaction in bytes, not the amount. A 10 BTC transaction can very well have a lower fee than a .1  transaction, in case the first one has one input and the second one 20. You can go to the tab "Coins" in latest Electrum to see how many inputs you have that comprised form .5

**Comment by ecdsa** [comment]
you can also click 'preview' to see how many inputs the transaction uses
