### ISSUE TITLE
Error Electrum Wallet "no Data" for 10 days

### ISSUE THREAD

**Issue by shshsgh** [spesmilo/electrum#2528]
cant trade with electrum wallet, because it shows "No Data" "no fx trade available" .how can i fixed this?
what is with my money? it is the new version ,

electrum have no customer support

**Comment by bauerj** [comment]
> electrum have no customer support

Indeed, especially since you are not a customer.


-----

Please note, Github issues are meant for bug reports only.

To get support using Electrum, take a look at either

* https://www.reddit.com/r/Electrum/ 
* IRC #electrum on [Freenode](http://webchat.freenode.net/)
* https://bitcointalk.org/index.php?board=98.0

instead.

Also: see #2525

**Comment by bauerj** [comment]
I answered your question here: https://www.reddit.com/r/Electrum/comments/6hqa6u/help_no_fx_rate_available/

**Comment by shshsgh** [comment]
@bauerj thank you so much for your help , it  works now ;)

**Comment by shshsgh** [comment]
now it is the same problem like bevor.  will wait of a new update
