### ISSUE TITLE
cannot sing messages with this type of address

### ISSUE THREAD

**Issue by dedoaltmann** [spesmilo/electrum#2564]
Hello,
please help. I need  Sign a message Electrum.
I downloaded new version. I have found right option (Sign a message Electrum), have found my address with bitcoin, after the typing a pass I have receive -cannot sing messages with this type of address.

how can I solve this problem?

regards,

**Comment by bauerj** [comment]
Is it a P2PKH address?

**Comment by dedoaltmann** [comment]
I took it from Electrum  addresses receiving..
p.s. what does it mean P2PKH?

**Comment by ecdsa** [comment]
you cannot sign a message with a multisig address, because it does not make sense.
"signing with an address" actually means signing with a private key, and verifying with the corresponding public key. a P2SH address does not have a unique public key, so the verifier will not be able to verify the signature.

it would be more productive to explain what is your use case, and what you expect

**Comment by dedoaltmann** [comment]
I would like to do same like here.
https://www.cryptocompare.com/wallets/guides/how-to-sign-a-message-with-electrum/

same wallet, why in guide is it possible?

**Comment by ecdsa** [comment]
I already explained you why.

**Comment by EagleTM** [comment]
Use case here might be proof of control of a multi-sig payment hash ("has private keys") for distribution of airdrops like Stellar Lumens / Byteball. They usually require a signed message from the payment hash which has a balance so you are allowed to link it to the distribution of coins.

**Comment by ecdsa** [comment]
@EagleTM  I guess that's why some users requested access to the redeem script
