### ISSUE TITLE
[bug] KeyError: 'type' in Wallet.add_transaction

### ISSUE THREAD

**Issue by dabura667** [spesmilo/electrum#2576]
During initial sync of a wallet that has 78 addresses used, this error appeared in the console and syncing hangs forever.

Restarting results in the same error, except this time the history actually displays partially, but it is completely messed up.

I can send the xpub if necessary.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 845, in run
    self.wait_on_sockets()
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 839, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 625, in process_responses
    self.process_response(interface, response, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 577, in process_response
    callback(response)
  File "/usr/local/lib/python2.7/dist-packages/electrum/synchronizer.py", line 146, in tx_response
    self.wallet.receive_tx_callback(tx_hash, tx, tx_height)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 663, in receive_tx_callback
    self.add_transaction(tx_hash, tx)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 585, in add_transaction
    is_coinbase = tx.inputs()[0]['type'] == 'coinbase'
KeyError: 'type'
```

**Comment by dabura667** [comment]
AHHHH

Found the cause using -v

```
cannot find address in input script 5355540b6f93598893578893588851
```

I previously used this wallet to receive funds from a P2SH workshop I did with some students, so my history contains a transaction where the input won't be parsed properly.

**Comment by dabura667** [comment]
The address that sent to my wallet https://insight.bitpay.com/address/3MbZjYS1Kjo5An9vVCwZYTd2JeobwjUsFh

The redeemscript: 6f93598893578893588851 (OP_3DUP OP_ADD OP_9 OP_EQUALVERIFY OP_ADD OP_7 OP_EQUALVERIFY OP_ADD OP_8 OP_EQUALVERIFY OP_TRUE)
The scriptSig part before the redeemscript: 535554 (OP_3 OP_5 OP_4)

**Comment by ecdsa** [comment]
is that a watching-only wallet made with addresses?

**Comment by ecdsa** [comment]
are you sure you had this issue with master?
type is already set to 'unknown' line 419

**Comment by ptilancelot** [comment]
Please, let me wake up it is 5am in the morning, Indeed I am overflowing
with thousands of messages for 3 days ... I myself put around 50th 2 months
ago that I do not find on my computer ... Explain me, please let me one
more one hour ..
He to 3 days with the mediator Thomas that he also send me a hundred
messages and want to explain ... Then he tells me it's not my fault it's
home. But the more I am sent messages, the less I understand site. I am new
1moi 1/2 that I try alone to understand first wallet, then the games
primedice, bitsler,
And a lot more, mining that I have always understood nothing and only
maintainat the crypto, bitcoin ether etc ... wallet I have all tried ...
Except late May or I put 50e On coinbase at 900e without knowing the
bitcoin and then I wanted to change into etherer ...
Luckily I got messages because it was 1 1/2 and I was more the site or how
I changed the 50euro ..
So here I am for 3 days on a site trying to solve a problem, including
French and the only language not translated ... more they speak to me in
all languages ​​...
If anyone can tell me,
If my money is still there, if yes in bitcoin, ether, ... What is there to,
since it to me 2 an 80th ether ether, now it's much more, the bitcoin was
at 1300eur now about 2600euro ...
I do not even see my money, just a site with codes, people who go and leave
... send me messages in all languages,
With always some letters or numbers whose existence I do not even know ....
Understand well for my first faith, beautiful placement in 2 me ... if the
change to was taken into account ???? But frankly there, with the fall of
the eter, all his messages, sometimes even naughty..EN full work must at
least answer to the mediator. It is called thomas
... very cool, but without the translation, to explain with words of which
I do not know the meaning to remove a thing and I see it, numbers that
serve no purpose ... Because it does not correspond of all to a Key wallet
... except yesterday A LITTLE ANGEL I HAVE MADE AN ETHER ADDRESS OF
COINBASE TO THE MILLIEUX
IF I COULD KNOW IN 1
If my money is there?
2
For what purpose all the world is on my 50th in bitcoin, it's little money
where 4 to 6 faith more ..
Especially first, so that I understand if I understood correctly ... My
50th or 0.002bitcoins are there ... Because if it falls ... is not even
that of which one speaks to me
Yet I swear,
Without knowing the cripto I wanted to just try with 50euro that I lost
track since the now more than 1 and a half
As I did not know how to sleep all in 3 days, in addition I work on my
PC..In return I spend my nights to have to do my job on computer ... With
potential customers in front of me ..
I am tired either of wasting my time, or trying to do a few things without
taking any risk for me, or for you. And yet I'm pretty good ... But there I
do not know what one wants me ...
Please explain to me as if I was 11 years old, with sentences ... With a
French translation that I understand all ...
And why on my addresses, what it serves you ???? Se site I lost it ...
still today it will seem complicated
I leave you and I made a copy paste for others ....
Time to drink one or two coffees .... wash me, etc..and banf
Here is the Thomas mediator who starts again to send me the same thing that
figures to change
..... I am going to be able to communicate by webcam .... Will be a good
idea .... But in what languages ​​????

2017-07-01 5:47 GMT+02:00 Dabura667 <notifications@github.com>:

**Comment by dabura667** [comment]
I was using 2.8.3 apparently. master works.
