### ISSUE TITLE
No FX rate available

### ISSUE THREAD

**Issue by Emmmmmmmm** [spesmilo/electrum#2585]
Hi since more than one month there this message on your page wallet.... I already sent you a message about this problem you replied, issue was know, OK, but WITHOUT OTHERS EXPLANATIONS..... Please could you indicate when the information about rate will be on line again ? 
That really embarrassing and if this bug continues, I ought to search another wallet, that would be pity.
Thanks for your attention
Regards

**Comment by EagleTM** [comment]
bitcoinaverage changed their API from one day to the other.
It's fixed in git head, so if you can install from source do so.
For most currencies you can select another rate provider in the settings (like winkdex for USD)

It will be fixed in 2.9 which is currently being prepared for release. I agree it would have bee nice to fix this with another 2.8.x release but there was little time to do so.

**Comment by EagleTM** [comment]
One other note: There are other providers availble for EUR for example if you switch off "Historic Rates" which is at least useful for converting your current tx / fees in EUR
