### ISSUE TITLE
Multiple improvments, see comment.

### ISSUE THREAD

**Issue by trugihr** [spesmilo/electrum#2650]
1. Wallet->History->Plot requires matplotlib module, which is not included in the default installer of 2.9.0, so an error pops when you click "Plot".

2. When you start up electrum and the default wallet contains no addresses, status bar will display "Synchronising...", though I don't think any actual synching takes place as there are no addresses. (Create a standard wallet, use importing private key for a single address, then remove this address from "Addresses" tab, you will get empty wallet with no addresses).

3. When you remove imported address from "Addresses" tab, it's label and all relevant address and tx history is not removed from the wallet. I think "Remove" should mean "completely delete everything related to the address".

**Comment by helpau** [comment]
scenario 1-Discussed in #6328
scenario 2-Now every wallet contains at least 1 address(or you'll got error "Cannot delete last remaining address from wallet"). By the way, is this expected for wallet where all addresses are imported?
scenario 3-I cannot reproduce(I tested with 2 imported addresses because of error from scenario 2)
I think issue can be closed
P.S. I didn't use console, probably scenario 2 can be reproduced
