### ISSUE TITLE
Electrum hangs when providing Trezor passphrase longer than the 50-character limit

### ISSUE THREAD

**Issue by stevenroose** [spesmilo/electrum#2670]
I recently tried to setup a Trezor with a passphrase. When entering a passphrase that is longer than the 50-character limit, the "please wait..." window stayed there forever (somehow also taking 15% of my i7 CPU).

It should either know about the 50-character limit or detect that the Trezor behaves wrong or refused the passphrase.

**Comment by stevenroose** [comment]
Also, they [confirmed](https://twitter.com/TREZOR/status/891959161218412546) that it's an arbitrary choice to put a 50-character limit on the passphrase. While the BIP39 spec doesn't mention a limit on the passphrase.

**Comment by prusnak** [comment]
There is surely a bug in Electrum. Because it should not hang and should not eat your CPU. This is worth fixing.

I am not able to increase the limit without major rewrite of the code, which will not happen. (The reason is that the whole passphrase needs to fit into one USB response which is 64 bytes and some bytes are already used by our protocol).

**Comment by gernotpokorny** [comment]
I cannot write in #203, because it got archived. I hope you don't mind me writing this here. If you don't like it, then please inform me and I open a new issue.

I do not agree at all that this is no important issue.

Please let me explain.

Actually the 50 character limit is a major issue in regards to wallet recovery in case of a single letter failure within the backup (or much worse multiple letters, which I explain below). 

If you use a long passphrase, then using a 12 word bip39 seed phrase as a passphrase with a checksum actually makes sense from a wallet recovery perspective in regards to storing your crypto safe and securely if you want to use a passphrase. I read on reddit that many people are doing this it seems with other wallets, but it is not possible with Trezor. Having a checksum in the passphrase is useful for recovery purposes in case of errors within the backup. If you don't use a bip39 seed as a passphrase, but instead a 50 letter random passphrase, you essentially made your chance of wallet recovery much worse in case for example two characters are missing within the backup. Even if you are using as an example a 20 character random string as a passphrase it is also much more susceptible to errors within the backup. You do not want your passphrase become the weak point, but with the 50 character limit it becomes the weak point.

With a bip39 seed phrase as a passphrase you can use common recovery tools on an offline PC in case of errors within the backup. The checksum is very useful there. If you do not have a checksum and you miss two letters of a 20 character random string passphrase then I don't see how you would be able to recover from that without spending an immense amount of time writing code and exposing the seed on a PC connected to the internet trying to brute force and check if funds are in the hidden wallet. And if too many characters are missing that becomes unfeasible. That sounds absolutely horrible to me and a situation that nobody wants to be in.

Actually this is one thing that I really do not like about Trezor, because this is bad and there is no argument to not remove this limit. The argument made by the Trezor team was it is not important enough, but as I outlined above it is definitely important and can potentially result in the loss of funds.

By the way using only the first 4 chars of a 12 word bip39 seed also weakens the ability to recover a wallet compared to using the full words, if you would want to suggest that. It would also become the weak point if your actual recovery seed backup does use full words, which it always should with a 12 word seed.

50 random characters without checksum is much more error prone to backup failure then a longer passphrase comprised of a 12 word bip39 seed which includes a checksum. 

The 50 character limit for the passphrase decreases the ability for people to secure their crypto securely if they use a passphrase as outlined above.

This is my understanding of this issue.

I would be happy to hear that this 50 character limit finally gets removed for the good of all.

Thank you for taking it into consideration.
