### ISSUE TITLE
Electrum asking for Google Authenticator code but it was never set up!

### ISSUE THREAD

**Issue by MSzlas** [spesmilo/electrum#2677]
Hi Everyone,

I have set up my Electrum wallet v 2.8.3 a month or so ago. I transferred my BTC to it just before the hard fork on the 1st of August and since, when trying to send the BTC back to my trading platform to sell, I am being asked for my password, then for my Google Authenticator code - which I have never set up! 

This prevents me from being able to send my BTC anywhere at all and I have been searching the web for a long time to find out how to fix this but can't.

Any and all help would be appreciated!

Thanks

Michal

**Comment by AbdussamadA** [comment]
do you know the seed of your wallet?

**Comment by CoinDiver** [comment]
I have the very same problem! 
Yes, I know the seed of my wallet.

**Comment by MSzlas** [comment]
Hi

I don’t have the seed to my wallet anywhere, trying o find it at the moment…

Is there any other way?

I dont understand why its asking for a second signature if I didn’t set one up.

Cheers

Michal

**Comment by CoinDiver** [comment]
You can find the seed in the bottom right corner where it's a button with the picture of an actual plant seed. 
With the default wallet this button is missing and the Seed can be found in the upper left corner in the dropdown menu of wallet. Unfortunately it's greyed out, which is yet another problem...

**Comment by ecdsa** [comment]
coindiver: 2FA wallets do not have the seed stored on disk, that's why it is greyed out.
if you know your seed, then you also probably remember if you created a standard wallet, or a 2FA wallet. In any case, restoring from seed will give you the answer.

**Comment by CoinDiver** [comment]
I know the seed, but when I enter it, it will still stay greyed out...

**Comment by ecdsa** [comment]
@MSzlas if you never set up a 2FA wallet, it is very likely that someone else installed that wallet on your computer. (the other possibility is that you don't remember what you did)

**Comment by ecdsa** [comment]
@CoinDiver that means you don't know the seed, or you made a typo

**Comment by CoinDiver** [comment]
I didn't. Does it not get accepted if it's copy pasted? 
And what about the other problem, about needing a google authentification even though that was never set up in the default wallet?

**Comment by ecdsa** [comment]
what I wrote above: someone else created that wallet

**Comment by ecdsa** [comment]
closing; there is no bug here

**Comment by CoinDiver** [comment]
That's absurd. When I installed electrum, I chose default_wallet. I was then given my seed in form of 12 random words. 
A two factor authentification wallet was never created and neither did I spell any words wrong. 
I didn't get hacked or anything. Doesn't it strike you at all curious that two persons (as of yet) have the exact same problem at almost the same time? 
So you're saying that I got hacked at some point and now I can look at my funds, but am unable withdraw them or send them to another wallet?! 
That is inacceptable! 
I don't think I was hacked. Why would the Hacker leave my funds in my wallet? To taugt me? No no no, the more logical explaination is that something go es wrong when you Set up a default_wallet (not standard), so that the System expects a 2 factor authentification had to be Set up when choosing the Option default_wallet. 
This is a dilemma, because a 2 factor authentification cannot be implemented after the default_wallet has been activated. 
Which is something I don't understand. It should be possible to switch wallet types afterwards, just like in any online wallet or exchange. 
This is a travesty! Please help me to get Access to my money! 
Please add the Option to choose 2 factor authentification after you already chose a wallet type! 
I tell you something is wrong with the default_wallet! Another signalisiert is that the seed Button doesn't Show up in the lower right corner. 
Please help me / us !!!



-------- Ursprüngliche Nachricht --------
Von: ThomasV <notifications@github.com> 
Datum: 03.08.2017  09:38  (GMT+01:00) 
An: spesmilo/electrum <electrum@noreply.github.com> 
Cc: CoinDiver <paradoxone@gmx.net>, Mention <mention@noreply.github.com> 
Betreff: Re: [spesmilo/electrum] Electrum asking for Google Authenticator code
  but it was never set up! (#2677) 

what I wrote above: someone else created that wallet

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.That's


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spesmilo/electrum","title":"spesmilo/electrum","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/spesmilo/electrum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ecdsa in #2677: what I wrote above: someone else created that wallet"}],"action":{"name":"View Issue","url":"https://github.com/spesmilo/electrum/issues/2677#issuecomment-319893059"}}}<span>​</span><span>​</span><span>​</span><span>​</span><span>​</span><span>​</span>​​

**Comment by ecdsa** [comment]
It is not possible to add two-factor authentication to an existing wallet. these are two different wallet types. Either you created this wallet, or someone else did. And if it is someone else then your funds might have been stolen.

**Comment by ecdsa** [comment]
it is quite possible that a hacker infected several machines at the same time; 
to know about that we would need a real investigation of your computer.

**Comment by CoinDiver** [comment]
And how would I go about that?

**Comment by CoinDiver** [comment]
Well, shit... 
I've never been hacked before. Ironically right when I try to up my security by getting on an offline wallet where I control the private key, I get jumped. So much for security with Electrum. 
I should have left my funds on the exchange. 

One thing is certain. I will tell everyone I know that Electrum has been hacked and hackers are waiting for you when you go on Electrum. 

My other funds on the exchanges are still safe, only Electrum was compromised, so yeah...

**Comment by MSzlas** [comment]
I managed to find my 12 word seed password and reinstall the wallet.

I dont know but hope this will be helpful to you, here is what I did:

- Find my 12 word seed
- Create / Restore a wallet 
- Create a new walled and name it something else
- during the installation process, pick that you want a wallet with 2FA
- also during installation, choose the restore from existing seed option
- it will ask you to put the 12 words in, then proceed with the installation
- It will ask you to create a new 2FA authorisation if you don’t have your current one and give you the barcode to scan with authenticator 
- once the installation is done, it will look like your old wallet, but now, you have set up your new 2FA which you can use to transfer the money you previously couldn’t.

Thats how I fixed it and thats how I just managed to transfer my funds back onto an exchange :)

Hope it helps

Michal

**Comment by ecdsa** [comment]
@MSzlas this means that your 12 word seed was a 2FA seed. 
with a standard seed it does not give you that option.

**Comment by CoinDiver** [comment]
I created a new wallet and transferred my funds onto it, once I found out that the way to go was not with google authentificator, but with Free OTP. 

Now, if only someone would explain to me, how I can get access to my Bitcon Cash coins...

**Comment by MSzlas** [comment]
Yes, I would like to know how to claim Bitcoin Cash also! :)

**Comment by CoinDiver** [comment]
I just had the Electron Cash wallet open for some time and now the status has changed to a green mark, meaning verified I guess. I didn't have to do anything. Maybe you just had to wait for a few transactions on the blockchain to clear and then the Bitcoin Cash in your wallet will automatically become available?

**Comment by AbdussamadA** [comment]
This repo is not for electron cash so please discuss that elsewhere.

**Comment by bern8** [comment]
Hi All, I have almost the exact same problem as the above contributor. I could not remember my 2fa setup and deleted my google authenticator in my old phone. 
When I tried to move funds recently, it asked for my OTP, which i obviously wont have. 
I restored my wallets (v2.8.3) but all were empty while my default remained locked. (I am pretty sure I have the seed correct as during the creation of the original wallet, you are asked to rekey them to confirm.) 
I had tried restoring, using the same seed, setting up standards as well as new 2fa wallets with google authenticator (enabled and disabled ones), but the wallets are still empty.
at my wit's end now. pls assist...many thanks in advance

**Comment by heavyluck** [comment]
maybe some of you guys do not know that electrum is protected by trustedcoin, this means you have to look for TRUSTEDCOIN.COM in your Authenticator not electrum or something else. 
hope that this will solve some of your problems.

**Comment by hmroep** [comment]
I have a big problem. When I did set up my wallet, I think I have set up a standard wallet. I have written down my password and one rule with 34 caracters. This I keep in my safe. That is all I needed to store. I cannot remember I got a seed. But when should I gotten it, I would have written it down to. So, I HAVE NO SEED!
Now my Wallet is 2fa... And I cannot get to my Bitcoins. I need a second code, but do not know how. Installed Authenticator, but that ask for A code to scan or a delevered key. Can somebody help me out?

**Comment by bern8** [comment]
Write to trustedcoin. They may be able to help.
Cheers

**Comment by hmroep** [comment]
Thanx! I Did write to them.

Greetings,
Hans


2018-01-15 18:07 GMT+01:00 bern8 <notifications@github.com>:

> Write to trustedcoin. They may be able to help.
> Cheers
>

**Comment by hmroep** [comment]
Hello Bern8,

Thank you very much for your tip! They did help me!

Best regards,
Hans M. Roeper


2018-01-15 18:07 GMT+01:00 bern8 <notifications@github.com>:

> Write to trustedcoin. They may be able to help.
> Cheers
>

**Comment by ssghost** [comment]
I have the same problem. I have written down my seed words. So how can I cope with the Google Authentication?

**Comment by ssghost** [comment]
sorry I never set a Google Authentication code, when I reinstall the walley, it's only a default wallet to choose, I have a google authenticate APP on my phone, but don‘t know how to generate the google code.

**Comment by hmroep** [comment]
The app automaticly generates the code when you make the wallet.


2018-02-02 13:19 GMT+01:00 Shuang Song <notifications@github.com>:

**Comment by AbdussamadA** [comment]
@ssghost Go to file > new/restore, enter a unique file name, click next, select 2 factor authentication and then follow on-screen instructions to restore your wallet from seed.
