### ISSUE TITLE
Feature Request: Add "Search for updates..."

### ISSUE THREAD

**Issue by MarkusZoppelt** [spesmilo/electrum#2694]
Hi,

could someone please add a "Search for updates..." menu bar item or preference to update Electrum from the application interface itself? At least prompt for an update to let users know that a new version is available.

Thanks.

**Comment by bauerj** [comment]
Hey,

there used to be a notification for new versions in the client but it was removed because of privacy concerns. The client used to check the electrum.org webserver for information about the latest version. This behaviour could have been used to track Electrum users.

However, there are other options to implement such a check. For example, the information about a new version could be stored within the blockchain. The client could use the existing server API to get that information. @ecdsa what do you think about that?

**Comment by ecdsa** [comment]
there's no reason to use the blockchain for that. 
the latest version number could be queried from electrum servers, without being on the blockchain.

**Comment by dabura667** [comment]
> This behaviour could have been used to track Electrum users.

This is the biggest concern with such a feature.

**Comment by bauerj** [comment]
> the latest version number could be queried from electrum servers, without being on the blockchain.

Yes, but kyuupichan was against adding such a feature: kyuupichan/electrumx#184.

**Comment by AbdussamadA** [comment]
github has atom feeds for tags. perhaps users could subscribe to those?

**Comment by skyerjoe** [comment]
> Yes, but kyuupichan was against adding such a feature: kyuupichan/electrumx#184.
what are you kidding ?

I think when things like [this](https://motherboard.vice.com/en_us/article/ev55na/electrum-bitcoin-wallets-were-vulnerable-to-hackers-for-two-years-json-rpc) happenyour have other problems to track the behaviour if an user is updating or not.

so do this immidiately 
It will improve electrum against threats like this cause many people dont search for an vulnerabilty all day

**Comment by MarkusZoppelt** [comment]
I think this can be marked as done, right?

**Comment by MarkusZoppelt** [comment]
I think this can be marked as done, right?

**Comment by bauerj** [comment]
Sure
