### ISSUE TITLE
Update https://electrum.org/bcc2.txt to stop scamming 

### ISSUE THREAD

**Issue by fyookball** [spesmilo/electrum#2696]
There's already imposter sites of electroncash.org with people getting scammed of both BCC and BTC.  To avoid this, you should link the correct url.  Please add this paragraph:

There are already imposter sites for Electron Cash, so be careful.  
If you choose to run Electron Cash, download it from their official site electroncash.org.

**Comment by AbdussamadA** [comment]
go to bitcointalk forums, remove the link to that shitty article in your sig and add one for electroncash.org instead. you have 8k posts on that forum so doing that will elevate your site to the very top in the search engines and the scammer's sites will be drowned out.

**Comment by ecdsa** [comment]
@fyookball there is no reason to believe that the binaries distributed on your website are safer than on the other websites. Since you are anonymous, you too could use the binaries to steal private keys. In these conditions, it is astonishing that you are asking us to endorse your website.

If you want to improve the safety of electron cash users, I believe you should do one of the following:
 - stop distributing binaries, distribute only source code
 - disclose your real identity, and sign your binaries with a trusted pgp key
 - let someone else sign and distribute the binaries

**Comment by fyookball** [comment]
@AbdussamadA good suggestion.  
@ecdsa  i have asked others in several reddit posts to build binaries.  I'm not asking for an endorsement, you are already telling people to build binaries.   Do whatever you want.
