### ISSUE TITLE
Feature request: Show unconfirmed balance rather than unconfirmed spend

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#2708]
In the balance section, if you have unconfirmed transactions, it shows you the total transaction amount that is unconfirmed next to your balance. This doesn't really make sense to me, and means that if I need to spend the last bitcoins in my wallet, I need to do some math (or simply take for granted that "Max" is doing its job properly) to figure out what my balance is. Instead of displaying the unconfirmed transaction total, it should display your unconfirmed *balance* (since it is labeled "Balance" after all)

For example, if I have 30 bitcoins and send 25 of them somewhere, the Balance section will say:

"Balance: 30 BTC [-25 unconfirmed]"

What I'd like it to say is:

"Balance: 30 BTC [5 unconfirmed balance]"

**Comment by bauerj** [comment]
> "Balance: 30 BTC [5 unconfirmed balance]"

That sounds even more confusing.

**Comment by fresheneesz** [comment]
How? How is it not more confusing to give you a sum of transaction amounts and label it "balance [unconfirmed]" ?

**Comment by bauerj** [comment]
Maybe "Balance: 30 BTC [5 BTC confirmed]" would make more sense.

**Comment by fresheneesz** [comment]
No.. I don't think that makes sense. That would imply that there are 25 unconfirmed btc on its way *to* your wallet, which is the exact opposite of what's happening in this case.

**Comment by ecdsa** [comment]
no

**Comment by fresheneesz** [comment]
@ecdsa Wow, these may be among the rudest responses I've ever seen on a github repository. The current way its done is confusing and unhelpful. Neither of you can even show me enough respect to give me a rebuttal? Really makes me lose respect in this project.

**Comment by ecdsa** [comment]
Sorry but I think @bauerj already answered; what you propose would be even more confusing.

I believe your main problem is that "max" does not send all your coins with the default settings, and I just fixed that by changing the default setting (see other commit). 

For the rest, you'll have to accept to do some mental math, because there will be mental math no matter how we show this information.

**Comment by dabura667** [comment]
nack

I also think the way it is currently is fine.

**Comment by fresheneesz** [comment]
> Sorry but I think @bauerj already answered

Saying "i don't like that" is not a productive answer. He gave literally 0 reasons for his opinions. dabura667's response has the exact same problem - no reasons, no discussion. Just a shut-down. That's disrespectful. 

> there will be mental math no matter how we show this information.

This I'm interested in. It goes along with my question above "what are people expected to do with that number?" What mental math do people have to do if we change to the way I'm suggesting? Why would anyone ever use the sum of unconfirmed BTC current being sent? It seems like a useless piece of information to me. I'm very curious why you disagree. Perhaps a compromise would be to show both pieces of information in the bottom bar?

I have one more suggested option for this change:

"Balance: 30 BTC [5 after pending transactions]"

**Comment by dabura667** [comment]
> "Balance: 30 BTC [5 unconfirmed balance]"

I showed this to my wife, and asked her what it meant, she said "oh, after unconfirmed balance is confirmed, the balance will be 35 BTC"

> "Balance: 30 BTC [-25 unconfirmed]"

I showed this to my drinking pal, and asked him what it meant, he said "oh, after the unconfirmed is confirmed the balance will be 5 BTC"

These two people knew nothing of Bitcoin, I primed them by saying that "in bitcoin, transactions are "confirmed" every 10 minutes or so, and thus, some wallets like to separate the confirmed balance and the unconfirmed balance"

Also, Re: the snippy quips about "productive answers":

An issue is a place where **the issue maker has the onus to convince the maintainer that their idea is good enough for someone to actually code it**, which is a high hurdle to overcome. A slightly lower hurdle would be if you _ACTUALLY CODED IT YOURSELF_. Then the question would be "does this code break anything, and is the feature something we want for the wallet?" and the work required of the maintainer is testing, and decision making only.

Imagine this scenario: Someone makes an issue saying "I THINK WE SHOULD MAKE THE APP ALL GREEN BECAUSE GREEN IS THE COLOR OF MONEY."

Do I really have to send out a survey to 6000 users and do quantitative analysis of whether or not green will increase usability or not and write you a 500 word reply on why your idea is wrong?

No. No I don't owe you that. I am not associated with Electrum, and even if I were the maintainer, I don't owe you anything. It's not a matter of respect. Your issue really has no meat on it to pick at or discuss any further than "no, that's more confusing." < "well, that's a matter of opinion isn't it." < "ok, then who's opinion matters?" < "The maintainer's"

And since we're just arguing opinion here, I gave mine, which is no.

And now I have wasted a few minutes of my family and friend's time to see what their opinions are, and they agree. And many others agree.

This is not an attack towards you, by the way (since you have shown that you are the type to take offense to these types of things already), and your life will be much less stressful.

**Comment by hachre** [comment]
I think the OP has a point in that a balance and a sum of transaction values is being mixed into that line without further clarification. It also wasn't clear to me what it meant the first time I saw it. 

If you wanna do something about it, there's two ways to fix this:
- make the language more precise (e.g. explain that the sum in brackets is not a balance)
- switch to making that entire line only show balances (one with and one without taking into account unconfirmed transactions)

Banks have the same thing in their online banking: While a money transfer is pending, it is being listed in your transaction list in an unconfirmed section, but the balance remains unaffected. They always primarily show the balance that is currently confirmed (just like Electrum). However, some banks additionally show a second balance below the confirmed one, which is usually written in a different color and with smaller font that says something like "balance after pending transactions". None that I've seen show you a sum of pending transaction values near the balance the way Electrum does.

The most simple solution to make this more clear is expand the wording to something like this maybe:
`Wallet Balance: 30 BTC | Unconfirmed Transactions: -25 BTC`

**Comment by ecdsa** [comment]
The "balance after pending transactions" is always positive value.
A positive value is ambiguous, because it can be two things:
 - the balance after pending transactions
 - the sum of unconfirmed coins in the wallet.
Note that these two things are identical in the case of an incoming transaction. They differ for an outgoing tx because of coins sent to change addresses. Newbies are unaware of this.

I prefer to have a negative value, because there is no confusion about what it is

**Comment by fresheneesz** [comment]
@dabura667 

> "I showed this to my wife... I showed this to my drinking pal... Do I really have to send out a survey"

I was hoping this would be a discussion where we could come to an agreement on how to improve Electrum. I'm not looking for market research on every suggestion, and I think you know that. I think my most recent suggestion would avoid the confusion your wife had. 

> if you ACTUALLY CODED IT YOURSELF

I'm not gonna code shit on any project unless I have some assurances my work will be accepted.

> I don't owe you anything

No you certainly don't. But if I were a maintainer, I would ignore your opinion unless you followed it up with valid reasons. I also do that as a non-maintainer...

> you are the type to take offense

I like Electrum, I would like it to improve. I'm not simply "taking offense" - I'm trying to tell you that shutting down suggestions from your users without offering any kind of reasonable discussion is bad for any project. And I don't want to see this project go down in flames. I'm sorry if I'm impatient with people who refuse to give me the benefit of the doubt and have actual non-sarcastic discourse. 

@ecdsa 

> A positive value is ambiguous

The current way Electrum does it will show a positive number as "unconfirmed" if you're receiving transactions. Isn't that ambiguity also a problem?

@hachre 

I like how you broke down the solution space there. However, I think simply switching to make the entire line only show balances, without also making the language more precise, doesn't get us all the way there. So I'd say any solution will involve more precise language there.

**Comment by ecdsa** [comment]
@fresheneesz no
