### ISSUE TITLE
Cant open electrum on macOS El Capitan

### ISSUE THREAD

**Issue by lutfime** [spesmilo/electrum#2726]
This is the error

Dyld Error Message:
  Symbol not found: _getentropy
  Referenced from: /Volumes/VOLUME/Electrum.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)

**Comment by ecdsa** [comment]
I recently upgraded macos on the machine I use to generate binaries.
Does it get fixed if you upgrade to Sierra?

**Comment by lutfime** [comment]
Probably it will works correctly if running at Sierra because the framework built for Sierra. Can you lower min deployment target to 10.11?

**Comment by ecdsa** [comment]
I am not sure if I can do that; it was built with py2app

**Comment by lutfime** [comment]
Oh ok. It seems I'll need to use v2.9.2 for now.

**Comment by ecdsa** [comment]
I guess I can try to downgrade macos

**Comment by lutfime** [comment]
Ok, thank you 👍

**Comment by westonal** [comment]
So:
El Capitan -> 2.9.2
Sierra -> 2.9.3

Please put this simple advice on the website. This must affect loads of people. Not may would dig out the github repo to find out problem.

**Comment by verynewb** [comment]
@westonal
hi thanks for this - where can I download 2.9.2

**Comment by ecdsa** [comment]
I set the link to 2.9.2 in https://electrum.org/#download

**Comment by westonal** [comment]
@verynewb There is a link on download page, "previous releases":

![image](https://user-images.githubusercontent.com/6041352/29313238-563df644-818f-11e7-9bdf-2a477754fd05.png)

Takes you here:

https://download.electrum.org/

**Comment by verynewb** [comment]
Thanks! 
of course 

all best
B

Alan Evans <notifications@github.com> wrote:
@verynewb There is a link on download page, "previous releases":

Takes you here:
https://download.electrum.org/
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spesmilo/electrum","title":"spesmilo/electrum","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/spesmilo/electrum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@westonal in #2726: @verynewb There is a link on download page, \"previous releases\":\r\n\r\n![image](https://user-images.githubusercontent.com/6041352/29313238-563df644-818f-11e7-9bdf-2a477754fd05.png)\r\n\r\nTakes you here:\r\n\r\nhttps://download.electrum.org/"}],"action":{"name":"View Issue","url":"https://github.com/spesmilo/electrum/issues/2726#issuecomment-322438259"}}}

**Comment by Leopdspots** [comment]
Hi,
I have also a problem working on OS X El Capitan (10.11.6)
I previously restored my wallet, and clicking on the 'trustedcoin' shield this message pops up:

'This wallet is was restored from seed, and it contains two master private keys. Therefore, two-factor authentication is disabled. '

The problem I have which I don't think is related, but just point this out as I was looking around the wallet for why it won't connect.  Bottom left hand corner says ' not connected'

I could use the wallet after restoring it. This was before the BTC/BCH split.

I have opened it today and the only other change to circumstance are that I have installed on my computer a VPN service. This I have tried both switched off and switched on, neither setting makes a difference.

This is the pop up upon pressing the 'red' network button.

![screen shot 2017-08-22 at 10 50 52](https://user-images.githubusercontent.com/29568303/29559794-f554c0a8-8727-11e7-85e4-c3b322f17378.png)

I was thinking of upgrading my wallet since it is version 2.8.3 and want to use it to transfer BTC from another wallet in order to collect the equivalent in BCH
