### ISSUE TITLE
Wasn't sure if this is a bug, or I am misunderstanding something?

### ISSUE THREAD

**Issue by l3uddz** [spesmilo/electrum#2768]
Im using the latest portable electrum 2.9.3 off the website. Im trying to send some money, expecting around a 2£ fee. Now this is where I am confused, if i set the fee to minimum, and then click max, I am presented with the following: 

![image](https://user-images.githubusercontent.com/7897162/29421751-ec855be4-836d-11e7-821f-1e3eea1f9554.png)

Now either I really suck at math, or does that not seem correct... the last transfer has 8 confirmations, which was made today. So I am a little unsure why this would be happening? Why does it want to charge such a high fee even when I have set it to the minimum? If I set max fee, it wants to send:

![image](https://i.imgur.com/mt2Nnge.png)

Any advice on why this would happen, its not a big deal if I loose the money, I'd just like to learn if its something I have done, so I dont cause it to happen again in the future?

**Comment by dabura667** [comment]
Every time you receive a transaction with bitcoin, you are receiving a single dollar bill with the amount of bitcoin you received in it.

Your balance consists of 11 transactions to make up your 0.01322312 BTC, so you have to stuff 11 dollar bills into your transaction data which is 148 bytes x 11 bills, so 1628 bytes.

Since fees are on a per byte basis. You are paying a TON of money to move everything.

My suggestion: if you received 0.013 BTC one time, and 0.00002231 BTC 10 times, "send max" probably will send less money than only sending the 0.013 BTC bill by itself... not sure though.

Did you receive a similar amount 11 times? or are some bigger and some smaller?

**Comment by l3uddz** [comment]
the last 8 transactions:

![last transactions](http://i.imgur.com/Kfey9Tx.png).  

my goal was to send ~42 gbp worth, but im unable too, as the send box shows an error wanting me to pay 13-14 when I put in the exact amount, even with the minimum fee e.g. ![send box](http://i.imgur.com/GYvS67h.png)

**Comment by l3uddz** [comment]
[0.13 transaction](http://i.imgur.com/nq6N4mz.png) is the only time I have ever received a transaction for 0.13XXXXX in this wallet. I have never received any transactions for 0.0000XXX.

**Comment by dabura667** [comment]
https://jochen-hoenicke.de/queue/#2h

Right now fees are very high.

One way to solve this is to wait for things to calm down.

**Comment by l3uddz** [comment]
Thats perfectly fine with me. I have just never encountered this behaviour before, or fee's as high as this. Thanks for letting me know. I was worried this was a bug, or I had done something to cause this.

**Comment by ecdsa** [comment]
you can also set the fee manually (in preferences)
