### ISSUE TITLE
Request: BIP-39 seed

### ISSUE THREAD

**Issue by fujicoin** [spesmilo/electrum#2833]
Since you started supporting BIP-39 seed, why do not you let the user select and deploy BIP-39(+BIP-44) seed as an option?

**Comment by ecdsa** [comment]
BIP39 seeds can be imported in Electrum so that users can access funds locked in other wallets.

However, we do not generate BIP39 seeds for our users, because they do not meet our safety standard.
BIP39 seeds do not include a version number, which compromises compatibility with future wallet software.

**Comment by fujicoin** [comment]
Hi ecdsa,

Of course I know your way of thinking.
However, electrum users should want to deploy it to other wallets based on electrum's seed.
Well, please think about a little more.

Thanks,
motty
