### ISSUE TITLE
Beaware! You may lose bitcoins with Electrum cold storage!

### ISSUE THREAD

**Issue by ChainSmoker2** [spesmilo/electrum#2836]
Something very weird is happening with this wallet now when using for cold storage.After creating a wallet on offline machine the wallet is created with 20 Receiving Address and 6 Change Address.Exporting master public keys and then importing these keys to Online Machine results in same 20 Receiving Address and 6 Change Address but once the wallet is synced then the problem starts.In Receiving Addresses 4 new addresses are added automatically at the bottom of 20 addresses and that's not all,you don't own these addresses.I tried signing the message using any of these 4 address and it results in error.In offline machine,error is 'Address not found in wallet'.In Online machine,also error which means both machines don't have private keys to this address so if we send bitcoins to these address they will be LOST.I expect some explanation to this from Electrum developer?

**Comment by dabura667** [comment]
What version are you using?

**Comment by SomberNight** [comment]
Have tried doing anything to force the offline machine to generate those extra addresses? Such as increasing the gap limit?
```
wallet.storage.put('gap_limit',50)
```

**Comment by dabura667** [comment]
Signing messages in offline mode is not supported.

You can use it by increasing the gap limit of the offline client.

Signing transactions will work without any gap limit changes. Even if the address doesn't show in the address tab.

**Comment by ecdsa** [comment]
signing a message with an address requires the private key for that address. it will not work if the key has not been explicitly derived.

signing a transaction does not require the private key to be derived. It only requires the master private key or seed and the derivation; that information is serialized in the transaction.

the OPs statements about how one could lose bitcoins because of that are hysterical.
