### ISSUE TITLE
Synchronising

### ISSUE THREAD

**Issue by winsor11** [spesmilo/electrum#2867]
Hi, my Electrum 2.7.9 , standard wallet running on Tails refuses to sync... not a single server work. It gave me a recieve adress i used but nothing came and the wallet does not synchronise! 
Thx for the answers

**Comment by SomberNight** [comment]
You should try with a more recent version. That version from the debian repositories is out-of-date.

**Comment by mryellow** [comment]
> from the debian repositories is out-of-date.

Is anyone keeping any of the debian releases updated?

**Comment by SomberNight** [comment]
There is a debian packager, yes. I think it is @mithrandi 
However the "official" releases are the ones on electrum.org, signed by ThomasV's GPG key.

Closing this, as the problem was most certainly due to using an old version.

**Comment by mryellow** [comment]
@mithrandi Debian release remains broken. Also impacts TailOS.

**Comment by SomberNight** [comment]
@mryellow stable-backports has 3.0.6: https://packages.debian.org/stretch-backports/electrum
What version of Electrum are you using?

**Comment by mithrandi** [comment]
Yes, the version in stable-backports should work. I have requested removal from [stable](https://bugs.debian.org/887412) and [oldstable](https://bugs.debian.org/887415) due to those versions being non-functional and the infeasibility of backporting the changes needed to make them work.

**Comment by mryellow** [comment]
> I'm not sure exactly what the situation on Tails is.

Interesting. Probably doesn't help the guys over at TailsOS too much though, I believe `apt` is disabled for users. They seem to be relying on whatever Debian packages.

> What version of Electrum are you using?

I went the route of enabling persistent encryption and downloading a new binary. Less sophisticated users are left scratching their head, while any issues like this get closed and documentation informing them of issues is thin on the ground. (I have a phonecall with one such user this week sometime to walk them through the install step by step).

> backporting the changes needed to make them work.

What about backporting some error checking so that it actual spits and error rather than silently hanging on API incompatibilities? Doesn't have to "work" so long as it gracefully informs the user that it isn't working.

Perhaps the API can be changed so that it spits out something the old client can actually read and then display appropriate errors for?

Will the current version also suffer from similar lack of errors when the API changes again in future?

**Comment by SomberNight** [comment]
> I'm not sure exactly what the situation on Tails is.

Tails 3.6, the next version, will contain Electrum 3.0.6. The current version contains 2.7.9.
https://labs.riseup.net/code/issues/15022

Tails 3.6 is currently at rc1.
https://tails.boum.org/news/test_3.6~rc1/index.en.html
