### ISSUE TITLE
Question about unsigned tx serialization

### ISSUE THREAD

**Issue by benma** [spesmilo/electrum#2935]
Hi

I am trying to understand the signing code better, and saw this:

About https://github.com/spesmilo/electrum/blob/dcd50c3467d9de778de9d0e4db3836ec84c6d1cc/lib/transaction.py#L623-L624

> if we have enough signatures, we use the actual pubkeys
> otherwise, use extended pubkeys (with bip32 derivation)

If the tx is unsigned, in the input script, it pushes not the public key, but the xpub. What is the reason for this?

Thanks for any hint.

**Comment by SomberNight** [comment]
First, note there is no standard way for serializing unsigned transactions, hence Electrum is free to do what it wants.
I would guess the reason is efficiency. How would you find which private key to sign with on the other machine, if you used public keys? Linear search? Or maintaining some large index and e.g. log search there; for how pubkeys would you keep in this index? What if the index is not big enough, so the sought pubkey is just outside it?

**Comment by benma** [comment]
Thanks a lot, that makes sense.
