### ISSUE TITLE
Can't Restore From System Tray

### ISSUE THREAD

**Issue by TomAshley303** [spesmilo/electrum#3023]
Electrum won't restore from the system tray. Tried double-clicking the icon and selecting the wallet from the popup menu.

Ubuntu 16.04
KDE Plasma Version 5.10.5
KDE Framework Version 5.38.0

**Comment by ecdsa** [comment]
with master?

**Comment by AbdussamadA** [comment]
I'm having this same problem. I have to kill the electrum process to get it's icon to go away. The software info is included in the attached image.
![versions](https://user-images.githubusercontent.com/3611810/32504233-202deeb0-c401-11e7-967a-93dc054399fb.png)

**Comment by JackDinn** [comment]
I can confirm this problem, just updated to 3.0.1 and i cant open the GUI from the tray icon or close the panel icon either. The only way iv found is to killall electrum.

System:    Host: jack-xxxx-5767 Kernel: 4.10.0-38-generic x86_64 (64 bit)
           Desktop: KDE Plasma 5.8.8 Distro: Linux Mint 18.2 Sonya

**Comment by SomberNight** [comment]
I've reproduced this. More specifically,
- using a config based on @AbdussamadA's description: OpenSUSE Leap 42.3 with KDE
- when using Electrum with the QT GUI, after closing all the windows, the process does not quit

Even more specifically, the main thread of the app runs
https://github.com/spesmilo/electrum/blob/9d4dd20b239c975e99aef4254160732c5031997b/gui/qt/__init__.py#L252
and the `exec_` call will never return.

To be fair, the [QT docs mention](https://doc.qt.io/qt-5/qapplication.html#exec) that `exec` might not return on some platforms, but the docs looks (to me) to be concerned with OS shutdown and similar cases. They suggest to connect to the `QCoreApplication::aboutToQuit` signal instead of expecting `exec` to return.

In this specific case, not even `aboutToQuit` is emitted.

`QGuiApplication::lastWindowClosed` is emitted however, and `QGuiApplication::quitOnLastWindowClosed()` is `True`, which based on the same docs, should result in the app quitting, but this does not happen for some reason. We can however connect our own slot to `lastWindowClosed` to fix this.

**Comment by bauerj** [comment]
This should be fixed with 9833baad3f1. Please reopen if you still encounter this issue.
