### ISSUE TITLE
All my Bitcoins are stolen on my electrum wallet

### ISSUE THREAD

**Issue by smilevik** [spesmilo/electrum#3238]
All my Bitcoins are stolen.
I hade yesterday an unknown Transaction on my electrum wallet. 
How is that possible?
What can i do to get my Bitcoins back?
Should I go to the Police?

**Comment by smilevik** [comment]
Could give Electrum  me the Information who get my Bitcoins?

**Comment by ariard** [comment]
From where have you download your version of Electrum ? Have you check the signature ?

**Comment by smilevik** [comment]
Where can I check the signature?

**Comment by ariard** [comment]
first comment explain how https://www.reddit.com/r/Bitcoin/comments/7a7i69/electrum_30_release/ but have you download your binary from https://electrum.org ?

**Comment by smilevik** [comment]
yes I have

**Comment by neocogent** [comment]
If indeed you have an unknown tx then most probably you cannot get your btc back. You can try filing a police report but it's very unlikely they can anything either.

This isn't really the place for user support - it's issues that devs can work on or fix, which they cannot do for you. There are dozens of possible ways that your system could be compromised and the wallet hacked. I'd suggest asking for help on https://reddit.com/r/electrum which is a user help/support forum. They won't be able to get btc back either but they may help with tracking down how it happened - what software you installed or used that may have compromised your system, and how to use Electrum more securely in future.

**Comment by ecdsa** [comment]
we cannot revert transactions. 
please use github to report bugs

**Comment by N3RG4L** [comment]
Have you found how you lost your btc ?
otherwise may be this is related, and were used : #3374

**Comment by ddimme** [comment]
me too, all my bitcoins stolen from electrum wallet!

**Comment by ddimme** [comment]
so far nobody could really help or investigate me, I don't know what I can do otherwise!?

**Comment by ysangkok** [comment]
Since you havn't posted any details at all, it is impossible for anyone to even try to help you. What is the transaction ID? How long was the wallet in use? Where did you save the seed? Anyone wishing to help would probably want to hear the full story.

**Comment by ddimme** [comment]
I loose my bitcoins with Electrum last Friday.
After Installation of the new Electrum Desktop Wallet Version 3.0.5 (Windows 10) I see this transfer in the history (5.1.2018 midday).
I opened my wallet with Electrum 3.0.5 on monday 8.1.2018 morning and in the same time there was shown this transfer to another bitcoin address. But I dont do that last friday.
In the other Version of Electrum 3.0.3 my bitcoins are still there (Friday night, after the alleged transfer !!!), my bitcoins are ok at this moment. After I opened in Electrum 3.0.5 all is lost, 3 days later.

This is the Transfer on blockchain.info
https://blockchain.info/address/34xsiBXp3wSGXgVTDtmnkatZ2LbJ3gFMVW

----

I checked alle downloads with an Electrum developer, all downloads are ok.
I checked my PC with an Security Expert, no problems.
I have more than one wallet software and coins. Only my Bitcoin from Electrum wallet are effected.

fact:
The transfer was only visible with Electrum 3.0.5 on Monday morning (8.1.2018) - 3 days later!!!
The transfer was actually on Friday midday (5.1.2018 11:33), BUT I still see all my bitcoin in the orig. Electrum 3.0.3 on Friday evening, houres lates, all bitcoins are ok at this moment.

thx

**Comment by danuker** [comment]
@ddimme: I am very sad to hear you lost money.
What I imagine could have gone wrong:
1. You visited a malicious website which scans for wallet RPCs on your computer (as per #3374, as @N3RG4L said) while having your wallet open
2. Password manager could be compromised? Which password manager are you using?

Do you think any of the above could be the case?

Even sadder, it seems the attacker was quite successful, the money got clumped together into this wad of dirty bitcoins: https://blockchain.info/address/35Kbv6MhTwvFCwbUcZMD6Yz8EsqL4ARVzm

**Comment by Ivanka200** [comment]
I just can't keep cool. My wallet was hacked and I lost 20btc which was my life time savings. I was left empty . I really appreciate my neighbor for referring a recovery expert to me. They recovered about 85% of btc stolen. I strongly recommend you to contact wealthrecovery94@gmail.com if you have experienced a similar situation.

**Comment by jonnie256** [comment]
Are you in need of the service of an Ethical Hacker? You probably do without realizing it.
List of services available include;
Mobile phone hack (a good way to investigate cheating spouse/partner)
Recovery of lost assets/cryptocurrency
Delete and expunge criminal records, mugshots and unwanted content from the internet
Fix credit score and all other related services tailored to your need
CONTACT: **reputablehacker@gmail.com**

**Comment by Paulayates** [comment]
I lost my entire fortune to trading with wrong crypto currency brokers or maybe so unlucky that i lost over $500k, of not just my money but from also friends and family. As fate would have it through a friend who met this genius on the darknet although skeptical at first he was able to help me Recover all of my funds back from the broker companies in no less than 72hours. I can confidently say Blackwebs is the best, he can be contacted through Recovery@blackwebs.org    or  508-556-9312. Please mention that you were referred by Yates.

**Comment by nika12345678** [comment]
About Recovery@blackwebs.org or 508-556-9312. I contacted the person behind this e-mail, told him the story, paid 0.56893 btc up front for recovery, at the end of 72 hr period he requested another 0.48 btc, and this looks like scam. I expected real recovery - no recovery, and no money back for the job not done.

**Comment by rained23** [comment]
posted on Jun 28, and the scam commend still not deleted till now and someone just got scammed.

someone should delete @Paulayates advertisement from the repo issue

**Comment by danuker** [comment]
@nika12345678 you should try to trace them. Start with the WHOIS database (`whois blackwebs.org`).

Once you have enough data, report them!

**Comment by Nickmice1** [comment]
The good news is that there's someone who's fighting against the bad eggs blackhatlord (at) protonmail (dot) com is the hacker who's ready to get everything back to you're just one email away from that victory do0 not give up and not let them win...You'll be convinced once you contact him

**Comment by Tammyrab** [comment]
Just last month i lost over 8 BTC to a Bitcoin investment scheme hoping to make profit but this turned out to be a scam. I was so devastated by this situation and needed my BTC recovered, luckily for me a friend introduced me to a genius hacker who helped me recover all my Bitcoins somehow in just a day. If you need such help feel free to contact him via:
Email: BITCOINRETRIEVAL2018 GMAIL COM
SMS/Whatsapp: (470)250-0531

**Comment by tomerkg** [comment]
i had the same problem just now . 
i opned my old version of electrum 3.0.3 and tried to send my money to my other wallet it sayed i have to upgrade to 3.3.4
so i did .
after the update i got in to my wallet and saw and unkown tracsation that happend on the 5th of january  and all my money is gone . 
how is it possible that they took my money 2 months ago and i only saw it after i updated . 
now i cant even open the old version of electrum . 
so my money is gone ? what can i do

**Comment by SomberNight** [comment]
@tomerkg could you look up the unknown tx in a block explorer (e.g. [blockstream.info](https://blockstream.info/)), and double-check the timestamp?
Also, please copy-paste the URL you have downloaded Electrum from "just now", from your browser history.

**Comment by Ivanka200** [comment]
One wouldn't really think much of this, all I really wanted to do was
invest and be part of it but the way I was misled by this brokers was
terrible, to easily take money from all in the name of investment and when
I wanted to make withdrawals every single attempt was fruitless with
constant hassle to invest more I really can't say more than I have already
said. I would really consider myself to be one of the very few lucky ones
as I was able to have my funds recovered from this scam Binary option
brokers, although it was through unethical means as far I am concerned but
what can I care after how my hard-earned funds where taken from me, these
guys are the best in less than 7days all my funds including bonuses had
been recovered, If your broker lost your funds trading Binary options or
any other online fraud, contact binaryoptionrefundnow@tutanota dot com  are
more than able to get your funds back without any traces. Best of luck
people.

**Comment by jessicaamber** [comment]
An uptick in digital heists of virtual currencies has left many crypto investors wondering if they have any options for tracing illicit Bitcoin transactions and recovering their stolen funds.
The short answer is that ‘it’s possible, but difficult.’ The long answer is that ongoing developments in the regulatory landscape surrounding cryptocurrency may offer victims more recourse going forward.

Recover all funds lost to cryptocurrency scams and thefts, Bitcoin scam, or basically any stolen money. The government is doing absolutely nothing to peg this menace. I even filled a report about my loss to the FBI and paid for proper trace and possible recovery of my lost investment. Time wasting and their lackadaisical attitude made me look elsewhere for help.
Thankfully, my old friend referred me to a colleague of his (who specializes and has the required skilled set in recovering funds lost to the wrong hands . I’ve been able to successfully recover back my stolen 15BTC. P.S : No upfront payment before recovery 
Contact quickfundsrecovery(@) gmail Com 
Text: +1(262) 872- 0558

**Comment by Tammyrab** [comment]
> i had the same problem just now .
> i opned my old version of electrum 3.0.3 and tried to send my money to my other wallet it sayed i have to upgrade to 3.3.4
> so i did .
> after the update i got in to my wallet and saw and unkown tracsation that happend on the 5th of january and all my money is gone .
> how is it possible that they took my money 2 months ago and i only saw it after i updated .
> now i cant even open the old version of electrum .
> so my money is gone ? what can i do

Sorry to hear that dear. Check out the website of the company that helped me in my situation www.bitcoinbinaryretrieval.com, I'm sure they can be of great help to you too

**Comment by broker10** [comment]
hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email

**Comment by nika12345678** [comment]
Hello,
can you help recover my stolen bitcoins?
thanks,

**Comment by Tammyrab** [comment]
To r

> Hello, can you help recover my stolen bitcoins? thanks, From: broker10 <notifications@github.com> To: spesmilo/electrum <electrum@noreply.github.com> Cc: nika12345678 <alex1707_141@yahoo.ca>; Mention <mention@noreply.github.com> Sent: Saturday, April 6, 2019 8:42 AM Subject: Re: [spesmilo/electrum] All my Bitcoins are stolen on my electrum wallet (#3238) hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email— You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

To recover your stolen Bitcoins, contact the company that helped me recover mine a week ago. www.bitcoinbinaryretrieval.com

**Comment by Ivanka200** [comment]
Contact binaryoptionrefundnow@tutanota.com for help

**Comment by OlyaGreen** [comment]
has anyone ever tried filing a complaint / police report against Electrum in the first place? it's their vulnerable software that exposes the user / consumer and this is a legal actionable.

**Comment by jessicaamber** [comment]
Cyber investigators can use due diligence investigations,asset searches,surveillance,witness location, and computer investigations to uncover the sometimes complicated details of company management. These investigations can be a big help in the recovery of asset lost to this fraud,or to their lawsuit cases.

I lost about $100,000 to a woman I met online. I was so close to ending my life when I discovers it was all a scam.
I’m posting this here because I have been able to recover all the money that was stolen from me and more with the help of a recovery agent. 
Thanks to Quick Funds Recovery , the leading Intelligence gathering agency for fighting fraudulent financial brokers and scammers who rescue me when everything was so hard on me,
If you’ve ever been scammed by binary options, if you are having a withdrawal problem with your broker
or any other fake ICO then you can reach out to them:
Quickfundsrecovery at g- mail com

**Comment by brainard25** [comment]
my bitcoins where once stolen also,i called the customer care unit,there was nothing they could do,that they told me,my business almost crashed,until a friend directed me to the customer care unit of a crypto recovery website,HELPDESKHACKERS at protonmail dot com ,where only able to recover 65% of the stolen coins because the thief already spent some i guess

**Comment by jon0190** [comment]
I reported them to my state police and their country and media. A lot of the banks and wallets won’t let you send coins to their addresses anymore

**Comment by winstonchurch** [comment]
I got the prof contact from a colleague at work when bitcoin was going up all the way up few weeks ago. I've been working with the prof for 5 days and i can confirm he help me mine 2.5 btc in total. I am still working with him to get more coins because i can never afford to lose this great opportunity at all. The crypto market is at a crucial point, If you have been wondering where to start and have some questions, I will advice you to email prof Donald right away and he will personally put you through on how you can also recover from electrum. Contact - Bitcoinrecoveryteam{@}yandex,ru

**Comment by Ivanka200** [comment]
Most brokers take advantage with customers funds because they fill these customers don’t know how to get their funds back, But trust me there are hidden ways you can get your lost funds back from the broker. I was able to withdraw my $230,000 from the two brokers i signed up with while trading. I’ve never done this before but i promise to recommend him if i help him out and i’m glad he did, If you want to recover your money back then mail him recoverywealthnow360 at gmail dot com

**Comment by Jesseh2219** [comment]
Here is a very important information for beginners, everyone involved in bitcoin and cryptocurrency in general. One of the biggest advantages of investing in digital currencies like BITCOIN is the possibility of making millions overnight. Also, bitcoin makes cross border payments possible, and also provides an easy way for people to escape failed government monetary policy. When some people hear about bitcoin, they think of it as nonsense but it’s simply because they have no knowledge or lack professional guidance/mentorship. Bitcoins can be sent from anywhere in the world to anywhere else in the world. No bank can block payments or close your account. I can go on and on to list the benefits of bitcoin investments but I will pause and let you find out more. Also, If you wish to make profits from bitcoin investments, need consultancy about any digital currency, mining of bitcoin or retrieve stolen wallet, lost passwords. Contact Professor John Hang via his email address
( c r y p t o j a c k i n g [at] g m a i l c o m ) for consultancy and help.

**Comment by stu25** [comment]
I reported mine to the police and Electrum who say the German police are looking into it. I have a private investigator looking into it who is compiling evidence so anybody with their transaction I.D and any address please reply

**Comment by Imran144** [comment]
I want to appreciate Digital Currency who helped me acquired Millions of dollars through bitcoin in a short period of time. All he did was to connect my wallet to His mining stream and that way i was able to realize an average of 0.7BTC daily. It all looked weird to me at first but there were a lot of testimonies on many bitcoin site how he had helped them achieved this so i decided to give it a try and the outcome was amazing. I'm the most happy man on earth, this I've made a huge profit from this. You too can become a millionaire like me today and live the kind of life you've always dreamed about. Contact (digitalcurrency14@gmail.  com or +1502-378-7817 ) and request His help. He'll help you get this done too. Thank me later

**Comment by marksman0063** [comment]
Thanks, Dr David from Hack Assets. Love the information and your working strategy. As a beginner, your tutorial guide at first seems a little bit confusing, but ultimately I learned a lot. Dr David, Manage investment project seems super interesting too. Invested 1Btc with him and his management, managed it to 7.6Btc in 3days. Thanks again Dave. I think if you trade crypto you should write on Hackassets via google mail, and google search about his management team,  I believe they can help with bitcoin recovery.

**Comment by judey040** [comment]
There is so much content on the internet regarding trading that it is overwhelming. Mr Joe Grimes strategy gave me everything I needed and the perfect basis to begin trading. I really valued his emphasis on minimizing risk because this is something I haven't seen on other websites and tutorials. It's not how much you make, it's how much you keep!”contact her directly on whatsapp +19412410496

**Comment by chriswebstin** [comment]
Hello traders, I have been earning huge Profits weekly with the help of Mr Sven Robert Vlad, after much loss of trading on my own. I call Mr Robert an expert because he helped me handle my trades and now am so happy to recover all my money back, I have made over $5950 with a startup of $500 and I had full access to my trading account which was different from the others.
Mr Sven Robert Vlad is 100% legit and your profit is guaranteed with him.
You can connect with him If you need his assistance contact him
Email: ULTIMATEFUNDRECOVERY at GMAIL dot COM 
WHATSAPP: +14079061584 
TEXT :+14079061584

**Comment by nika12345678** [comment]
just shut up and continue making "huge" profits.

    On Saturday, November 30, 2019, 11:08:17 p.m. GMT-4, chriswebstin <notifications@github.com> wrote:  
 
 
Hello traders, I have been earning huge Profits weekly with the help of Mr Sven Robert Vlad, after much loss of trading on my own. I call Mr Robert an expert because he helped me handle my trades and now am so happy to recover all my money back, I have made over $5950 with a startup of $500 and I had full access to my trading account which was different from the others.
Mr Sven Robert Vlad is 100% legit and your profit is guaranteed with him.
You can connect with him If you need his assistance contact him
Email: ULTIMATEFUNDRECOVERY at GMAIL dot COM
WHATSAPP: +14079061584
TEXT :+14079061584

**Comment by Ivanka200** [comment]
Hello

Have you lots lost money to crypto? Losing money to crypto investment or
scams is past tense when you contact recoverywealthnow369@gmail.com

**Comment by chriswebstin** [comment]
He is no scam,i tested him and he delivered a good job,he helped me settle bank loans,he also helped my son upgrade his scores at high school final year which made him graduate successfully and he gave my son free scholarship into the college,all i had to do was to settle the bills for the tools on the job,i used $500 to get a job of over $50000 done all thanks to ultimatefundrecovery at gml dot com  he saved me from all my troubles,sharing this is how i can show gratitude in return for all he has done for me and my family. his 
WHATSAPP is +14079061584 
TEXT: +14079061584

**Comment by celine50** [comment]
> Hello, can you help recover my stolen bitcoins? thanks, From: broker10 <notifications@github.com> To: spesmilo/electrum <electrum@noreply.github.com> Cc: nika12345678 <alex1707_141@yahoo.ca>; Mention <mention@noreply.github.com> Sent: Saturday, April 6, 2019 8:42 AM Subject: Re: [spesmilo/electrum] All my Bitcoins are stolen on my electrum wallet (#3238) hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email— You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Don't stress yourself contact BITCOINRRCOVERY @AOL . COM  they will work without any upfront until the recovery is successful

**Comment by nika12345678** [comment]
hello, please help recover my stolen bitcoins if possible.

    On Monday, December 9, 2019, 1:05:30 p.m. GMT-4, celine50 <notifications@github.com> wrote:  
 
 

Hello, can you help recover my stolen bitcoins? thanks, From: broker10 notifications@github.com To: spesmilo/electrum electrum@noreply.github.com Cc: nika12345678 alex1707_141@yahoo.ca; Mention mention@noreply.github.com Sent: Saturday, April 6, 2019 8:42 AM Subject: Re: [spesmilo/electrum] All my Bitcoins are stolen on my electrum wallet (#3238) hello everyone for a payment of 1 bitcoin we can recover your stolen bitcoins and find out who stole write me an email— You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.


Don't stress yourself contact BITCOINRRCOVERY @aol . COM they will work without any upfront until the recovery is successful

**Comment by SomberNight** [comment]
Guys, there is no such thing as a legitimate recovery service for stolen bitcoins.
All these "services" are SCAMs.
Use your common sense.
