### ISSUE TITLE
Generous donation for whoever can solve my wallet problem

### ISSUE THREAD

**Issue by michaelelwan** [spesmilo/electrum#3240]
I am new to the crypto world and I need your help please... My situation is challenging so I will try to simplify it in the following points:

1- I have installed "Bitcoin ABC" and "Knots" on the same computer 
2- Transferred bitcoin to the "knots" and bitcoin cash to "bitcoin ABC" from internet trading website. 
3- The transfer went smooth and I saw the coins (although they were mixed up in type.. for example it showed bitcoin cash coins as bitcoins) 
4- Hearing about an easy way to store bitcoin, I installed Electrum also on the same computer by creating a standard wallet (for some reason now I realised it is a multi-sig wallet, even though I am sure I did not create it this way) 
5- I obtained the private key that has the bitcoin from "Knots" and swapped it in Electrum 
6- When I saw the bitcoin in my electrum I thought that this will enable me to send it at anytime using electrum so I deleted the "knots"
7- Now I have: 
a) Electrum wallet it is called "wallet try_1 [2_of_2]" but I cannot find the 1_of_1 wallet (if I will need it to send the bitcoin) 
b) I have full access to this electrum wallet so I managed to get the private key, address that has the coin and the transaction details. However, I cannot send the coin anywhere since it is watch only wallet 
c) Also have full access to the knots wallet

Can anyone help please? I am more than happy to send a generous donation in return if I got my bitcoin

Cheers

**Comment by neocogent** [comment]
If you created a multisig by mistake then most likely it was bu choosing "2 Factor" as the type. It behaves like a multisig, requires signing by TrustedCoin (for a fee) but has simple setup steps. True multisig would have required you to create two separate wallets and copy/paste xpubs between them and I don't see how that could happen by mistake.

If it is a 2 Factor then you can disable the 2nd signor by restoring the wallet from seed and choosing the option "Disable 2 Factor" (on the second screen I think). That will generate a second key in the wallet allowing you to sign both and send.

If you are very sure it's not 2 Factor but real 2of2 Multisig then during the wallet creation you had to provide an xpub to even generate an address list in the wallet. It couldn't have been an xprv or seed as that would give you full signing ability. So you will need to figure out / recall where you got that xpub from - another wallet somewhere, and go get the xprv to match it in order to sign a tx. I don't think you can update it with a new xprv (except manually putting it in correct place in wallet file) and probably would need to restore the wallet with both seed and xprv.

**Comment by michaelelwan** [comment]
Hi Neocogent, thanks for your response, things started to make sense!

So, now I restored the 2fa wallet and it shows zero coins there, while in my 2_of_2 wallet, I can see the coins. What can I do to proceed?

Also, copying the xprv method you just mentioned sounds like something I did!! I have both the knots and ABC wallets.. how can I get the xpup from them?

Thanks

**Comment by SomberNight** [comment]
If you created a 2FA wallet it would say `2fa` instead of `2_of_2`.
Also, `2fa` wallets are actually 2-of-3 multisig, not 2-of-2.

**Comment by neocogent** [comment]
It sounds like you took an xpub from your Knots wallet and used it as a signor for your Electrum one. I don't know how you could have done that. I don't think that Knots (easily) gives you the xpub. The xprv is available using the dumpwallet command. If you did somehow take the xpub from Knots and then deleted Knots wallet then you are in trouble as you'd have to find a way to recover that wallet in order to get the xprv. However, that seems unlikely and more likely you're confused about how you managed to create a 2of2 multisig. You would have to provide an xpub from somewhere. Did you maybe create or have another Electrum wallet you may have got it from?

**Comment by ecdsa** [comment]
as @neocogent said. you need the xprv if you want to create a wallet that signs.

**Comment by michaelelwan** [comment]
hi neo, yes I do remember providing an xpub when I created this wallet. Having said that, I do not remember which one I used (as I have many wallets in the electrum wallet folder). What do you think I can do now? thanks

**Comment by neocogent** [comment]
I guess your best bet is to open each wallet and check the xpub value (Wallet, Master Public Key) against the (second) one shown in your current wallet you want to spend from. It came from somewhere and you need to find where. Once you know you'll need the xprv or seed from the wallet to restore a new wallet that has both seeds or xprvs instead of having only one.

**Comment by michaelelwan** [comment]
Alright.. so I have followed Neo's advise and finally I found the following:

a) in my current wallet (2_of_2): I looked at the master public key for cosigner 2 and started to compare it with the other wallets
b) I found a match in a wallet called (default_wallet [2fa]). It matches the cosigner 2 key also in this wallet. Having said that, this 2fa wallet has 3 cosigner keys

What do you think guys? I feel I am close to solve this problem thanks to Neocogent!

**Comment by neocogent** [comment]
So let's review because I can't quite make out what you have now.

You have an **xpub** you took from your "default_wallet" [2fa] and then pasted it as an **xpub** in your current wallet [2_of_2]. Both of these are multisig and as long as you didn't take the #3 signor xpub from the [2fa] wallet you should be able to recover the BTC. 

Now the BTC you want is in the current wallet [2_of_2], right? And what exactly does that wallet file have in it for x1/ and x2/ values? Don't paste here but indicate if x1/ has **seed**, **xprv** and **xpub** or is missing one or more. Likewise for x2/. Also, you say this x2/ xpub matches the [2fa] wallet x2/ xpub but I gather the [2fa] x2/ xprv is missing (because you haven't disabled the 2fa yet), right?

Depending on what you actually have you may or may not be good. I just need to be clear what you have where and I can tell you what to do, if anything.
