### ISSUE TITLE
unconfirmed

### ISSUE THREAD

**Issue by maksim7776** [spesmilo/electrum#3279]
c6918fe907b54119dd0dd37650bbabbc8454372e75510eef1f775048dc4f1094
transaction is not confirmed. You can cancel?

**Comment by SomberNight** [comment]
http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

Once a tx is out there, it can't really be cancelled. If you want it to confirm fast, you will need to use RBF/CPFP. Otherwise you should just wait. GitHub is not customer support though, please refrain from these kind of questions here.

**Comment by chadchen2017** [comment]
hopefully a miner takes pity on your soul, and gives it back

**Comment by maksim7776** [comment]
can I get a private key, delete my wallet, and upload a private key so that I can not wait for cancellation?

**Comment by chadchen2017** [comment]
Just uninstall and reinstall

**Comment by ecdsa** [comment]
@maxme that will not have any effect on your transaction.

**Comment by chadchen2017** [comment]
It will fix it

**Comment by chaelbulatao** [comment]
Hello,

kindly help me to push may transaction, coz still un confirmed for almost 24 hours

BITCOIN TRANSACTION

https://www.blocktrail.com/BTC/tx/9100c4b1acf1ce1c1d5cf6e6f68ad836aec46abef19ac00d8c9959c199571a2e
