### ISSUE TITLE
sweep paper wallet fails

### ISSUE THREAD

**Issue by wessjan** [spesmilo/electrum#3363]
I'm still in Testnet. 
When I try to sweep the private key of a paper wallet, electrum (3.0.2) finds the funds, creates a transaction and signs it. But every time when I hit Broadcast, the error "**min relay fee not met**" occurs. I've not seen a way to set the fee at all.  
![electrum001](https://user-images.githubusercontent.com/15079538/33190777-e8696d80-d0b0-11e7-8245-336e758f933c.PNG)

**Comment by SomberNight** [comment]
This happens when we originally underestimate the transaction size, and the intended sat/byte fee is really low. On testnet, the dynamic fee estimate for a 5 block confirmation target is often ~1 sat/vbyte, which is also the minimum default relay fee used by servers.

Also, unfortunately, there is currently no straightforward way to set a fee when sweeping. ( https://github.com/spesmilo/electrum/issues/2179 )

A trivial example for Electrum underestimating the transaction size is when a WIF with an uncompressed pubkey is being swept.
https://github.com/spesmilo/electrum/blob/9fc946492bb329f274431c9af6105bccc1560fea/lib/transaction.py#L620-L623

**Comment by SomberNight** [comment]
The user can now set a fee when sweeping: https://github.com/spesmilo/electrum/pull/3380. This applies from version 3.0.3 going forward.
I think this can now be closed.
