### ISSUE TITLE
electrum-wallet fake

### ISSUE THREAD

**Issue by ronaldobini** [spesmilo/electrum#3371]
Why is this website still alive???

https://electrum-wallet.com/#home

it is completly the same website. What can the team do about it?

You should at least put a great warning about it in your front website page!

**Comment by AbdussamadA** [comment]
I've reported the site to google. You should do the same:

https://safebrowsing.google.com/safebrowsing/report_badware/

Both Chrome and Firefox check websites against google's list of malware sites. If a site is on the list they stop the user from browsing it.

There's been a spate of fake electrum sites recently. I don't know what we can do to stop them apart from reporting them to google. Anyone is free to put up a site on the web.

**Comment by fr3aker** [comment]
it's noteworthy that they even went to the lengths of creating a fake GPG signing key (0xE0EE06E91CDEB1B3)

correct one is 0x2BD5824B7F9470E6

**Comment by fr3aker** [comment]
also they were kind enough to release the source code changes for their backdoor. Here's the diff: https://gist.github.com/fr3aker/a284bd0d535cc99d39cd10d65918590d

**Comment by bauerj** [comment]
Does the binary also use `robertpaulson.me`, `pinnacle-consulting.pw` and `bestoftechforums.org`?

**Comment by ecdsa** [comment]
@EagleTM did you report that one?

**Comment by EagleTM** [comment]
No, i only reported the one without dash and another TLD, so electrumdesktop.org

Best cause of action is to do a whois on the domain and then report to their abuse desk by email stating that the domain is exclusively there to distribute malware.

Namecheap is pretty responsive (days to a week), Namesilo for example does not do much, might be best to call them as the latter also have a phone number listed in the whois for abuse complaints.

I'll report this one as well, it's with namecheap.

**Comment by AbdussamadA** [comment]
I reported electrum-wallet dot com to namecheap a few days ago and they suspended it.

**Comment by AbdussamadA** [comment]
The scammers can just put up more sites. It would be a game of whack a mole. The only solution is to educate users on how to verify the downloads properly.

**Comment by EagleTM** [comment]
----- snip -------
Hello,

Thank you for the report.

Please be assured that the electrum-wallet[.]com domain was suspended. It any content is still available from your side, this is due to the propagation period. Once cache of your local internet provider is cleared, no content will be available from your side.

If any further assistance is required, please contact us back.

------------------
Regards,
Alexander Neustroev
Legal & Abuse Department
Namecheap.com

Ticket Details
Ticket ID: ADK-844-95090
Department: Domains -- Legal and Abuse
Type: Issue
Status: Awaiting Client Response
Priority: High
----- snip -------
