### ISSUE TITLE
Consistent error attempting to send any amount of bitcoin to any address "Script failed an OP_EQUALVERIFY operation)"

### ISSUE THREAD

**Issue by bhound** [spesmilo/electrum#3408]
Getting the attached error no matter which address or amount I try to send. This is on Electrum 3.0.2

![ewwer](https://user-images.githubusercontent.com/34085123/33359011-488a2906-d49a-11e7-8613-69a6892f2971.JPG)

**Comment by SomberNight** [comment]
- When creating the transaction in the `Send` tab, use the `Preview` button.
- _Please use the `Copy` button there, and paste the unsigned transaction here, if possible. (Note that sharing an unsigned transaction greatly reduces your privacy)_
- Then sign the transaction using the `Sign` button.
- Use the `Copy` button again, and paste signed transaction here. _This does not reduce your privacy much._

What type of wallet is this with and what script type? (check `Wallet`>`Information`)

Alternatively, could you come to the #electrum IRC channel on freenode? This might be much faster that way. If you do, please link to this issue.
If you do figure it out, please share your conclusions here.

**Comment by bhound** [comment]
In the IRC channel now

**Comment by SomberNight** [comment]
notes regarding claims:
- user is using Windows 10
- he created a wallet in October; standard Electrum seed, p2pkh outputs
- he received a single transaction T1 (and sent none) since, around the time of creation
- he shared the txid of T1 with me
- he still has the original wallet file A but he can't open it, the password he wrote down gets rejected
- while he still had access to wallet file A, he used Electrum's `Save Copy` feature to create wallet file B
- he now opened wallet file B, which has the original tx in its history
- he tried to spend the UTXO from tx T1, but the bitcoin network rejects every spending tx he is trying to create
- for a particular spending transaction T2, he provided me with the unsigned and the signed raw hex transaction, uT2 and sT2 
- he also provided me with the xpub X found in wallet file B
- when I synced a watch-only wallet from his xpub X, I found no history at all associated with the addresses within the gap limit
- none of the output addresses of T1 seem to be associated with the xpub X from wallet file B
- upon loading uT2 or sT2, I noted that they are trying to spend the UTXO created by T1, as expected; however the pubkey in the scriptSig is for a **different** address than the output address of T1
- upon inspecting uT2 I saw that the input x_pubkey in it is for the first receiving address of xpub X
- hence, it seemed Electrum was trying to spend the correct UTXO but was using the wrong pubkey for it
- he was asked to try restoring from the same seed words, which he did ~3-4 times
    - on 2 tries, Electrum crashed for him upon pressing `Next` in the wizard after entering his seed
    - on other tries, he derived different first receiving addresses `wallet.receiving_addresses[0]` and xpubs from the same seed words; one of these was the same I had obtained independently
    - he seemed to have gotten at least 3 different first addresses for the same seed words
    - I gave him a mnemonic I generated to restore from it, and he obtained the correct xpub from it; but we only tried this once
- he had downloaded and been using the 3.0.2 setup.exe, for which he calculated the correct sha256 sum for me

We agreed to try to debug this further, later.

**Comment by bhound** [comment]
It's a mystery! I can look in IRC for the next test steps we discussed last night but if you want to repost them here that'd be helpful.

**Comment by bhound** [comment]
Loaded the wallet on another computer running Windows 7, still Electrum 3.0.2, got the same error when trying to spend.

**Comment by SomberNight** [comment]
The problem has been tracked down to the host computer. The user is getting different-and-different xpubs/addresses when restoring from the same seed; and we tried multiple seeds. For any given seed, there seems to be a small set of xpubs Electrum derives for him.
We did not test different operating systems on the same machine, so it's not clear if it is due to malware or (less likely) lower level software/or even hardware fault.

**Comment by bhound** [comment]
No evidence of malware on the system. Windows Defender, HitmanPro and Malwarebytes all return nothing - if anyone has any other malware detection programs they'd recommend

**Comment by ecdsa** [comment]
it would be interesting to know if the corruption occurs at the seed -> xpub step, or at the xpub-> address step.
do you always get the same xpub?

**Comment by ecdsa** [comment]
I asked this user to sign/verify a message using the funded address from wallet B. Verification failed, which suggests that the xprv in the wallet does not match the xpub.

I asked this user to restore from seed a bunch of times, and record the receiving address 0 generated. There was 3 different addresses. The correct one occured in 50% of cases.

Notes:
- malware cannot be ruled out; absence of evidence is not evidence for absence.
- lower level software bug: maybe, but that does not explain why the results are inconsistent. 
- hardware fault might explain that, but in that case you would expect xpub and xprv to match

**Comment by bhound** [comment]
Nothing has been ruled out, including your software misbehaving :P - there is more testing to do and I'll see if I can check your previous question:

"it would be interesting to know if the corruption occurs at the seed -> xpub step, or at the xpub-> address step. do you always get the same xpub?"

**Comment by SomberNight** [comment]
> do you always get the same xpub

Did we not have a (brief) look at this, and seen at least 2 xpubs from the same seed?

In any case, if you don't set a password on the wallet, you can use the console as:
```
wallet.keystore.xprv
wallet.keystore.xpub
wallet.receiving_addresses[0]
```

To get the xprv / xpub / first address of the wallet.

**Comment by SomberNight** [comment]
(Closed due to inactivity, and also because I don't think we will know more about what happened at this point. If there is any more relevant info, feel free to reopen)

**Comment by ecdsa** [comment]
all right

**Comment by bhound** [comment]
Honestly I haven't had the time to pursue this further
