### ISSUE TITLE
2FA OTP might expire while signing large transactions

### ISSUE THREAD

**Issue by cryptoforex** [spesmilo/electrum#3429]
Hello,

I try to send my BTC from my 2FA wallet and it's stay many time in signing transaction and after 1 min appears invalid OTP, it's like 2fa code is wrong but I think that is because it stay many time signing the transaction and the code changes during this time. 
Help me please.
Thanks.

**Comment by SomberNight** [comment]
What kind of transaction are you trying to make so that it takes that long to sign it? How many inputs/outputs are there?

In any case, I have not tested this, but the problem looks to be real.

The signing process is:
- user is prompted for the 2FA code
- local cosigner signs tx
- partially signed tx is sent to TrustedCoin server, along with 2FA code from before

If the local tx signing takes too long, the 2FA code might expire.

https://github.com/spesmilo/electrum/blob/80f99b68e0f32b94238e030658a6a3170118ab21/gui/qt/main_window.py#L1405-L1423

https://github.com/spesmilo/electrum/blob/80f99b68e0f32b94238e030658a6a3170118ab21/plugins/trustedcoin/qt.py#L90-L102

https://github.com/spesmilo/electrum/blob/80f99b68e0f32b94238e030658a6a3170118ab21/plugins/trustedcoin/trustedcoin.py#L272-L288

**Comment by ecdsa** [comment]
@badmofo can you check this?

**Comment by cryptoforex** [comment]
Hello,

Were 46 little transactions received from mining in my wallet.
I finally solved the issue restoring a new wallet without 2fa but I think it's not the good way.
Thanks.

**Comment by ecdsa** [comment]
@SomberNight I agree, we should sign locally before asking second factor

**Comment by SomberNight** [comment]
There was another report of this on [reddit](https://www.reddit.com/r/Electrum/comments/8hubsp/sending_btc_invalid_otp_only_when_high_amount/)
