### ISSUE TITLE
Using segwit without the redistributable.

### ISSUE THREAD

**Issue by paders** [spesmilo/electrum#3501]
How can Electrum do this? I don't have hundreds of MB available for the installation.

**Comment by bauerj** [comment]
What "redistributable" do you mean?

**Comment by paders** [comment]
The Visual C++ Redistributable. It seems it doesn't work without it.

**Comment by SomberNight** [comment]
So are you using Windows older than Win10?

As described in https://github.com/spesmilo/electrum/pull/3185, it should also work with the KB2999226 Windows update. This is also what is mentioned on the official website near the download links.

As far as I understand, we need this due to using Python 3.5+, so it is not really "Electrum's fault". The only thing that could be done better is somehow bundling this dependency in the binary.

**Comment by paders** [comment]
Yes, windows 7. I would guess KB2999226 would install the redistributable.
Electrum was so portable and robust before. Bundling would increase its size 20 times.
Is there a way to just copy the necessary scripts to the previous version folder?

**Comment by ecdsa** [comment]
not possible
