### ISSUE TITLE
Fiat value is not up to date

### ISSUE THREAD

**Issue by mathiuscalcius** [spesmilo/electrum#3527]
The Fiat value of bitcoin is incorrect. It keeps showing the fiat value using an outdated exchange rate. It never uses the current exchange rate. For example, 0.036 BTC is shown as 231CHF while at the current rate it should be 593CHF

**Comment by SomberNight** [comment]
Where? If in the `History` tab, as part of the table, the items there use historical value. They use the price on the given day.

**Comment by garinthengineer** [comment]
I am on a Windows machine running the "2.8.2" version wallet.
For me it shows "No data" in both "USD amount" and "USD Balance" rows.

It is my first time resolving an issue at GitHub, hope I'll manage to understans the code and contribute.

**Comment by SomberNight** [comment]
@garinthengineer You should test with the latest release or master first. It might already be fixed.

In general (and especially if you are considering contributing), run the latest release or master.

Also make sure that your IP is not banned by the exchange rate API, because unfortunately it is easy to run into that [e.g. Tor exit nodes are often banned :( ]... https://github.com/spesmilo/electrum/issues/3063

**Comment by garinthengineer** [comment]
@SomberNight wow, that was super helpful, thanks!
