### ISSUE TITLE
Please don't keep re-broadcasting a "stuck" low fee tx, let it expired!

### ISSUE THREAD

**Issue by Kylejustknows** [spesmilo/electrum#3579]
Recently, the fee needed suddenly rise in 24 hours, my normal fee tx sadly become a "low fee".

It is OKEY. I wait for 4 days, until the xpub online monitor showing that the "unconfirmed" tx disappeared. I double checked it is not in mempool anymore.
(you know, wait for the tx expired and cancelled, money come back to sender. So i can transfer again with a higher fee)

But as I open the electrum wallet, 10 seconds later, the "unconfirmed tx" got re-broadcast and it is back into the mempool. (So I need to wait another 72 hours to let it go??!!)

I am not sure its the electrum client or server side problem, but something is keep re-broadcasting the "stuck tx" and won't let it drop out of mempool as long as the electrum wallet is open. This is so bad.

Please let go of the stuck and low fee tx, let it expired , DON'T broadcast it again and again.
(BTW because it is an all out transfer, I don't have any btc left to do the child-pay-for-parent things )

**Comment by AbdussamadA** [comment]
It's done by the server not by the client so it's not relevant to this repo. Different servers have different transactions in their mempools so you simply connected to a different server.

**Comment by SomberNight** [comment]
>  I double checked it is not in mempool anymore.

Well that's the thing, there is no "the mempool". It might not be in the mempool of whatever service you used to check this, but it is in the mempool of the server you just connected to.

First, the time-based expiration is 2 weeks, since Bitcoin Core 0.14.0, not 3 days. (https://github.com/bitcoin/bitcoin/pull/9312)
Second, you can't really count on that. A signed tx is valid basically forever, unless another tx that conflicts with it gets confirmed. That is, even after the 2 weeks, or however long, if someone saved a copy of your tx, they can just broadcast it, and the 2 weeks start again.

It is a distributed network, once a tx is out there, it's out there. 

> BTW because it is an all out transfer, I don't have any btc left to do the child-pay-for-parent things

If you used RBF, you can bump the fee regardless.
