### ISSUE TITLE
Problemas de envio

### ISSUE THREAD

**Issue by Leondj90** [spesmilo/electrum#3589]
buenas amigos, me dirijo a ustedes para notificar un problema al realizar un envio de la cartera electrum a coinbase usando la version de electrum 2.9.3 he podido conectarme de lo mas normal y sincronizar la cartera pero al realizar el envio me dice low fee pero no me realiza el envio al cabo de un rato, luego descargue la ultima version 3.0.3 pero en esa version no me conecta la cartera no llega ni a sincronizar, desde el 6 de diciembre he intentado realizar el envio y antes me decia incorfirmado y luego me borraron el evnio para devolverme la cantidad a enviar intente nuevamente con un fees un poco mayor y nada qque realiza el envio ahora mismo me dice low fee y en la parte de abajo me dice unconfirmed ya llevo 20 dias intentando enviar y nada que he podido realizar el envio

**Comment by ysangkok** [comment]
We cannot handle bug reports in any languages except English, French, Danish, Hungarian and German, but I have translated this using Google Translate, and it seems you have issues due to fees. Electrum is working as designed, low-fee transactions will not get confirmed during network congestion. We are aware of these issues and encourage you to consult the [FAQ](http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do) to try to fix the problem yourself. Meanwhile, we are working on improving fee estimation, but it is difficult to have good fee estimation that does not allow miners to make you raise fees, which would be a vulnerability.
