### ISSUE TITLE
unable to install…

### ISSUE THREAD

**Issue by aotto1968** [spesmilo/electrum#3613]
~/electrum> uname -a
Linux linux02 4.4.103-18.41-default #1 SMP Wed Dec 13 14:06:33 UTC 2017 (f66c68c) x86_64 x86_64 x86_64 GNU/Linux

> electrum 
cannot import name 'icons_rc'
Error: Could not find icons file.
Please run 'pyrcc5 icons.qrc -o gui/qt/icons_rc.py', and reinstall Electrum

→ what can i do?

**Comment by SomberNight** [comment]
Are you trying to run from source?
If just by mistake, you could just follow the "easy installation" steps from https://electrum.org/#download

Otherwise, do what it says,
```
pyrcc5 icons.qrc -o gui/qt/icons_rc.py
```
which is by the way part of the instructions for [setting up a development version](https://github.com/spesmilo/electrum/blob/master/README.rst#development-version).
