### ISSUE TITLE
Can't package with FPM for deb file

### ISSUE THREAD

**Issue by ChiefGyk** [spesmilo/electrum#3645]
I am trying to get fpm to work with packaging electrum 3.0.3 into a deb so I can make a ppa for a project I am trying to do but it keeps failing at this step when cloning from this git. Any ideas on what I may be doing wrong as this has been a kind of learning project for myself and want to eventually have snap and deb packages for electrum.

Process failed: /bin/bash failed (exit code 1). Full command was:["/bin/bash", "-c", "env PYTHONPATH=/var/lib/gems/2.3.0/gems/fpm-1.9.3/lib/fpm/package python setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build-38224e1c57eaacfad92ab27d4e394f85c246c2b08e35a12ee65bb9b6c480/metadata.json"] {:level=>:error}

**Comment by ysangkok** [comment]
We don't have experience with FPM. But since FPM reports that setup.py failed, maybe you should try to install Electrum without FPM first. Feel free to comment on this issue, but I will close it since this issue doesn't contain any information relevant to Electrum specifically. If you have an actual issue with setup.py, open a new issue. We cannot help you debug FPM.
