### ISSUE TITLE
Error Message when trying to sign/verify with BTR

### ISSUE THREAD

**Issue by RoriT23** [spesmilo/electrum#3647]
Hi there wondering if someone can help, im just new to electrum and im trying to register for BTR segwit with my bitcoin currently in electrum. I require to sign via my BTC address as well as the one BTR give me in the message column, however i receive this error message

Cannot sign messages with this type of address.

Signing with an address actually means signing with the corresponding private key, and verifying with the corresponding public key. The address you have entered does not have a unique public key, so these operations cannot be performed.

this is after i input my password, can someone help?

thanks in advance

**Comment by SomberNight** [comment]
> Cannot sign messages with this type of address.

Not sure how to change that text in the source to make it clearer.

Whatever type of address that is, I would guess p2sh-multisig btw, it can not sign messages. As **the error explains**, the operation of **message signing** is **undefined** in this case.

You could ask "BTR" what to do. Before this, I suggest looking up `Script type` in `Wallet`>`Information` to know the exact script type for your addresses.

**Comment by RoriT23** [comment]
Thanks for the swift reply, i checked my script type and it certainly is P2sh, is there anyway around this from electrum side? as i know of people who have managed to register for BTR using electrum however the sign/verify option appears when right clicking on the BTC address as opposed to mine which appears in the tools option.

appreciate the help

**Comment by SomberNight** [comment]
It's not because you are using Electrum, that's unrelated. Electrum supports many kinds of wallets.
The wallet you have has certain kind of addresses that can not sign messages, simply because, again, the operation is not defined for them.

I'm guessing this is a 2FA (two-factor auth) wallet? That type of wallet uses multisignature addresses, to provide true two-factor authentication that can be enforced on the Bitcoin consensus level, not just some hand-waving. As the name implies, for every address there are multiple possible keys that can sign, and hence, it's not clear how to sign a message in that case (only transactions).

> however the sign/verify option appears when right clicking on the BTC address as opposed to mine which appears in the tools option

It does not appear in the right-click context menu, because there is already a preliminary check there that hides the option if it can't sign messages.

**Comment by RoriT23** [comment]
sorry i'm new to all this, yes i did indeed choose a 2FA wallet, so basically asides from creating a new electrum, there is no way around this problem?

Thank you

**Comment by SomberNight** [comment]
The point is that the addresses in that wallet can not sign addresses.
If you create another wallet, in Electrum (for example a "standard" wallet) or in another app, that contains addresses that can, then those addresses will be able to sign of course.

**Comment by RoriT23** [comment]
ahh okay perfect, would this be a multi signature wallet or a standard wallet to allow this to happen?

Thank you very much for your help
