### ISSUE TITLE
Orbot warning for request to unencrypted port 110

### ISSUE THREAD

**Issue by jmliz** [spesmilo/electrum#3674]
Hi, due to the recent critical bug I updated my wallet to Electrum 3.0.5.0 and configured it to proxy to the local running Orbot 127.0.0.1:9050 via the Network settings. 

It happened to me that I was looking to the Orbot log tab while Electrum was in the background loaded and it threw a warning for a request to an unencrypted port (110). I don't know what it means but I'm very sensitive due to the latest bugs. It may be no issue but I thought better share it.

Here's a screenshot. You just configure electrum to route to the proxy and then start orbot while looking to the log tab (swipe right side):

![screenshot_2018-01-08-16-51-10_1](https://user-images.githubusercontent.com/25148851/34679213-935b4954-f495-11e7-8daa-6c9b792e1265.png)

Electrum was the only app running and configured to route to tor and running in the background. For the rest of the behaviour it seems that the app is really routing via tor.

**Comment by bauerj** [comment]
Hey,

there is an Electrum server on ecdsa.net that uses port 110. Your Electrum client probably wanted to connect to it through Tor. This port is usually used for POP3 traffic (email) but of course in this case the Electrum protocol is used. 

Since port 110 on that server is the TLS-enabled port your connection to it is encrypted.

**Comment by jmliz** [comment]
thanks for the fast reply. so it's just a generic warning then as I though, thanks.
