### ISSUE TITLE
Question on "Warning - Segwit addresses may not be compatible with other wallets"

### ISSUE THREAD

**Issue by foederati** [spesmilo/electrum#3694]
After creating a normal segwit wallet with 3.0.5, I noticed when viewing the private key of an individual receiving key, there's the warning in the title. Was just hoping to get more elaborate explanation on this -- how are these addresses not following a standard and what's the contingency for a point in the future where Electrum may no longer be maintained/running on a modern OS?

**Comment by bauerj** [comment]
I explained this in a bit more detail here: 
https://www.reddit.com/r/Electrum/comments/7dku5r/segwit_wallets_and_electrum/

For the second part of your question: Spending funds from segwit addresses does not rely on Electrum or any specific address format.

**Comment by SomberNight** [comment]
@bauerj I think that's not what the question is about.

![elec_305_privkeys](https://user-images.githubusercontent.com/29142493/34802289-46e096fe-f66d-11e7-8ac6-b20e712b5a00.PNG)

@foederati If you mean the above warning, that is regarding the private key WIF.
Electrum currently uses an extended Wallet Import Format, due to segwit.
This started with version 3.0, and is also in the release notes:
https://github.com/spesmilo/electrum/blob/a9973ce6ab60c21e8d074b1f0727d5dfc8ea7229/RELEASE-NOTES#L90-L103

The code is here:

https://github.com/spesmilo/electrum/blob/3c755aaa90dbbbe02cceb4eb81908f5f0e8ea81f/lib/bitcoin.py#L512-L528

In short, Electrum encodes information in the WIF regarding the script type. By virtue of doing this, the app can know when you import a key that it is a segwit key and exactly what type even within that broad term. The alternative could be for example to import a key and guess the wrong type, hence not finding coins, OR import ALL the types........
We had originally hoped other wallets would follow as this would be beneficial to everyone, but at the moment it looks Bitcoin Core might not do this, and we might have to act accordingly. It seems they might be going with the "import ALL the types" option...
The point is that, as the warning states, the format is not inter-operable with other wallets.

However, the key contains, as can be seen from the code above, the ECDSA secret material, hence with potentially some wizardry, you can extract that and re-encode it to another format that you need, even 10 years from now, if you label your backup well (e.g. exported from Electrum 3.0.5 on 2018-01-11; corresponding bitcoin address; script type).

In any case, if you want to be really sure, you should back up seed words.

> how are these addresses not following a standard

That's the thing, there is no standard, and we were trying to set one.

**Comment by bauerj** [comment]
Oh sorry, I misunderstood.

**Comment by ecdsa** [comment]
same as #3620

**Comment by foederati** [comment]
@SomberNight Thanks for the detailed response.  I didn't realize Core provided no guidance - scary on the frontier!  I was coming from a place where an offline individual private key generated in 2009 is still as usable today as it was then.  Protect that key and you can always spend from that address. I've always found a certain comfort in that.  I guess seed words and relying on restoring derived addresses are realistically the "minimum" today as Bitcoin evolves.

>In any case, if you want to be really sure, you should back up seed words.

So to clarify, the seed words would not be dependent on Electrum and Core would be able to restore the wallet?

**Comment by SomberNight** [comment]
> So to clarify, the seed words would not be dependent on Electrum and Core would be able to restore the wallet?

No;  seed words too would be dependent on Electrum, or another tool that implements the spec.

There are two de-facto-standards for seed words today, the one used by Electrum, and BIP39. Both are well documented. Both have their pros and cons, but one of the pros of Electrum seeds is especially relevant in this context, they are [versioned](http://docs.electrum.org/en/latest/seedphrase.html). Due to this versioning, there are much better guarantees that you will be able to find/access all your coins in the ~distant future.

It is unrealistically unlikely that IF Electrum was discontinued, but Bitcoin itself lived on, there were no tools at all to recover coins from Electrum seeds. There would be such tools, and they would be easy to use.
