### ISSUE TITLE
RFC: payment requests sets automatically label 

### ISSUE THREAD

**Issue by ser** [spesmilo/electrum#3708]
### Problem
Currently when payment request is asked for, the client is able to set memo field. But that memo field is not visible in other synchronised Electrum wallets than the merchant wallet server itself, which makes verifying transactions harder.

### Solution
Adding payment request should automatically set label identical to the memo field or, if memo field was not set by the client (empty), label should be set identically to the payment request ID. This is totally unobtrusive and IMHO has no negative consequences. 

### Who is responsible for PR 

Me

**Comment by ecdsa** [comment]
it would be better to save the payment request on the labels server. bip70 payment requests are signed data, that can be used as a proof that the payment was requested. thus, a service that archives them would be useful

**Comment by ser** [comment]
From my experience, most of people use now certs from LetsEncrypt. It means that the signature is valid for three months only, in the best scenario. How we can access data over these three months in such a situation?

**Comment by ecdsa** [comment]
no I am talking about invoicees emited by bitpay, coinbase, etc

**Comment by ser** [comment]
Ah, OK - let me think :-)

**Comment by ecdsa** [comment]
yeah, maybe that is not the same as your issue.

**Comment by SomberNight** [comment]
While this might/would have made sense in the past, due to recent changes in version 4.3, it would result in confusing behaviour now.

Now the client creates a single type of request that can be paid either on-chain or via lightning. Each request contains an RHASH and an on-chain address. If the wallet set a label at request-generation time for the on-chain address, and then the sender paid the request via LN, it would be confusing to have the address-label linger in the wallet. (in fact unused addresses are sometimes reused for future LN payment requests)
