### ISSUE TITLE
Unable to install dns with pip after updating electrum & pip

### ISSUE THREAD

**Issue by quantumproducer** [spesmilo/electrum#3711]
```
~/electrum/python electrum
Error: No module named 'dns'. Try 'sudo pip install <module-name>'
~/electrum/pip install dns
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns
~/electrum/git log
commit c8e67e2bd07efe042703bc1368d499c5e555f854 (HEAD -> master, origin/master, origin/HEAD)
Author: ThomasV <thomasv@electrum.org>
```

on OSX. How do I fix this?

**Comment by SomberNight** [comment]
You are on git master. That is a development version and is often not stable.
If this is deliberate, follow the instructions in the [README](https://github.com/spesmilo/electrum/blob/master/README.rst)
In particular
```
python3 setup.py install
```

Otherwise, to use the latest release, you should check out "Easy installation" in the [download page](https://electrum.org/#download).

**Comment by quantumproducer** [comment]
Thank you
