### ISSUE TITLE
OS X build documentation

### ISSUE THREAD

**Issue by Sehlor** [spesmilo/electrum#3775]
Hello,

I am trying to build electrum from source on mac os x, but there is no setup-release.py file on current release, instead i am trying to use setup.py but it says "You must specify either app or plugin" soo i modified setup.py file to this: 

APP = ['electrum']

setup( app = APP, name="Electrum", etc )

i can now run electrum using python3 electrum without any issues BUT when i try to build it like this: 

sudo python3 setup.py py2app

it compiles but does not open Electrum.app when i double click on it, instead it gives me an error.

Does anything special needs to be done while compiling on MacOsx?

I can compile on Linux with wine without a problem and works like a charm. Only mac os BUILD gives errors.

Thanks for help
Regards.

**Comment by bauerj** [comment]
Hey,

we're currently working on documenting and improving the Mac build process. Eventually we want deterministic builds there too.

Please use https://github.com/spesmilo/electrum/blob/master/contrib/make_osx to create the dmg. You will need to edit the OS X specfile and change the path there.

Please note that we have to build it on an older version of OS X since building on High Sierra only supports High Sierra systems.

Let me know if you notice anything else.

**Comment by Sehlor** [comment]
Hello,

when i try to run contrib/make_osx it gives me an error saying:

pyinstaller: command not found

I installed pyinstaller using pip3 install pyinstaller but still gives me
same error, any input?

Thanks
