### ISSUE TITLE
allow fees to be set below 1 sat / B

### ISSUE THREAD

**Issue by dlebrecht** [spesmilo/electrum#3793]

**Comment by dabura667** [comment]
This is not a client parameter.

99% of nodes on the bitcoin network will not propagate transactions with less than 1 sat/b in fees.

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum/blob/743ef9ec8f1e69c56f587359f00de19f4f05ff0a/gui/qt/main_window.py#L1482-L1484

@dabura667 
Currently, Electrum does not allow at all to create a txn that pays below 1 sat/vB.
So it's not just the restriction imposed by the network.

@dlebrecht 
What is the suggestion here? Remove this restriction completely?
To what end? So that you can create one and send it out of band to a miner?
I'm asking to better understand what you want.

**Comment by dlebrecht** [comment]
@SomberNight 

well, txs are going this weekend on fee rates of ~3 sat / B, which is pretty close to the limit of electrum

theoretically the minimum mining fee greater than zero that one can pay is 1 sat / transaction. 

one tiny transaction has > 100 B, thus 1 sat/B forces > 100 sat / tx 

potentially BTC price can go very high and that 100 sat / tx can be very expensive

im in favor of no restrictions

**Comment by SomberNight** [comment]
There is a policy enforced by bitcoin nodes that enforces a minimum of 1 sat/vB limit. They don't propagate any transaction that pays less. This is what @dabura667 was referring to.
Electrum enforces this same limit on the client side. We could remove this limit, however bitcoin nodes would not propagate the transaction in any case. This is a DDOS mitigation by them.
