### ISSUE TITLE
Add request for servers

### ISSUE THREAD

**Issue by fact0real** [spesmilo/electrum#3796]
hi all,
I have set up a new Electrumx server for Bitcoin, I want to add my server to electrum client software. The config for `servers.json` is:
```
"btc.asis.io": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.1"
    }
```
You can see screenshots about working this server.
<img width="612" alt="screen shot 2018-01-29 at 11 51 12" src="https://user-images.githubusercontent.com/228022/35500532-04709746-04ec-11e8-8794-f195b58df554.png">
<img width="612" alt="screen shot 2018-01-29 at 11 51 18" src="https://user-images.githubusercontent.com/228022/35500533-0497fb7e-04ec-11e8-828e-5f42df9025c3.png">
Please verify this server and add it.
Thanks

**Comment by SomberNight** [comment]
`servers.json` is generated by manually running `scripts/servers`. We don't usually add individual servers to it.

We will probably re-run the script at some point before the next release, as the next version of the client is planned to require protocol version 1.2. Make sure you will update your e-x to support that protocol version and try to have your server running when we run the script (:P) if you want to be included in the default list.

Side-note: @ecdsa atm `servers.json` does not contain onion servers, is this deliberate? I think the script should be run with a running Tor proxy so that it lists onion servers too.
