### ISSUE TITLE
mistake?

### ISSUE THREAD

**Issue by rain031** [spesmilo/electrum#3864]
how did I make a mistake?
The first transaction on Electrum purse - 32zgFAHGdkHiHpgnaDBz22GHuaFRf7kAnW
  - Successfully. Came in 0.00448141 btc.
But the second transfer to the same wallet did not work.
https://live.blockcypher.com/ltc/tx/5bce7309484b965006fa4733660b6a82c63fc3425e142a9ed03273a294997eac/
and I did not understand why the purse number changed? now he is - 35GQUszj8jHeY8XJh5qX14NnjxCW9PYwno

Does Electrum support the reception of LTC?
Please? help dudes

**Comment by SomberNight** [comment]
Electrum is for bitcoin only. There are forks of the project for different altcoins, including litecoin, maintained by different people.

Unfortunately there is an overlap between litecoin addresses and bitcoin addresses, which you've managed to run into, and sent litecoin to a bitcoin address. You can recover these coins, due to bitcoin and litecoin being sufficiently similar. How to do it is however out of scope here, sorry.

**Comment by rain031** [comment]
why the address changed wallet?
How to recover?
:(

**Comment by bauerj** [comment]
Do you use Electrum or Electrum-LTC?

**Comment by rain031** [comment]
Electrum
