### ISSUE TITLE
Electrum Failed to connect Tor in Tails 

### ISSUE THREAD

**Issue by harmloh** [spesmilo/electrum#3969]
I am using Tails , I set up network on Tails such Electrum docs website said, and I followed that instructions
 
Sock5 localhost 9050/9051 .
 
Blablabka.onion (forget the link) 50001

And it failed to connect

**Comment by SomberNight** [comment]
What version of Electrum?
Tails anecdotally ships with quite old versions.

**Comment by harmloh** [comment]
I am running new Tails 3.5 ,oout on 26 January , not persistent
So I am sure the Electrum is new version in Tails

But I saw the circle green Dot in Electrum , I thought blue dot in Electrum mean that I connect to Tor 
But it was green Dot /circle and when i set up manually , follow instructions on Electrum docs website , it failed

**Comment by SomberNight** [comment]
I think the latest Tails at this very moment possibly ships with Electrum 2.7.9; although I am not fully certain; and that version has several problems. The next version of Tails should AFAIK ship with Electrum 3.0.6 however.

You can manually install a newer version of Electrum on Tails. There are guides on e.g. reddit, such as [this](https://www.reddit.com/r/Electrum/comments/7cjjpg/electrum_synchronizing_message_on_tails/dpqflmh/).

Please make sure you use the latest (or at least a fairly recent) version of Electrum when you report bugs.

**Comment by gits7r** [comment]
Tails 3.5 uses electrum 2.7.9 which is incompatible with the servers currently due to the client-server protocol upgrade.

I have just tested Electrum 3.0.6 from stretch-backports in Tails 3.6 and it will be there, this is just few days away, but if you don't want to wait:

1. Start Tails with administrator account enabled (it's disabled by default so you have to configure it at the start screen). This will let you do sudo commands.

2. Edit /etc/apt/sources,list and add the following line at the bottom without altering the existent content:

deb tor+http://ftp.debian.org/debian/ stretch-backports main contrib

3. Edit /etc/apt/preferences and add the following lines at the top, without altering the existent content:

Package: electrum python3-electrum
Pin: release o=Debian,n=stretch-backports
Pin-Priority: 999

4. Run sudo apt-get update && sudo apt-get -y install electrum/stretch-backports

That's it. Make sure you properly backup your seed (like writing it on a piece of paper) so you can restore the wallet every time you boot Tails.

**Comment by SomberNight** [comment]
> Tails 3.5 uses electrum 2.7.9

Thanks for confirming; closing then.

> I have just tested Electrum 3.0.6 from stretch-backports in Tails 3.6 and it will be there

Great! Thanks again. :)

**Comment by harmloh** [comment]
Can't wait Tails 3.6 .
Big thanks guys
