### ISSUE TITLE
User saved txn as local by mistake; the intention was to send

### ISSUE THREAD

**Issue by ROLER86** [spesmilo/electrum#4124]
Добрый день. Я вчера переводил Bitcoin на банковскую карту через обменник .Средства не поступили обменник отменил заявку что делать. Счет с которого отправлял деньги 15v8RxLoHxMYcjpK9Bv7tdg9zsVj9FkTz7 счет обменника 1FBw74rQ9pixKhRid7fuEqNgyfY4JCPqHC .
![default](https://user-images.githubusercontent.com/37368807/37399451-c55d723a-2792-11e8-81dc-d07668197316.jpg)
![opera _2018-03-14_112849_blockchain info](https://user-images.githubusercontent.com/37368807/37399459-cb37aa90-2792-11e8-8281-92b1ef5e70c5.png)

**Comment by SomberNight** [comment]
Hi. The transaction is "local". That means it has not been sent out ("broadcast") to the network, it is only stored in your wallet. You need to broadcast it if you want the network to see it so that it can actually "happen".
You can also simply delete the transaction at this state, as it was not broadcast to the network yet: `right-click`>`Remove`

**Comment by ROLER86** [comment]
спасибо все решилось
