### ISSUE TITLE
Electrun SYNCHRONIZING for Ever

### ISSUE THREAD

**Issue by Theqwerty11** [spesmilo/electrum#4153]
Hello

I have 2 transactions that are NOT VERIFIED since March 6
and Electrun keep  SYNCHRONIZING since March 6

Using Electrum 2.6.4
thanks

**Comment by bauerj** [comment]
Hey,

please update to a more recent version, e.g. Electrum 3.1.1.

If you need any assistance in upgrading, let us know.

**Comment by Theqwerty11** [comment]
Hello

Thanks for your reply
Yes please i will need assistanve for the upgrade

Thanks

**Comment by bauerj** [comment]
First of all, make sure you have your seed words backed up. Otherwise, click on Wallet -> Seed, write the words down and store them safely.

The further process depends on your operating system:

### Windows
1. Close Electrum.
1. Go to https://electrum.org/#download and download the Windows Installer.
2. Run it.

### Mac OS X
1. Close Electrum.
1. Go to https://electrum.org/#download and download the Executable for OS X.
2. Open the file and drag the "Electrum" app to your applications folder.
3. Run it. If a security message pops up that prevents you from running it, open the Security settings and click the button to allow running it.

### Linux
1. Close Electrum
2. Remove the version that you have currently installed. On Ubuntu, for example you would run `sudo apt remove electrum` in a terminal.
3. Install Python 3 and pip, on Ubuntu you would do `sudo apt install python3-pip`. You can run `pip3` to check if it's already installed.
4. Install Electrum: Run `sudo pip3 install https://download.electrum.org/3.1.1/Electrum-3.1.1.tar.gz`.

Let me know how this worked out.

**Comment by Theqwerty11** [comment]
You are the best. I will try that and let you
Thanks a lot

**Comment by Theqwerty11** [comment]
Hello

I have downloaded the Windows Installer. but can not run it . Error: An eeroor occured while loading the Archive.
Using Tor Broweer

Thanks a lot

**Comment by bauerj** [comment]
It seems that you are trying to run Windows programs on Linux. Linux has its own set of software and cannot run Windows .exe files to install any software.

Can you confirm that this is the case? If so, please use the instructions provided for Linux.

**Comment by ecdsa** [comment]
lol, using 2.6.4
