### ISSUE TITLE
Electrum devided my transaction, without my activity

### ISSUE THREAD

**Issue by maxShaban** [spesmilo/electrum#4154]
Today i have a bag. When i try to send the bitcoin to abucoins.com. Then I was creating the transaction it  contained only one resive address, but after confirming my transaction recived 2 adresses, sudenly. I dont understand how it happen! Help me please!

**Comment by maxShaban** [comment]
Transaction id ab1091fc7773b43578d47f1f26038b8e38366971e9469db7b01958bd3fd0d563

**Comment by bauerj** [comment]
Hey,

no worries about that transaction. It appears like the second address in that transaction is in fact one of your own addresses.

Here is what happens when you send coins with Electrum: Electrum has to spend all the inputs on one address. Since you don't want to send all your money, a part of those funds are sent back to an address of your wallet. To improve privacy, Electrum uses special "change addresses" for that purpose.

To verify that that's the case, right click the transaction on the history tab and click "Details". It will show two outputs for that transactions. If one of those is marked yellow, that's a change address.

**Comment by maxShaban** [comment]
I dont understand)
How i can check it?

**Comment by maxShaban** [comment]
I check it, It's not the yellow

**Comment by bauerj** [comment]
Can you show a screenshot?

**Comment by maxShaban** [comment]
![default](https://user-images.githubusercontent.com/11194579/37679045-dfd748b8-2c90-11e8-903b-392e8b116042.png)

**Comment by bauerj** [comment]
Are you sure that didn't happen because you highlighted the text? Highlighting removes the color for me too:

This is how it normally looks like:
![electrum-3 1 0_2018-03-20_20-50-15](https://user-images.githubusercontent.com/598790/37679146-65935c96-2c80-11e8-9189-468f4a074d95.png)

----


This is how it looks like when the text is highlighted and has no focus:
![electrum-3 1 0_2018-03-20_20-50-20](https://user-images.githubusercontent.com/598790/37679147-65b24250-2c80-11e8-9382-b4241703939a.png)

**Comment by AbdussamadA** [comment]
That is the 2fa fee. See 2 [here](https://bitcoinelectrum.com/frequently-asked-questions/#why-did-my-wallet-send-money-to-an-unknown-address-without-my-permission).

**Comment by maxShaban** [comment]
if i understand correctly it was a commision?
