### ISSUE TITLE
2FA - Seed is not recovering my wallet. Made with 2.9.2 (Probably Stolen)

### ISSUE THREAD

**Issue by angeant** [spesmilo/electrum#4281]
I made my wallet with electrum 2.9.2 2 Factor Auth --> Google Authenticator. (TrustedCOin)

After that my cellphone went broken. So no more Google Authenticator..

Ok, lets recover that wallet with the SEED...  (Thats the only way to do it, cause all the private keys are "mixed" with the other 3 signatory entities --> 1 my password, 2 googleAuth, 3 TrustedCoin) 

SEED ( 12 words, listed perfectly in the dictionary) but not passing the (GRAY NEXT) button.

I supose when I created my wallet a FAKE SEED *but with all 12 correct words* was given to me.

I still have my wallet, and the bitcoin balance is still the same.. no unknown transactions on it.. 

But I cannot send bitcoin from it of course.

And probably the thief has the right seed and can recover it whenever he wants and it's not doing it just because they don't want to get caught.

Any idea guys?

Thanks.

**Comment by SomberNight** [comment]
Are you sure the seed words you have are for this wallet? (you might have mixed them up with a seed for a different wallet software - as electrum does not accept it as a valid seed)
If yes, the easiest explanation is that you wrote your seed down incorrectly. You might have swapped two words next to each other, or even more likely is to write down a similar word instead of the actual one (e.g. `core`, `corn`).

I have a python script here for bruteforcing a single missing word (with unknown position) here:
https://gist.github.com/SomberNight/a53257cf9e05ac07fd47ce0821b2a1fb
It spits out possible correct seeds.
You can adapt it to your case.
If you run it, change `given_seed` and `seed_type` (to `2fa`).

**Comment by angeant** [comment]
Hi, SomberNight This makes me 4 x 13 word passphrase. And they don't work.

Do you suggest something else? Should I delete one word and keep trying your script?

Thanks

**Comment by SomberNight** [comment]
My script is not exactly for your usecase, I just posted it because it is close enough, so it can be modified.
If you don't want to modify it, the easiest thing to use it is to delete one word of your seed words, feed that into the script, try the candidates it outputs, and then try again by deleting a different word this time from your seed.
The script, as the description states, "bruteforce(s) a single missing word for a seed". So in its current state, it assumes that you have n-1 words, in the correct order, and the missing word has an unknown position.

**Comment by angeant** [comment]
My fault, I was using another passphrase.. I found the right one. Sorry.
