### ISSUE TITLE
[add-feature] integrate all address formats in the same wallet file (or in the same wallet.dat or default_wallet whatever)

### ISSUE THREAD

**Issue by jonjonez** [spesmilo/electrum#4345]
It is annoying every time you want to change the type of receiving address format in Electrum to have to use the seed in "new/restore" [and expose the wallet to risk since it will expose the seed again] and change the only way to use the type of address format we want, while in other wallets also known use the three address formats: "legacy, "p2wpkh-p2sh-segwit" and "p2wpkh-bech32-native-segwit" in the same or similar account wallet.dat or whatever, such as coinomi wallet and bitcoin core [okay that in the core this process is a bit bureaucratic] being able to switch between address formats when you want, inclucisve in the core we can change the type of change address [-typechange="bech32" and etc ...)

My suggestion is: since the Electrum wallet accepts all formats of bitcoin addresses, once we create a new wallet (or recover with the backup seed) integrate the three types of address formats, both receiving and change addresses to user disposition.

I would like to thank you for providing the native and compatible SegWit (p2sh-segwit) to the community, the community thanks, my suggestion is just to facilitate and improve the software experience electrum, keep up the good work and sorry if this is not the right place to leave suggestions.

**Comment by SomberNight** [comment]
> every time you want to change the type of receiving address format in Electrum to have to use the seed in "new/restore"

You can create multiple wallets that use different output scripts to receive ("address formats"), and then just open them. You don't need to re-create wallets from seed every time.

You are asking for supporting multiple output script types in the same wallet. Why? Because bech32 is not widely supported? It is just a matter of time. If we do a release that derives multiple script types for a seed, we would need to keep doing that for that seed type FOREVER. Otherwise users would lose coins.
The promise of Electrum is to support all seeds it created forever. This is surprisingly easier for electrum seeds than for bip39 seeds, but not if we start introducing the same complexities as bip39.

We could of course support multiple script types with the same seed if it ever became useful long term; but for legacy/p2sh-segwit/native-segwit, it would only be useful for a short time and then quickly grow into a burden for everyone.

Also see https://github.com/spesmilo/electrum/issues/3460 and https://github.com/spesmilo/electrum/issues/3283

**Comment by jonjonez** [comment]
I agree, so what I can suggest is to add a "use bech32 change address"
option because since the adoption of bech32 is still small, we can use this
type of address as change, coinomi already does this.

Em Dom, 6 de mai de 2018 18:00, ghost43 <notifications@github.com> escreveu:

**Comment by jonjonez** [comment]
> Electrum seeds are incompatible with Coinomi.

yeah I know that

> In order to add a new type of derivation you would need a new seed version. A “hybrid” seed...

When you say "hybrid" do you mean seed BIP39 or that seed is compatible with p2sh-segwit? As far as I know, the seeds generated in electrum in both standart and segwit mode you can derive p2sh-segwit addresses in retrieving wallet by changing the derivation path to: **m/49 '/0'/0 '** only that the seeds generated by Electrum are not compatible with other wallets nor with the [Mnemonic Code Converter](https://iancoleman.io/bip39/), if I want to recover this wallet in the future I will only be able to recover on the electron because the electrum uses its own type of seed, yes I know that, I know the difference between seeds BIP39 and seeds in the format of the Electrum.

> Currently Electrum seeds have the rule “this seed only derives bech32” “this seed only derives p2sh” embedded in the seed itself.

Yes, but if the user wants it it can pick up that bech32 format seed and go on retrieve wallet and change the derivation path to m/49 ... for example. I did this a while back and it worked, so even if that seed is in segwit bech32 format, from the yes to generate p2sh-segwit addresses just by changing the derivation path.

> You would need to make a new seed version to say “this seed derives all types of addresses” and whenever someone restores that seed, you need to check every address of every type forever.

NO! you do not need to check each address for only one option within the already created wallet even if you change the address script to check the outputs. something like: [addresstype: legacy          ] 
                                                                                                              [                     p2sh-segwit ]
                                                                                                              [                     bech32         ]

that once I select one of these options, I would change all the addresses in the "receive" I know that each address format has a different seed, as you said, but we can not deny that each private key, we can derive 3 different addresses using the same key.

> I receive money on p2sh, but change is on bech32, and maybe the HD paths are non-standard.

Wrong, a coinomi uses derivation: m/ 84'/0'/0 ' so why would not it default? except for Electrum which has its own seed format for bech32 addresses, and even if the coinomi disappears from the map of to recover the money by importing the seed and change the derivation to BIP84 that even has that option when we import a seed the electrum asks if we want to recover in legacy, p2sh-segwit or native segwit.

> Coinomi is gone, OR I forget the name of the app and try to use the phrase in another app.

even if this happens, it is very likely that this person seek help in forums and in FC groups and what is not lacking are experienced users on the subject who are sure to help you, downloading an old version of electrum already solves the problem , because coinomi's seed is BIP39 and if imported into the electrum changing to BIP84 it manages to recover the money, or it can use the [mnemonic converter](https://iancoleman.io/bip39/) making the process offline

**Comment by SomberNight** [comment]
> Yes, but if the user wants it it can pick up that bech32 format seed and go on retrieve wallet and change the derivation path to m/49 ... for example. I did this a while back and it worked, so even if that seed is in segwit bech32 format, from the yes to generate p2sh-segwit addresses just by changing the derivation path.

This is not true. You are confused. That is for bip39 seeds, not for electrum seeds. Electrum seeds are versioned, and each version currently only derives one type of output script. That's what @dabura667 meant by a hybrid seed; creating a new version that can derive multiple types.

> but we can not deny that each private key, we can derive 3 different addresses using the same key.

Actually, it's more like (almost) infinite. There was p2pk, then uncompressed p2pkh, then compressed p2pkh, there's also of course p2sh-p2wpkh and p2wpkh, and then all the p2sh and p2wsh with any conceivable redeem scripts/witness scripts. Do you want the wallet to derive all?

> import a seed the electrum asks if we want to recover in legacy, p2sh-segwit or native segwit

That WHOLE DIALOG is only there for bip39 seeds. It is only ever going to get more complicated. More and more. That dialog is NOT there for electrum seeds. Why? Because it is a better design :) We want to keep it that way. It is simpler and hence safer for users.

**Comment by SomberNight** [comment]
Is your suggestion to allow hybrid wallets specifically for bip39 seeds?

**Comment by jonjonez** [comment]
@SomberNight  I do not understand, what do you mean "hybrid" wallets? which allows the 3 scrypts in the same wallet specifically if the seed is BIP39?

**Comment by ecdsa** [comment]
sorry but we will not do that. it is a waste of time.
