### ISSUE TITLE
Non-tech person here. How to restore full functionality if have private keys and wallet, but no seed or F2A

### ISSUE THREAD

**Issue by supahcodah** [spesmilo/electrum#4368]
Hello, first time ever posting to GitHub. I lost my F2A and seed (long story, believe me I tried). I have private keys, my password and my wallet file. Is there any way to get to my bitcoins or are they lost forever?

**Comment by AbdussamadA** [comment]
When you created the wallet you were asked for an email address. Do you have control over that? If you do contact trusted coin via their site trustedcoin.com and ask them to reset 2fa on your wallet. Then move your bitcoins to a new wallet so you don't get locked out again if you ever lose your phone with the 2fa code.

**Comment by supahcodah** [comment]
@AbdussamadA Thank you - will try that now!

**Comment by supahcodah** [comment]
When I try to sweep the keys Electrum gives an error: "redeemed script required for p2sh".

**Comment by SomberNight** [comment]
For each 2FA address, there are three private keys, 2 of which are required to spend. You only have one key. That's why it is two factor. If you could extract enough private keys from a wallet file to spend, it would not be two factor. Sweeping won't work.
You need either the seed words OR (wallet file AND google authenticator).
Asking TrustedCoin to help is essentially cheating on the google authenticator; i.e. even if they do help, you also need the wallet file.

**Comment by supahcodah** [comment]
Thanks... I do have the wallet file!
