### ISSUE TITLE
electrum do not work with windows vista

### ISSUE THREAD

**Issue by AngelTs** [spesmilo/electrum#4370]
electrum 3.1.3 do not work with windows vista SP2, even after installation of KB2999226 update!

**Comment by SomberNight** [comment]
what error message are you getting?

**Comment by AngelTs** [comment]
This application failed to start because it could not find or load the QT platform plugin "windows" in "".
Available platform plugins are: minimal, offscreen, windows.
Reinstalling the application may fix this problem.

**Comment by SomberNight** [comment]
ok, I can reproduce.

Related:
https://github.com/pyqt/python-qt5/issues/2
https://github.com/pyinstaller/pyinstaller/issues/2857

**Comment by bauerj** [comment]
Isn't Windows Vista unsupported already?

**Comment by SomberNight** [comment]
Oh indeed. For some reason I thought it still has a few years.

https://support.microsoft.com/en-us/help/22882/windows-vista-end-of-support

> As of April 11, 2017, Windows Vista customers are no longer receiving new security updates, non-security hotfixes, free or paid assisted support options, or online technical content updates from Microsoft. 

People should not store bitcoins on operating systems that no longer receive security updates; so closing.

**Comment by bauerj** [comment]
We should document that on the download page though.

**Comment by AngelTs** [comment]
Actually some old versions of Electrum (1.8.1) can work under Vista without problem!
It is good to be notice in download section

**Comment by casper** [comment]
I managed to get it to work on Vista SP2 32-bit. It took me a full day to finally figure out the right combination. However it's easy to do, once you know how :) 

These instructions are for Electrum 3.3.8, with Python 3.6.1.

**Step 1:**
Install Anaconda Python `Anaconda3-4.3.0-Windows-x86.exe`. You need to install an archived version, because this will give you a version of Qt that is compatible with Vista. 

This was the biggest issue - trying to find a Python + Qt combination that works on Vista and with Electrum.

Direct download link:
https://repo.anaconda.com/archive/Anaconda3-4.3.0-Windows-x86.exe

Archive repository:
https://repo.anaconda.com/archive/

**Step 2:**
Once installed, launch "Anaconda Prompt (Anaconda3)" from the Windows Start menu.

**Step 3**:
The installed Anaconda version runs Python 3.6.0, but Electrum needs 3.6.1. 
Upgrade by typing:
 
     conda install python=3.6.1

**Step 4**:
Download Electrum-3.3.8.zip from the Electrum Github releases. Extract it somewhere.

**Step 5**:
In the Anaconda DOS prompt you opened in step 2, `cd` to the Electrum folder, and then type:

    python run_electrum

Enjoy your working Electrum on Vista.
