### ISSUE TITLE
Feature Request: Custom Transaction Fee Resolution of Hundredths of a Satoshi per Byte

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [spesmilo/electrum#4415]
I think that being able to set the transaction fee rate at 1.00 or 1.01 or 1.07 or 2.00 satoshis per byte, for example, would be quite useful in managing confirmation times, especially as the fee market seems to have compressed and there are most transactions are in a narrower, lower, range of fee rates.  Having the additional resolution on fee rate could help people precision place their transactions in the "order book" of fee bidding.

**Comment by SomberNight** [comment]
On master we already allow 0.1 sat/byte precision, since https://github.com/spesmilo/electrum/pull/4324
The precision can be easily changed later if it is thought useful.

Also, note that both on 3.1.3 and on master, there is another field in the same line as the fee rate edit, that allows setting the absolute fee. That is as precise as the Bitcoin protocol allows, you can specify the exact satoshi absolute fee you want.
![send_tab_313_1](https://user-images.githubusercontent.com/29142493/41096891-5f797070-6a56-11e8-90e2-fce0aa296f19.PNG)
