### ISSUE TITLE
Question: What is the frequency that a client switches to another server if the current server is behind some blocks?

### ISSUE THREAD

**Issue by vinnyvoo** [spesmilo/electrum#4785]
Question: What is the frequency that a client switches to another server if the current server is behind some blocks?

**Comment by SomberNight** [comment]
Every time the client receives a block header from any server, it checks if the current server is lagging, and if so, it switches to one that hast the best block.
"lagging" is defined to be missing at least two blocks

**Comment by vinnyvoo** [comment]
So in `auto_connect` it switches immediately if its behind more than 2 blocks. 
Cool. Thank you. Closing.

**Comment by kyuupichan** [comment]
@SomberNight fwiw I think that is sub-optimal behaviour.  It should be time-based (e.g. 2 mins since I saw a better block elsewhere and still my server is behind).  We've seen 2 blocks behind happens all the time because you get a big, slow-to-process block, and then a fast 1-tx block, and Electrum deems its server is lagging, whereas it's really only a few seconds behind.
