### ISSUE TITLE
PSBT does not have timelock set

### ISSUE THREAD

**Issue by crwatkins** [spesmilo/electrum#4802]
The PSBT created by the coldcard plugin has a timelock of 0 (and not a recent block height).  Is this intentional?

**Comment by SomberNight** [comment]
The issue is here:
https://github.com/spesmilo/electrum/blob/bcdb0c46fc13c00dcd3d6baf8045199aab54b4c5/electrum/plugins/coldcard/coldcard.py#L449
- `tx` has `locktime` set
- `tx.serialize()` has `locktime` serialised correctly
- `CustomTXSerialization(tx.serialize())` has `locktime=0`; as it the constructor does NOT deserialise the raw hex
- `CustomTXSerialization(tx.serialize()).serialize_to_network(witness=False)` has `locktime=0` serialised
