### ISSUE TITLE
Feature request Android: Lockout with too many wrong PIN

### ISSUE THREAD

**Issue by Engelberg** [spesmilo/electrum#4812]
I'd like to see the mobile app lock up or wipe the wallet if too many wrong PINs are entered.  Given there's only a 6-digit PIN protecting the wallet, I think a feature like that would help security considerably.

**Comment by gits7r** [comment]
I have suggested exactly this before  (tried to search for that issue where I commented but couldn't find) and was explained by @ecdsa that securing the wallet on Android is different than on a desktop, and it's outside the scope of a wallet application.

And he is 100% right about it, because even if such a feature is implemented, the security against physical access to the mobile phone will not be dramatically improved, the attacker can simply take the device physically, see there is a PIN setup for Electrum wallet app and not proceed in a continued stupidity to try more and more PINs until the wallet file si deleted by Electrum wallet app protection. Instead, he will simply connect the data cable and take out the wallet file externally where he can really crack that PIN fast and bypass any protection or timeout the app may have.

So, this is just to highlight that 100% protection for Electrum wallet file on mobile devices relies on phone lock / encryption (Android OS lock, the stronger the better).

However, I see absolutely no harm if we implement such a feature to make it a PITA for less sophisticated attackers (the dumb and violent type, that just take the device without actually understanding how things work under the hood) so I say concept ACK for this. I see only (small) advantages and mitigations of really non sophisticated attackers, but no downsides, so overall I think it's worth it only if the code required is minimal, and no significant re-write is required --because as stated and explained the security gains are small). If everyone is OK with it, sounds good to me. 


Related: 
#2045
#2417 

https://www.reddit.com/r/Electrum/comments/57yfy3/electrum_android/d8wy3pf/

**Comment by SomberNight** [comment]
Not directly addressing the issue, but one related thing that would be useful is to use stronger KDFs (see https://github.com/spesmilo/electrum/issues/3147).
Then again, this will not help much for a 6 digit PIN, the address space is just too small.

**Comment by vinnyvoo** [comment]
@git7r youre right. And instead of only numbers why dont we have alphanumerics and symbols as password?

**Comment by SomberNight** [comment]
@vinnyvoo That is explained in the above [linked reddit comment](https://www.reddit.com/r/Electrum/comments/57yfy3/electrum_android/d8wy3pf/).

> On Android, applications are isolated, so there is no danger that your seed in going to be stolen by another app. In addition, typing a long password would be unpractical for mobile payments (and even dangerous if we used the systems keyboard, which is another app). That is why Electrum, like other wallet apps, uses a 6-digit PIN to encrypt the seed on Android.

**Comment by farzher** [comment]
your arguments for 6 digit pin sound okay, but it's not good enough.
since it can be brute forced, you're basically forcing everyone to store their raw key on their phone!
if android level drive encryption actually worked, then it would be okay. (maybe i should learn more about that but i've had it bug before and delete all my data).
this lockout feature request isn't good enough either.
you need the option to encrypt it beyond brute force.
even if you make decryption insane slow, the space is too small.

i recommend just allowing for a normal text passphrase, like the desktop version, since that's (probably?) the best way humans can remember entropy

**Comment by ecdsa** [comment]
Electrum version 4.0 has password + optional PIN. The password is entered only once, and the PIN can be requested to confirm payments

Since the PIN is shared across wallets, it would not make sense to reset the PIN with the password, or to ask for the password if too many wrong PINs are entered.
