### ISSUE TITLE
Allow transactions with low/no fees

### ISSUE THREAD

**Issue by Timwi** [spesmilo/electrum#485]
There are enough warnings in the client to let users know that low/no transaction fees will mean that the processing will take longer.

There is no excuse for making it completely impossible to create a transaction by outputting an error and not even trying.

Please fix this and allow transactions with zero fees.

**Comment by TheButterZone** [comment]
Followup to @dabura667's comment https://github.com/spesmilo/electrum/issues/485#issuecomment-66408376 - Electrum 2.8.0 needs these 3 lines commented out: (# at the beginning of the lines) https://github.com/spesmilo/electrum/blob/8cc8f8a5e1fe2313163de53a0c4590c4a1b250a9/gui/qt/main_window.py#L1313-L1315

**Comment by besoeasy** [comment]
doesnt work as electrum server doesn't support 0 fees

**Comment by besoeasy** [comment]
then why its saying use 1 sat/Byte fees or use a server that allows low fees

**Comment by shawnpringle** [comment]
I think Aman was conflating the bitcoin peers that actually mine and the
electrum servers.  If the user can send a zero fee transaction now, the
problem is fixed.  The newbies won't understand though the problems that
come after, however.  It is up to the mining pools to accept the
transaction.

On 7 Jun 2018 19:08, "Neil" <notifications@github.com> wrote:

Electrum server doesn't care about fees

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/spesmilo/electrum/issues/485#issuecomment-395581267>,
or mute the thread
