### ISSUE TITLE
Feature request : implement alerting system protocol silimar to Bitcoin.

### ISSUE THREAD

**Issue by doremon1** [spesmilo/electrum#4980]
This feature will save us from emergency situations like recent phishing attack. Any thoughts?

**Comment by leafcutterant** [comment]
It will ruin everyone because the owners of that key will be able to disseminate similar phishing messages. And the key can be stolen as well.

It would recreate the problem.

The alert system in Bitcoin Core has been removed and the alert key has been published to make any message signed by it non-relevant.

**Comment by doremon1** [comment]
ohh i didn't think and knw that. Thanks mate. Closing.
