### ISSUE TITLE
Ignoring/hiding/blacklisting/fighting dust attack/spam inputs/UTXO

### ISSUE THREAD

**Issue by birdie-github** [spesmilo/electrum#5061]
Sometimes your receive transactions like this one:

https://www.blockchain.com/btc/tx/6e41f6acb7541cf4ffeddf126dbd87a01092be8d021a897350a6a332ba67a071

And it's quite expensive to spend them (actually **more** expensive than not to spend them at all).

It would be great if Electrum allowed to blacklist/hide/disable such inputs/UTXOs.

**Comment by iPherian** [comment]
I agree. Or let you know by highlighting the transaction red or something.

**Comment by wtoung** [comment]
please help restore my stolen fund due to electrum wallet which i didn't open for months.
shocking to see my small lost from a PC, which i didn't touch for months.

or is that electrum itself steal our funding !! sorry, i may not know culture of dev team, but want to trust electrum developers are smart, good and honest people.

https://www.blockchain.com/btc/tx/bb08b3ed52955da3c98562638e5d1486328995e029f8b33ce35320deeddcd0b3

any clue restoring? Thanks.

**Comment by AbdussamadA** [comment]
Are you sure the cost of spending these utxos is high enough to worry about? I mean if they are included with other utxos in a transaction then it might not matter much. 

If you want to exclude them here's how. You can select specific inputs to a transaction by going to view menu > show coins and ctrl+clicking them on that tab to select them, right click and choose to spend. So simply spend any other utxos sent to the address where the dust was sent and then on the addresses tab right click on that address and choose to freeze it. Freezing means coins sent to that address are ignored by electrum. This way the dust will never be spent.

**Comment by birdie-github** [comment]
@AbdussamadA 

Your workaround looks overly complicated for average people. It would be so much better to be able to go to the addresses tab, right click a bad transaction and choose something like freeze/hide/blacklist/etc. so that you won't be able to spend it ever.

Also your workaround implies that the user has to move his funds on the blockchain in order to combat dust spam. This is just inefficient/complicated/prone to errors or/and funds loss and generally should be avoided.

**Comment by AbdussamadA** [comment]
- Ordinary people don't care about dust spam. 

- Addresses tab doesn't list transactions. 

- You don't have to move your coins now. You can simply do this the next time you spend your bitcoins.

If you want to be able to freeze specific utxos then you're asking for a feature to be added to electrum. In that case you should edit the OP and the issue title to reflect that.

**Comment by SomberNight** [comment]
I think CoinChooser is really unlikely to automatically select these dust UTXOs when creating new transactions. Did this actually happen to anyone?

**Comment by SomberNight** [comment]
Note that you can now manually freeze individual UTXOs since https://github.com/spesmilo/electrum/pull/5152
Further note that as I said before, it is actually quite unlikely that these ~dust UTXOs would be automatically selected by the CoinChooser. Especially so, as we now ~never spend coins with negative "effective value": https://github.com/spesmilo/electrum/commit/cb69aa80f7f9751ee5ed4699f93e4b00f8c59b10

There is actually another thing we could do to "fight" this, namely we could automatically freeze addresses that become empty (and are "used"), so that we would not spend future coins arriving there without user interaction. That is another discussion however, it would have its own pros/cons. If you are interested in that, I suggest opening another issue; and referring back to this one.
