### ISSUE TITLE
I'm lose ~12 BTC ~ $42k, from an UPDATE SHOW ME ON 3.3.3 OFFICIAL !!!! my family going to dead

### ISSUE THREAD

**Issue by djhoangwar** [spesmilo/electrum#5064]
Electrum 3.3.3 show me a message to update, go to update 3.3.4 and lose all money ~**12 BTC** ~ **$42k**

**PROBLEM IS THE SCAM UPDATE SHOW ME ON 3.3.3 OFFICIAL !!!!**

what the fuck going on with electrum ? i feel like crazy now, my wife, my son going to dead because electrum ??? WTFFFFFCKCKKCKCKK

https://imgur.com/a/vtFSx6G

**Comment by andronoob** [comment]
3.3.4 is obviously a malware, but AFAIK 3.3.3 has already fixed the phishing issue.

Though it doesn't seem to have a chance to recover your stolen fund, if you are still willing to help identify the malware, please post the SHA256 hash of your electrum-3.3.3/3.3.4.exe . You may use 7-zip to calculate the hash.

**Comment by andronoob** [comment]
There's a serious bug in old versions of Electrum: a malicious server could return arbitrary error/warning message to the user. This was exploited by some phishers to trick user into downloading fake "update".
NOTE: Electrum servers are not controlled by the devs, anyone may set up their own server to serve people.

**Comment by ecdsa** [comment]
sorry for your loss. you have been victim of a phishing attack, see issue #4968

**Comment by djhoangwar** [comment]
But this scam message showed from official app 3.3.3
Its bullshit

**Comment by andronoob** [comment]
@djhoangwar If you are willing to help the community analyze the attack, you may upload your Electrum installer exe/zip file. Simply drag & drop here, please.

**Comment by anynamehere** [comment]
Here is the compromised Mac version that got me: https://drive.google.com/open?id=1_Kp5F5eypIAKzkgTf8pnitwDdDxr8yds

I want to know if my whole system has been compromised.

**Comment by Cryptolista** [comment]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  1FcvMGQN9c5aE1o3WQnFqhUN9ShQssNoYd

**Comment by Cryptolista** [comment]
u are so fast to deleted my comment, amazing.  i need help, i need my money back.

**Comment by Cryptolista** [comment]
> Electrum 3.3.3 show me a message to update, go to update 3.3.4 and lose all money ~**12 BTC** ~ **$42k**
> 
> **PROBLEM IS THE SCAM UPDATE SHOW ME ON 3.3.3 OFFICIAL !!!!**
> 
> what the fuck going on with electrum ? i feel like crazy now, my wife, my son going to dead because electrum ??? WTFFFFFCKCKKCKCKK
> 
> https://imgur.com/a/vtFSx6G

I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  1FcvMGQN9c5aE1o3WQnFqhUN9ShQssNoYd

**Comment by redtula1488** [comment]
I have the same problem. I received a message from the wallet that you need to download the update, I downloaded and went there, but I had no money in the account. I was going to translate with the help of private keys via trusted bitcoin mixer. I inserted private ones and made a standard procedure, but they did not go anywhere, the transaction did not appear at all and nothing happened. Then I checked my chips on the bitcoin mixer, but they were already seized. I checked the address where the chips are transferred from the mixer, but it does not display transactions and chips are withdrawn
What to do? I've all lost my money?

**Comment by gits7r** [comment]
We are sorry for this, but this message is confusing and too alarming and causes panic among users.

Electrum doesn't have a bug that can be exploited, it cannot be controlled remotely, it has no open vulnerability that can cause loss without user's action. Electrum was no more "hacked" or "exploited" than gmail, yahoo, outlook and all financial institutions (banks, etc.) as well as various other online services are every day.

Because of how peer discovery works in Electrum, there is not much we can do for old versions, since we can't prevent them with 100% success rate to run into a malicious server.  This is because, unlike other lightweight wallets, Electrum decided to not have only few harcoded  servers that will be responsible for the privacy of all users, and act as single point of failure, but instead allow users to run their own servers or use servers that they trust. Electrum takes user privacy very seriously, which is why proper peer to peer discovery without central authority arbitration was adopted, instead of anything else.  This way an attacker cannot keep an Electrum user offline, or isolate him, or pull various attacks.

While the entire Electrum team is doing absolutely everything possible to protect the users, such as:

- patch Electrum wallet to not display rich text, and don't allow arbitrary messages, only strict codes;

- patch  ElectrumX server implementation to detect sybil (malicious servers that send the phishing message) and not further broadcast them to clients;

- implement blacklist logic to maintain malicious servers outside the view of the clients;

- heavily advertise on social, website and all communication forms existent with the users that they should always run the latest version and always only install from the official source (electrum.org), accessed over secure protocol (https) with prior verifications of the PGP signature;

...the sad truth is that nothing can be truly done to protect an user from its own actions. If you are willing to install Electrum from a different source, when the official is electrum.org, and you don't verify signatures, even with the latest patch that does not display rich text you are still vulnerable as you can receive an email or text message with the same phishing message, and install a backdoored Electrum.

After all, when you install and use security software and finances software such as Electrum the first rule is to make sure you are running a version that has no discovered vulnerabilities and your build is signed and genuine.

I know this is not pleasant to read after loss of funds, and we are sorry, but this is the sad truth. This is not a vulnerability in Electrum, so we are going to respectfully close such issues / tickets on github because we are already doing everything possible to limit the effects of phishing attacks, and such issues do not provide any new information.

**Comment by andronoob** [comment]
@anynamehere 
Sorry, I'm not a malware analyst, so I can't ensure that this fake Electrum didn't install other malwares on your computer. You'd better reinstall your operating system (macOS).

However, I still tried to decompile it, then I made a diff vs official Electrum 3.2.3. You may found the bitcoin addresses used by the attacker.
Notes:
1.The whole `fake-3.3.4-13b57883/PyQt5` subdirectory was ignored;
2.Binary files were ignored;
3.Files which only exist in official Electrum were ignored.
[electrum-phishing-vs-3.2.3-ignore_PyQt5-ignore_binaries.diff.zip](https://github.com/spesmilo/electrum/files/2834687/electrum-phishing-vs-3.2.3-ignore_PyQt5-ignore_binaries.diff.zip)

**Comment by commontree** [comment]
> We are sorry for this, but this message is confusing and too alarming and causes panic among users.
> 
> Electrum doesn't have a bug that can be exploited, it cannot be controlled remotely, it has no open vulnerability that can cause loss without user's action. Electrum was no more "hacked" or "exploited" than gmail, yahoo, outlook and all financial institutions (banks, etc.) as well as various other online services are every day.
> 
> Because of how peer discovery works in Electrum, there is not much we can do for old versions, since we can't prevent them with 100% success rate to run into a malicious server. This is because, unlike other lightweight wallets, Electrum decided to not have only few harcoded servers that will be responsible for the privacy of all users, and act as single point of failure, but instead allow users to run their own servers or use servers that they trust. Electrum takes user privacy very seriously, which is why proper peer to peer discovery without central authority arbitration was adopted, instead of anything else. This way an attacker cannot keep an Electrum user offline, or isolate him, or pull various attacks.
> 
> While the entire Electrum team is doing absolutely everything possible to protect the users, such as:
> 
> * patch Electrum wallet to not display rich text, and don't allow arbitrary messages, only strict codes;
> * patch  ElectrumX server implementation to detect sybil (malicious servers that send the phishing message) and not further broadcast them to clients;
> * implement blacklist logic to maintain malicious servers outside the view of the clients;
> * heavily advertise on social, website and all communication forms existent with the users that they should always run the latest version and always only install from the official source (electrum.org), accessed over secure protocol (https) with prior verifications of the PGP signature;
> 
> ...the sad truth is that nothing can be truly done to protect an user from its own actions. If you are willing to install Electrum from a different source, when the official is electrum.org, and you don't verify signatures, even with the latest patch that does not display rich text you are still vulnerable as you can receive an email or text message with the same phishing message, and install a backdoored Electrum.
> 
> After all, when you install and use security software and finances software such as Electrum the first rule is to make sure you are running a version that has no discovered vulnerabilities and your build is signed and genuine.
> 
> I know this is not pleasant to read after loss of funds, and we are sorry, but this is the sad truth. This is not a vulnerability in Electrum, so we are going to respectfully close such issues / tickets on github because we are already doing everything possible to limit the effects of phishing attacks, and such issues do not provide any new information.

OK this is bullshit - and for electrum to take no responsibitliy is weak to say the least. First off the phishing attack is initiated in Electrum not from any other software. 
There is a pop up that comes up "in electrum" not anywhere else.
Just got screwed fro $600

**Comment by ValdikSS** [comment]
>First off the phishing attack is initiated in Electrum not from any other software.
>There is a pop up that comes up "in electrum" not anywhere else.

This is no different when you download a virus using internet browser. Or Bittorrent client. Neither internet browser developer nor Bittorrent client developer is responsible for that.
I agree that this may be confusing as it is assumed that Bitcoin client use developer's infrastructure, but once you learn how Electrum work, you'll understand it.
And the most important, you need to read licensing terms you've accepted to use this software. It comes with absolutely no warranty. If you disagree with it, you shouldn't use it in the first place.

**Comment by fukuro-kun** [comment]
@andronoob I found at least 380 interesting btc-addresses in your file. Do you have the URI of the provided / analyzed malware? Wich steps did you perform to decompile malware?

**Comment by 4oo4** [comment]
@djhoangwar 

https://github.com/spesmilo/electrum/blob/01f582cc147fcd84555e7e13e366c397c85f7c78/LICENCE#L14-L20

**Comment by chriswebstin** [comment]
Till date I still wonder how I fell for this cheap scam, they kept convincing me to invest more and most payments were by bitcoins, I was super surprised when ultimatefundrecovery on gmail com was able to get most of my money back because by their name I felt they could only recover other forms of payments related to binary options but to my surprise they came out good. I’m done with any form of these investments.

**Comment by PleaseHelpMeToday** [comment]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet: 16qjcKKdjMxLhXmWQ8EoqLptTTKSd6HA9k
