### ISSUE TITLE
BTC Stolen

### ISSUE THREAD

**Issue by petersullivan99** [spesmilo/electrum#5071]
They stole 1.5 btc from me 
Why Electrum shows me that I have to update software ?
I was using it for 1 year and this fucking message came from Electrum server

**Comment by ecdsa** [comment]
hi, can you report the website where you downloaded the fake update?

**Comment by ysangkok** [comment]
> Why Electrum shows me that I have to update software ?

Electrum showed arbitrary rich text coming from servers. We did not realize that Qt allowed rich text per default before the attack started. Arbitrary error messages from the server are not shown anymore, only specific error messages are allowed now.

**Comment by redtula1488** [comment]
> hi, can you report the website where you downloaded the fake update?



> hi, can you report the website where you downloaded the fake update?

I have a similar situation, these bastards stole from me 0.29 btc which I swept into my wallet electrum from bitcoin mixer. They made a transfer from my private key here: 1J2Skp224Gqjqob38GhxAnH7cJkDg2nVdy, and from this account to another: 19443h6JzhetXyevdEy58iqjiwBvt8eMvz, there they are 923$ malware downloaded from this link: https://github.com/electrum-official/EIectrum/releases/tag/3.3.4

**Comment by ecdsa** [comment]
electrum-official has been taken down, thank you

**Comment by gits7r** [comment]
We are sorry for this, but this message is confusing and too alarming and causes panic among users.

Electrum doesn't have a bug that can be exploited, it cannot be controlled remotely, it has no open vulnerability that can cause loss without user's action. Electrum was no more "hacked" or "exploited" than gmail, yahoo, outlook and all financial institutions (banks, etc.) as well as various other online services are every day.

Because of how peer discovery works in Electrum, there is not much we can do for old versions, since we can't prevent them with 100% success rate to run into a malicious server. This is because, unlike other lightweight wallets, Electrum decided to not have only few harcoded servers that will be responsible for the privacy of all users, and act as single point of failure, but instead allow users to run their own servers or use servers that they trust. Electrum takes user privacy very seriously, which is why proper peer to peer discovery without central authority arbitration was adopted, instead of anything else. This way an attacker cannot keep an Electrum user offline, or isolate him, or pull various attacks.

While the entire Electrum team is doing absolutely everything possible to protect the users, such as:

- patch Electrum wallet to not display rich text, and don't allow arbitrary messages, only strict codes;

- patch ElectrumX server implementation to detect sybil (malicious servers that send the phishing message) and not further broadcast them to clients;

- implement blacklist logic to maintain malicious servers outside the view of the clients;

- heavily advertise on social, website and all communication forms existent with the users that they should always run the latest version and always only install from the official source (electrum.org), accessed over secure protocol (https) with prior verifications of the PGP signature;

...the sad truth is that nothing can be truly done to protect an user from its own actions. If you are willing to install Electrum from a different source, when the official is electrum.org, and you don't verify signatures, even with the latest patch that does not display rich text you are still vulnerable as you can receive an email or text message with the same phishing message, and install a backdoored Electrum.

After all, when you install and use security software and finances software such as Electrum the first rule is to make sure you are running a version that has no discovered vulnerabilities and your build is signed and genuine.

I know this is not pleasant to read after loss of funds, and we are sorry, but this is the sad truth. This is not a vulnerability in Electrum, so we are going to respectfully close such issues / tickets on github because we are already doing everything possible to limit the effects of phishing attacks, and such issues do not provide any new information.

**Comment by MyLifeIsOver** [comment]
> They stole 1.5 btc from me
> Why Electrum shows me that I have to update software ?
> I was using it for 1 year and this fucking message came from Electrum server

I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  1FcvMGQN9c5aE1o3WQnFqhUN9ShQssNoYd
