### ISSUE TITLE
Bitcoin wallet address invalid

### ISSUE THREAD

**Issue by Tractorface123** [spesmilo/electrum#5073]
my receiving address for my bitcoin wallet is invalid. 
ive just created this wallet and used a website called "moon bitcoin" the address says invalid when you enter it on the site.  The same thing happens with "coinpot" a thing you can deposit the coins to from the moon website.
if those websites are hacks/scams the wallet is empty anyway as i dont know how to add to it.

is this a bug or am i doing something wrong? - ive never used bitcoin before.

**Comment by ecdsa** [comment]
maybe you are using segwit addresses and they do not recognize them?

**Comment by SomberNight** [comment]
Create a new wallet, and choose "legacy" as seed type.
Some old websites don't support the new address format.
![seed_type](https://user-images.githubusercontent.com/29142493/52299510-ddcb7b00-2985-11e9-9656-68e9cf0b1900.PNG)

**Comment by SomberNight** [comment]
Fairly certain this is due to bech32 addresses not being implemented on the mentioned websites. Closing.

**Comment by chriswebstin** [comment]
Till date I still wonder how I fell for this cheap scam, they kept convincing me to invest more and most payments were by bitcoins, I was super surprised when ultimatefundrecovery on gmail com was able to get most of my money back because by their name I felt they could only recover other forms of payments related to binary options but to my surprise they came out good. I’m done with any form of these investments.
