### ISSUE TITLE
Tails Latest Version 3.12 and Electrum 3.1.3 with Server/Scam/Warnings etc etc

### ISSUE THREAD

**Issue by electuser** [spesmilo/electrum#5083]
On latest version of Tails (Build 3.12 release circa Jan 2019) is still shipping with Electrum 3.1.3

Using Tails without persistance you get a fresh and secure copy of Electrum every time to use, and you are certain that the version is correct (provided you verified Tails in the first instance). 

If you dont use persistance in Tails, you would have to keep upgrading Electrum to latest version everytime you run Tails......so for now you are stuck on 3.1.3. You can also use off-line signing of transactions with Tails, thus increasing security.

Downsides to this is that the Electrum development has kept updating much faster than the Tails O/S can keep track of versions. Hence, Tails is still shipping with Electrum 3.1.3.

When broadcasting transactions on certain Electrum servers, a message saying something along the lines of:

_"Error: Your transaction was still broadcasted but you are using an older version of Electrum that has a vulnerability. Please upgrade at: https://electrum.org"_

**Question I have:**

I currently feel with so many issues regarding Electrum versions it is safer to continue to use old version on Tails - for now???

Secondly, will Tails version upgrade Electrum to current version now that Tails is using an unsafe version of Electrum which in theory could not only affect Electrum but also the whole Tails O/S ???

I assume this is more of Tails developers job that Electrum, but as Tails has supported the Electrum project for years is it worth engaging with them to upgrade (if not done so already?)

**Comment by gits7r** [comment]
We are aware. The situation of software shipped by default in Tails is a little bit different. It has to be in debian `stable-backports` in order to be shipped with Tails. At this moment, this is what we have in `stable-backports`. Electrum Debian package maintainer @mithrandi was offline for a period and will hopefully resume work by Mid February. 

As soon as Electrum is upgraded in Debian `stable-backports`, it is also automatically included in the next Tails release.

As for your questions:
1. I wouldn't call them issues. It's a phishing scam, that exists since the internet exists, and will continue to do so and target anything from wallets, online bank accounts, social media accounts, email accounts, etc. The problem is that Electrum displays is as rich text and adds more weight to the confusion.

2. The Electrum version currently used in Tails is safe to use. Except is somewhat annoying because you get warning messages all the times (from malicious servers the message with the phishing scam and the malware website to install a backdoored Electrum, and from honest servers the message we use to counter the phishing attack that your transaction was broadcasted but you should upgrade from https://electrum.org because you are using a vulnerable version). Other than this annoyance, there is no security risk.

Under any circumstances the entire OS is NOT affected, nor other applications. In fact not even Electrum is affected, it requires action from the user to manually install a backdoored Electrum from an untrusted source without verifying signatures. In Tails it's not so simple like in other OSes to install third party software, so Tails Electrum users are better of held back from doing such mistakes. As long as the phishing message is ignored and no malware is installed, not even Electrum is at risk, that version is OK to use. Not to mention the entire OS and other apps, it has absolutely nothing to do with them.

Yes, this is a Tails / Debian thing. This issue actually has no scope here, but it's good that you opened it so interested people can have the confirmation that things are being taken care of. There are tickets on both, I am closely monitoring them and I assure you the version in Tails and Debian `stable-backports` will be upgraded. Some time has to pass when uploading a package to Debian, it goes through unstable ... wait ... testing .... wait ... and then `stable-backports`. Nothing we can do about these time wait periods.

**Comment by electuser** [comment]
**gits7r** thank you for coming back to me and taking the time to accurately respond through what is a github forum full of people getting phished by this clever but equally callous attack resulting in novices loosing funds. 

Just to touch on that before I respond to you **gits7r**, for years now it is fair to say that no O/S, especially any Windows O/S, is just not safe to run a hot wallet with any funds in them. As gits7r described, this attack was a simple phishing attack. If we include zero-day exploits and the sheer amount of untrustworthy files on the internet and couple that with windows which has ALWAYS been notoriously insecure, you are literally asking for trouble. 

Unless you are storing small amoutns of funds ($100 or less), I would recommend a hardware wallet at the absoulte minimum. Obviously that isnt going to do anything for the unfortunate (and growing) amount of electrum users who seemed to have lost funds. 

Anyway, to answer your points **gits7r**

**1)** Thank you for clearing that up. These are small phishing issues but it appears a lot of novice users have been stung. It is pleasing to hear they are no more than that for any longer term Electrum users. 

However, I will take you back to around this time last year, when electrum had a JSON security flaw where any wallet that was open and connected to the interent was affected. In theory when a user visited a certain website, an attacker could connect to a website and the website's cookie could excute remote code and pull funds from the wallet (provided the wallet.dat was not passworded or insufficiently passworded). 

I am not sure if TAILS users were affected by this (as I am not sure how JSON is configured through the browser), but it is was a concerning attack for a lot of people. 

**2)**

I meant something slightly different by this. Say the user on TAILS, (or any OS for that matter), clicked the malicious link and downloaded the rouge Electrum file and then installed it, at this point, the whole O/S could be compromised.

This is why forum members are recommened any Electrum users who download and install a copy of this software should reinstall a fresh copy of Windows (or whatever O/S they are using), as there is no way of knowing what other potential backdoors this unverified software could contain. That was my point thats all....


**3)** It is refreshing that @mithrandi is back and will be working on the new Electrum version. There are a lot of Electrum users on Tails and as far as I know, Tails has zero-interest supporting any other BTC wallet software, or any other alt-coin wallet for that matter!

There is a lot of new features implemented in recent versions of Electrum, and it would be nice to see them upgraded in Tails in the not too distance future. 

Going forward, do you think  @gits7r Electrum under Tails with offline signing or Electrum and a Trezor is the more secure? 

As far as I am aware the Trezor is the most secure hardware wallet (providing you verifiy the company you brought it from) and is probably the strongest option, as its less prone to bugs as Tails is (as Tails is an O/S and therefore has a lot more software prone to attack)...... Whats your thoughts?

**Comment by gits7r** [comment]
> 
> 
> **gits7r** thank you for coming back to me and taking the time to accurately respond through what is a github forum full of people getting phished by this clever but equally callous attack resulting in novices loosing funds.
> 
> Just to touch on that before I respond to you **gits7r**, for years now it is fair to say that no O/S, especially any Windows O/S, is just not safe to run a hot wallet with any funds in them. As gits7r described, this attack was a simple phishing attack. If we include zero-day exploits and the sheer amount of untrustworthy files on the internet and couple that with windows which has ALWAYS been notoriously insecure, you are literally asking for trouble.

I think this is a different subject. Nobody said anything about the security of Windows operating system or compared cold wallets with hot wallets on any OS. You could be right, or not, but this is a different subject unrelated.

> 
> Unless you are storing small amoutns of funds ($100 or less), I would recommend a hardware wallet at the absoulte minimum. Obviously that isnt going to do anything for the unfortunate (and growing) amount of electrum users who seemed to have lost funds.
> 
> Anyway, to answer your points **gits7r**
> 
> **1)** Thank you for clearing that up. These are small phishing issues but it appears a lot of novice users have been stung. It is pleasing to hear they are no more than that for any longer term Electrum users.
> 
> However, I will take you back to around this time last year, when electrum had a JSON security flaw where any wallet that was open and connected to the interent was affected. In theory when a user visited a certain website, an attacker could connect to a website and the website's cookie could excute remote code and pull funds from the wallet (provided the wallet.dat was not passworded or insufficiently passworded).

The JSON RPC interface that wasn't protected was not exploitable in Tails due to its firewall and default networking settings. That was indeed a vulnerability, a bug in Electrum, unlike this phishing attack that relays on the user himself to be the vulnerability. This has also nothing to do with the current situation and what we were discussing. Nobody who had a decent enough password on their wallet lost funds due to the JSON RPC vulnerability.

> 
> I am not sure if TAILS users were affected by this (as I am not sure how JSON is configured through the browser), but it is was a concerning attack for a lot of people.
> 
> **2)**
> 
> I meant something slightly different by this. Say the user on TAILS, (or any OS for that matter), clicked the malicious link and downloaded the rouge Electrum file and then installed it, at this point, the whole O/S could be compromised.
> 
> This is why forum members are recommened any Electrum users who download and install a copy of this software should reinstall a fresh copy of Windows (or whatever O/S they are using), as there is no way of knowing what other potential backdoors this unverified software could contain. That was my point thats all....

OK, So? It's a good practice, better safe than sorry. Nobody has clearly reviewed the code of all the malware apps that are out there and stealing coins, so nobody can tell for sure if they are taking anything more than the coins in the wallet, so any sane security advisor would recommend this. Without actually reading the code nobody knows for sure what exactly is the malware doing.

> 
> **3)** It is refreshing that @mithrandi is back and will be working on the new Electrum version. There are a lot of Electrum users on Tails and as far as I know, Tails has zero-interest supporting any other BTC wallet software, or any other alt-coin wallet for that matter!
> 
> There is a lot of new features implemented in recent versions of Electrum, and it would be nice to see them upgraded in Tails in the not too distance future.
> 
> Going forward, do you think @gits7r Electrum under Tails with offline signing or Electrum and a Trezor is the more secure?

I never used Trezor. I don't know and I cannot comment on this. It's up to any user to use whatever wallet they want or whatever combinations of wallets. From my perspective, any wallet is good as long as you use it properly. If you are .... distracted and you install unverified software from untrusted sources that you receive in phishing messages (might come via email, phone, any other app, not just Electrum Error message return by the server) -- than nothing can truly protect you.
> 
> As far as I am aware the Trezor is the most secure hardware wallet (providing you verifiy the company you brought it from) and is probably the strongest option, as its less prone to bugs as Tails is (as Tails is an O/S and therefore has a lot more software prone to attack)...... Whats your thoughts?

Nobody has done any tests to confirm or infirm this.  It's up to anyone to decide and use whatever they want. I am not advising for its usage, but also not against it. 

I have no thoughts at all about this. Use whatever you think it's good for you, but just make sure to read instructions and use it right and make sure you are running a good version that has no known bugs. More than this, I have absolutely nothing to comment on question if Trezor and Electrum used together are more secure in Tails OS. I can't recommend, nor say anything against. Up to anyone to do whatever they want. All I can tell you is that I am using pure Electrum with good security practices and nothing more.

**Comment by SomberNight** [comment]
This looks answered, so I'll close it.
