### ISSUE TITLE
LOST MONEY WITH ELECTRUM LATEST VERSION

### ISSUE THREAD

**Issue by merkelanno** [spesmilo/electrum#5108]
Today when I checked my balance I saw I have no any bitcoin on my electrum wallet
could you please help me :!!!!

this is the transaction without my approval

fraud address
bc1q92md7868uun8vplp9te0vaecmxyc5rrphdyvxg

**Comment by merkelanno** [comment]
how to recover them, how to stop this fraud transaction

**Comment by SomberNight** [comment]
Where did you download Electrum from? Please check your browser history and copy the link from there.

**Comment by merkelanno** [comment]
https://electrumapps.com/#home

**Comment by ysangkok** [comment]
that's not the real website...

**Comment by merkelanno** [comment]
It was pushed from version 3.3.2 as an UPDATE

**Comment by SomberNight** [comment]
The official website is [electrum.org](https://electrum.org/#home). See the warning at the top:
> Warning: Versions of Electrum older than 3.3.3 are vulnerable to a phishing attack, where malicious servers are able to display a message asking users to download a fake version of Electrum. Do not download software updates from another source than electrum.org. In order to reach users of vulnerable versions, we have started to use the same vulnerability, and to direct them to electrum.org.

Also see https://electrum-malware.surge.sh/

I guess you must have seen a phishing popup and download and installed a fake electrum.
Sorry but there is nothing that can be done.

**Comment by ValdikSS** [comment]
@merkelanno 
Electrum is a "lite" Bitcoin wallet, which does not download full blockchain and keep it locally, but relies on a servers with full blockchain. Such servers may be set up and operated by anyone, including me and you, and they would be automatically used in Electrum.
When you send money, if the transaction can't be performed, server may respond with text error message with the reason of that.

During last month, some malicious servers appear, which do not accept money transactions and only return bogus error message. This error message states that your client is outdated and you should download a new, updated one. This "updated" client is not an official Electrum client but one provided by a hacker (by this server operator), designed to stole your money and probably to perform further malicious activity on your computer (e.g. stole your browser passwords and other private data). It's uploaded to the website unrelated to Electrum official website or github page, but it is designed to look very close to original one, to fool you to download the file and install it.
Unfortunately, you've installed such client, and now you lost your money. There's no way to return your money. Electrum developers have nothing to do with this malicious "updated" versions. Official Electrum page https://electrum.org/ have the following text on top:

>Warning: Versions of Electrum older than 3.3.3 are vulnerable to a phishing attack, where malicious servers are able to display a message asking users to download a fake version of Electrum. Do not download software updates from another source than electrum.org. In order to reach users of vulnerable versions, we have started to use the same vulnerability, and to direct them to electrum.org. 

Just to be clear, once again: you've installed a virus instead of original Electrum client, uninstall it or better, reinstall the whole operating system because nobody has investigated if the virus perform other actions other than money stealing. And you can't return your money since it Bitcoin, a system built without any party which should be trusted, like banks. You can only monitor further transactions from the address where your money go, and try to determine the person behind that.
