### ISSUE TITLE
Wrong public key shown on version 3.3.3

### ISSUE THREAD

**Issue by otaviobps** [spesmilo/electrum#5115]
I have four electrum wallets. Three of them are HW p2wsh wallets that were imported to electrum, and one of them is a p2pkh wallet created by electrum. Two of the three HW wallets are multisig wallets. All of them work fine.

In version 3.3.3, I was checking my pubkey from my two multisig HW wallets, but something strange happened. Electrum showed the same pubkey for both wallets (one is 1/2 and the other 2/2). They are different wallets, with different transactions, but the same pubkey was shown to both.

Another bug happened when I tried to see my cosigner pubkey. I had to switch between both cosigners radio buttons multiple times, because the same pubkey was being shown for both:

Wallet 1/2:

<img width="470" alt="screen shot 2019-02-13 at 11 26 19" src="https://user-images.githubusercontent.com/28715087/52715084-b1fe5580-2f82-11e9-8845-895a0f83b1e8.png">
<img width="471" alt="screen shot 2019-02-13 at 11 26 33" src="https://user-images.githubusercontent.com/28715087/52715094-b6c30980-2f82-11e9-99c7-90a821d60e42.png">

Wallet 2/2:

<img width="471" alt="screen shot 2019-02-13 at 11 32 31" src="https://user-images.githubusercontent.com/28715087/52715265-1faa8180-2f83-11e9-8552-a029ca02e580.png">

After switching from cosigner 1 and 2 multiple times, another pubkey was shown (probably mine from the 2/2 wallet), but the same pubkey was shown for both cosigners:

<img width="469" alt="screen shot 2019-02-13 at 11 34 29" src="https://user-images.githubusercontent.com/28715087/52715377-7912b080-2f83-11e9-9927-799846ee3297.png">
<img width="467" alt="screen shot 2019-02-13 at 11 35 06" src="https://user-images.githubusercontent.com/28715087/52715384-7ca63780-2f83-11e9-9ddb-1eda5d992ff5.png">

The expected behavior would be electrum showing a different pubkey for each wallet and each cosigner

Edit: I'm running version 3.3.3 on Mac
Edit2: I downgraded to version 3.3.2 and the same bug happened

**Comment by SomberNight** [comment]
Can you please see https://github.com/spesmilo/electrum/issues/4777 and say if you think it's the same issue?
That issue is about the text not refreshing when you switch the radio button state.

**Comment by otaviobps** [comment]
Part of. If you click multiple times, it refreshes the pubkey. But the same pubkey is being shown in two different wallets. They were supposed to have different pubkeys. No matter what I try, I can't view the pubkey of the 1/2 wallet

**Comment by SomberNight** [comment]
Try in console:
```
>> wallet.get_keystores()[0].xpub
>> wallet.get_keystores()[1].xpub
...
```
Do you see expected xpubs then?

**Comment by otaviobps** [comment]
I see different xpubs for the same wallet (cosigner 1 and 2 pubkeys), but they are the same for both wallets (they should be different)

**Comment by SomberNight** [comment]
Ok, so that is a separate issue from the Qt display bug of course.

I think I understand now.
> Electrum showed the same pubkey for both wallets (one is 1/2 and the other 2/2). They are different wallets, with different transactions, but the same pubkey was shown to both.

They are correctly the same master public keys, derived from the same seeds, but you are reusing them for two different wallets. The generated addresses between the wallets are different because the wallets use different scriptPubKey templates (output scripts). (well because of segwit witness stuff, it's a bit more complicated, but nevermind that)
So e.g. for a 1 of 2 multisig, the script is `1 <pubkey1> <pubkey2> 2 CHECKMULTISIG`
While for 2 of 2 multisig, the script is `2 <pubkey3> <pubkey4> 2 CHECKMULTISIG`
In your case, pubkey1==pubkey3, and pubkey2==pubkey4.
The two scripts result in different addresses, but they reuse pubkeys.

For privacy reasons, this setup is not ideal, but otherwise it's fine.

**Comment by otaviobps** [comment]
Oh I see. I didn't know electrum worked like this. Both multisig wallets were generated by electrum, but I'm implementing my electrum personal server and I'm not getting luck on make it work with my 1/2 wallet. I get `This means Electrum is requesting information about addresses that are missing from Electrum Personal Server's configuration file.` from the server.
What's the best way to fix it? Create another 1/2 multisig wallet? If so, how can I force electrum to generate a new pubkey?

**Comment by SomberNight** [comment]
Can you paste/upload you EPS config? Just mask/mock out private stuff.

**Comment by SomberNight** [comment]
> If so, how can I force electrum to generate a new pubkey?

Well the issue is with bip39/bip44 really. Given a mnemonic, and derivation path, you get a bip32 node. The script type does not enter the calculation, so if you want to reuse the mnemonic (seed words), but get different pubkeys, the only thing you can do is change the derivation path.
Which is why bip49/bip84 was made, to use different derivation path and standardise them for p2sh-segwit single signing, and native segwit single signing respectively. There are no standard paths for "m of n" multisig.

**Comment by SomberNight** [comment]
```
TE_Giro = 2 (pubkey1) (pubkey2)
PSW = (pubkey)
TE_Cold = 2 (pubkey1) (pubkey2)
```

What does the `2` mean? shouldn't it maybe be `1` for one of those wallets to make it "1 of 2"?

@chris-belcher

**Comment by otaviobps** [comment]
You are right. I edited it and now I'm rescanning. I'll close this issue if this solves the problem with electrum. Thanks!

**Comment by otaviobps** [comment]
Perfect, that was the problem. Thanks!
