### ISSUE TITLE
"new transaction" OS notification is confusing when sending

### ISSUE THREAD

**Issue by leishman** [spesmilo/electrum#5171]
When sending a transaction with the MacOS app, a Mac notification appears saying: "New transaction received: -1.2434 BTC (-500 USD)". (numbers just an example). This notification is a bit confusing since users aren't receiving funds when sending them (although technically the change output may be seen as a receive).

**Comment by SomberNight** [comment]
What happens when you create and send a transaction is the following:

-----
1. the client broadcasts the tx to the server
2. the server gives it to the bitcoin node to broadcast
3. the bitcoin node puts it in its mempool and relays it to other bitcoin nodes

4. the server sees the new transaction in the bitcoin node's mempool, and processes it
5. while processing, the server notices that there is a client subscribed to some of the touched addresses (which may be the "input addresses")
6. the server sends a notification that the history of an address changed to the client
7. the client compares the history status hash against what he has, and realises the disagreement
8. the client requests the whole history (txids and block heights) for that specific address
9. the client sees it does not have some transactions corresponding to the txids
10. the client requests the missing transactions
11. upon receiving them, the client processes the transactions and adds them to its own history
12. and now the Qt notification is sent to the operating system
-----

Notice that if the client "receives" an incoming transaction (coins from someone else), the flow is the same, except step (1)-(3) are skipped.

So I guess this explains the current behaviour.

What exactly is your suggestion? To "not show a notification if the balance change due to the txn is negative"?
What if two people share the same wallet, and one of them sends a tx; should the other not get a notification?
What if there is a 3-of-5 multisig wallet, and 3 people collaborate to sign and send a tx; should the others not get a notification?
What if you have some presigned transactions that you give to a lawyer, and he at some point broadcasts them; should you get a notification?

So I guess instead of negative balance change, it could be that we "don't show a notification on the client that broadcasts it"? Do you think that would be useful?

**Comment by leishman** [comment]
I assumed the flow was something like this and definitely see the complexity given the many ways electrum could be used. One potential approach could be a simple update to the presentation logic:

If negative amount, show something like: "Outgoing transaction detected: -1.2434 BTC (-500 USD)"

If positive amount, use the current messaging.

I think this small update would be strictly better than the current logic. Do you see any flaws with this?

**Comment by SomberNight** [comment]
> If negative amount, show something like: "Outgoing transaction detected: -1.2434 BTC (-500 USD)"
If positive amount, use the current messaging.

One edge case is if the transaction is a completely internal transfer: all inputs and outputs are controlled by the wallet. Naively, the amount (wallet delta) is negative then; it is the fee; but "Outgoing transaction" is not exactly the case then. Should that have a third wording then? :/

How about having a single wording for all cases like now, but changing that wording from "New transaction received"? Maybe simply to "New transaction"...

**Comment by leishman** [comment]
> How about having a single wording for all cases like now, but changing that wording from "New transaction received"? Maybe simply to "New transaction"...

I think this is probably the best approach for now to keep things simple.
