### ISSUE TITLE
Sending Max bitcoins automatically unintentionally 

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#5187]
I tried to submit two separate payments of 2 and 3 micro bitcoins. I had a total of 9 micro bitcoins in my wallet the first time and it sent the max when I very clearly did not hit max. I sent 24 micro bitcoins to my account and this time when sending 2 micro bitcoins and being very wary of the send max button hit the preview button and the amount changed from 2 micro bitcoins to the max. This is happening over and over right after I updated etherium and now I can't send bitcoins from etherium or it will send all of it.

**Comment by AbdussamadA** [comment]
See [here](https://github.com/spesmilo/electrum/issues/5183#issuecomment-471024756). Sorry for your loss.

**Comment by ecdsa** [comment]
@ghost did you recently upgrade Electrum?
if yes, can you post here the URL where you downloaded from?

**Comment by Boutag** [comment]
Hello @ghost,
I had the same problem, but when sending 0.0005 BTC it sent all amount of my Wallets to somewhere, i still do not know where the money went because there is no final Bitcoin Adress but the oparation was confirmed at the blockchain and my Bitcoin Adresses are all empty !!!
if you are using the Version 4.0.0 of Electrum you risk to lost all the amount of your wallet, so i suggest you to uninstall it and to get the Version 3.3.4 from the offical website https://electrum.org and do not go to other website.
Be carefull please and good luck.

**Comment by SomberNight** [comment]
@ghost will not reply, as he had already deleted the account

**Comment by Boutag** [comment]
Hello @SomberNight,
Thank you for your help :+1:
