### ISSUE TITLE
Missing funds from Electrum

### ISSUE THREAD

**Issue by Deeeez44** [spesmilo/electrum#5216]
I updated to electrum 4.0, added my nanoledger as a wallet and now all my funds are gone! Can somebody help me figure this out?

**Comment by SomberNight** [comment]
There is no Electrum 4.0. Where did you get the idea otherwise?

Where did you download what you downloaded from? Copy the link from your browser history.

Lastly, if you have a Ledger hw wallet that you use with Electrum, every transaction needs to be confirmed on the screen of the Ledger using its dedicated buttons. Not even malware can bypass this protection.

**Comment by Deeeez44** [comment]
I was using Electrum 3.3.2 before and it asked me to update. 4.0.0 was the version it made me download. 

As for the confirmation, when I loaded up my ledger, it asked me to confirm the funds. It shows the funds being transferred out on my history. This same thing happened for my non hardware wallet.

**Comment by Deeeez44** [comment]
https://i.gyazo.com/6a096e0761a6808678e88c737beca3ff.png

**Comment by Deeeez44** [comment]
Looks like I'm out $3k... Just read an article about this being Phishing.

**Comment by Deeeez44** [comment]
Any idea how compromised my computer could be?

**Comment by ecdsa** [comment]
when exactly did you see the phishing message asking you to update to 4.0 ?

**Comment by Boutag** [comment]
@Deeeez44, sorry for you loss, you are not the only one !
Take a look at these other issues :
Electrum 4.0.0 : Serious Error !!! #5183
Sending Max bitcoins automatically unintentionally #5187
Phishing attack #5190

**Comment by Boutag** [comment]
@Deeeez44, if you are still using the Version 4.0.0 of Electrum you risk to lost all the amount of your other wallets, so i suggest you to uninstall it and to get the Version 3.3.4 from the offical website https://electrum.org and do not go to other website, that is what i did and untill now it is ok.
Be carefull please and good luck.

**Comment by bitzicoin** [comment]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  1FcvMGQN9c5aE1o3WQnFqhUN9ShQssNoYd

**Comment by bitzicoin** [comment]
> Looks like I'm out $3k... Just read an article about this being Phishing.

I am dying

**Comment by Deeeez44** [comment]
> @Deeeez44, if you are still using the Version 4.0.0 of Electrum you risk to lost all the amount of your other wallets, so i suggest you to uninstall it and to get the Version 3.3.4 from the offical website https://electrum.org and do not go to other website, that is what i did and untill now it is ok.
> Be carefull please and good luck.

Thanks @Boutag, I've downloaded the up to date version and using that now. Costly mistake!

**Comment by Deeeez44** [comment]
> when exactly did you see the phishing message asking you to update to 4.0 ?

It just asked me to update to the latest version as my older version was no longer supported.  This was all within Electrum. It brought me to the "fake" electrum page where I downloaded the 4.0 version. I wish I had the link still but I cleared browser already.

**Comment by ecdsa** [comment]
my question was "when exactly". Not "why", not "how"...

**Comment by AbdussamadA** [comment]
- If you reuse the same PC without doing an OS reinstall your at risk from secondary infections that might have been left behind by the malware

- Reusing the same seed in a legit electrum is also a bad idea. The attacker has your seed/private keys so you have to create a new electrum wallet after you do an OS reinstall

**Comment by Santana888** [comment]
Same happend to me last Sunday. I wanted to transfer 480 Euros in Bitcoin and was suddenly prompted that in order to do that I need to upgrade to version 4.0.0.
Then all my funds like 520 Euros was sent. 
Never arrived at the address. 
How is such a scam possible?
Antivirus didn't find anything on my computer. 

Please advise.

**Comment by SomberNight** [comment]
> upgrade to version 4.0.0.

There is no Electrum version 4.0.0. Latest version atm is 3.3.4.

There is a vulnerability in Electrum <3.3.3, using which servers can send you arbitrary text messages; some servers use this to try to trick users to download malware.

See https://github.com/spesmilo/electrum/issues/4968 and https://electrum-malware.surge.sh/

If you downloaded and used software from those phishing messages, then what you used was not Electrum. Those coins are gone.

**Comment by 0aa123456** [comment]
Same happened to me, Is it permanently lost?

**Comment by Amitie10g** [comment]
Is there a way to sue the scammers? I also lost my funds and I'm angry.

I contacted the FTC and the FBI through the [IC3 compliant report](https://complaint.ic3.gov/default.aspx) (although I'm not from the US). If you're an US citizen, you may also contact a lawyer at least for advisory (free of charge).

I found [this WHOIS](https://gist.github.com/Amitie10g/19d9d7feccd6368d7e68cb0e8f38ea0f) and provided it to the report, and also reported to Privacy Protect service, in order to find the criminals.

Also, my funds were sent to the following address:

1GK4PjSqYCMVigcuMSY1GmEbhEbijf9Hkr

You may aslo report the address https://electrumstart.net as scam website.

**Comment by SadLife1** [comment]
I was robbed of a very high value, which was years ago to pay for a medical treatment, I am dying slowly. so I still have hope because I have God in my heart.
I created a new account and I am accepting donations to anyone who feels the desire to help me.
Thank you and best wishes to you and your family.

My bitcoin Wallet:  3NiddVKEBCPY29vuh9RKUgNWPUsqZztt98
