### ISSUE TITLE
PLEASE HELP ME OUT URGENTLY

### ISSUE THREAD

**Issue by INEEDTHIS1** [spesmilo/electrum#5371]
I have just downloaded Electrum 3.6.6. updated version to my PC (windows).

Installed the process and have the wallet, but when i tried to send BTC to the wallet for a payment that needs to be done right now, from my Localbitcoins wallet, it tells me that the Electrum wallet address is not valid or not correct.

I have doubled checked for any mistake in copying the Electrum wallet address, but it's all correct though on my Localbitcoins portal the address can't receive BTC.... Please I need urgent help to resolve this problem (anyone pls).

**Comment by SomberNight** [comment]
Localbitcoins probably does not support segwit bech32 addresses (this a [standard from 2 years ago](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki)), which Electrum now uses by default.
You should complain to Localbitcoins.

For the meantime, you can create another wallet in Electrum, `File`>`New/Restore`, and select
`Standard wallet`>`Create a new seed` and then select `Legacy` instead of `Segwit`.
This will create an old type wallet that has old type addresses.

Again, please complain to Localbitcoins.

**Comment by INEEDTHIS1** [comment]
Got it solve. thanks to you SomberNight.

Now the Electrum receives BTC, and so I have to pay BTC from Electrum to Coingate.  I hope it works on sending to Coingate now.

Thanks

**Comment by INEEDTHIS1** [comment]
Another issue again with the Electrum 3.6.6.

It fails to indicate receipt of another BTC which i have paid to the wallet once again, because it seems there will be charges to make further payments to coingate. THE BTC WAS RECEIVED IN THE WALLET BUT IT'S SHOWING Unconfirmed[149.3 sat/b, 0.50MB], BUT THE BALANCE SHOWS THE ADDITIONAL BTC PAID TO THE WALLET.

I hope this is not a problem and would allow me make payments from the Electrum wallet to Coingates invoice wallet ??
Please
