### ISSUE TITLE
tar.gz sdist should be reproducible/deterministic

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#5434]
The [source distributable](https://github.com/spesmilo/electrum/blob/cb204dd969955e6ac6b23821500c406678a3ce97/contrib/build-linux/README.md)  should be made deterministic.

(requested on IRC)

**Comment by ldz1** [comment]
Version 3.3.8 (diffs):

1. Deterministic build doesn't generate:
- packages/bitstring.py
- electrum/gui/kivy/theming/light/lightning.png
- electrum/gui/kivy/theming/light.atlas
- electrum/gui/kivy/theming/light-0.png
- electrum/gui/kivy/theming/light-1.png
- electrum/gui/kivy/theming/light-2.png

2. Same content but different order:
- Electrum.egg-info/PKG-INFO
- Electrum.egg-info/requires.txt
- PKG-INFO

3. Deterministic Electrum.egg-info/SOURCES.txt doesn't contain "electrum" and the entries mentioned in 1 (I hope the fix for 3. will fix 1.)

4. File diffs (missing in deterministic build):
- "Certinomis - Root CA" in packages/certifi/cacert.pem 
- SUBS_TREE in packages/typing_extensions.py

5. Different version inside packages/certifi/__init__.py
