### ISSUE TITLE
Electrum will not open. 

### ISSUE THREAD

**Issue by Rorschached99** [spesmilo/electrum#5442]
I downloaded from Electrum installed ok but all I see is the blue word Electrum. I turned off VPN, enabled permissions, uninstalled AVG. I only see the blue Electrum screen. Any ideas? TKS in advance, Chris.

**Comment by SomberNight** [comment]
Is this on Android? What version of Android; and what phone do you have?

**Comment by Rorschached99** [comment]
Yessir. Android 7.0 Asus Zenpad.

**Comment by DavidTangye** [comment]
I have just installed it for the first time on Android, and it works fine.

The reason I installed it there was that as today it fails to start on my Odroid xu4 ARM SBC. The error I get is -

```
MESA-LOADER: failed to retrieve device information
libEGL warning: DRI2: failed to open exynos (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
Unable to find an X11 visual which matches EGL config 1
```
Perhaps the failure is due to an update of software on the xu4. It is running Ubuntu 18.04.1. Anyway let me know if this should be raised as a separate issue.
