### ISSUE TITLE
No me permite enviar fondos

### ISSUE THREAD

**Issue by dalton819** [spesmilo/electrum#5454]
Buenas tardes....
Estoy tratando de enviar fondos y me indica que no puedo que tengo que actualizar la versión de Electrum, ya actualizé a 3.3.6 y aun no me permite usar mis fondos, me indica que tengo los fondos pero al colocar cualquier monto inferior indica fondos isuficientes

Agradeciendo su gestión para solucionar este inconveniente

**Comment by SomberNight** [comment]
Do you have more than say 0.001 BTC in this wallet?
If you go to the `Coins` tab, (View>Show Coins), then how many items in the list do you see?

**Comment by dalton819** [comment]
Me indica que tengo un saldo de 0.0014067 BTC que lo conforman 9 items

**Comment by dalton819** [comment]
Buenos dias...
Luego de varios intentos logre realizar un envió, sin embargo de 0.0014067
de tengo de saldo lo máximo que me permitió enviar fue de 0.0009775.
Agradeciendo explicar el motivo

**Comment by dalton819** [comment]
Y al verificar mi billetera me indica que esta en cero (0.00000) ….? asumo que cobran una comisión pero cuanto es el porcentaje por que ahí una diferencia de 0.0004292, mas del 30%...?

**Comment by SomberNight** [comment]
Glad it worked out.
The transaction fee depends on the size of the transaction in bytes; so e.g. the number of inputs.
It does not depend on the value at all.
For small transfers like yours, doing on-chain bitcoin transactions is not really practical because of this.

What you can try is use really low fees, and risk waiting a lot. See https://bitcoinelectrum.com/how-to-manually-set-transaction-fees/
