### ISSUE TITLE
On startup electrum attempts to connect to a lot of different servers

### ISSUE THREAD

**Issue by leishman** [spesmilo/electrum#5455]
When electrum starts up it attempts to connect to  A LOT of different servers. Is there any particular reason for this? This seems like a privacy issue for users, as their presence & IP address seems to be broadcast to a lot of random servers.

Perhaps the default setting should be to connect to one of a handful of servers known to be controlled by good actors and users can choose to change the server manually if they want.

**Comment by peleion** [comment]
What you described is _exactly_ what happens - Electrum bootstraps to a hard coded server list who then provide their peer list and Electrum then attempts to connect with 8 reachable servers (I believe, the number may be different).  Actually getting on a server can be problematic due to a) sybil/botnet attack b) the relative scarcity of authentic servers and c) resource limits on ElectrumX servers, notably over Tor as they appear to all come from relatively few source IPs. 

You can manually choose to connect to just one server by running:

`python3 run_electrum --oneserver --server <server URL>:<port>:s`

using linux from the command line in the source directory. This is what most people do who run private servers (including myself)

**Comment by leishman** [comment]
I see. Ok that is good to know. Thank you for the insight. And how well vetted are these peer lists? It has come to my attention that chainalytics companies are running electrum servers and I'm trying to understand the likelihood of any electrum application connecting to a bad actor like this.

**Comment by peleion** [comment]
They are not vetted. You could run one in the public pool if you want.

There is a default blacklist that SomberNight (one of the devs) maintains but it is a cat and mouse game where the rules are constantly changing - is not a straightforward task. 

Analysis is big business - I block what I can at the bitcoind level (using gmaxwell's list) but it would not surprise me if they are attempting Electrum surveillance as well  but it would be a different beast - the bitcoind daemon actually broadcasts the transaction - ElectrumX is just used basically as an SPV (header index).

**Comment by SomberNight** [comment]
https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#does-electrum-trust-servers

**Comment by peleion** [comment]
Damn. Would have saved me the time writing this up if I knew that was in the FAQ :)

**Comment by SomberNight** [comment]
I just added it.

**Comment by Amitie10g** [comment]
Beaware about the fake Electrum 4.0 version!
