### ISSUE TITLE
Lost Bitcoin

### ISSUE THREAD

**Issue by brennanjoles** [spesmilo/electrum#5463]
Sent bitcoin to coinbase and 100% put in the correct address and triple checked it and then after I sent it the address changed and it was sent somewhere else and now I am out of $500. Can anything be done?

**Comment by brennanjoles** [comment]
Ah so I was tricked into the electrum 4.0.0 download. Absolutely ridiculous that electrum devs don’t have any warnings inside their wallet about this scam. DONT USE ELECTRUM TO STORE BITCOIN! They obviously don’t care about their users losing money as they have known about this for a long time. The link pops up INSIDE their own wallet which resulted in myself losing $500 worth of BTC. What a joke

**Comment by tinhhn2** [comment]
Me too, I pay to correct address , I sent it the address changed and it was sent somewhere else.
Used electrum 4.0.0

**Comment by ecdsa** [comment]
we cannot add warnings, or any other feature, to the software that you run on your machine, without you actively installing a new version. (please understand that if we could do that, we could also steal your bitcoins)

please report the theft to the police of your jurisdiction, and inform us about it (email electrumdev@gmail.com)

**Comment by chriswebstin** [comment]
Till date I still wonder how I fell for this cheap scam, they kept convincing me to invest more and most payments were by bitcoins, I was super surprised when ultimatefundrecovery on gmail com was able to get most of my money back because by their name I felt they could only recover other forms of payments related to binary options but to my surprise they came out good. I’m done with any form of these investments.
