### ISSUE TITLE
Local incoming transaction

### ISSUE THREAD

**Issue by freezable** [spesmilo/electrum#5473]
I have a incoming transaction with the status local as you can see here: 
https://gyazo.com/63da7c5d14fb2e27e728e13a1f1519d6

I tried to look up what it means and it was said that it means that the transaction was created but not signed/broatcasted yet. This all makes sense but what does it mean when its an INCOMING transaction. It cannot be not broatcasted because then I wouldn't see it, right? 

Could someone please explain what this exactly is, how it happend and what to do with it?

**Comment by SomberNight** [comment]
The server you connected to told you about it, the client saved it, and then at some point later the server you were connected to then, did not know about it at all.
So instead of deleting it completely, the client marked it as local.
This can organically happen e.g. when the mempool is full and a transaction pays a too low fee (although looking at current mempool, it seems unlikely now).

You can try to connect to another server, or just broadcast it, see if it is still valid (or if it conflicts with another tx now).
Hard to tell exactly what happened though.

**Comment by freezable** [comment]
First, excuse the duplicate, don't know how this happend.

This transactions are not recent. I have them in my wallet for some time. I tried changing the server, as expected nothing happend. Broadcasting them also does not work, "Missing input" warning is shown.

Could this also be that someone double spended me? 

Since I cannot do anything with them, should I just delete them?

**Comment by ecdsa** [comment]
yes, "missing input" means that the transaction was double spent. you can delete the transaction, you will not be able to receive these funds. if you believe this double spent was done maliciously, you can save the transaction to disk (export) and use it evidence later.

**Comment by freezable** [comment]
Thank you for clarification. In my opinion the explanation of "Local" transaction status should be added somewhere in the Electrum documentation.

**Comment by ecdsa** [comment]
or as a tooltip..

**Comment by zebra-lucky** [comment]
There is another possible situation, when tx can become local -- wallet switching to lagging server and tx is recently added to blockchain.

And hence rises a question in a different domain. Local transactions not fall into used addresses and it is posslible to use for change/payment request already used addresses. I can make PR to count as used addresses in `wallet._history_local` if that makes sense.

**Comment by zebra-lucky** [comment]
Found it's already fixed in master branch.
