### ISSUE TITLE
phishing

### ISSUE THREAD

**Issue by alex9522** [spesmilo/electrum#5478]
You are just  useless cunts who steal from their users. This fishing atack is made from you , and now i am gonna report that you are scammers in every cryptocurrency forum and facebook group so nobody will use your shit wallet anymore.  Useless cunts!

**Comment by SomberNight** [comment]
This is not constructive. We have spent a lot of time on trying to mitigate the phishing (see https://github.com/spesmilo/electrum/issues/5452#issuecomment-505141428) but due to the decentralized architecture of the server network, and the fact that we cannot change the code of already download old versions (otherwise we would be able to steal your coins just like a bank!), we cannot protect users of old software.
