### ISSUE TITLE
thiefs

### ISSUE THREAD

**Issue by alex9522** [spesmilo/electrum#5479]
Ok i read other people posts, and i saw i am not the only one who get scammed and lost all his balance. What to say... Seems that this issue have been here from monts. Electrum support are pretending , the new versions are protected from the fishing and the hole in the code is closed. I saw the topic ,phishing,, from where is obvious the guy have used the latest electrum verison 3.36 but sill lost all his funds??! But even if thats not truth, the question is , why they did not exclude the vulnerable versions from their servers? They hope their users gonna check the electrum site regulary? Ofcourse they know very well, most of us use their wallets pretty rarely its unlikely to check their site. They know we all trusted Electrum becouse its offline wallet.i think, electrum support is part of the scheme. As a programmer i can not imagine, how this is possible. I think you are scammers and i will everything to crush you to dust so you loose all your users! Anyway,scammers or useless people, you do not deserve to support wallet if your coustomers loose all their balance! Shame on you!

**Comment by ldz1** [comment]
I have been looking at these threads for some time and I am starting to think it takes on the form of trolling. Unfortunately, in these threads there is less and less room for discussion because everything has already been said. You can call people scammers, but some shortcomings can always happen. However, they were quickly corrected which was already explained.

The user is responsible for:
- Using only the official web page.
- Learning to verify GPG singatures.

>I saw the topic ,phishing,, from where is obvious the guy have used the latest electrum verison 3.36 but sill lost all his funds??!

Sorry, it is not true. Your tone is very arrogant. I understand the bitterness caused by the loss of money, but this discussion does not make sense. All the best.

**Comment by SomberNight** [comment]
same as https://github.com/spesmilo/electrum/issues/5478
