### ISSUE TITLE
I sent bitcoin and it was subtracted from my wallet but it never was received at the other end. Can someone please help me? 

### ISSUE THREAD

**Issue by heinness** [spesmilo/electrum#5480]
Can anyone help me with an unsuccessful bitcoin transaction?

**Comment by heinness** [comment]
I have the same problem- I sent bitcoin and it was subtracted from my wallet but it never was sent/received at the other end. 
Here's the transaction on Electrum in the History section: what does this even mean? There should be an actual date showing the bitcoin was transferred successfully.
DATE
Local [rbf, 10.sat/b]

**Comment by ecdsa** [comment]
'local' means that the transaction is not in the memory pool of the >Bitcoin network, but only exists on your machine. it usually happens because the transaction fee was too low, so the transaction is dropped from the memory pool.

you can remove that transaction and send the same payment again with a higher fee.
