### ISSUE TITLE
`electrum restore xpriv....` derives the wrong wallet in 1-out-of-256 cases

### ISSUE THREAD

**Issue by DanielWeigl** [spesmilo/electrum#5490]
The function `restore_wallet_from_text` (which gets called by cli commands, but not if you initialize the wallet via GUI) trys to decide if the provided text is a seed or a xpriv here: https://github.com/spesmilo/electrum/blob/94b721baa484972cc360332a4d4ba7b6cb77a2dd/electrum/wallet.py#L2054

The check for seed is in my understanding only if the first byte of the hash of the provided text is `0x01` (here https://github.com/spesmilo/electrum/blob/94b721baa484972cc360332a4d4ba7b6cb77a2dd/electrum/version.py#L7 ) - so in 1 out of 256 cases this leads to wrong interpretation of a valid `x/y/zpriv` key:

eg this:

```
electrum restore yprvAJBpuoF4FKpK92ofzQ7ge6VJMtorow3maAGPvPGj38ggr2xd1xCrC9ojUVEf9jhW5L9SPu6fU2U3o64cLrRQ83zaQGNa6YP3ajZS6hHNPXj

electrum  listaddresses           
[
    "19L5Xs8zN9ADyBHbsdtDQiqc3puzMKaZ9a",
    "1PM5onyqwBkdzNuhuGcbtHrT8fizAo9jAw",
    "14CW17Js9V2y7sUynbfPptKJnCGWMjZ3ZH",
    "1LQQnN1CtMQRf2mT2hVwgWaPezLqdPN18D",
    "1Lyu7NArkLqpMbjv6WTcNdFXKVYYQRVx7q",
    "146Bh8Rq1kMd5kHfnaeyspHdBmLT754Bfw",

```

where as this should be P2SH-Segwit addresses

If I try to import this key via the GUI assistant i get the correct "3..." addresses, because it uses `keystore.from_master_key(text)`, which checks for xpriv first and then for seed:
![grafik](https://user-images.githubusercontent.com/1370302/60716943-e3bb8d00-9f20-11e9-8a14-ced99c535e23.png)
![grafik](https://user-images.githubusercontent.com/1370302/60716964-f6ce5d00-9f20-11e9-8290-0c4f2577caaf.png)

(this is a main-net key, but it was never used - keep it that way :) )

**Comment by SomberNight** [comment]
Yes, you are right... Thanks for reporting this.
The issue is that the string `yprvAJBpuoF4FKpK92ofzQ7ge6VJMtorow3maAGPvPGj38ggr2xd1xCrC9ojUVEf9jhW5L9SPu6fU2U3o64cLrRQ83zaQGNa6YP3ajZS6hHNPXj` is both a valid xprv and a valid electrum seed. The definition of what is a valid electrum seed is quite lax. :)
I guess the easiest fix would be to reverse the order of checks here:
https://github.com/spesmilo/electrum/blob/9b82321fc083f3fb4728d9f3785a04861a617011/electrum/wallet.py#L2054-L2059
