### ISSUE TITLE
I mststkely used my old versio, of tails electrum to transfer money.Now the transaction showing as 16 verifications but he money has gone. I dont know how to get the tails error to windows to post it please help

### ISSUE THREAD

**Issue by pyoulesgmail-com** [spesmilo/electrum#5549]

**Comment by AbdussamadA** [comment]
the version on tails is outdated and no longer displays accurate balances. update electrum on tails : http://docs.electrum.org/en/latest/tails.html

alternatively install the latest version of electrum on windows and restore from seed.

**Comment by ecdsa** [comment]
thanks @AbdussamadA

**Comment by pyoulesgmail-com** [comment]
Thank you for your help I can seem to uprade the old wallet and the new windows one doesn’t even ask me for my seed. Any idea? I lost £70.00 yesterday.

Regards

Paul
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pyoulesgmail-com** [comment]
I have managed to upgrade my old electrum wallet on tails to the latest. I have also restored my windows one with a seed. My money is still missing and now has over 165 confirmations. Can you help any further

Paul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pyoulesgmail-com** [comment]
I Manged to upgrade my old tails wallet and restore my new windows one with a seed. The money is still missing and has over 165 confirmations. Can this be reopened?

Regards

Paul


ThomasV<mailto:notifications@github.com>
Sent: 09 August 2019 09:10
To: spesmilo/electrum<mailto:electrum@noreply.github.com>
Cc: pyoulesgmail-com<mailto:pyoules@hotmail.co.uk>; Author<mailto:author@noreply.github.com>
Subject: Re: [spesmilo/electrum] I mststkely used my old versio, of tails electrum to transfer money.Now the transaction showing as 16 verifications but he money has gone. I dont know how to get the tails error to windows to post it please help (#5549)


Closed #5549<https://github.com/spesmilo/electrum/issues/5549>.

**Comment by AbdussamadA** [comment]
Just to be clear you tried to receive money to your electrum wallet? See [here](https://bitcoinelectrum.com/frequently-asked-questions/#what-can-i-do-if-i-havent-received-bitcoins-sent-to-me) for things you can try.

**Comment by pyoulesgmail-com** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Paul Youles<mailto:pyoules@hotmail.co.uk>
Sent: 11 August 2019 10:01
To: spesmilo/electrum<mailto:reply@reply.github.com>; spesmilo/electrum<mailto:electrum@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>
Subject: RE: [spesmilo/electrum] I mststkely used my old versio, of tails electrum to transfer money.Now the transaction showing as 16 verifications but he money has gone. I dont know how to get the tails error to windows to post it please help (#5549)

**Comment by pyoulesgmail-com** [comment]
I actually tried to send not receive

Regards

Paul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by AbdussamadA** [comment]
I haven't sent you any emails. What you are receiving as emails are comment reply notifications from github because you posted an issue on electrum's git repo: https://github.com/spesmilo/electrum/issues/5549. The image you posted does not appear in this issue. You should upload it to imgur.com and post the link here.

Post the transaction id as well. You can get it by right clicking on the transaction on the history tab, choosing to view details and copying the large hexadecimal number up top.

Finally post what you intended to do and what really happened. If you intended to send money and money was in fact sent then what is the problem? Did the recipient not get it? Did the money get sent to the wrong address? Do post the intended amount and intended recipient's address as well.

We don't have access to your wallet or your mind.
