### ISSUE TITLE
bitcoin stolen

### ISSUE THREAD

**Issue by costi90** [spesmilo/electrum#5569]
my Bitcoin wallet is empty… all my Bitcoins are stolen yesterday… help!!!!
![2019-08-18 (1)](https://user-images.githubusercontent.com/54239867/63225056-bffc8f80-c1cc-11e9-9272-ad52be29b9c5.png)
![2019-08-18 (4)](https://user-images.githubusercontent.com/54239867/63225059-c12dbc80-c1cc-11e9-80b2-9279938bfaf7.png)
![2019-08-18](https://user-images.githubusercontent.com/54239867/63225060-c12dbc80-c1cc-11e9-9f62-762579d782ac.png)

**Comment by costi90** [comment]
![2019-08-18 (5)](https://user-images.githubusercontent.com/54239867/63225142-93954300-c1cd-11e9-9b65-be74b37fff3c.png)

**Comment by gits7r** [comment]
There is absolutely 0 information in this ticket. Why do you think the screenshots are helpful? They only show an instance of Electrum running with some transaction history, like any regular wallet will look like. There is absolutely nothing special about them and nothing anyone can come to a conclusion from.

The only way your coins could have been transferred without your intent is if you are running a malicious, malware infected Electrum which WAS NOT downloaded from the official website https://www.electrum.org - you can go to that page and see the checksums and GPG signature for all packages, and determine if you are running a genuine installation. If your system was compromised due to a mistake someone made, well...

**Comment by AbdussamadA** [comment]
>There is absolutely 0 information in this ticket. Why do you think the screenshots are helpful? They only show an instance of Electrum running with some transaction history, like any regular wallet will look like. There is absolutely nothing special about them and nothing anyone can come to a conclusion from.

They are useful. They show us he's using the latest version, he's connected to the network so the history is accurate and the coins were moved to an address outside his wallet. So overall it appears that it is not a misunderstanding on his part. His coins really were stolen.

They don't tell us who stole them though. 

@costi90 please do check your browser history to confirm the exact URL you downloaded electrum from. Also did you install any other software recently? Did you enter your seed on some website or upload it to cloud storage?

**Comment by ecdsa** [comment]
well, the information that is provided is better than nothing, but it is not useful from a development perspective. we don't know how the coins have been stolen, and we cannot use this report to improve the software. I'll close this; please keep the discussion on bitcointalk
