### ISSUE TITLE
tor proxy

### ISSUE THREAD

**Issue by ubone** [spesmilo/electrum#5580]
from journalctl

```
Tor[2691]: Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Tor[2691]: Application request to port 110: this port is commonly used for unencrypted protocols. Please make sure you don't send anything you would mind the rest of the Internet reading!
Tor[2691]: Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
Tor[2691]: We tried for 15 seconds to connect to '[scrubbed]' using exit $somestring at someip. Retrying on a new circuit.
Tor[2691]: Tried for 126 seconds to get a connection to [scrubbed]:50002. Giving up.
Tor[2691]: Tried for 125 seconds to get a connection to [scrubbed]:110. Giving up.
```
[electrum status](https://i.imgur.com/WlxkCqc.png)

**Comment by SomberNight** [comment]
> Tor[2691]: Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.

DNS resolution failed for some server host. Could happen.

> Tor[2691]: Application request to port 110: this port is commonly used for unencrypted protocols. Please make sure you don't send anything you would mind the rest of the Internet reading!

Some server is hosted at port 110. Possible. E.g. ecdsa.net IIRC uses it

> Tor[2691]: Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)

Probably because of the Tor-proxy-discovery done by the Qt Network Dialog. It sends an HTTP request on candidate Tor SOCKS proxy ports to detect them.

> Tor[2691]: We tried for 15 seconds to connect to '[scrubbed]' using exit $somestring at someip. Retrying on a new circuit.

Not sure. I guess this is just an ordinary timeout... ?

> Tor[2691]: Tried for 126 seconds to get a connection to [scrubbed]:50002. Giving up.
Tor[2691]: Tried for 125 seconds to get a connection to [scrubbed]:110. Giving up.

Also look like timeouts; probably for certain Electrum servers. Could easily happen.

-----

These all look like harmless warnings / log lines. Do you experience any actual issues?

**Comment by ubone** [comment]
> Do you experience any actual issues?

no but I haven't sent/recieved

another thing I noticed is that those are only spammed when the GUI is visible
