### ISSUE TITLE
Qt Addresses tab: show and sort-by derivation path

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#5641]
I would need this to be able to know which address is the next one unused and not create large gaps.

Right now I can sort the address list by:
![image](https://user-images.githubusercontent.com/388716/64931661-f2b79900-d807-11e9-8cd5-ca2eeb4ae8da.png)

But can't sort by simple chronological derivation order.

Also it would be great to see the derivation origin somewhere, preferably in Wallet > Information

**Comment by SomberNight** [comment]
Note that the default sort order is based on the derivation indices.

I think adding a new column, even optionally, that shows the derivation path might be overkill.
However, I would like to modify the sort order of the `Type` column to sort based on derivation paths (we can also show the derivation path in a tooltip if you mouse-over).
Unfortunately due to implementation specifics, this would depend on https://github.com/spesmilo/electrum/issues/4920

**Comment by SomberNight** [comment]
Master now shows the derivation path for an address in the tooltip for the first column: https://github.com/spesmilo/electrum/commit/d8180c678b9f476da9807556debf1974284e3825

I had a look at sorting by it, but as above it's a bit slow (although not as slow as I remembered).
https://github.com/SomberNight/electrum/tree/202003_qt_addr_list_proxy and atm https://github.com/SomberNight/electrum/commit/3d2043ed8857538fdeb564db585ff81dbefc6b6e
It would be better with `QAbstractItemModel`...

**Comment by SomberNight** [comment]
The time needed to refresh the Addresses tab if we added custom sort orders (not just based on the text content of the fields as currently) would increase by about 40%. This would only be noticeable for really large wallets. I think the utility outweighs the performance penalty.
