### ISSUE TITLE
Does the Cosigner Plugin also works on Testnet ? 

### ISSUE THREAD

**Issue by skyerjoe** [spesmilo/electrum#5678]
**Win7 
Electrum  3.3.8  with Testnet Flag
Conection: Over Tor** 

Hello Folks,

I tried to test the Multisig Wallett in Testnet  and it works with the manual sending of the Transaction but not with the Plugin Cosigner. 

So does it work in Testnet Mode ? 

best regards

**Comment by SomberNight** [comment]
Yes, the cosigner plugin should work on testnet too.
Do you get an error?
You should [enable debug logs](https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#how-to-enable-debug-logging) and upload your logs.

**Comment by skyerjoe** [comment]
Okay i want to reproduce the scenario from scratch and then attach the logs: 


**1.** Two  Multisig Wallets ( 2 of 2) created. And added the Cosigner MPK on each other.
**2.** On both Wallets Cosigner Plugin activated.
**3.**  Sent an Amount from an Different Wallet ( Single Electrum Segwit Wallet)  to the Multisig Wallet 1.
**4.** Waiting for at least 2 Confirmations on Multisig Wallet 1. 
**5.** Activate log file logging refer to FAQ.
**6.** Send funds back from Multisig Wallet 1. to Different Wallet 
_* Doesnt work with Multisig Plugin Button is missing*_
**7.** Send funds back from Multisig Wallet 2 to Different Wallet  
**8.** Push the Cosigner Button "Send to Cosigner" 
**9.** Cosigner Info Box rises in Multisg Wallet 2 
_*But there is no Cosigner Message in the Multisig Wallet 1*_

Before we investigate with the help of the logs, did i make anything wrong so far  ? 

best regards

**Comment by skyerjoe** [comment]
alright there we go: 
[electrum_log.txt](https://github.com/spesmilo/electrum/files/3694390/electrum_log.txt)

best regards

**Comment by skyerjoe** [comment]
but what i dont understand.

if i do point 3 the transaction also showed up in the Multisig Wallet 2 , why? it's on other wallet isnt't it?

best regards

**Comment by skyerjoe** [comment]
And what ive discovered in some tests that some cosigner transactions are arriving the 2cnd cosigner and some not.  

then i have to restart wallets than it may u got the message then but this doesnt wor in any way. 

 dont know may the cicumstance that it's only an testnet plays an role.

best regards

**Comment by lunarovic** [comment]
The cosigner pool plugin doesn't work for me in testnet, while it is working perfectly on mainnet with the same setup - two 2of2 wallets.

The "Send to Cosigner" button is completely missing in one wallet, while in the other I get this error when clicking the button:

> Failed to send transaction to cosigning pool:
> <ProtocolError for cosigner.electrum.org/: 301 Moved Permanently>

Here is the debug log:
[electrum_log_20200612T204252Z_11568.log](https://github.com/spesmilo/electrum/files/4773199/electrum_log_20200612T204252Z_11568.log)

**Comment by lunarovic** [comment]
My previous message was referring to version 3.3.8. Now when I do the same thing in 4.0.0b1, everything is the same as I described, except now the error message reads:

> Failed to send transaction to cosigning pool:
> SSLError(58, 'nested asn1 error (_ssl.c:4003)')

Much more error details in the debug log:
[electrum_log_20200628T231344Z_5316.log](https://github.com/spesmilo/electrum/files/4843150/electrum_log_20200628T231344Z_5316.log)

**Comment by SomberNight** [comment]
@lunarovic your new issue is probably caused by your OS ssl certificate store.
I made some changes so we don't rely on that in the future: https://github.com/spesmilo/electrum/commit/1a9e6a434f9fb5277c0813e2438805e1f23397be
Though I don't understand why this would be related to testnet vs mainnet at all.

**Comment by lunarovic** [comment]
@SomberNight I just tested this on mainnet and I think you were right that this has nothing to do with testnet, but with the fact that I (and probably OP) use testnet in a different circumstance/environment than mainnet, which is - two wallet windows open at the same time on the same computer. That's why the issue showed up only in testnet for me.

Steps to reproduce:
1. Obviously turn on the Cosigner plugin.
2. Create two 2of2 wallets by following the steps marked **(*)** below to kill two birds with one stone, because another issue is there.
3. Open both wallet windows and have them stay open concurrently.
4. Fund an address in the multisig wallet.
5. Choose a wallet window, go to the Preview/Advanced window (reproducible in both 3.3.8 and 4.0.0b1) and Sign some transaction. Note the presence or lack of the "Send to cosigner" button. Optionally close the Advanced window.
6. Go to the other wallet window and do the same as in the previous step. Compare.

The "Send to cosigner" button will show up only in the **last opened wallet**. In the other wallet (which was opened first), the button will not show up. Somehow the most recently activated GUI "steals priority" (with my lack of a better expression) from the older window. You can now close both windows and try and open them in the opposite order, and the button will switch places.

**(*)** Another possibly related issue (see the bold text above and below) is that the wizard GUI locks up if you are creating two multisig wallets at the same time. Steps to reproduce:
1. Open any existing wallet (just to be able to easily access the wizard at File -> New/Restore)
2. Start creating the first multisig 2of2 wallet.
3. Save the Zpub somewhere and click Next once or twice. Now you have to obtain the cosigner's key, so you have to leave the wizard at that step.
4. Go to File -> New/Restore and start creating the second 2of2 wallet.
5. Copy the Zpub and paste it in the other wizard window (where you stopped at step 3 here).
6. Click Next. Nothing happens, you are stuck there and can't finish creating the wallet.
7. Return to the more recently opened wizard window, click Next and paste the previously saved Zpub from the first wizard.
8. Click Next. In this wizard window, **which was opened last**, the button works and you can finish creating the wallet.
9. Finally you can return to the remaining wizard window and this time the Next button will work.

**Comment by SomberNight** [comment]
the second issue you describe is tracked in https://github.com/spesmilo/electrum/issues/3286

**Comment by SomberNight** [comment]
re first issue, see https://github.com/spesmilo/electrum/issues/3080

Ok, so maybe this is actually the issue being reported here. Let's defer to that issue then.
