### ISSUE TITLE
Pairing of hardware wallet to keystore can appear to fail in multisig setup

### ISSUE THREAD

**Issue by craigraw** [spesmilo/electrum#5789]
It is common in a multisig setup to have hardware wallets that are geographically separated, thus Electrum must handle situations where only one hardware wallet is plugged in at any given time, even though the Electrum wallet specifies several hardware keystores.

On loading a wallet with hardware keystores, Electrum scans for available devices and attempts to match the xpubs. There exists a [conditional in plugin.py](https://github.com/spesmilo/electrum/blob/b469df5283f9ba890555666299338974fbf3a308/electrum/plugin.py#L561) that detects that if only one device has been found in the scan, it is automatically returned so that the device xpub can be compared to the keystore xpub (without first comparing labels as happens with multiple scanned devices). 

In the case where the first keystore xpub does not match the xpub of the single device plugged in, Electrum displays an error "Electrum cannot pair with your ...". Electrum then goes onto the remaining keystores, and should successfully pair with the device, but the user is left in doubt due to the warning displayed in the interface.

**Comment by SomberNight** [comment]
ACK, indeed.

related: https://github.com/spesmilo/electrum/issues/5759

**Comment by SomberNight** [comment]
It's not clear what we would even want to do though.

https://github.com/spesmilo/electrum/blob/b469df5283f9ba890555666299338974fbf3a308/electrum/plugin.py#L504-L511

The point of the warning is to point out to the user that he might not be able to spend received coins.
E.g. if you have a standard wallet with a single hw keystore, and the device is disconnected, it is intended that you get the warning.
Now, if you have a 2of2 multisig with two hw keystores, and only one device is connected, should you not get the warning?

Perhaps what we should change is the phrasing of the warning; or point out which keystore couldn't be paired. (e.g. keystore index, expected hw device type, expected hw device label)

Or perhaps this warning is just redundant? The warning is in the spirit of the watching-only warning:
https://github.com/spesmilo/electrum/blob/b469df5283f9ba890555666299338974fbf3a308/electrum/gui/qt/main_window.py#L487-L494
which was added because people not understanding what it means, who have lost or did not even have the corresponding keys, kept receiving coins and hence losing them.

Then again, back to the 2of2 with two hw keystores example, if you can only pair with one, you get the warning; but if it is a 2of2 with one hw keystore and one master pubkey with the hw keystore paired, then there is no warning, so...

**Comment by SomberNight** [comment]
Maybe we could suppress the DeviceUnpairableError warning for multisig wallets; i.e. only show them for standard ones?
@ecdsa

**Comment by ecdsa** [comment]
> Maybe we could suppress the DeviceUnpairableError warning for multisig wallets; i.e. only show them for standard ones?

ACK

**Comment by SomberNight** [comment]
I had a look but maybe it's not that simple. Tried to simply ignore the exception for multisig wallets:
```patch
diff --git a/electrum/plugins/hw_wallet/qt.py b/electrum/plugins/hw_wallet/qt.py
index 897f8d034..18aa9dafc 100644
--- a/electrum/plugins/hw_wallet/qt.py
+++ b/electrum/plugins/hw_wallet/qt.py
@@ -220,7 +220,14 @@ class QtPluginBase(object):
             keystore.thread = TaskThread(window, on_error=partial(self.on_task_thread_error, window, keystore))
             self.add_show_address_on_hw_device_button_for_receive_addr(wallet, keystore, window)
             # Trigger a pairing
-            keystore.thread.add(partial(self.get_client, keystore))
+            def trigger_pairing(keystore):
+                try:
+                    self.get_client(keystore)
+                except DeviceUnpairableError:
+                    # suppress warning dialog for multisig wallets
+                    if len(wallet.get_keystores()) == 1:
+                        raise
+            keystore.thread.add(partial(trigger_pairing, keystore))
 
     def on_task_thread_error(self: Union['QtPluginBase', HW_PluginBase], window: ElectrumWindow,
                              keystore: 'Hardware_KeyStore', exc_info):
```

However with this, if there is a same vendor hw wallet but not the one expected, and the exc gets raised, we silence it and move on from this keystore. However if there was no hw wallet at all connected, we would then display this message:
https://github.com/spesmilo/electrum/blob/88307357ec3798e6d78720c74bae46d68c622bb8/electrum/plugin.py#L550-L559

Not sure how to make it consistent...

Maybe we should fix https://github.com/spesmilo/electrum/issues/5759 first; to make pairing smarter: only try to pair with a device with which we have reasonable expectations to succeed (see https://github.com/spesmilo/electrum/issues/5759#issuecomment-555148334).

**Comment by craigraw** [comment]
> Maybe we should fix #5759 first; to make pairing smarter: only try to pair with a device with which we have reasonable expectations to succeed

I think this is reasonable - have added a [comment to #5759](https://github.com/spesmilo/electrum/issues/5759#issuecomment-558041182). 

There is a related use case worth considering here too - that of the permanently airgapped hardware wallet. Currently, the second 'Please insert...' message  above is displayed, and the user always selects 'No' to continue. It may be unclear the Electrum wallet is still usable after this.

**Comment by SomberNight** [comment]
The original issue should be fixed in https://github.com/spesmilo/electrum/commit/4ef313a1acfb0be1045c9d81b5e02ae1e9be5c50

> There is a related use case worth considering here too - that of the permanently airgapped hardware wallet. Currently, the second 'Please insert...' message above is displayed, and the user always selects 'No' to continue. It may be unclear the Electrum wallet is still usable after this.

This is a valid usecase though I am not sure how common -- probably only some coldcard users atm.
There could be a "never ask again" or similar option in the prompt.
This could be raised as a separate issue.

**Comment by craigraw** [comment]
Tested, works as described.

> There could be a "never ask again" or similar option in the prompt.
> This could be raised as a separate issue.

Will do.
