### ISSUE TITLE
Missing payment. Noob so may be straight forward. Or may have been scammed.

### ISSUE THREAD

**Issue by BearlyHuman** [spesmilo/electrum#5838]
HI 
Please someone help my find my transaction. I sent a payment from Electrum wallet to the correct address. with full fee payment. It seems to have just vanished. I need help to understand if there is a bug in the system as the payment may not have actually gone but I cant see it in the wallet. I am very confused by this and it is way too much money to loose. I seem to remember it suggesting that it had not been able to do the transaction but the money is not there any more. where do i start? Slightly crapping my pants here.

**Comment by SomberNight** [comment]
- What version of Electrum are you using?
- What do you see in the `History` tab? Do you see the tx there?

**Comment by BearlyHuman** [comment]
Im on v 3.3.8
should i paste a screen snip of the history output here?

**Comment by BearlyHuman** [comment]
Thanks for help by the way i'm starting to panic here
![wall](https://user-images.githubusercontent.com/58821833/70732698-d93bc580-1d00-11ea-8783-0227c0d8a7bb.PNG)
re.
I have tried to read up but none of it seems to relate to what im seeing in the app

**Comment by SomberNight** [comment]
don't panic.
"local" means the transaction is only on your local computer
the server you are connected to does not know about it
you can either right-click>`Remove` it, or right-click>`Details`>`Broadcast`

**Comment by BearlyHuman** [comment]
So when i broadcast it that is when it sends the payment?

**Comment by SomberNight** [comment]
Kind of.

The payment is only really fully "sent" once the transaction is mined (=included) in a block.
Miners can only include transactions they know about.
On the Bitcoin peer-to-peer network, nodes can send txns to each other. The node that receives a txn, check if it's valid, and if so, sends it to its peers (other nodes). This way the transaction propagates and reaches most nodes on the network; including miners.
Electrum is a light client, not a full Bitcoin node. The Electrum client connects to one or more Electrum servers, which are also full Bitcoin nodes.  Servers can use the mechanism I described to get a txn propagated across the network.
The Electrum client, when it connects to an Electrum server, asks it for all txns that are related to its own addresses.
The fact that this particular txn is marked "local" in your history means that the server you connected to haven't heard about this txn before (when the client asked for relevant txns, the server did not include this one).
Typically the server not knowing about this txn is a good proxy for "most of the network" not knowing about this transaction. Hence this transaction is likely not going to get mined.

But the Bitcoin network is decentralised, so there are no guarantees about this, it depends on the particulars.
This txn of yours might be "local" because you never even tried to broadcast it in the first place (you might have just clicked "Save"). Or it might be local because you did broadcast it but then the server you sent it to "forgot" about it for any number of reasons (if this happened however, other nodes on the Bitcoin network might still remember the tx).

Hence, if you want this payment to "happen", you should re-broadcast this txn.

**Comment by BearlyHuman** [comment]
Will take a while to decipher all that but at least i was not scammed. Worked my way through the menus in the app and finally cleared and reset up the payment, broadcasting it and  
 watching the confirmations on the 'view on block explorer. The payment has now gone through. Thanks for your time
