### ISSUE TITLE
Electrum handle both SegWit and Legacy in same wallet

### ISSUE THREAD

**Issue by chrissv** [spesmilo/electrum#6015]
I am using Electrum 3.3.8 on Windows 10.

I created a wallet with Android Coinbase wallet app. The Coinbase wallet supports receiving Bitcoin on both SegWit (bc1....) and Legacy (1....) addresses.
I used the same seed phrase and added the wallet to the Android Coinomi application, and it also shows support for receiving Bitcoin on the same SegWit (bc1....) and Legacy (1....) addresses.

I performed 2 Bitcoin transactions, one adding coin via the SegWit address, and another adding coin via the Legacy address.
In both the Coinbase wallet and the Coinomi wallet, both transactions show up with their respective addresses.

I added the same seed phrase to Electrum and it shows only the transaction SegWit addresses.
I was able toexperiment and import the seed phrase again in Electrum and provide a different derivation path so that the transactions associated with the Legacy addresses are shown. But it is two different wallets in Electrum.

My issue: should Electrum be able to handle a single wallet which supports SegWit and Legacy addresses seamlessly, the same way the Coinbase and Coinomi wallet do?

**Comment by SomberNight** [comment]
> My issue: should Electrum be able to handle a single wallet which supports SegWit and Legacy addresses seamlessly, the same way the Coinbase and Coinomi wallet do?

No, this is not implemented.
It is the view of this project that in general it is not safe due to long term compatibility (of seed words) to do what Coinomi (and Coinbase apparently) does.
This has been discussed at length around the time segwit activated, see e.g. https://github.com/spesmilo/electrum/issues/3460 and https://github.com/spesmilo/electrum/issues/4345; or specifically about bip39 seeds: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-August/013061.html (see point (6)). It was also an intentional design choice of [modern Electrum seeds](https://electrum.readthedocs.io/en/latest/seedphrase.html) (post-Electrum 2.0) that the seed itself encodes the derivation path and script type to use to make it truly self-contained (unlike bip39).

However, if future-compatibility of seed words is not a concern, I agree that it would be nice to support having a wallet that can have many potentially independent chains of addresses without restrictions. I've been wanting that for some time but apparently it was not written up, so I have opened an issue for it now: https://github.com/spesmilo/electrum/issues/6016.
I will close this issue in favour of that one, but feel free to comment in whichever thread your comment is more relevant to.

**Comment by chrissv** [comment]
Thank you for your quick and detailed response!
