### ISSUE TITLE
Qt GUI Receive Page (tab) UX issues

### ISSUE THREAD

**Issue by Keyare** [spesmilo/electrum#6053]
Context:
The Receive page on 3.3.8 displayed an available address, with a QR code, and allowed you to choose to create a new address using the "New" button. This is user friendly.

Issue:
1) 4.0.0 does not display an address, so the user must create a new address each time. Or manually pick one from addresses. This would be easy for experienced Electrum users, but is not user friendly. One would need to poke around for quite a while to figure it out.

2) "New" is replaced with "On-Chain". This is a challenge to comprehend for even a regular user.

The combination of issue 1 and 2 make the receiving BTC page a breaking UI challenge.

![image](https://user-images.githubusercontent.com/7099087/77792900-6b54a900-7026-11ea-8759-768fc456ab7b.png)

Suggested: 
Use the similar UI as 3.3.8
Changes are required for LN is understood.

**Comment by SomberNight** [comment]
Yes, we know the "Receive" tab is not ideal. We don't know how it should look though.
There have been multiple iterations already :/

See previous discussions:
https://github.com/spesmilo/electrum/issues/5710
https://github.com/spesmilo/electrum/pull/5822
https://github.com/spesmilo/electrum/issues/5929

**Comment by SomberNight** [comment]
It is more complicated than it looks at first sight.

- We would like very similar (~identical) flows in the Receive tab for on-chain and lightning.
- In lightning, there is no "address", rather there are only payment requests.
- Even on-chain, it actually makes sense to deal with payment requests, and not addresses (in the sense that addresses should not be reused).
- Note that there is a list of payment requests at the bottom (not visible in your pics!), which actually determines what text/QR code to show.

**Comment by gits7r** [comment]
Well, from all the versions we had this one provides the least chances for less experienced users to footgun themselves.  I don't think it is that bad, in terms of UX.

The only slightly more confusing (or quite different) thing is that the "Receive" tab now when navigated to, does not contain any pre-populated data (address, QR code, etc.) and users needs to: minimum press a button, maximum enter some details (description, expire date) and press a button. This might confuse the users expecting to be shown directly an address or QR code when hitting the "Receive" tab. I don't know what can be done more than renaming the On-Chain button to something like "Regular Bitcoin Transaction" and "Lightning Network Transaction".

**Comment by Keyare** [comment]
Is it stupid to suggest a "Lightning mode" and "Classic mode"?

**Comment by Keyare** [comment]
Like two forms, one for each "Mode"

**First Run in Classic Mode:**
1) "Receive" page displays in "Classic mode" with BTC address, QR code, 
plus two buttons instead of one: "New BTC address" and "Lightning Mode"

a) Pressing "Lightning mode" refreshes the screen in lightning mode with all the UI specific for LN
b) Pressing  "New BTC Address" behaves as previous 3.3.8 UI 
c) Pressing "Receiving address" goes to the "Address" menu


**in Lightning mode:**
2) "Receive" page shows Last LN Request, with QR 
plus two buttons: "New LN Request" and "Classic Mode"

a) Pressing "Classic Mode" refreshes the form in regular mode with all the UI specific for a regular BTC tx .
b) Pressing "New LN Request" generates a new LN request.
c) Pressing "Request" (which classic mode displays as "receiving address") goes to the "Request" menu

3) Opening the wallet should open in the last mode used.

**Comment by gits7r** [comment]
It's not dumb at all, but if we choose this approach the "Receive" tab should have two instances:

1. table with 1 row and 2 columns, 50% with 50% where user can select: Normal On-Chain Bitcoin Transaction and Lightning Network Transaction , each with corresponding icon and should be represented as square buttons (maybe also a small description with smaller font what each is, for less experienced users)

2. As soon as one button is pressed, the corresponding form is displayed:
a) For Normal On-Chain Transaction, something like 3.3.8 where we also populate the field with the first unused receiving address and display its QR code.
b) for Lightning Network Transaction, what we have now, with requests lists in the bottom.

I also like the current Receive menu, if we rename the two buttons more explicitly it is maybe fine. I leave it for @SomberNight to decide what's the best move here also from code perspective, because for us it's simple to request I want something to look like this and move like that, however under the hood is not always that simple, and might affect other things (like running electrum in merchant mode).

**Comment by ecdsa** [comment]
I agree that "on-chain" is difficult to understand if lightning is disabled. 
in that particular case, we should display "Request", or "OK"

I don't think a "lightning mode" is a good idea. it just makes everything more complicated.
