### ISSUE TITLE
zbar dependency for qrcode plugin is not working

### ISSUE THREAD

**Issue by dabura667** [spesmilo/electrum#610]
I have tried to install the zbar dependency for the qr code plugin.

Trying to install zbar with python 2.7 is like pulling teeth, and it doesn't work once I get it installed (compiling it from source with mingw).

It causes a lot of crashes when I have the qr code plugin enabled.

I would assume this is a problem with zbar not being updated for 2.7 or 3 python.

I have looked online for other qr code de-coder python libraries etc... but nothing really viable seems to come up.

I am very interested in the offline wallet tx sending / signing via QR code. However, the zbar plugin won't work... so I'm stuck.

If anyone has any advice (Thomas or slush especially) I would appreciate any words of wisdom.

**Comment by tunkaflux** [comment]
I've been checking up on zbar on Mac OS X. This is the current situation:

- Installing zbar with 'pip install zbar' on Mac OS X will result in segfaults.
- The zbar python plugin can be compiled without issues with the patch mentioned here: http://stackoverflow.com/questions/21612908/zbar-python-crashes-on-import-osx-10-9-1. This way, Electrum detects zbar and works without segfaulting.
- Zbar does not have hooks for video on Mac OS X. Compiling zbar without "--disable-video" fails because it cannot find a suitable video4linux device.

How exactly does Electrum use zbar? Is it only for scanning qrcodes with the camera? 

If that's the case, I think it's best to detect & disable zbar completely on Mac OS X upstream whether it's install or not...

**Comment by ecdsa** [comment]
it's only used to scan qr codes

**Comment by slush0** [comment]
Correct. Is there any other, usable library on MacOS? I think scanning Qr codes is quite useful even on desktop computers (Electrum).

**Comment by tunkaflux** [comment]
My quick search didn't turn up anything immediately useful. It seems that OpenCV can read qrcodes...

**Comment by mperklin** [comment]
I spent some time looking into this recently and found a few options.
Unfortunately I don’t have the time to implement either, but perhaps someone watching this repo has the motivation.

https://github.com/zxing/zxing <https://github.com/zxing/zxing>
or
https://github.com/LazarSoft/jsqrcode <https://github.com/LazarSoft/jsqrcode>

Best of luck to whoever works on this,

—MP

**Comment by tunkaflux** [comment]
No Python bindings on both though...

**Comment by mperklin** [comment]
here’s a dirty hack: https://github.com/oostendo/python-zxing <https://github.com/oostendo/python-zxing>
