### ISSUE TITLE
[REQ] Consider ways or options to allow BIP39 "decoy" passphrases without failure.

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#6108]
One of the great advantages of using a BIP39 passphrase is to guard against the [$5 wrench attack](https://xkcd.com/538/).  The philosophy goes something like this:

1. Keep 90% of your funds in your BIP39 seed salted with the passphrase "cat"
2. Keep 10% of your funds in your BIP39 seed salted with the passphrase "dog"
3. If someone brandishes a wrench tell them your seed and provide the passphrase "dog"
4. Attacker sees a balance is happy with their theft and never knows about the other 90%

The issue arises when trying to perform this safeguard on Electrum paired to a HW wallet with a passphrase.  Since the wallet file stores the XPUB of the "cat" wallet and is encrypted with the "cat" seeds, trying to enter the decoy passphrase of "dog" causes a decryption failure.  In this sense, the wallet file can serve as a passphrase oracle allowing an attacker with the seed to begin to brute-force the passphrase.

It may be possible to encode the wallet using either "cat" or "dog" and storing both wallets beneath that encryption, but that would be superficial at best.  An attacker could decrypt the wallet with "dog" and clearly see that there were two wallets encoded with it alerting him that he used a decoy.

Honestly I don't have a novel solution, but wanted to put it to your team to consider.  Perhaps there is some method of key mixing that could arrive at a solution no one has thought of yet.

**Comment by My1** [comment]
Considering you can establish a reliance on the hw wallet, why store the xpub in the first place?

In fact you could if you don't care for offline usage literally just store a bunch of keys that caan open this de facto empty file. Although to avoid a file size oracle, enough padding should be added. Of transaction history is stored similar as you can truecrypt hidden vaults, file size can become an oracle, as there is no concept of free space in a wallet as with a file container.

The biggest issue tho is probably to find an algo to allow decryption using multiple keys you have no control over without actually showing that other keys exist

**Comment by SomberNight** [comment]
In my view, if this attack vector is part of your threat model, you should delete the wallet file every time.

As @My1 sort of points out, this would require the file to be "de facto empty"; which is ~identical to deleting it every time.
The file cannot contain anything meaningful as that would provide ways to distinguish the passphrases: just consider tx history (which is currently is stored as an optimisation: it is not fetched from servers every time): we could either
- store tx history in wallet file just for passphrase A
  - if user types passphrase B, a network observer can tell that we are fetching it now (also, the wallet would longer to startup... it would visibly sync
- just for passphrase B
  - follows by symmetry
- for both passphrase A and B
  - encrypted file might be noticably larger
  - also, if attacker can decrypt the file they might see clues for other passphrase
  - also, what about passphrase C?
- not store tx history at all
  - this would work

I think this line of reasoning above would result in the file having to be essentially empty.

**Comment by brianddk** [comment]
I see your point.  Thx for the explanation... closing.

**Comment by lunarovic** [comment]
@brianddk Why did you close this issue? This is exactly what I wanted to open (and like a good user I used the search first 🙂).

I'd argue that the "empty wallet file" implementation would be great, for three reasons:

1. Plausible deniability, which was discussed above. I would add that it's not ideal to sacrifice comfort for an improved threat model, especially when other wallet implementations already offer this.

2. It's much better to have an existing wallet file to which you simply "login" with two clicks, rather than using the wizard to create a new wallet file every time, which is cumbersome because it includes the following:
   - type wallet name
   - choose wallet type
   - choose keystore
   - choose a hardware wallet
   - type a long passphrase
   - type a long passphrase again
   - choose script type and derivation path
   - choose encryption
   - delete the wallet file after use

3. There is actually a related issue #6564, which would be automatically solved if Electrum didn't check if the passphrase is "correct", but instead open the wallet associated with a given passphrase.

**Comment by brianddk** [comment]
@lunarovic the maintainers can reopen if they feel the issue warrants work.  I just closed it when I realized that the entire contents of the wallet would need to be nuked on each launch.  But your correct in the sense that the wallet could effectively say:

```
action = ask_trezor
```
