### ISSUE TITLE
Testnet bug: Cannot create watch-only wallet with Vpub 

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#6146]
How to reproduce in Kivy (all testnet, current master):
1. Create a wallet and copy the vpub  (or Vpub)
2. Create new wallet: Standart wallet
3. Use a master key
4. Paste the vpub (or Vpub) 
5. Next button is greyed out. (both for vpub and Vpub)

The same problem exists also in qt. However interestingly only Vpub does not work.  the vpub does work.

**Comment by ecdsa** [comment]
I cannot reproduce your issue: the vpub works on kivy and on qt.
(the only problem is if you test on linux, it pastes a test xpub instead)

The Vpub format means that the key should be used in a p2sh wallet, not in a standard wallet.
That distinction was made in order to prevent the creation of standard wallet.

**Comment by ecdsa** [comment]
I'm assuming you ran into the same issue as in #5925, but did not notice it.
I will remove that test seed and xpub

**Comment by relativisticelectron** [comment]
> I cannot reproduce your issue: the vpub works on kivy and on qt.
> (the only problem is if you test on linux, it pastes a test xpub instead)
> 
> The Vpub format means that the key should be used in a p2sh wallet, not in a standard wallet.
> That distinction was made in order to prevent the creation of standard wallet.

Yes I think you are completely right.   Thanks for the explanation.
