### ISSUE TITLE
Sorry to withdraw Electrum

### ISSUE THREAD

**Issue by Lightning076** [spesmilo/electrum#6149]
Hi !

I post this message here cos I didnot find the proper place. So please receive my apologies.

As a longtime free software user, I'm sorry to say that electrum (using last version : 3.3.8) is almost unusable because it involves too many questions:
Why are they so many addresses associated with my account ?
Why, when I want to withdraw cryptos from an exchange, does Electrum generate a different recieve address ?

This does generate distrust instead of trust.

So I withdrawed my coins from Electrum to my Exodus wallet which is much simpler (but not free).

Even when I tried to withdraw my funds from Electrum I turned in trouble : would it be too simple to add a button to withdraw all of the coins instead of guessing the correct amount ?

Not talking about the mess of the menus you never understand what they are about...

Exodus may become a great free software wallet, but it's very far from the goal : I'm sorry about that as I am a free software enthusiast.

Even this remark is irrelevant, wouldn't it have been easier to indicate a link so that my message arrives at the right place? (I'm not a github nerd)

**Comment by Pantamis** [comment]
The problem is that you look at some "advanced features" of Electrum wallet and 
you expect to understand everything without learning more than the 101 basics.

`Why are they so many addresses associated with my account ?
Why, when I want to withdraw cryptos from an exchange, does Electrum generate a different recieve address ?`

You have an infinite number of address in your "account" to avoid reusing adresses to protect your privacy learn about this here: https://en.bitcoin.it/wiki/Address_reuse  With the words seed you write on paper with a pen and that was shown by Electrum when you created the wallet "account" you can find back all the addresses Electrum shows you and withdraw.

When you "generate" a receiving address, Electrum allows you to write where the payment comes from so that you remember. You can be waiting several payments and Electrum don't know if you just ask again an address for the same payment so it always shows you a new one to avoid that you use the address to receive more than one payment (imply address reuse).

`would it be too simple to add a button to withdraw all of the coins instead of guessing the correct amount ?`

Version 3.3.8 is old even if it is the last release, this feature will be available in version 4.0 which will be a VERY BIG realease.

So if ergonomy is not good in version 3.3.8, which I agree with, continue to use exodus and come back to Electrum when version 4.0 is out !

In the meantime : Learn about how Bitcoin work especially a bitcoin wallet (read about BIP 32 and 39) !

**Comment by ecdsa** [comment]
@Pantamis I believe this user is a troll, do not waste your time answering. He is asking for a button to withdraw all the coins, but Electrum already has such a button. I think he is just trying to promote Exodus, and making up issues.
