### ISSUE TITLE
Displayed channel balance not consistent with LND

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6177]
LND substract the commitment fee from the balance of the initiator, but we don't.
I do not know what other implementations do.
shall we try to be consistent with them?

**Comment by SomberNight** [comment]
We had originally decided not to subtract onchain fees from the balance due to them not being static.
The thinking went: it would be confusing for users that their balance changed without user-interaction.

Note that there is also the "can send" / "can receive" amounts, which include more stuff; although those are atm not displayed for all channels.

**Comment by ecdsa** [comment]
c-lightning seems to do what we do, see https://github.com/spesmilo/electrum/issues/6103#issuecomment-633620846

**Comment by ecdsa** [comment]
ok, let's keep it that way
