### ISSUE TITLE
we send channel_reestablish after we sent and received closing_signed

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6182]
Currently the CLOSING state means that shutdown was sent and closing tx is unconfirmed.
We will try to reestablish the channel if it is in the CLOSING state.

BOLT2 says:
 - if shutdown has been sent, we must resent it upon reconnection
 - if closing_signed has been sent, it 'must be retransmitted upon reconnection'

This suggest that we are right to reestablish even after we have sent closing_signed.

However, I had the following traceback:

```
20200526T171254.975836Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending SHUTDOWN
20200526T171254.976508Z |    DEBUG | lnchannel.Channel | Setting channel state: OPEN -> CLOSING
20200526T171255.061797Z |     INFO | storage.WalletStorage | saved /home/voegtlin/.electrum/wallets/default_wallet
20200526T171255.062490Z |    DEBUG | util.profiler | WalletStorage.write 0.0203
20200526T171255.067139Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | saved remote_update
20200526T171255.070811Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | process_gossip 0 0 1
20200526T171255.071931Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | adding 1 unknown channel ids
20200526T171255.095773Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending CLOSING_SIGNED
20200526T171255.117270Z |     INFO | lnpeer.Peer.[LNGossip, 93.123.80.47:9735] | Querying 1 short_channel_ids
20200526T171255.117998Z |    DEBUG | lnpeer.Peer.[LNGossip, 93.123.80.47:9735] | Sending QUERY_SHORT_CHANNEL_IDS
20200526T171255.197776Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending CLOSING_SIGNED
20200526T171255.246309Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | saved remote_update
20200526T171255.339742Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending CLOSING_SIGNED
20200526T171255.417792Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending CLOSING_SIGNED
20200526T171255.490084Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending CLOSING_SIGNED
20200526T171255.574112Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Disconnecting: LightningPeerConnectionClosed()
20200526T171255.598769Z |     INFO | network | success: broadcasting closing 7031a7358e7d0c6c4e5660034e6c8107689be040ee5f38da2c6cf59b425695d3
20200526T171255.599516Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | (624976x1759x1) Channel closed 7031a7358e7d0c6c4e5660034e6c8107689be040ee5f38da2c6cf59b425695d3
20200526T171255.917026Z |     INFO | lnworker.LNWallet | adding peer 03c561e88180ba5d6d90f0406ab9746eddf52b02c8919566df346517d7315eb4c7@93.123.80.47:9735
20200526T171256.033208Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending INIT
20200526T171256.187924Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending PING
20200526T171256.919662Z |    DEBUG | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Sending CHANNEL_REESTABLISH
20200526T171256.921127Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | channel_reestablish (624976x1759x1): sent channel_reestablish with (next_local_ctn=21, oldest_unrevoked_remote_ctn=20)
20200526T171256.976182Z |     INFO | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | remote peer sent error [DO NOT TRUST THIS MESSAGE]: Multiple channels unsupported
20200526T171256.979386Z |    ERROR | lnpeer.Peer.[LNWallet, 93.123.80.47:9735] | Exception in wrapper_func: Exception("Remote peer reported error [DO NOT TRUST THIS MESSAGE]: b'Multiple channels unsupported'",)

```

In that instance the remote peer did send closing_signed, because the log shows that I was broadcasting the closing tx.

Apparently, after both parties have sent closing_signed, the channel should not be reestablished.
BOLT2 does not really say it explicitly, but I think we can assume that it is reasonable to not reestablish.

In order to implement that, we would need a new state. I suggest to rename CLOSING as SHUTDOWN, and to call the new state CLOSING.

**Comment by ROSAISS81** [comment]
Claro as lo que creas conveniente gracias

rosaiselaperez@gmail.com rosa Isela perez martinez

**Comment by SomberNight** [comment]
I think we might need two new states instead of one.

(1) `SHUTDOWN` - we sent "shutdown"
(2) `CLOSING_NEGOTIATION_IN_PROGRESS` - received "closing_signed"
(3) `CLOSING_NEGOTIATION_DONE` - the "closing_signed" msgs back-and-forth converged and we have a fully signed tx we are content with

- we need (1) as we need to retransmit it upon reconnection https://github.com/lightningnetwork/lightning-rfc/blame/9e8e29af9b9a922eb114b2c716205d0772946e56/02-peer-protocol.md#L1283
- I think we need (2) to check for https://github.com/lightningnetwork/lightning-rfc/blame/9e8e29af9b9a922eb114b2c716205d0772946e56/02-peer-protocol.md#L1242
- I think we need (3) to handle the exception you got: not to try to reestablish after the negotiation finished

relatedly, I think we should save the closing tx into the wallet as "local"

**Comment by SomberNight** [comment]
but I guess you are right that even a (4) state might be needed for "send closing_signed", as we need to retransmit that then (instead of "shutdown") when we reconnect. https://github.com/lightningnetwork/lightning-rfc/blame/9e8e29af9b9a922eb114b2c716205d0772946e56/02-peer-protocol.md#L1301

hmhm... that's a lot of states :D
Maybe (2) is not needed though and we could just potentially re-send revack even if we did not need to.

----
in that case we could have:

(1) `SHUTDOWN` - we sent "shutdown"
(2) `CLOSING_NEGOTIATION_IN_PROGRESS` - we sent "closing_signed"
(3) `CLOSING_NEGOTIATION_DONE` - the "closing_signed" msgs back-and-forth converged and we have a fully signed tx we are content with

**Comment by SomberNight** [comment]
Maybe (4) is not needed either due to https://github.com/lightningnetwork/lightning-rfc/blame/9e8e29af9b9a922eb114b2c716205d0772946e56/02-peer-protocol.md#L1283

**Comment by ecdsa** [comment]
my interpretation is that lines 1283-1284 cover it, so we only need one extra state
