### ISSUE TITLE
Very slow to open on Mac (startup speed, catalina, 10.15)

### ISSUE THREAD

**Issue by mariodian** [spesmilo/electrum#6225]
Hey, every time I open Electrum it takes at least 30 seconds just for the icon to show up on the MacOs dock and another 5 seconds for the password prompt to show up.

I usually open the wallet through the terminal like so:

`/Applications/Electrum.app/Contents/MacOS/Electrum --oneserver --server 127.0.0.1:50002:s` 

However clicking the icon or omitting any parameters makes no difference. 

I deleted the `~/.electrum` folder and tried running a fresh instance but it opens only a bit faster (maybe by 5 seconds).

My `blockchain_headers` file is around 50 MB and the main encrypted wallet file around 37 KB (~30 addresses used).

I'm running 2018 MBP 15" so there's plenty of performance. 

I'm using the 3.3.8 build from the website.

**Comment by SomberNight** [comment]
This is on Catalina (10.15), right?
It it slow because it is phoning home.

**Comment by SomberNight** [comment]
My conjecture is that it it so slow due to PyInstaller unpacking a whole folder of temporary files (this happens at every start, when using PyInstaller in "onefile" mode), after which the Mac phones home to Apple for each unpacked file.

This slowness is not present on 10.14 (at least when I tested) but it is on 10.15 (which is when they started phoning home, for the user's "security").

**Comment by NiExTy** [comment]
Electron Cash listed this fixed in its release notes, maybe it helps: https://github.com/Electron-Cash/Electron-Cash/commit/03c3eca856c7b766acbe61caf508c1edf6f976e9

**Comment by SomberNight** [comment]
I think it is fixed by https://github.com/spesmilo/electrum/commit/75cdae0e5b0d29ff8459fc2a90020d263390fbff

We build a `.app`, codesign it, and then upload it to Apple to notarise it, and then we attach Apple's sig to the `.app`, and then we bundle it into a `.dmg`... quite a dance

Anyway, looks like that unlike with pyinstaller onefile mode where Apple is not satisfied with its own attached sig to the `.app` and still does the network requests to check if they really signed all this stuff, with pyinstaller onedir mode they accept the attached sig.

**Comment by mariodian** [comment]
I moved over to the 4.0 beta and it's fast again. Thanks
