### ISSUE TITLE
BTC was send to wrong account via Electrum Wallet

### ISSUE THREAD

**Issue by rost3177** [spesmilo/electrum#6240]
Hi everyone,

I have not used my Electrum wallets for more than 2 years. Yesterday I decided to take off my BTC and tried to send them to another account. But my wallet showed me a mistake and asked me to update the wallet's version. So I did it and from 3.0.5 Electrum wallet's version I was updated to 4.0.0. Then again I made a copy-paste of the address of the receiver and sent BTC (2-factor authentication was passed successfully). But after BTC had been sent I checked the transaction and noticed that most likely BTC was sent on the WRONG address. I don't know how it happened as I used only copy-paste operation. Later, I read a mass of information that Electrum wallet has a problem with phishing (or how it is calling). 

What should I do now? Could I return my BTC? Could I reach in any way Electrum customer service support directly? I am technically very weak with this issue and just store BTC without any operations with them, except this one :(

Thank you all for any help!

Best wishes,
Rostyslav

**Comment by uFire** [comment]
Hi @rost3177 

Unfortunately, there is nothing you can do to get your coins back.

**Comment by rost3177** [comment]
could any rep from Electrum wallet contact with me? How is it possible to reach them? And could cyber policy be helpful in this case?

**Comment by ecdsa** [comment]
You downloaded malware. There is no Electrum version 4.0.0 at this point; old versions of Electrum, such as 3.0.5, are vulnerable to an attack where the server forces the client to display a popup, instructing the user to download a fake software update from a phishing website. After you downloaded the malware, it stole your coins.

There is a warning on electrum.org (and on github as well) against this attack, and it has also been reported in the news in early 2019.

There is an ongoing police investigation in order to find the attackers. You should file file a police report with the bitcoin addresses involved, and forward it to the german police (Berlin LKA, cybercrime unit)

**Comment by rost3177** [comment]
thank you very much with this instruction
