### ISSUE TITLE
Error while spend transaction

### ISSUE THREAD

**Issue by warfield2016** [spesmilo/electrum#6319]
<img width="323" alt="54449d3efa32fb10e96cc3ca780115eb" src="https://user-images.githubusercontent.com/55124935/86455745-bcf98780-bd29-11ea-93b6-dfaa0b55c269.png">

What can I do about it?

**Comment by ecdsa** [comment]
which version of Electrum are you using?

**Comment by warfield2016** [comment]
3.3.8

**Comment by ecdsa** [comment]
you should provide a traceback if you can.
otherwise, we are not going to investigate this, because it might be fixed in the upcoming 4.0 version

(you can try the beta here https://download.electrum.org/4.0.0b1/)

**Comment by warfield2016** [comment]
How can I do it?

**Comment by SomberNight** [comment]
Are you using a Trezor?

**Comment by warfield2016** [comment]
Correct.

**Comment by SomberNight** [comment]
Then this was fixed in https://github.com/spesmilo/electrum/pull/6198
It happens with new Trezor firmware.

Electrum 3.3.8 does not have this fix, but the the 4.0.0 beta versions do.
There has not been a stable release since 3.3.8, but if you want, you can try the betas, available at https://download.electrum.org/

Please give as many relevant details as you can next time; it saves everyone time.
