### ISSUE TITLE
Feature Suggestion: Ability to display balance in satoshis with thousands separators

### ISSUE THREAD

**Issue by wingsuit** [spesmilo/electrum#6423]
To improve readability when displaying balance in satoshis, displaying the balance with spaces, commas or periods would dramatically improve readability.

Allowing the user to click on the balance to cycle through the various options would be useful (no separator -> commas -> dots -> spaces)

Another readable way could be using SI prefixes, such that a balance of 584849211 satoshis (5.8 btc) would be displayed as 584M 849k 211 

While the debate around satoshis is ongoing, the ability to at least allow proponents of this unit to display them in meaningful ways would increase inclusivity.

**Comment by SomberNight** [comment]
I agree we should try to do something like this.
To be clear it's not just about the wallet "balance" but most values displayed all over the GUI, so also e.g. the "Amount" and "Balance" columns in the Qt GUI.

Re the thousands separator character itself, I think we should use whitespaces " ", as the dots and commas are used by many countries with varying meaning (in some place dot is decimal point, comma is thousands separator; in other places it is the other way around).

So instead of `86940861 sat`, we could show `86 940 861 sat`.
I think we can also extend the thousands separator to the fractional part:
so instead of `0.86940861 BTC`, we could show `0.869 408 61 BTC`.

Maybe there could be a config option to enable/disable this behaviour (the thousands separator).
Although I think it is a net improvement, so maybe there is no need for an option.

**Comment by dhruv-joshi-7** [comment]
I have implemented some changes to my local system regarding the readability of the amount. Attaching the images with commas and with whitespaces. Do tell me which one you find better.

![commas](https://user-images.githubusercontent.com/73574557/125932756-77d030bf-323e-4039-8a2b-0b8b35380cc0.png)
![spaces](https://user-images.githubusercontent.com/73574557/125932771-bb09cc79-0214-42b4-9459-eec4e9968b4c.jpeg)
![spaces_decimal](https://user-images.githubusercontent.com/73574557/125932780-d8bc8f1c-353f-4abc-8d46-ffc9936a88ce.jpeg)

**Comment by SomberNight** [comment]
Done in https://github.com/spesmilo/electrum/pull/7427
(atm only whitespaces can be used as thousands separators)

**Comment by paintballpanda** [comment]
Being a user in a country that uses commas as a thousands separator, the spaces being used is very confusing and looks as if there is a bug in the GUI. I actually just assumed it was a bug that had crept in and would be fixed in the next version but upon coming here to post the bug it looks like it was intentionally done. 

Can we please have an option to remove the spaces, and use commas as thousands separators on the left side of the decimal, and no commas on the right side of the decimal? (Basically asking for an option for it to follow US locale settings). 

From a UI/UX perspective, the spaces just make it look like its broken. 

Thank you for your consideration.
