### ISSUE TITLE
Pay does not go through (dust outputs)

### ISSUE THREAD

**Issue by Javcho2020** [spesmilo/electrum#6445]
This is what I see after trying to make a  pay:
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Transaction could not be broadcast due to dust outputs.

I downloaded Electrum today, so I have the latest update. please let me know how to fix this. I'm New to this system.
Thanks

**Comment by tylerchambers** [comment]
The first two are saying that the electrum server you connected to returned an error.
"Transaction could not be broadcast due to dust outputs." Is the error you received from the server.

The transaction you are trying to send contains 'dust' outputs, meaning that they are of an amount too small to be accepted by bitcoin nodes. 

This does not sound like an electrum issue, but rather an issue with the transaction you are trying to send.

**Comment by lucasmoten** [comment]
For reference, here's where the limits on dust are calculated
https://github.com/bitcoin/bitcoin/blob/6d8543504d8c5bde1d12a3c60407dee44d2c8e11/src/policy/policy.cpp#L14

Recommend outputs be well above dust limits.  

This does seem like something that could have checks and displays in the UI to help inform users to this before transactions are finalized and broadcast.

**Comment by SomberNight** [comment]
The typical root cause for this error is the user not understanding the units, i.e. `1000 mBTC = 1 BTC`, the default unit being `mBTC`.
You can't just copy-paste an amount into Electrum that has different units and expect it to work.
