### ISSUE TITLE
Allow creation of a single watch-only wallet with multiple public keys

### ISSUE THREAD

**Issue by zndtoshi** [spesmilo/electrum#6450]
It would be perfect to be able to create a single watch-only wallet for multiple wallets. Of course this should be only for the non-spending ones. 
![e](https://user-images.githubusercontent.com/47448562/88898006-3919b900-d25d-11ea-9178-3b77bbefd6e8.png)

**Comment by ecdsa** [comment]
sorry, but we will not impölement that
a single wallet file cannot contain multiple wallets.

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/6016

I think we could do this at some point; it would be nice to allow more advanced wallets than current `m/0/i` and `m/1/j` structure, and as part of that allow arbitrary output script descriptors or similar

**Comment by jonjonez** [comment]
Certainly, if this release occurs with all these features mentioned, it would be great. I hope you take into consideration what I mentioned in #8879 , and adding:

> For a newbie, the easiest and safest thing to do is to sweep the private key.
As an advanced user, you can create an imported wallet, and use pay-to-multi (batched payment) where you directly pay whatever amount you want to whomever and also send the rest to a change address in your other (HD) wallet.

Sweeping a private key is not viable in times of congested mempool, in addition, the user may have several reasons for just wanting to import instead of sweep. Please take this into consideration.

I know about pay-to-multi, but doing this manually is not viable, it would be nice if this was automatic in the wallet (considering if the private key was imported into the existing keypair).

Currently I can import private keys by creating a new file just for imported keys, there is a change address option to select, then the wallet sends the remaining balance to the next address added as change, but this is not satisfactory, because in an imported wallet I I can only add private keys, that is, if I want to add only addresses to this file without revealing the private key to use it as change I can't, I have to import the private key, and this address of mine can be used as cold storage, but then it will no longer be cold storage because I'd have to reveal the private key, this is insecure and exposes me to risk without any need.

Wouldn't it be easier or no longer distinguish between private keys and watch-only addresses when creating a new file just to import new addresses and/or private keys than one just for private keys and the other just for watch-only, do you understand my point?

Or import directly into the existing keypair of an HD wallet, and if you find this insecure due to the possibility of an inexperienced user losing funds by deleting either the imported private key or the HD wallet, then consider adding a command in the console.
