### ISSUE TITLE
dnspython: compatibility with 2.0.0

### ISSUE THREAD

**Issue by prusnak** [spesmilo/electrum#6538]
Electrum requires `dnspython<2.0` in `requirements.txt`.

However, it would be nice it Electrum was able to use recently released dnspython 2.0.0 as well.

Here is the error when using dnspython 2.0.0:

```
=================================== FAILURES ===================================
_________________ TestDnsSec.test_python_validate_rrsig_ecdsa __________________

self = <electrum.tests.test_dnssec.TestDnsSec testMethod=test_python_validate_rrsig_ecdsa>

    def test_python_validate_rrsig_ecdsa(self):
        rrset = dns.rrset.from_text("getmonero.org.", 3599, 1, 48,
                                    "257 3 13 mdsswUyr3DPW132mOi8V9xESWE8jTo0d xCjjnopKl+GqJxpVXckHAeF+KkxLbxIL fDLUT0rAK9iUzy1L53eKGQ==",
                                    "256 3 13 koPbw9wmYZ7ggcjnQ6ayHyhHaDNMYELK TqT+qRGrZpWSccr/lBcrm10Z1PuQHB3A zhii+sb0PYFkH1ruxLhe5g==")
        rrsig = dns.rdtypes.ANY.RRSIG.RRSIG.from_text(1, 46,
            dns.tokenizer.Tokenizer("DNSKEY 13 2 3600 20180612115508 20180413115508 2371 getmonero.org. SSjtP2jCtXPukps7E3kum709xq2TH6Lt Ur32UhE7WKwSUfLTZ4EAoD5g22mi1fpB GDGb30kCMndDVjnHAEBDWw=="))
        keys = {dns.name.Name([b'getmonero', b'org', b'']): rrset}
        origin = None
        now = 1527185178.7842247

        # 'None' means it is valid
>       self.assertEqual(None, dnssec.python_validate_rrsig(rrset, rrsig, keys, origin, now))

electrum/tests/test_dnssec.py:21:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

rrset = <DNS getmonero.org. IN DNSKEY RRset: [<257 3 13 mdsswUyr3DPW132mOi8V9xESWE8jTo0d xCjjnopKl+GqJxpVXckHAeF+KkxLbxIL fDLU...Uzy1L53eKGQ==>, <256 3 13 koPbw9wmYZ7ggcjnQ6ayHyhHaDNMYELK TqT+qRGrZpWSccr/lBcrm10Z1PuQHB3A zhii+sb0PYFkH1ruxLhe5g==>]>
rrsig = <DNS IN RRSIG(DNSKEY) rdata: DNSKEY 13 2 3600 20180612115508 20180413115508 2371 getmonero.org. SSjtP2jCtXPukps7E3kum709xq2TH6Lt Ur32UhE7WKwSUfLTZ4EAoD5g22mi1fpB GDGb30kCMndDVjnHAEBDWw==>
keys = {<DNS name getmonero.org.>: <DNS getmonero.org. IN DNSKEY RRset: [<257 3 13 mdsswUyr3DPW132mOi8V9xESWE8jTo0d xCjjnopKl...zy1L53eKGQ==>, <256 3 13 koPbw9wmYZ7ggcjnQ6ayHyhHaDNMYELK TqT+qRGrZpWSccr/lBcrm10Z1PuQHB3A zhii+sb0PYFkH1ruxLhe5g==>]>}
origin = None, now = 1527185178.7842247

    def python_validate_rrsig(rrset, rrsig, keys, origin=None, now=None):
        from dns.dnssec import ValidationFailure, ECDSAP256SHA256, ECDSAP384SHA384
>       from dns.dnssec import _find_candidate_keys, _make_hash, _is_ecdsa, _is_rsa, _to_rdata, _make_algorithm_id
E       ImportError: cannot import name '_to_rdata' from 'dns.dnssec' (/nix/store/nh4fj4kqi894476z606lj6a2003vm3i9-python3.8-dnspython-2.0.0/lib/python3.8/site-packages/dns/dnssec.py)

electrum/dnssec.py:69: ImportError
__________________ TestDnsSec.test_python_validate_rrsig_rsa ___________________
```

**Comment by prusnak** [comment]
This patch might be relevant: https://github.com/Electron-Cash/Electron-Cash/commit/7daf291b3fa8f2c8562c23cf986367ffc79a298f

**Comment by SomberNight** [comment]
Thanks for the Electron-Cash change; unfortunately I find it unsatisfactory.
`dnspython[DNSSEC]` is no longer pure python, as it pulls in `cryptography`.
(so it's more complicated than just putting that in `requirements.txt`)

A lot has changed between `dnspython` 1.16 and 2.0 for dnssec.

Previously, for dnssec, `dnspython` required `pycryptodomex` and `python-ecdsa`. We have been [monkey-patching](https://github.com/spesmilo/electrum/blob/fdaf6e775cdbe461a8466d1d7e46360c8a90e4d7/electrum/dnssec.py#L178) `dnspython` to only need `python-ecdsa` (and hence be pure python). This was especially important before Electrum 4.0 when Electrum itself could still be used as pure python. (btw these monkey patches proved extremely stable in the past, hardly needed to be touched at all for 5 years, but all good things have to end :P)

Now with `dnspython` 2.0, the dnssec code changed significantly.
In particular, first in https://github.com/rthalley/dnspython/pull/422, and then in https://github.com/rthalley/dnspython/pull/449.
It now requires `cryptography`.

Since Electrum 4.0, Electrum is no longer pure python: `libsecp256k1` is required, and more relevantly, either one of `cryptography` or `pycryptodomex` is required.

So, if we want to keep the dnssec functionality in Electrum, the easy way out would be to drop `pycryptodomex` and always require `cryptography`...

@ecdsa

**Comment by SomberNight** [comment]
On the plus side, we might finally be able to remove the `python-ecdsa` dependency completely, as it is currently only used for dnssec.
(well it's also pulled in indirectly by e.g. some hw wallet deps though; but that's not part of the core lib)

**Comment by prusnak** [comment]
I think that requiring `dnspython>=2` and `cryptography` sounds reasonable.

That allows to:
* remove `pycryptodomex` and `python-ecdsa` from the dependencies
* cleanup the code to use only `cryptography`, not `pycryptodomex`
* use upstream `dnspython` without monkey-patching

**Comment by SomberNight** [comment]
note: one unfortunate thing is that [ubuntu 18.04 has `cryptography 2.1.4` in apt](https://packages.ubuntu.com/bionic/python3-cryptography) which is sufficient atm but dnspython 2.0 requires cryptography 2.6
([debian buster (stable)](https://packages.debian.org/buster/python3-cryptography) and [ubuntu 20.04](https://packages.ubuntu.com/focal/python3-cryptography) are fine)

**Comment by ecdsa** [comment]
ACK. we should wait a few months because 20.04 is still recent

**Comment by birdie-github** [comment]
Fedora 33 is left without Electrum because of this bug.

**Comment by SomberNight** [comment]
Ah ok. Good to know, thanks. In that case I think we should make the change sooner.
The question then is whether to do it in next 4.0.x or 4.1.0 only. I'll add it to 4.0.x milestone so we don't forget about it near next release.
