### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by arcaela** [spesmilo/electrum#6548]
/.local/lib/python3.8/site-packages/aiohttp/helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore

**Comment by SomberNight** [comment]
How are you running Electrum?

-----

This is coming from `aiohttp` (a dependency).
There is not much we can do about it.
When there is a new release of aiohttp, we will package that in the binaries.

I guess what we could do is silence deprecation warnings in certain cases.

Currently, you see all deprecation warnings if you are running from source with `-v`.
If you are not running from source, I think they don't get logged at all.

The tricky combo is when you run from source without `-v`; in which case a few will slip through during startup, such as this one.
(because we first detect that we are running from source, at which point we enable them, and only later we see if `-v` was specified)

**Comment by arcaela** [comment]
I running with daemon command and -d option but I dont use -v

**Comment by ecdsa** [comment]
Closing, this is not an electrum issue.
Also, it has been fixed in aiohttp 3.7, see https://github.com/aio-libs/aiohttp/issues/4842
