### ISSUE TITLE
Cannot sign transaction in multisig wallet

### ISSUE THREAD

**Issue by berto202020** [spesmilo/electrum#6579]
I recently updated my electrums wallets to electrum 4.0.3. I have two, one for signing transaction only and one I store my BTC on that require multisig for making transactions. Normally when I do a transaction I export the file and open it with my "signing wallet" sign it and broadcast it. So far it worked until I updated to the newest version. 

The transaction files used to be .txn but now there is a new format .psbt. but you can still choose from one to another. In my case when I open the transaction file in my "signing wallet" there is no option for signing it the button is just grey. It is also written : "Transaction unrelated to your wallet" and the Status: Partially signed (2/0). When I open the same transaction file in the multisig wallet the status says Status: Partially signed (2/4)

It is really weird and also frustrating I'm not the most familiar person with all the functionalities of the electrum wallet but I've done quite a bit of transactions over the years using my wallets so I am not a complete beginner either. 

What I'm thinking to do right now is the delete my wallets and recover them using my seeds, I don't know if it will resolve the problem. But before doing that I wanted to know if someone have the same issue or if I'm doing something incorrectly.

Thanks

**Comment by SomberNight** [comment]
It is a bit hard to understand your setup.

Go to statusbar `Wallet`>`Information` in the GUI. What does it say for "wallet type", "script type", "keystore type" (or for multisig wallet, the list of keystores/cosigners, under "Select keystore")? For both wallets you have.

Also, do you have these wallets on two different machines? Are you offline signing on one, and is the other just a watch-only?
If you have multiple machines, have you upgraded Electrum to 4.0.x on both?

The transaction format has been incompatibly changed in 4.0.x compared to 3.x, so you need to upgrade all Electrum installs you use at the same time.

**Comment by berto202020** [comment]
First Wallet
Wallet type : 2of2
Script type: p2sh
there is two keystore

Second Wallet (the wallet that I use for the sole purpose of signing transactions of the First Wallet)
Wallet type : standard
Script type: p2pkh
Keystore type: Bip32 (the keystore match the second keystore of the first wallet) 

Both wallets are on the same machine

Thanks

**Comment by SomberNight** [comment]
Ok, I see.

So you have two wallet files, a 2of2 multisig that presumably has private keys for one cosigner, and a standard single-signer wallet that has private keys for the other keystore. This setup was never intended to work, it just used to work due to a bug.

related: https://github.com/spesmilo/electrum/issues/5948

-----

To fix your current setup, you should create a "third wallet" that is a 2of2 multisig. As for the two cosigners, you should use the seed words (or xprv) from your "second wallet", and the first xpub from the "first wallet" (see Wallet>Information in first wallet, first master public key).
Then, you can create an unsigned tx in "first wallet", sign in "first wallet", transfer it to "third wallet", sign in "third wallet", and then broadcast the signed tx.

-----

However, I have to point out that having a 2of2 multisig wallet with both cosigners (secrets) being on the same computer does not make much sense. From a security point of view, this will only give you a marginal ("security by obscurity") improvement against attackers/viruses.

Instead I suggest either:
- have two separate computers with a 2of2 multisig, e.g. two PCs; or one PC and an Android phone
- have two PCs, one always offline and one online; have a standard single-signer wallet with the secret keys only on the offline machine. You would then create unsigned tx on online machine, transfer it to offline machine, sign there, transfer back to online machine, and broadcast there.
- buy a hardware wallet, and create a standard single-signer wallet with Electrum using the hardware wallet. The secret keys would never leave the hardware device.
- you could use a two-factor wallet with Electrum, which uses 2of3 multisig, and you normally sign with your local wallet with one key and also enter a one-time password (TOTP) from e.g. Google Authenticator to get a server to add another signature (see https://api.trustedcoin.com/#/electrum-help for more details)

**Comment by berto202020** [comment]
I't worked!! Thanks a lot man it's a good thing that there is people like you around. 

But for the security reasons I totally understand that my setup didn't make much sense. Back in the days(few years ago) I didn't understood completely what I was doing. 

I was using this setup for short term storage or as a transit wallet, it was never meant to be for long term storage or large amounts either. 

Glad it worked! Thanks again!
