### ISSUE TITLE
Electrum wallet is not opening on new mac os BIG SUR!!!!

### ISSUE THREAD

**Issue by Igv0** [spesmilo/electrum#6734]
Electrum wallet is not opening on new mac os BIG SUR!!!! 2 topics was closed by "SomberNight" but nobody say when it gonna be fixed. Second day i can't use my wallet. I understand it gonna be fixed with new version but when.....How long to wait? Please, don't close this topic if you're not fixed it yet.

**Comment by SomberNight** [comment]
First of all, this issue tracker is about bugs/features in the git tree (source). There is already a workaround for the issue in the git master branch. This means the next release will contain the fix.

Let me copy my response (https://github.com/spesmilo/electrum/issues/6730#issuecomment-727617196) into this new duplicate thread too then.

To be clear, even in the meantime, you can access your coins, as you could
- run from source (see e.g. https://github.com/spesmilo/electrum/issues/6461#issuecomment-709218267)
- fire up a VM with e.g. older macOS or GNU/Linux or Windows and run from there
- use an Android phone and run from there
- use another PC of yours and run from there

Also, you might want to consider using an operating system that does not break userspace. Sane OS maintainers would consider this whole issue a bug in the OS, not the other way around.

Anyway, we will try to do a release soon, probably in the coming week.

-----

Please, do NOT open duplicate issues. There is already an issue **pinned** at the top of the issues tab identical to this. It is closed because it is fixed in master. You can comment there instead.
