### ISSUE TITLE
Error: Forbidden after setpassword

### ISSUE THREAD

**Issue by mapapuche** [spesmilo/electrum#6762]
Hello,

After start electrum with electrum daemon -d & change password i can't anymore interact with electrum ... i can't restart it and i'm totally blocked. 

~ $ electrum setconfig rpcport 7777
true
~ $ electrum setconfig rpcpassword "test"
true
~ $ electrum stop
Error: Forbidden

I got Error:Forbidden with all other commands too now 
Any idea of how i can reset ?

**Comment by ecdsa** [comment]
I can reproduce. There are two issues here:
1. the password was modified while electrum was running. This modifies the config file, but not the password for the session.
2. it is not possible to unset rpcuser/rpcpassword from the command line. 

As a workaround, you can `kill -2` your electrum daemon, and then restart it. It should then use the new password.
If you want to change the password again, stop the daemon first, then set the password while offline: 
`electrum -o setconfig rpcpassword blah`

Now considering this issue:
1. setconfig should not be allowed to modify rpcuser/rpcpassword while electrum is running. 
2. it should be possible to unset rpcuser/password from CLI. That is caused by `_setconfig_normalize_value`. see also #4225 and a58d01ed54320e2e8eb2a495a8d9b48d8d4c4949

**Comment by ecdsa** [comment]
also, related: `get_rpc_credentials` in daemon.py tests `rpc_password` for None, then for an empty string. 
(an empty string is what we currently would get when trying to unset the password)
