### ISSUE TITLE
The new Arabic font isn't readable.

### ISSUE THREAD

**Issue by EZ0010** [spesmilo/electrum#6777]
After updating to 4.0.5 of Electrum, the new Arabic font isn't readable, this kind of fonts is used on large UI titles elements only, not normal UI text. it was different on the past versions. this one isn't readable at all.

**this is how Electrum shows the arabic txt:**
![image](https://user-images.githubusercontent.com/75021359/100224532-01323200-2f2e-11eb-980d-5d2631e5307a.png)

**and this is how it should look like with "Arial" font:**
![image](https://user-images.githubusercontent.com/75021359/100223997-42761200-2f2d-11eb-849e-8b6e41fde992.png)

**Comment by bauerj** [comment]
Do you know which version you used before?

**Comment by SomberNight** [comment]
if it changed between 4.0.4 and 4.0.5 then it must be due to the [Qt version change](https://github.com/spesmilo/electrum/commit/77f75f102b14cebe315df63c2343e48999d6692e)
3.3.8 uses Qt 5.11.3
4.0.1-4.0.4 uses Qt 5.14.2
4.0.5 uses Qt 5.13.1

As bauerj asks, what versions of Electrum have you used in the past?

**Comment by EZ0010** [comment]
I'm not sure if it wasn't like this in the older version of Electrum because I can't install old version and run it since it won't run on BigSur. and I didn't try using arabic version on older versions too.

**Comment by EZ0010** [comment]
I noticed this issue no longer exists and now Electrum uses the native macOS system Arabic font.
