### ISSUE TITLE
Test fails when pycryptodomex is not available.

### ISSUE THREAD

**Issue by prusnak** [spesmilo/electrum#6834]
pycryptodomex dependency was removed in 4.0.7, but it is still required for the test suite

Not surprisingly the test `Test_bitcoin.test_pycryptodomex_is_available` fails.

I am unsure whether this is intended or just an oversight

**Comment by SomberNight** [comment]
Right. For now I had decided to keep the compatibility wrappers in [`crypto.py`](https://github.com/spesmilo/electrum/blob/d40bedb2ac77ed9e91c67bfd69451f7af69fece7/electrum/crypto.py) so that those methods can still use either of pycryptodomex or cryptography.
Removing them would not simplify much I think, so unless it causes issues we might as well keep them.

If that code is kept in crypto.py however, then we should also run the tests with pycryptodomex too.

Btw re running the tests, there is a pip extra:
https://github.com/spesmilo/electrum/blob/d40bedb2ac77ed9e91c67bfd69451f7af69fece7/setup.py#L57

Feel free to express your opinion if you disagree though. It would not cost much to remove that code either.

**Comment by prusnak** [comment]
I have nothing against keeping `pycryptodomex` as test dependency. I just wanted to make sure this was intended.

Closing.
