### ISSUE TITLE
Allow seeing xpub/ypub/Ypub/zpub/Zpub in Wallet information

### ISSUE THREAD

**Issue by 1datatec** [spesmilo/electrum#6858]
Hey, this could be quite handy for multisig validation.
More details are in https://shiftcrypto.ch/blog/how-nearly-all-personal-hardware-wallet-multisig-setups-are-insecure/
Under "Show Electrum Zpub... and Ypub... formats"

**Comment by SomberNight** [comment]
I don't understand. What exact change do you recommend?
You can already see the xpub/etc in Wallet Information, and that eye icon is there.
In fact you can already see this [on a picture in that article](https://shiftcrypto.ch/blog/content/images/2020/11/image-106.png).

**Comment by 1datatec** [comment]
Some hardware wallets only show their own xpub(in xpub format). Electrum shows Ypub/Zpub. To verify things i normally take them to a converter https://jlopp.github.io/xpub-converter/
Which is not very handy or secure. Having a radiobutton to switch between xpub/ypub/Ypub/zpub/Zpub in Wallet information could've been great!

**Comment by SomberNight** [comment]
Ah I see. This would be confusing for many users.
In fact one of the motivations ([see here](https://github.com/spesmilo/electrum-docs/blob/master/xpub_version_bytes.rst#considerations)) for creating the x/y/zpub to differentiate between script types is so that users cannot simply copy-paste a masterkey and restore the incorrect wallet from it. That would be a huge footgun.

There is a built in "xpub converter" command in Electrum, which you can use from CLI or even Qt console.
Qt console usage example:
```
>>> wallet.keystore.xpub
'vpub5VmsevU91fpRaJkfa8b6c9MK53gKY8rSzZjrZdp6dkHZjnFhM1HN74ezHY96JCgFnbQJhRbeUyr5S1vzdcTB6qUKrrG7GBuwPYDTzBjLQmv'
>>> convert_xkey(wallet.keystore.xpub, "standard")
"tpubD9p2nVdf2JrqYhKkh39SEEsgk74sQmLWNRNbUyf1jfoDbGYrvYTaVde6Zz93pWwLPnApoxJdwQPDtmejTs8SakHpf8QG7YD9WwwAXLtosc7"
```

The situation might get better with output script descriptors indeed, although they are not the full solution either (see https://github.com/spesmilo/electrum/issues/5715).

**Comment by 1datatec** [comment]
That makes sense.
