### ISSUE TITLE
Would it be easy to add Ledger support (connected via USB) on Android?

### ISSUE THREAD

**Issue by loupiote** [spesmilo/electrum#6876]
Not a bug report, just a feature request feasibility question:

Would it be easy to add Ledger hardware wallet support (connected via USB) on Android?

I can connect my Ledger Nano on my Android phone, and web wallet apps like MyCrypto on Chrome can use it (via the U2F bridge). But  of course Electrum is an app, not a web app, and right now it has no support for Ledger on Android.  Other apps (e.g. Ledger Live mobile) can connect to my Ledger on Android. So technically, it is possible.

So, would it be easy to add support for Ledger on Electrum Android? (at least via USB)

**Comment by ecdsa** [comment]
There is already somebody working on hardware wallet support for electrum on android, see #6320 
If you are a developer and you want to help, you are very welcome.

I am closing this issue, because it is redundant. Before you open a new issue, please check the existing ones. Keeping the number of open issues low will save everyone time.
