### ISSUE TITLE
BTC lost

### ISSUE THREAD

**Issue by Tennis-racket** [spesmilo/electrum#6910]
Transaction ID: 90a6845f6bdf9ee63ecfd319d3c86ada3e3089b48b120808ebfcac232031f77f
Status: 61060 confirmations
Date: 2019-11-12 00:31
Sumă trimisă: 72.82457 mBTC
Comision: necunoscut
Mărime: 54907 bytes
Replace by fee: True
LockTime: 603367 (height)
At block height: 603368
Included in block: 0000000000000000000b22e6e6f5b248b702506fa11ede6e6d0c6a565c9a165c
https://blockstream.info/tx/90a6845f6bdf9ee63ecfd319d3c86ada3e3089b48b120808ebfcac232031f77f 
 I installed electrum this morning after almost 3 years, just to find out that my btc were sent without my permission one year ago. Do you have any idea? Is there anything I can do? Thank you!

**Comment by Tennis-racket** [comment]
I forgot to mention Electrum 4.0.9 version.

**Comment by ecdsa** [comment]
There is not enough information to know what happened. The fact that you are using the 4.0.9 version is not relevant here. We would need to know if you downloaded malware at that time, or if your seed was otherwise compromised.

The transaction has a lot of inputs, but the info you pasted suggests you lost 72.82457 mBTC. If the other inputs are not from your wallet, then the transaction was probably not created in Electrum; even a malware/phishing version of Electrum would not consolidate inputs from different people. Thus, it seems likely that you have leaked your seed or private key.

**Comment by Tennis-racket** [comment]
I didn't download any malware at that time and I don't think it was compromised otherwise as I didn't use it. Yes, I lost 72.82457 mBTC, is there any chance that I could recover my loss?

**Comment by ecdsa** [comment]
if you lost 72.82457 mBTC, then it confirms what I wrote above: your seed or private was compromised, and someone imported your private keys in another wallet. It does not matter that you didn't use your wallet for a year, the theft transaction may have been created while your wallet was not being used. I don't think there is any chance to recover those funds.
