### ISSUE TITLE
CI script needs to be updated for new Crowdin API

### ISSUE THREAD

**Issue by bauerj** [spesmilo/electrum#6936]
Crowdin will shut down it's v1 API by the end of 2021 according to https://support.crowdin.com/api/api-integration-setup/.

`contrib/push_locale` needs to be [updated](https://support.crowdin.com/api/v2) accordingly:

1. A new API key has to be generated (Who is admin? @rdymac?)
2. The file needs to be uploaded to the /storages endpoint
3. /electrum/files needs to be scanned to find the file id (maybe the file id can be hard-coded)
4. Storage and file ID need to be sent to /electrum/files (PUT)

**Comment by SomberNight** [comment]
I've tried to do the migration now (in https://github.com/spesmilo/electrum/commit/8b9296654e0a3672a103137a41d1c5ed57be2f8e), as part of changing from Travis CI to Cirrus CI.

Looks like we've lost the v1 API key that Travis has been using...
Note that that was a "project-key".
There looks to be [two generation of even the v1 API itself](https://github.com/crowdin/crowdin-api-client-js/issues/76#issuecomment-669811442);
see e.g.
```
POST https://api.crowdin.com/api/project/{project-identifier}/update-file?key={project-key}
POST https://api.crowdin.com/api/project/{crowdin_identifier}/update-file?login={username}&account-key={crowdin_api_key}
```
where the first one is using a [project-specific API token](https://github.com/crowdin/crowdin-ruby-client-v1/blob/4ce72c58fc92158db97f04713415f47d19d0d9a4/lib/crowdin-api/methods.rb#L70), while the second one is using an account/user-specific API token.
Not sure if v1 project-specific tokens can even be generated at this point -- but v1 user-specific tokens can still be generated at least.

Nevertheless, I've figured if we had to change from v1 project-specific stuff to v1 user-specific stuff, might as well try to migrate to the v2 API directly.

Since this issue has been opened, crowdin even released libraries to use their new API in a few languages, including python [[github]](https://github.com/crowdin/crowdin-api-client-python)[[pypi]](https://pypi.org/project/crowdin-api-client/). That seems overkill for me however, so we are using `requests`, still.

**Comment by SomberNight** [comment]
note: I haven't changed `pull_locale` though (not sure if the API used there is ok to keep using)
https://github.com/spesmilo/electrum/blob/8b9296654e0a3672a103137a41d1c5ed57be2f8e/contrib/pull_locale#L39-L40
