### ISSUE TITLE
Electrum bug 

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6983]
Hello ,

How can I make the payment from my wallet, the money doesn't go away, what happens, I need a certain windos linux or what to do, I didn't have this problem anymore or in which village to make the payment
Thank you for your support

**Comment by TUPAK007** [comment]
nice support man lose lots money now afther day send it my order nice .....

**Comment by ecdsa** [comment]
@TUPAK007 This website is not a support hotline, it is a bug reporting system. 
Its purpose is not to answer questions that have already been answered elsewhere.

Regarding your question, we already told you multiple times to check this link:
https://electrum.readthedocs.io/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do

Your problem is not caused by a bug in Electrum, but simple ignorance of how bitcoin works.
Please stop posting the same issue over and over again, or you will be blocked here.
