### ISSUE TITLE
Error server

### ISSUE THREAD

**Issue by TUPAK007** [spesmilo/electrum#6985]
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

bad-txns-inputs-missingorspen

what can i do in this case

**Comment by TUPAK007** [comment]
i can change it static with mempool its ok that option ?

**Comment by Blackhawke** [comment]
I'm also getting this error, so adding my voice to the choir. :) 

running on Ubuntu 18.04, btw.

Is this an Electrum error, or some other problem, and is there a work around? Right now neither I nor the originator can move our btc.

**Comment by ecdsa** [comment]
`bad-txns-inputs-missingorspent` : most likely, you have a local transaction in your wallet and you are trying to build another transaction on top of it.

**Comment by Blackhawke** [comment]
Well, not in my case.

 * I've re-seeded my wallet, since some have suggested it could be a bad signature in the wallet file.
 * I've tried I don't know how many different servers (since that seems to be a common "answer"). Both from the list in the wallet itself and from the list at 1207k.com/bitcoin-eye.
 * Finally, before even trying to send this transaction, and even before upgrading to 4.0.9, I received btc to this same wallet just fine. So it can apparently receive transactions, but not send anything.

So those are the solutions I've found and they're not working. I'm looking for new ideas. :)

**Comment by SomberNight** [comment]
> I'm looking for new ideas. :)

Please upload a screenshot of the History tab, with full window visible (but you can redact private details).
Please share the raw transaction hex for which you get the `bad-txns-inputs-missingorspent` error. You can get this if you click `Advanced` in the payment flow and then copy the signed tx to the clipboard.

**Comment by Blackhawke** [comment]
Thanks for that. Here's the screenshot:

![electrum_scrnsht](https://user-images.githubusercontent.com/1757829/108604279-d0fa0400-7361-11eb-9680-5b0dee9664c5.png)

As for the "signed tx", here are both the input and the output:

Inputs(1):
 `f19f257adf33f72575adc971c6005136850229cd879ef86b402633e51b443f4e:0    1HsN6wC6x3svW1HSsbqNw8kzw26bRYgyEp     6.09561000`
Outputs(2):
 `1EJnweebqkcQZ5vEvjRmw9vF67pY7723yo	     0.59546000
SCRIPT 21035c5bf713149a2c7176304c1686df1daa42aa8b61811d7c65095cc444034babd9	     5.22781000`

**Comment by SomberNight** [comment]
> As for the "signed tx", here are both the input and the output: [...]

Can you share the complete raw transaction though? This is what gets sent to the connected Electrum server and then to a bitcoin full node to verify and broadcast.

In Send tab, fill in form, then click `Pay...`, then click `Advanced`", then click `Finalize`, click `Sign`,
then `Export`>`Copy to clipboard`.

**Comment by Blackhawke** [comment]
Ah! Got it. Here you go:

`0200000001777e2ecc96eb7ea6ef666e568ba0d37d49adcb7a18d54f8917a8fa1823f7ec2e000000008a4730440220410a7a5b89ee4068892528fa8b7e152292cabf85054f7a1a9dae46d2eb2f41af02206193626111a5567a9afe957bb509e48abe5cce94c0e66678ad0f501d7098b272014104d6e60a6e04cf12bc5dc382d5cc1c8e8a7c2266fbac8ea50b92a6f09647cb6e5f6a9061abc72fd6ba1d604289bf3f86948022f7532c96014edf6ebc25910361f2fdffffff024d9f0c00000000001976a91491f70ea33f9669fd0187b9979aca7680c4d33c2088ace7b65100000000002221035c5bf713149a2c7176304c1686df1daa42aa8b61811d7c65095cc444034babd9fc3e0a00`

**Comment by SomberNight** [comment]
@Blackhawke your messages implied you were also getting the `bad-txns-inputs-missingorspent` error but that is not the case.
That tx is getting error `scriptpubkey`.
The tx looks consensus-valid but [it is not standard](https://github.com/bitcoin/bitcoin/blob/4a540683ec40393d6369da1a9e02e45614db936d/src/policy/policy.cpp#L117) according to policy.

This is because output 1 is non-standard (`SCRIPT 21035c5bf713149a2c7176304c1686df1daa42aa8b61811d7c65095cc444034babd9`).
This output is just pushing a pubkey onto the stack. Perhaps you meant to include an `OP_CHECKSIG`?

So this is totally unrelated from the OP.
OP already got his own answer IMHO, so I will close this.
