### ISSUE TITLE
Assist with CC and Electrum

### ISSUE THREAD

**Issue by nterry709** [spesmilo/electrum#6986]
The newest version of Electrum does not appear to have the option  Export>For hardware device>Export to file (include xpubs). This appears to be the issue with me not being able to sign a PSBT with my CC. Can anyone assist?

**Comment by SomberNight** [comment]
Is this for a multisig wallet; or a standard single-signer wallet?

> The newest version of Electrum does not appear to have the option Export>For hardware device>Export to file (include xpubs)

The option should be there. Can you take a screenshot?

**Comment by nterry709** [comment]
This is for a stadard wallet. 

![elecss](https://user-images.githubusercontent.com/78389837/106606967-4fbb0880-653d-11eb-82fe-cc35e4dc5a1c.png)

**Comment by SomberNight** [comment]
Looking at the code, this suggests the tx is not a partial transaction.
How did you create this tx?
Also, what does it say from "Status" in this same dialog?

**Comment by nterry709** [comment]
I try and send some BTC from Electrum to my CC exported Elextrum wallet. So I get an address from the skeleton wallet that I see in electrum, then hit pay, finalize, then export to hardware device.

I am able to now to export a pstb file via the export tab -- for hardware devices; include xpubs -- save to file but I am still getting the error message Failure none of the keys involved in this transaction belong to this coldcard. 

Am I missing something?

**Comment by SomberNight** [comment]
Your description is confusing.
It is hard to tell where you are sending from and sending to. I think you yourself are confused about this.

> So I get an address from the skeleton wallet that I see in electrum, then hit pay, finalize, then export to hardware device.

The coldcard is associated with the "skeleton wallet", i.e. the coldcard can sign when you are spending FROM that wallet;
but you just said you are sending TO that wallet ("I get an address from the skeleton wallet").

**Comment by nterry709** [comment]
I am trying to send btc to the cc. From Electrum desktop wallet to exported skeleton on a microsd then the cc.

**Comment by SomberNight** [comment]
Check out some guides: https://coldcardwallet.com/docs/ -- look for "Guides by the Community">"Electrum" on that page

-----

I suspect you now have multiple wallets in Electrum. When you open the "skeleton wallet" that was exported from the coldcard, that is just another wallet from Electrum's perspective.

The coldcard can only sign txs that spend FROM *that* specific wallet (the "skeleton wallet"). However you have said that you are trying to send TO that wallet; the coldcard cannot sign that tx, that's why you are getting the error.

It would be easier to help if you provided full screenshots with main window and tx dialog visible. Note that you can test all this on testnet too.

**Comment by SomberNight** [comment]
I believe this issue was mostly due to user confusion; there is no bug to fix.
