### ISSUE TITLE
Electrum Wallet Transaction ID: Unknown 2 Inputs | 2 Ouputs

### ISSUE THREAD

**Issue by Newton-gif** [spesmilo/electrum#6987]
![Bug](https://user-images.githubusercontent.com/78447786/106662792-22a14100-65a3-11eb-8085-34eb9ca4f9c6.PNG)

Since I downloaded Python 3.8 my Electrum 3.3.8 got an multiprocess error. 

I deinstalled 3.3.8 and installed the newest version on electrum.org. Now I can´t send any transactions from my wallet. 

I even deleted the wallet and created it with the seed again, but now I also lost all my Descriptions for each of the 400+ Transactions. I completely lost track of everything.

I fucking hate Electrum and will never use it again. I just want to send my btc to another wallet. Please help me.

**Comment by SomberNight** [comment]
> Since I downloaded Python 3.8 my Electrum 3.3.8 got an multiprocess error.

This suggests you are running from source? If not, I don't know what you did...

> I deinstalled 3.3.8 and installed the newest version on electrum.org. Now I can´t send any transactions from my wallet.

Why is that? Everything looks ok on the screenshot.
Click "Finalize", "Sign", and then "Broadcast". ("Finalize" was added in 4.0, but otherwise it is identical to 3.3.8)
Also note that this is the "Advanced" dialog; if it is too confusing, just don't click "Advanced"...

> I even deleted the wallet and created it with the seed again, but now I also lost all my Descriptions for each of the 400+ Transactions.

Indeed, labels/descriptions are not recoverable from seed. You could have synchronised your labels to a server using the "LabelSync" plugin, or have made a backup of your wallet file before deleting it...

> I fucking hate Electrum and will never use it again. I just want to send my btc to another wallet. Please help me.

What exactly is the problem? You haven't specified it and it is far from obvious from your screenshot -- everything looks ok there.

**Comment by Newton-gif** [comment]
I know what happened. 

On 3.3.8 you don´t need to sign the transaction. I just had to  press sign on the new electrum. All the anger was senseless...


How do I recover my Descriptions? I really need it for the tax office, otherwise I am screwed.

**Comment by SomberNight** [comment]
> Also I never had 2 Ouputs before on Electrum 3.3.8. 

You don't seem to be familiar with Bitcoin enough to use the "Advanced" mode. There is more than 1 output every time you need change back, which is very common.

> Normally you can see a Transaction ID, but look, there is written "Unbekannt" (Unknown).

That's because the tx is not finalised yet in your screenshot, and such a state did not exist in 3.3.8.
Again, this whole thing is only visible if you click "Advanced".

> How do I recover my Descriptions? I really need it for the tax office, otherwise I am screwed.

If you had not used the LabelSync plugin previously then all your labels were only stored in your wallet file. If you don't have a backup of the wallet file you have deleted, then your labels are lost.

**Comment by Newton-gif** [comment]
Thanks for helping me out SomberNight. What is your btc adress? I want to gift you a coffee.

**Comment by SomberNight** [comment]
You are welcome.

Feel free to donate to one of the Electrum server operators instead.
When running Electrum, go to `Help`>`Donate to server`.
