### ISSUE TITLE
timeout when opening a lightning channel with hardware wallet

### ISSUE THREAD

**Issue by raph431** [spesmilo/electrum#7027]
When I try to open a lightning channel, I do not have enough time to accept the transaction with my Nano S hardware wallet. Besides I cannot check whether the address that is displayed on my device is correct, because the electrum window does not show me the channel funding address. I tried it twice, but it seems impossible to accept it fast enough on the device. Those failed channel funding attempts still seem to leave a trace, because when I select "Tools -> Lightning" it shows "2 channels", which definitely do not exist.

**Comment by ecdsa** [comment]
> When I try to open a lightning channel, I do not have enough time to accept the transaction with my Nano S hardware wallet. 

This timeout is here for P2P negotiation. The time taken to sign should not be part of it.
Maybe we could move the signing/broadcasting logic out of `_open_channel_coroutine`

> Besides I cannot check whether the address that is displayed on my device is correct

What kind of extra security do you think that would bring you? The point of displaying the address on the device is so that you can compare it to the address in a payment request. It is not mean to be compared to the address displayed on your computer.

**Comment by raph431** [comment]
> What kind of extra security do you think that would bring you? 
It would ensure, that the payment really is the electrum channel funding and not some other nefarious program. But I agree, it is not really necessary.

**Comment by raph431** [comment]
Thank you, the timeout problem is now fixed. I did get an error window though:
https://imgur.com/a/qTcshzx
Another issue seems more severe:
While I do see the correct amount (0.0021 BTC) in "Local" in the "Channels" plane, above the table it reads "Can send 0.0014016 BTC; can receive 0. BTC" Where does the 0.0006984 difference come from? Is this the fee reserved for the closing transaction? Seems quite a lot. I opened the channel for a 0.000077 BTC fee.

**Comment by raph431** [comment]
I would like to add some positive feedback. LN transactions work great. I tested with BLW, Bluewallet and Phoenix. I wasn't able to send to Bluewallet or Phoenix, but all of them could send via LN to my Electrum wallet. (I suspect the issue was caused by insufficient remote balance on Bluewallet and Phoenix.)

**Comment by SomberNight** [comment]
Re "available to spend", the logic is quite complex unfortunately.
In short, the difference between balance and "available to spend" is due to "channel reserve" + "commitment tx fee" + ["fee spike buffer"](https://github.com/lightningnetwork/lightning-rfc/blob/edd45ecf22095ce97c1b5e9136a7d79351bd68cb/02-peer-protocol.md#requirements-9).

> Thank you, the timeout problem is now fixed. I did get an error window though:
> https://imgur.com/a/qTcshzx
>`Could not open channel: RuntimeError("There is no current event loop in thread 'Dummy-5'.")`

When do you get that error? And you say the channel still opened? Weird; not sure what is going on there or which line it could be coming from... I suppose you don't have a trace?

**Comment by raph431** [comment]
Indeed this free reservation is more complex than I thought. 

I got that error right after opening the channel. Yes, the channel was opened successfully. And I'm sorry, no, I didn't trace it.

**Comment by ecdsa** [comment]
I guess that error is hardware-wallet related.
