### ISSUE TITLE
Cannot double spend [350k sat]

### ISSUE THREAD

**Issue by Transisto** [spesmilo/electrum#7049]
We'd have wanted to use the double spend feature but can't.

I suspect it could either be because we haven't produced any change (Send MAX)
or because all outputs are being sent to the local wallet.

**Comment by Transisto** [comment]
I wish there was a way to make use of UTXOs that have been used in a still unconfirmed transaction.

I'm thinking either the coin selection tab could show them as grayed out but would be able to manually select them. (There'd be a small chance it could create invalid transactions when tiring to spend outputs of different still unconfirmed parent transactions.)

But IMO much simpler, What if we could simply ignore a specific transaction in the mempool to then be able to craft a custom double spend?

**Comment by SomberNight** [comment]
> We'd have wanted to use the double spend feature but can't.
> I suspect it could either be because we haven't produced any change (Send MAX)
or because all outputs are being sent to the local wallet.

I assume you mean the "Cancel (double spend)" feature, which spends back the inputs to your wallet.
Indeed, it is not shown if "all outputs are being sent to the local wallet" -- what would be the point then? Why don't you just use "increase fee" instead?

> But IMO much simpler, What if we could simply ignore a specific transaction in the mempool to then be able to craft a custom double spend?

- go to the Console tab, and run `wallet.remove_transaction(TXID)`, where TXID should be substituted for the txid of the old tx you are trying to replace
- the GUI should refresh, the tx should disappear from the History tab, and the input UTXOs should reappear in the Coins tab. If needed, you can try to force a refresh by pressing F5
- go to the Coins tab and manually select inputs such that they would conflict with the old tx
- go to the Send tab and create a new tx
- before signing the tx, during the payment flow, go to the "Advanced" tx preview dialog and manually verify that the new tx indeed conflicts with the old tx (i.e. they have at least one shared input)

**Comment by Transisto** [comment]
Because it's a very large consolidation, and I'd like to invalidate a single UTXO with a higher fee.
Not sure what are the miners policy when choosing between a large transaction with sum fee of 100k sat or a much smaller one with a sum of 15k sat.

Thanks will try this out.

**Comment by SomberNight** [comment]
>  Not sure what are the miners policy when choosing between a large transaction with sum fee of 100k sat or a much smaller one with a sum of 15k sat but I assume it'd work.

Ah that won't work I am afraid. [BIP125 rule 3](https://github.com/bitcoin/bips/blob/3a7585365ff3280a4fc9d34ea6a1e43c39cfa7be/bip-0125.mediawiki#Implementation_Details) says the absolute fee needs to increase.

**Comment by Transisto** [comment]
```
>>> wallet.remove_transaction(Correct TXID)
Traceback (most recent call last):
```

Doesn't seems to be doing anything, 

I disconnected the wallet before.

**Comment by Transisto** [comment]
Is there a general way to donate to electrum?

I'll try anyway and report back if any miners overlooked rule #3

**Comment by ecdsa** [comment]
Electrum does not accept donations, but you can donate to the operators of Electrum servers.
