### ISSUE TITLE
[Linux] Can't verify GPG signature

### ISSUE THREAD

**Issue by tifDev** [spesmilo/electrum#7057]
Hello, 

I can't verify the Electrum download:

**Try 1 (copy ThomasV.asc from github and pasting in local created file ThomasV.asc):**
``` bash

gv  ~  Downloads  gpg --import ThomasV.asc
gpg: key 2BD5824B7F9470E6: "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

gv  ~  Downloads  gpg --verify ThomasV.asc electrum-4.0.9-x86_64.AppImage 
gpg: verify signatures failed: Unexpected error
```

**Try 2:**
``` bash
gv  ~  Downloads  gpg --keyserver keys.gnupg.net --recv-keys 6694D8DE7BE8EE5631BED9502BD5824B7F9470E6
gpg: key 2BD5824B7F9470E6: 13 duplicate signatures removed
gpg: key 2BD5824B7F9470E6: 388 signatures not checked due to missing keys
gpg: key 2BD5824B7F9470E6: "Thomas Voegtlin (https://electrum.org) <thomasv@electrum.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gv  ~  Downloads  gpg --verify ThomasV.asc electrum-4.0.9-x86_64.AppImage
gpg: can't open 'ThomasV.asc': No such file or directory
gpg: verify signatures failed: No such file or directory
```

I can't verify the download. How can I do this?

Thank you.

**Comment by SomberNight** [comment]
Please see: https://github.com/spesmilo/electrum-docs/blob/master/gpg-check.rst

For example:
```
$ gpg --verify electrum-4.0.9-x86_64.AppImage.asc electrum-4.0.9-x86_64.AppImage
```

**Comment by tifDev** [comment]
I seen that too..
Where do I get _electrum-4.0.9-x86_64.AppImage.asc_ ?

```
gpg --verify electrum-4.0.9-x86_64.AppImage.asc electrum-4.0.9-x86_64.AppImage
gpg: can't open 'electrum-4.0.9-x86_64.AppImage.asc': No such file or directory
gpg: verify signatures failed: No such file or directory
```

Thank you

**Comment by SomberNight** [comment]
>  Where do I get electrum-4.0.9-x86_64.AppImage.asc ?

There is a `signature` link next to the link of the binary on the main download page (https://electrum.org/#download).

Also, all the release files are listed here: https://download.electrum.org/4.0.9/

**Comment by tifDev** [comment]
Thank you!

**Comment by yeru83** [comment]
Hey; Can't seem verify Thomas keys via GPG Keychain on MacOS (worked fine for other keys):


Receiving keys failed.
Import failed!
Code = 0
Error text:
gpg: key 2BD5824B7F9470E6: 401 signatures not checked due to missing keys
gpg: no writable keyring found: Not found
gpg: error reading '[stdin]': General error
gpg: import from '[stdin]' failed: General error
gpg: Total number processed: 0

**Comment by tifDev** [comment]
Have you downloaded the .asc keyfile from electrum **downloads** page?

**Comment by yeru83** [comment]
Thanks for checking. For some reason it works today.  It gives the message "untrusted," I have not found where to verify to mark as trusted. 
Yes, on March 11, 2021, I downloaded electrum-4.0.9.dmg.asc (833 bytes) from the electrum downloads page; and that is what I couldn't get to work. I meant to post this re: MacOS rather than Linux sub.
