### ISSUE TITLE
Failed to Disable 2fa HELP!

### ISSUE THREAD

**Issue by WooDy2x** [spesmilo/electrum#7225]
I am trying to disable 2fa but it is useless my wallet is still 2fa.

What I do is ...

 -FILE
- NEW / RESTORE
- I choose: Standard wallet
- I choose I already have a seed
- I choose: Disable 2fa

Is it a bug or do I need to do it another way?

![image](https://user-images.githubusercontent.com/82826170/115257872-1c2c5b00-a0f6-11eb-8e45-ba980f6efbdd.png)

I have tried 3 times and the "[2fa]" is automatic on restore even choosing to disable it.

**Comment by SomberNight** [comment]
The wallet type being "2fa" (a special kind of 2of3 multisig) is a property of the seed. That cannot ever be changed. The only option you have regarding that is creating a new seed and sending your coins to it.

What happens when you "disable 2fa" when restoring from seed is both of the two keys derivable from the seed gets saved in the wallet file effectively downgrading the wallet to a single factor: you will be able to spend from it without the time-based one time passwords.
