### ISSUE TITLE
Unconfirmed transfer

### ISSUE THREAD

**Issue by Schnitzel777** [spesmilo/electrum#7229]
sorry bit since two days nothing happens when I wanna send coins ?!? Can you tell me what to do?

all the years everything works but since two days it s like a freeze or so ...

it was the newest version

**Comment by Transisto** [comment]
Could you provide more details about "nothing happens" ?

The fees is higher than usual because the chain is slower due to a portion of the miners being offline.

It should get back to normal in about a week.

Check a website like https://mempool.space/ to know how much fees to put if you're in a hurry.

**Comment by Schnitzel777** [comment]
Thanks this could be the reason why over hours and hours nothing happened.

I paid a fee to cancel this transfer- or is it better let them works over
days ?

Transisto ***@***.***> schrieb am Mi. 21. Apr. 2021 um 03:06:
