### ISSUE TITLE
Possible "Coin Control" GUI feature (reference: Bitcoin Core)

### ISSUE THREAD

**Issue by dabura667** [spesmilo/electrum#726]
Similar to the "send from address" with right click. This feature would allow to use specific outputs attributed to the wallet on an output by output basis.

I don't think it would need a completely separate UI like Core, but maybe expand the right click option to "send from" to have a tiny pop up listing outputs to the selected address(es) and default is all are selected. The user would then click on outputs to deselect or select them and choose the outputs individually. The send box would then give an error if the send amount + fee amount is greater than the sum of the chosen outputs.

If this is planned, or already similar functionality in the code base (I looked, but maybe I'm just not smart enough to notice), I apologize.

**Comment by leafcutterant** [comment]
Revisiting this as I think the present form of coin control is not intuitive enough.

I'd like to emphasize that coin control (second to one-use addresses, of course) is an essential part of control over anonymity. It is this why it should be made as easy as possible.

I was glad to find that CC is possible through Ctrl+click style choosing addresses and "Sending from...". However, this is cumbersome, as one simultaneously scrolls through the addresses (many of them empty), opening down the Change section (or worse, the Change, Used and Imported sections too), calculating in head to make sure the selected balances will be enough, while trying not to screw up the selection by releasing the Ctrl button or clicking at he wrong spot. This is, I admit, feasible, but I advocate lowering the bar to bring the everyday user closer to the control over their anonymity.

I suggest a "Coin control..." button to be placed on the right of the Amount textbox(es) (plural because of the potential extra textbox with the fiat value). This button would open up a window. It would have a scrollable table listing all non-frozen addresses that have non-zero balance, their labels if any, the balances (with fiat value if plugin is enabled) and a tick box; one per line. Above the table, there would be displayed:
1) An amount that is the sum of the entered amount + tx fee in the main window (also in fiat if plugin enabled), which of course would be invisible if there was nothing specified in the main window. This amount would be named something like "Required input/funds".
2) An amount that is the sum of the ticked addresses (also in fiat if plugin enabled), named something like "Selected input/funds". This would be colored green if it is greater than or equal to "Required input" or if there was none specified in the main window; in every other situation, it would be red and something like "Insufficient inputs/funds, select more"  would read next to it.
3) There would be a "Clear" button.
4) There would also be a "Default" button, which would return the selection to its original state (the wallet-defined selection if there were amounts specified, or nothing if there was none).
The addresses would be ordered as on the Addresses tab, but an address would be brought to the top of the list if ticked.
Below the table, there would be an "Ok" and a "Cancel" button, saving the selection or returning it to the previous state.
After closing, the selected inputs would be added to the now-visible From table.

In case the CC is opened after specifying amounts, the default selection choice would be made and displayed by Electrum to provide the user with a starting point. If there is no deviation from the default selection, the From table would not appear.

The user would be allowed to have insufficient funds selected, or to specify sufficient inputs and then increase the amount(s) in the main window, but in this case, there would be the normal warning in the status bar and the "Send..." button would be disabled.

To have an easy way out if the user becomes confused, the "Clear" button would also reset the coin control state, just as it works now.

I advocate the above way also because when you transact, the primary priority is that you have to send a certain amount, the source is secondary. Meeting that certain amount is easier if you have a selection tool that counts for you and lets you selectively add or remove inputs.

This functionality would not hinder the already existing "Send from" method.

What do you think?

**Comment by kyuupichan** [comment]
If you're interested in privacy try git HEAD where I implemented a coin
chooser.  Look in the preferences.

**Comment by ecdsa** [comment]
I suggest to create a new tab, similar to 'addresses', that shows utxos in the wallet.
That tab would be optinal. (I'm going to make 'addresses' optional too, btw)

**Comment by leafcutterant** [comment]
@kyuupichan Thanks, I'll try it out once I learn how to compile.

@ecdsa If we go that way – just to simplify things – why not just use the Addresses tab for it? There could be a check box (e.g. "Show only funds") to switch between the views.
I don't believe this direction addresses the CC usability question well, but it's more than nothing.
