### ISSUE TITLE
Reduce Tor spam due to Electrum probes

### ISSUE THREAD

**Issue by rkfg** [spesmilo/electrum#7317]
Related to #5580. Electrum seems to probe the Tor ports to see if it's running, this causes excessive amount of log spam like `Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)` every 10 seconds. The related code is here: https://github.com/spesmilo/electrum/blob/cad4e77853b1d3ae5fdaaa868c2fce67780a8870/electrum/gui/qt/network_dialog.py#L462

It's really unnecessary to do this all the time as we only care about whether Tor is running when the user opens the network settings dialog. I think it would be best to start the detector on dialog show and stop it as soon as the dialog is closed/hidden.

**Comment by gits7r** [comment]
Once you open the Network Dialog and go to "Proxy" tab, regardless you close the dialog window it will run every 10 seconds a `GET\n` to `localhost` .  Because Tor does not accept HTTP proxy requests on its SocksPort it will spam the Tor's daemon log message as follows:

```
2022-12-29 17:52:19.493 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:52:29.606 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:52:39.717 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:52:49.831 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:52:59.943 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:53:10.046 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:53:20.158 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:53:30.276 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:53:40.386 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
2022-12-29 17:53:50.498 [WARN] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
```

There must be a better way to achieve this. 

This is more confusing because, even if you don't setup Electrum to use a Socks5 / HTTP Proxy, you still get this in your Tor's daemon log file, and wonder what app on your host might be trying to use Tor as a HTTP proxy.

**Comment by gits7r** [comment]
I have been thinking about this, and looked for solutions, but I think the best and simplest thing we can do here is to use the method as we are currently using (send a `GET\n` partial HTTP request to `localhost:9050` and `localhost:9150` and look if the response looks like Tor, and use that, but just do it one time, not in an endless cycle every 10 seconds even if the Network dialog window is closed.

Otherwise, we can:

- try to query Tor's `ControlPort` and `GET_PROTOCOLINFO` - however, one can run Tor without `ControlPort` enabled, and even if, maybe it's authentication protected and this needs extra code to work, maybe permissions, which are non-trivial and maybe a bit overkill as we just want to know if it's running or not, not so much information.
- use `tor-resolve` tool that usually comes with Tor and try `tor-resolve 0:0:0:0:0:0:0:0` and we should get a correct reply, otherwise a fail. This will let us know for sure that there is a Tor SocksPort listening and running on the host, however we need extra logic to detect the port on which the Socks5 is running on. And last but not least, `tor-resolve` is not mandatory to exist, so there will be isolated cases when this approach will not work.

For the above stated, I think the best way is **to just change the code to send a SINGLE (1) request of `GET\n` to `localhost:9050` and `localhost:9150` when the NetworkDialog -> Proxy tab is accessed, not try it every 10 seconds in a spammy way, because there is no sense for that**, and if Tor responds, suggest that to use, otherwise don't. 

The one time probe should be sent every time the NetworkDialog -> Proxy tab is accessed, as many time as the user views it (because one user can start Electrum, go there, see Tor is not detected and then start Tor, open NetworkDialog again).

**Comment by gits7r** [comment]
An additional reason to fix this faster is because, after 40 minutes or so of probes every 10 seconds, Tor process will not accept anything on the SocksPort any more (break Tor or Tor Browser for the entire system and for all apps using that SocksPort, until a restart of the process). Just tested it with latest `Tor Browser 12.0.1`.

**Comment by gits7r** [comment]
OR
We can use the code here:

https://github.com/torproject/tor/blob/main/contrib/client-tools/tor-resolve.py

and run it ONCE (1) on `localhost 9050` , and ONCE (1) on `localhost 9150` , to do a `tor-resolve 0:0:0:0:0:0:0:0` every time NetworkDialog -> Proxy tab is accessed, and if we get a reply, Tor works on that port -> suggest to use.

**Comment by SomberNight** [comment]
> An additional reason to fix this faster is because, after 40 minutes or so of probes every 10 seconds, Tor process will not accept anything on the SocksPort any more (break Tor or Tor Browser for the entire system and for all apps using that SocksPort, until a restart of the process).

Why is that? Is it IP-banning localhost?

**Comment by gits7r** [comment]
@SomberNight no, it's not related to IP-banning - it's a problem with how Tor Browser is reading the `stdout` from the Tor daemon, it did not used to occur in past Tor Browser releases and it also doesn't affect the System Tor (If Tor is not launched by Tor Browser). More details here:

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41549

But still, our method should be at least changed to try ONE TIME when the Proxy Tab of the Network Dialog is accessed, not once very 10 seconds for as long as Electrum is running.  At least check every time the Proxy Tab is accessed, if not use `tor-resolve 0:0:0:0:0:0:0:0` and if returned without error, it means Tor is running and can be used.

**Comment by trinity-1686a** [comment]
if you want to do what tor-resolve does in a cheap/more hardcoded way, you can send `b'\x05\x01\x00\x05\xf0\x00\x03\x070.0.0.0\x00\x00'`
And expect `b'\x05\x00\x05\x00\x00\x01\x00\x00\x00\x00\x00\x00'` as a reply. That shouldn't log anything on tor side.

(that's a socsk5 handshake followed by a socks RESOLVE request as defined in [tor's socks extension spec](https://github.com/torproject/torspec/blob/main/socks-extensions.txt#L63), resolving `0.0.0.0`, which being an IP, tor resolves itself without needing to ask a relay. If you want details about each particular byte, wireshark decodes it quiet well)

**Comment by trinity-1686a** [comment]
that looks about right. The comment should say it mimics `tor-resolve 0.0.0.0` though.

non-Tor SOCKS5 proxy should not know the command RESOLVE/0xF0 and reply with Command not supported/0x07 (something starting with `b'\x05\x00\x05\x07\x00`). In the unlikely case they use the same command for something else, they are unlikely to answer exactly what's expected

**Comment by SomberNight** [comment]
Thanks. Pushed in https://github.com/spesmilo/electrum/commit/2e06a7992e7d692a2ade81dff01ecf2ff9c98e09
