### ISSUE TITLE
better document available config options (config keys/values)

### ISSUE THREAD

**Issue by ChzenChzen** [spesmilo/electrum#7325]
Where can I find possible options for config files? 
I want to set default fee options for all transactions through `electrum setconfig [key/values]`. I want to have mempool fee estimator and max depth level.

**Comment by SomberNight** [comment]
The config keys/values are unfortunately not really documented.
Currently you have to look for them in the source code; and even there they are scattered all over the place. :/

Re your specific question for mempool depth fees, what is stored in the config is the slider position rather than the depth in bytes.
See e.g.
https://github.com/spesmilo/electrum/blob/a425ab030194c135b1f3b853073be1a7ec6ffc7c/electrum/simple_config.py#L494

**Comment by SomberNight** [comment]
related https://github.com/spesmilo/electrum/pull/5649
