### ISSUE TITLE
Channel closed remotely. Can't return money

### ISSUE THREAD

**Issue by alexander-koval** [spesmilo/electrum#7332]
Hello. Channel closed suddenly and I lost money?

![image](https://user-images.githubusercontent.com/1667444/120461118-f0beb080-c3c3-11eb-824d-6c56cedd5da3.png)

**Comment by SomberNight** [comment]
Why do you think you lost money?

**Comment by bitromortac** [comment]
This looks like the Acinq node opened a channel to the wallet, how is that possible? Then, it looks like the Acinq node force closed the channel and there's one output of 635904 sat that should be available to spend, if I interpret onchain data correctly.

**Comment by SomberNight** [comment]
Yes, I guess it looks a bit unusual that the Acinq node initiated the channel but in principle there is nothing wrong with that.
Maybe OP could explain how they got the channel opened originally?

The txs are:
https://blockstream.info/tx/6e106e5fe41d67001562bb58e37126be4ce118647c99807424de47f1b7d78eaf
https://blockstream.info/tx/98657626359132c79d05a0a1ca69ded55fa71ce60ee73a361325f95c2b5d44bb

Indeed it looks like the Acinq node force-closed. The to_remote output of the commitment tx should directly pay to a wallet address (due to static_remotekey). So I don't understand why OP thinks the money would be lost.

Again, more info needed.
