### ISSUE TITLE
Force-close or cooperative close?

### ISSUE THREAD

**Issue by gcomte** [spesmilo/electrum#7360]
When closing a channel this dialogue pops up:
![Selection_374](https://user-images.githubusercontent.com/8024734/123104561-59370580-d437-11eb-9efd-81fb9f69b0cd.png)

It doesn't make a lot sense to me because:
1) A force-close is a unilateral close, you don't need to request anyhting for that from the remote peer. `Request *cooperative close* from remote peer` would make more sense.
2) Having a checkbox AND a `Yes` and `No` button seems redundant

**Comment by SomberNight** [comment]
There are three ways to close a channel (disregarding cheating attempts)
1. it can be closed cooperatively
2. it can be force closed by the LOCAL party
3. it can be force closed by the REMOTE party. There is a trick to achieve this: we can fake having lost data/state and trigger the REMOTE to force close themselves.

In the Qt GUI, in the Channels tab, if you right-click a channel, the context menu has two options:
- `Close channel`: this pops up the dialog shown in your image.
  Clicking "no" is just cancelling the dialog.
  Clicking yes, with checkbox checked, is option (1), coop/mutual close.
  Clicking yes, with checkbox unchecked, is option (3), REMOTE force-close.
  Note that both these options need "help" from the remote party.
- `Force-close channel`: this is option (2), LOCAL force-close.
  This option can be used even if the remote party is unreachable.

**Comment by gcomte** [comment]
Okay sorry, my 2nd point was stupid.

The first one is also clear now aside from the fact that I don't understand why one would want the remote to force-close the channel.

**Comment by SomberNight** [comment]
Oh, regarding rationale:

> it can be force closed by the REMOTE party. There is a trick to achieve this: we can fake having lost data/state and trigger the REMOTE to force close themselves.

This option is interesting for game theoretic reasons.

First, note that there is no "ask remote to force-close" protocol message; instead the protocol specifies that you should force-close a channel if you believe the counterparty has lost state. We trigger the remote-force-close by pretending to have lost state.

Consider not having the option. People would only ask the remote to force close when they have actually lost state. 

If so, the remote might consider cheating by broadcasting an older state where they have a higher balance knowing we cannot penalise them due to having lost state.
Two ways to try to decrease their expected value of cheating:
- some people should use watchtowers; the more people do, the lower the expected value
- sometimes fake having lost state, preferably in an unpredictable way

**Comment by gcomte** [comment]
Ingenious!! 

Thank you for sharing the rationale with me and keep up the good work :-)
