### ISSUE TITLE
Onion-related warnings from Tor

### ISSUE THREAD

**Issue by Liisachan** [spesmilo/electrum#7478]
Testing Electrum 4.1.5 over Tor, I got two kinds of warnings from Tor. (1)
[warn] Warning! You've just connected to a v2 onion address. These addresses are deprecated for security reasons...

If I understand this correctly, a client should not try to connect to v2 onion anymore, even if such an address is in the server list.
https://support.torproject.org/onionservices/v2-deprecation/

(2) Another warning I got from Tor when I opened Tools > Network in Electrum is:
“[warn] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)”

I’m not sure what this means, but if Electrum uses http(s) via Tor, that port is 8118 (at least for me), not 9050, so it might be nicer if this port number is configurable, not hard-coded as 9050 (a potential feature request).

Connection via Tor itself is working fine. So, sorry in advance if these are none of Electrum-side problems. My settings in Tools > Network are: [Use Tor proxy at port 9050 - checked][Use proxy - checked, with SOCKS5, 127.0.0.1, 9050] and Tor version is 0.4.5.10.

**Comment by SomberNight** [comment]
I've updated the default list of servers in https://github.com/spesmilo/electrum/commit/27fb5a6dbd731030f26bc9ff3ea01de9d6389445.
Note that the above list is only used for bootstrapping, and connected servers can tell you about other servers, which might still end up being v2 onions.

Regardless, it is perfectly fine for the client to try to connect to a v2 onion and fail.
In fact, by design, it is perfectly fine to fail to connect to some servers.
The servers are community-run and there is no uptime expectation whatsoever. As long as the client manages to find **some** servers that work, it is usable.

**Comment by Liisachan** [comment]
Thank you very much for updating the list (really appreciated) and for taking your precious time to explain how v2-onion errors will be handled gracefully. That does make sense!
