### ISSUE TITLE
bump required python version to 3.8

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7486]
I would like to bump the min version of python we support from 3.6.1 to 3.8.

The main motivation atm is wanting to be able to use latest [aiorpcx](https://github.com/kyuupichan/aiorpcX/) which [started to require python 3.8](https://github.com/kyuupichan/aiorpcX/commit/1ea6c5e52c077f294177727d6249d73832864424). It only has a few minor fixes compared to `aiorpcx 0.18.7` which we are using currently so the upgrade is not too urgent.

However, note that newer aiorpcx also has breaking API changes, which means that even if a user has new enough python they currently need to make sure not to use new aiorpcx. This potentially also affects Linux distros as they cannot package new aiorpcx if they want to package electrum.

It is not feasible for us to support both the old and the new API of aiorpcx due to the nature of the changes, so the cleanest solution would be for us to only support new aiorpcx but that entails bumping the min python version to 3.8.

I have been postponing this issue until debian stable has new enough python...
but now that debian 11 bullseye got released as stable a few weeks ago which has python 3.9,
and ubuntu 20.04 LTS has python 3.8,
I think we can consider bumping the required python version to 3.8.

Note that debian 10 buster ships python 3.7,
and ubuntu 18.04 LTS ships python 3.6.

Note that endusers who run binaries we distribute are unaffected, which includes Linux users who use the amd64 AppImage.

Thoughts?

**Comment by ecdsa** [comment]
ACK

**Comment by MrNaif2018** [comment]
What about making some exact policy for python versions supported by electrum? For example we do it this way: we support 3 latest python versions (3.7, 3.8, 3.9 for now), when new python version is released we temporarily add new version to CI build matrix and test all 4 versions, and after a month or so when all packages are ready, wheels uploaded etc, we drop the oldest version (so it would soon become 3.8, 3.9, 3.10). So in CI we test all versions on basic tests, and run functional tests (regtest tests) on the earliest supported version (in our case, 3.7, because that's what is used in our releases).
That way such issues won't appear in the future, and maintenance costs would reduce by supporting only a specified set of versions (3 versions is usually fine, maybe LTS distributions have to be considered)

**Comment by SomberNight** [comment]
> What about making some exact policy for python versions supported by electrum? For example we do it this way: we support 3 latest python versions (3.7, 3.8, 3.9 for now), when new python version is released we temporarily add new version to CI build matrix and test all 4 versions, and after a month or so when all packages are ready, wheels uploaded etc, we drop the oldest version (so it would soon become 3.8, 3.9, 3.10). 

I'd rather not make any commitment re what versions of python we support.
It should be reasonably easy for endusers of modern Linux distributions to run Electrum from source, so in practice we try not to require newer python than what the latest LTS releases of popular distros have.

---

another minor nudge to bump min python: https://github.com/spesmilo/electrum/commit/1705c1999ae5e82b3f203bb7f478917ec9316511
