### ISSUE TITLE
Electrum 4.1.2 - Electrum Tampoline fee insufficient

### ISSUE THREAD

**Issue by VadimEv** [spesmilo/electrum#7526]
Opened Lightning channel with 0 issues.
However I can't send anything.

Destination node: 02c1ac5cee87e4f40f24ea4560ab0e63f398ef5fb630cf50a0e2f638ce51e3169e@(Blockstream's BTCPay)

3 years in and still so much work ahead.
![image](https://user-images.githubusercontent.com/10043733/136338627-e97e186b-2a11-488f-aaad-ac22ec84d769.png)

**Comment by SomberNight** [comment]
Also, if you disable trampoline and wait for the gossip to sync, does the payment go through?

**Comment by SomberNight** [comment]
Just realised you are using an old version.
There have been several relevant bugfixes since 4.1.2. Please try with latest.

-------- Original Message --------
On 7 Oct 2021, 16:06, ThomasV < ***@***.***> wrote:
actually, the error relevant is the last line, MPP_TIMEOUT.
try to open more channels, or to send smaller amounts.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. ￼
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/spesmilo/electrum/issues/7526#issuecomment-937826404">https://github.com/spesmilo/electrum/issues/7526#issuecomment-937826404", "url": "[https://github.com](<a href=)/spesmilo/electrum/issues/7526#issuecomment-937826404">https://github.com/spesmilo/electrum/issues/7526#issuecomment-937826404", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
