### ISSUE TITLE
corrupted wallet file in electrum  (Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files)

### ISSUE THREAD

**Issue by Paayam** [spesmilo/electrum#7565]
when i open my wallet in electrum show me error (Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files) and after that when i accept it and i want to send coin to an other wallet address cant send coin and show me error (
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

Script failed an OP_EQUALVERIFY operation
)
please review this bug and fix it 
thanks a loot

**Comment by Paayam** [comment]
Please Responde to this email address : Payamkazemi72@gmail.com

**Comment by SomberNight** [comment]
> when i open my wallet in electrum show me error (Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files)

You should try restoring from seed words as the error says.

> when i accept it and i want to send coin to an other wallet address cant send coin and show me error ([...] `Script failed an OP_EQUALVERIFY operation`)

Yes, this is expected given the corruption error. Some or all addresses in your wallet file do not match the stored public keys, so the wallet will not be able to correctly sign for them.

-----

We would be very interested in figuring out *how* your wallet file got corrupted, in order to try to fix the underlying issue.
It would be much appreciated if you could write down some history and relevant details of your system and behaviour, including:
- when did you create the wallet file? using what version of Electrum?
- when did you start getting the corruption error, and have you previously successfully spent from this wallet?
- what version of Electrum are you using now?
- have you recently upgraded Electrum?
- what type of wallet do you have? that is, if you go to menubar>`Wallet`>`Information`, what does it say for `Wallet type`, `Script type`, `Keystore type`, `Seed available`?
- what operating system do you use?
- how do you run Electrum? is it using one of the official binaries - if so which one?
- where do you store the wallet file? (e.g. is it on a removable flash drive or network attached storage, or are you just using defaults?) do you have an SSD or a hard disk drive?
- do you have a password set for your Electrum wallet? and if so, do you have wallet file encryption enabled (when you open the wallet, does it already prompt you for the password)?

**Comment by Paayam** [comment]
We would be very interested in figuring out *how* your wallet file got
corrupted, in order to try to fix the underlying issue.
It would be much appreciated if you could write down some history and
relevant details of your system and behaviour, including:

   - when did you create the wallet file? using what version of Electrum? *i
   created wallet on 29 july 2013 and i use electrum ver1.8    *
   - when did you start getting the corruption error, and have you
   previously successfully spent from this wallet? *its show me cruppted
   error on 23 sep 2021 and yes i spent some tx on my some address in my
   wallet before cruppted error show.*
   - what version of Electrum are you using now? *i use electrum ver 4.1.5*
   - have you recently upgraded Electrum? *yes i have*
   - what type of wallet do you have? that is, if you go to menubar>Wallet>
   Information, what does it say for Wallet type, Script type, Keystore type
   , Seed available? wallet type : standard - script type : p2pkh - seed
   avalablie : True(standard) - KeyStore Type :  bip32 and my master public
   key is :
   -

   xpub661MyMwAqRbcGyDtkkdzJukvTDps3E

   qU8YPTGuaKzVDnvRx7denFrvm7famv99qV81PpsH4tTDtTz9VdrtDNw3djx1T7TTbj3GCz
   jjrqBmJ

   - what operating system do you use? *i use os is windows10  *
   - how do you run Electrum? is it using one of the official binaries - if
   so which one? *i run it normal mode and dont use binaries mode*
   - where do you store the wallet file? (e.g. is it on a removable flash
   drive or network attached storage, or are you just using defaults?) do you
   have an SSD or a hard disk drive? *stored in HDD Disk 7200 rpm*
   - do you have a password set for your Electrum wallet? and if so, do you
   have wallet file encryption enabled (when you open the wallet, does it
   already prompt you for the password)? *no ihavent*
   -

**Comment by SomberNight** [comment]
>> - when did you create the wallet file? using what version of Electrum?
>
> *i created wallet on 29 july 2013 and i use electrum ver1.8    *

>> - what type of wallet do you have? that is, if you go to menubar>Wallet>
   Information, what does it say for Wallet type, Script type, Keystore type, Seed available?
>
> wallet type : standard - script type : p2pkh - seed avalablie : True(standard) - KeyStore Type :  bip32

Hmm, that does not seem possible as bip32 support was only added in Electrum 2.0, in 2015.

>> - how do you run Electrum? is it using one of the official binaries - if
   so which one?
>
> *i run it normal mode and dont use binaries mode*

So do you run from source code using python?
If you downloaded an .exe file that you use to run Electrum then you are using a binary (an exe file is a binary).
The official binaries are distributed on electrum.org, so if you run using an exe file, ideally you would have gotten it from there.

**Comment by Paayam** [comment]
sorry i wrong aboute this part of your qustion and wrong answered so ...
Yes, I did.  i used exe  file and downloaded from electrum.org and verify
sha gpg from validating special identity of downloaded exe file .
 tnx for quickly answerving my question

**Comment by Paayam** [comment]
can you please help me to fix my problem?
tnx

**Comment by mhsmith** [comment]
This is probably a scam: see https://github.com/Electron-Cash/Electron-Cash/issues/2385.
