### ISSUE TITLE
Can't run electrum 4.2.0 on Windows 7 - please make build with Python 3.8

### ISSUE THREAD

**Issue by denbkh** [spesmilo/electrum#7728]
When I start electrum-4.2.0.exe on Windows 7 I get this error: 
`The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.`
According to [this](https://stackoverflow.com/questions/66718131/software-based-on-python-3-9-is-not-working-on-windows-7), the problem is related to python 3.9, it doesn't support Windows 7.
Readme file for electrum contains _Language: Python (**>= 3.8**)_, therefore, it should be possible to build electrum for Windows 7 with Python 3.8.
Could you please build the latest electrum with Python 3.8?

**Comment by SomberNight** [comment]
And to confirm, Electrum 4.1.5 did run on Windows 7, right?
May I ask why you are still using Windows 7?

Is Win7 still getting security updates?
Wikipedia lists ["Expiration date"](https://en.wikipedia.org/wiki/Windows_7#Support_lifecycle) as:
```
Mainstream support	January 13, 2015
Extended support	January 14, 2020
```


We did not realise we broke compatibility with Win7 -- the change was not intentional, but I wonder if Win7 is still worth supporting.
As long as it is that simple, I suppose we could build the Win binaries with python 3.8. py3.8 is getting security fixes for several more years.


Hmm, according to the [Steam hw survey](https://store.steampowered.com/hwsurvey/?platform=pc), 4.4% of Windows users (using Steam) are on Win7 these days.
I find that surprisingly high. Even more so, considering I would expect the Steam survey to skew towards power users.
```
February 2022
Windows Version

Windows 10 64 bit    78.54%
Windows 11 64 bit    16.18%
Windows 7 64 bit      4.24%
Windows 8.1 64 bit    0.66%
Windows 7             0.19%
Windows 10            0.08%
Other                 0.11%
```

**Comment by denbkh** [comment]
> And to confirm, Electrum 4.1.5 did run on Windows 7, right?

Yes, Electrum 4.1.5 runs on Windows 7 without any problems.

> May I ask why you are still using Windows 7?

Old hardware (no drivers for win 10 & 11), don't have time for upgrade, 99.9% of software (browsers, IDE, developer tools, etc..) still work on Windows 7 without problems.

> 4.4% of Windows users (using Steam) are on Win7 these days

[Global market share](https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide) for Windows 7 is ~12%, and in some countries much higher: [China  ~32%](https://gs.statcounter.com/os-version-market-share/windows/desktop/china), [India ~25%](https://gs.statcounter.com/windows-version-market-share/desktop/india), etc...

**Comment by SomberNight** [comment]
>> And to confirm, Electrum 4.1.5 did run on Windows 7, right?
>
> Yes, Electrum 4.1.5 runs on Windows 7 without any problems.

I've tested this myself now. Documenting here for posterity.
Testing with a fresh install of Windows 7 x64 SP1, I've tried to run Electrum 4.1.5:

- got first error:
  > `The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.`
  - fixed by installing `Windows6.1-KB2999226-x64`
- got second error:
  > `Failed to execute script pyi_rth_pkgres`
  - using the "debug" exe unpacked by the Electrum installer exe we distribute, traceback:
  ```
	C:\Program Files (x86)\Electrum>electrum-4.1.5-debug.exe
	Traceback (most recent call last):
	  File "C:\python3\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py
	", line 13, in <module>
	  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
	  File "pkg_resources\__init__.py", line 35, in <module>
	  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
	  File "plistlib.py", line 65, in <module>
	  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
	  File "xml\parsers\expat.py", line 4, in <module>
	ImportError: DLL load failed while importing pyexpat: The parameter is incorrect
	.
	[3552] Failed to execute script pyi_rth_pkgres
  ```
  - fixed by installing `Windows6.1-KB3063858-x64` (and then rebooting)

**Comment by SomberNight** [comment]
>  As long as it is that simple, I suppose we could build the Win binaries with python 3.8. py3.8 is getting security fixes for several more years.

Ah, I forgot that for the Windows builds we use the official binary builds of python from python.org (instead of cross-compiling from source on Linux, see https://github.com/spesmilo/electrum/issues/6565).

New releases from the Python 3.8.x branch no longer get binary builds anymore, only source-only security fixes. (see https://peps.python.org/pep-0569/)
The last binary release was `3.8.10: Monday, 2021-05-03 (final regular bugfix release with binary installers)`

This means that with our current build scripts if we wanted to bundle python 3.8, we would be stuck with 3.8.10, and not get security fixes. :/

**Comment by denbkh** [comment]
Is it possible to build electrum with python from [msys2 repository](https://packages.msys2.org/package/mingw-w64-x86_64-python)? I installed the Python 3.9.11 from there and it seems to work on Windows 7.

**Comment by SomberNight** [comment]
Not sure... do you mean we would build python from their sources, or that they distribute a binary and we could use that?

We currently use the binary built by python.org, so we trust them. It is not ideal but I find this reasonable.
I am not sure I would trust anyone else to build the binary for us; which leaves the alternative of building from source.

We could try to cross-compile the msys2 python using mingw, as in https://github.com/spesmilo/electrum/issues/6565. If that could be made to work, I would actually prefer that to the status quo. However, that seems like a lot of work. PRs would be welcome.

**Comment by SomberNight** [comment]
Possible ways to fix:
- bundle pre-built Python 3.8.10 from python.org
  ❌ we would be missing out on later 3.8.x security fixes
- build the ["hacky" `api-ms-win-core-path-l1-1-0.dll`](https://github.com/nalexandru/api-ms-win-core-path-HACK) ourselves (as part of the build scripts) and include it in the binary
  - not sure how future-proof this would be... but currently the lack of this dll looks to be the only reason why Python 3.9 cannot run on Win7
  - note that I've tested simply including the dll provided by Wine, and that does not work
- cross-compile the msys2 python using mingw, as in https://github.com/spesmilo/electrum/issues/6565
  - this could be a long-term win regardless of Win7 support, as we would no longer need to trust the python.org binary

Note that any approach would require being able to build reproducible binaries (as is already the case), and we heavily dislike bundling pre-built binaries.

-----

Considering that 
- Win7 itself is no longer receiving security fixes,
- there does not seem to be an easy way to keep supporting Win7,
- I am still a bit doubtful there are a lot of Win7 users out there,

my decision for now is to drop support for Windows 7.

If someone comes along and starts contributing towards supporting Windows 7, then we could potentially reintroduce support, however as it stands we don't have time to do it ourselves.

Existing Win7 users can keep using Electrum 4.1.5 for the time being -- but they should consider upgrading or changing their OS.

**Comment by BeholdersEye** [comment]
>     * build the ["hacky" `api-ms-win-core-path-l1-1-0.dll`](https://github.com/nalexandru/api-ms-win-core-path-HACK) ourselves (as part of the build scripts) and include it in the binary

You might consider including the dll in the portable version, at least, since that would significantly increase its portability (the reason people presumably use the portable version).


 
>     * I am still a bit doubtful there are a lot of Win7 users out there,

Even now it represents 10% of Windows installs.

https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide


> Existing Win7 users can keep using Electrum 4.1.5 for the time being

That is an ominous "for the time being". I'm a happy user of Electrum on Linux so it's no skin off my own nose but I would like to be able to recommend Electrum to my friends without saying "The first step is back up all your files before we can install a new operating system..." and in any case it should not be necessary to upgrade one's operating system to use "portable" software.

**Comment by anzz1** [comment]
> and in any case it should not be necessary to replace the host operating system to use "portable" software.

:+1: :+1: :+1: :+1:
