### ISSUE TITLE
portable exe creates electrum_data directory inside temporary _MEIPASS folder

### ISSUE THREAD

**Issue by sheslikeheroin** [spesmilo/electrum#7729]
I compiled electrum from source code via this command: ELECBUILD_COMMIT=HEAD ELECBUILD_NOCACHE=1 ./build.sh

The version I downloaded from the official site works fine, the directory is created without problems.

Win 10 build 2004

**Comment by SomberNight** [comment]
First of all, the official builds use the same build scripts, and most of the build process is containerised, so your local build should behave the same as the official builds (when built from the same commit).

Please provide more details as otherwise it is not possible to help.
What exactly happens when you run the `portable` windows exe that you built?

**Comment by sheslikeheroin** [comment]
@SomberNight 
on startup, a black window appears for milliseconds and electrum starts, but the electrum_data folder is not created, that's all I can tell you.

After that, I tried to build from the commit that is attached to the release of the 4.2.0 version and this bug was not there, the electrum_data directory was created when the portable version of electrum was launched (eb8ab74698b5cb8bc35da9e5baa604715c543de1)
https://github.com/spesmilo/electrum/commit/eb8ab74698b5cb8bc35da9e5baa604715c543de1

to build off this commit, I just reverted to it via "git checkout eb8ab74698b5cb8bc35da9e5baa604715c543de1" and wrote "./build.sh" in the build-wine directory

**Comment by SomberNight** [comment]
Ah, so you are saying there is a regression on master re the portable binary *since* the 4.2.0 tag.
I've just tested and indeed that's the case...

(portable exe located in `C:\Users\user\Desktop\`)
Electrum 4.2.0 portable exe, Qt console:
```
>>> config.path
'C:\\Users\\user\\Desktop\\electrum_data'
>>> config.get("portable")
True
>>> config.get("electrum_path")
'C:\\Users\\user\\Desktop\\electrum_data'
```

Current master HEAD (https://github.com/spesmilo/electrum/commit/25fee6a6be7e8e4bb8a0a62ef6737f6019d372e4) portable exe, Qt console:
```
>>> config.path
'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI59122\\electrum_data'
>>> config.get("portable")
True
>>> config.get("electrum_path")
'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI59122\\electrum_data'
```

I guess this might be due to changes in pyinstaller? (re https://github.com/spesmilo/electrum/commit/b5951adc29c1e39335350b8e03c316b41f33ef0f)

**Comment by SomberNight** [comment]
Relevant code is here:
https://github.com/spesmilo/electrum/blob/25fee6a6be7e8e4bb8a0a62ef6737f6019d372e4/run_electrum#L333-L337

> I guess this might be due to changes in pyinstaller? (re https://github.com/spesmilo/electrum/commit/b5951adc29c1e39335350b8e03c316b41f33ef0f)

Indeed it was changed in pyinstaller 4.3:
https://github.com/pyinstaller/pyinstaller/pull/5649
