### ISSUE TITLE
Electrum 4.2.x not compatible with Windows 7 (`api-ms-win-core-path-l1-1-0.dll` is missing from your computer)

### ISSUE THREAD

**Issue by oidhdozens** [spesmilo/electrum#7848]
Hi,

Since version 4.2.0 can use portable and independent exe - getting 2 errors (see below the messages).
Version 4.1.5 (one version before 4.2.0) is running ok - so you missed something in between.
I tried to run even later version from 4.2.0 but all of them are showing the same errors.

Here it the messages:
electrum-4.2.1-portable.exe - System Error
---------------------------
The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 

Fatal error detected
---------------------------
Error loading Python DLL 'C:\Users\user\AppData\Local\Temp\_MEI52802\python39.dll'.
LoadLibrary: The specified module could not be found.

**Comment by SomberNight** [comment]
Are you using Windows 7?

probably same as https://github.com/spesmilo/electrum/issues/7728

**Comment by oidhdozens** [comment]
Yes, Win7 but still why to break the compatibility?
The issue you mentioned is helping me since there's no fix this ;-(

------- Original Message -------

**Comment by oidhdozens** [comment]
Yes, Win7 but still why to break the compatibility?
The issue you mentioned isn't helping me since there's no fix this ;-(

------- Original Message -------

**Comment by SomberNight** [comment]
> The issue you mentioned isn't helping me since there's no fix this ;-(

Yes, I know.

> still why to break the compatibility?

That's why I linked the other issue, it gives context.
We did not break it intentionally, we updated some dependencies due to security fixes and build system problems (Python 3.8.x to 3.9.x), and it is the dependency that broke the compatibility.
Even if we kept using Python 3.8 (which in itself would take quite some work if we wanted a recent patch version of it that does not have prebuilt binaries), likely other dependencies will follow and break Win7 support, e.g. Qt6.

As explained in https://github.com/spesmilo/electrum/issues/7728 already, it would take a lot of work to keep supporting Windows 7.
Win7 is already long-past end of support, it's not getting security fixes. Electrum is security-critical software, especially in the most common usecase of using it as a standard software wallet.

You should upgrade to Win10, or some desktop Linux, e.g. Ubuntu or Manjaro. Sorry.

**Comment by oidhdozens** [comment]
Yes, Win7 but still why to break the compatibility?
The issue you mentioned is NOT helping me since there's no fix this ;-(

------- Original Message -------
