### ISSUE TITLE
Versions newer than 4.1 won't run on Windows 7

### ISSUE THREAD

**Issue by Psychosynthesis** [spesmilo/electrum#7924]
New versions do not work on the seven.

Okay, I'm ready to use my 4.1.5, but you won't let me use the wallet that I created in version 4.3 on Linux.

What are the considerations for this decision? Don't you think gentlemens developers, that this is, khhhm... a little disregard for your users?

![изображение](https://user-images.githubusercontent.com/32971513/183772288-0f880fee-188f-4a25-9bfb-3aadd55c8d11.png)

**Comment by SomberNight** [comment]
> New versions do not work on the seven.

As in https://github.com/spesmilo/electrum/issues/7848, recent versions of Electrum (>=4.2.0) do not run on Windows 7.
As in that thread, in short, this is because we want to bundle a Python version that is still getting security updates and those versions are not compatible with Win7. As in that thread, there might be involved workarounds but someone would have to contribute their time to implement them. And in any case, Windows 7 itself is not getting security updates anymore.

> Okay, I'm ready to use my 4.1.5, but you won't let me use the wallet that I created in version 4.3 on Linux.
> What are the considerations for this decision?

This is independent of the operating system being used.
Regarding creating a wallet file using 4.3.0 and then opening that on 4.1.5, the wallet database is versioned, and downgrades are not supported. It would impose considerable maintenance burden to restrict ourselves to a DB format that allows downgrades.

Btw, if you have access to a Linux machine and already created a wallet there, why would you then want to move that wallet file to an outdated and insecure version of Windows?

**Comment by Psychosynthesis** [comment]
> Btw, if you have access to a Linux machine and already created a wallet there, why would you then want to move that wallet file to an outdated and insecure version of Windows?

Unfortunately, Linux, although it has become much better over the past few years (in terms of ease to use), still cannot boast of having a dozens necessary programs. Even those analogues that are, this is a real squalor compared to the Windows versions.

I have to work on Linux, but using Windows 7 is much more convenient for me to use in general.

In addition, all this talkings about the "bad security of old windows versions" is a big clowning, because. due to popularity, the vast majority of new vulnerabilities are in new versions, and all old vulnerabilities have long been known and closed (in one way or another).

**Comment by SomberNight** [comment]
> In addition, all this talkings about the "bad security of old windows versions" is a big clowning, because. due to popularity, the vast majority of new vulnerabilities are in new versions, and all old vulnerabilities have long been known and closed (in one way or another).

Windows versions are not independent of each other, ultimately it is a single codebase that Microsoft has kept working on for almost 30 years now.
See for example the [Eternal Blue](https://en.wikipedia.org/wiki/EternalBlue) wormable RCE vulnerability that was publicly revealed in 2017 affecting every version of Windows since Windows 95.
> Operating system(s) affected: Windows 95, Windows 98, Windows Me, Windows NT, Windows 2000, Windows XP, Windows Vista, Windows 7, Windows 8, Windows 8.1, Windows 10, Windows 2003 Server, Windows 2003 Server R2, Windows Server 2012, Windows Server 2016

(re that specific exploit, it was so severe that Microsoft released a fix even for XP, which was much past its support period, but my point is that the idea of old versions being safe despite no guarantee of getting fixes for known vulnerabilities has limited merit)

**Comment by Psychosynthesis** [comment]
Sorry, but I don't consider the issue closed.

You are suggesting to upgrade the OS version when this is not a solution.

> See for example the [Eternal Blue](https://en.wikipedia.org/wiki/EternalBlue) wormable RCE vulnerability that was publicly revealed in 2017 affecting every version of Windows since Windows 95.
Such vulnerabilities are closed by antivirus software, this is not a problem.

**Comment by accumulator** [comment]
We can't support unsupported OSes, period. Your only options are upgrading Windows to a supported version, or keep using an older version of Electrum.

WONTFIX

**Comment by Psychosynthesis** [comment]
> support unsupported OSes

Nobody is asking you to support my OS - it works great without your help.

Make your software runs on this OS, clowns.

**Comment by Psychosynthesis** [comment]
Ok that make sense
