### ISSUE TITLE
Lightning channels: "WE_ARE_TOXIC" Unable to recover BTCs there!

### ISSUE THREAD

**Issue by fwittingham** [spesmilo/electrum#7974]
Hello I opened two LN Channels and leave some BTCs there months ago and I used a Ledger HW to create my wallet. Today I restored my W10 from a BK and updated Electrum wallet to the last version also I have BK of my channels. The problem is when open the Electrum I am unable to close or sent the funds in the channels and the status of my Channels said: 

"WE_ARE_TOXIC"

What's the problem? How I can close/recover the funds?

![Screenshot 2022-09-11 002328](https://user-images.githubusercontent.com/104582945/189512359-7cf30029-5dde-4004-9419-fa4aaaec16e5.png)

![Screenshot 2022-09-11 002929](https://user-images.githubusercontent.com/104582945/189512492-62e978c2-08fe-4afb-99e2-85d93052d652.png)

![Screenshot 2022-09-11 002531](https://user-images.githubusercontent.com/104582945/189512385-6f606bfa-8413-4494-8f8e-06b168628cb0.png)

![Screenshot 2022-09-11 002624](https://user-images.githubusercontent.com/104582945/189512426-f7006113-de8f-4ca9-9db6-c2201b9c01f1.png)

![Screenshot 2022-09-11 013033](https://user-images.githubusercontent.com/104582945/189513881-66702018-482f-4a0b-b28c-3e4fd7f60d58.png)

**Comment by ecdsa** [comment]
`WE_ARE_TOXIC` means that your wallet does not have the latest channel state.
You probably created a wallet backup by naively copying the file, which should never be done with lightning.

In this situation, you must not force close (Electrum will not allow you to do so), because if you do so the remote party can steal all funds in the channel. 

If you have lost the wallet file that has the latest state, then you should request force close of those channels 
(that option should be in the menu)

**Comment by fwittingham** [comment]
The option to force close channels is gone.

![2022-09-11 (1)](https://user-images.githubusercontent.com/104582945/189538187-876fda7a-5ad1-49a8-9b81-a49cfaab8abc.png)

**Comment by fwittingham** [comment]
Lucky I found a working wallet BK and now I closed the channels.
