### ISSUE TITLE
Missing paymentrequest_pb2.py in sourceonly tarball

### ISSUE THREAD

**Issue by sorenstoutner** [spesmilo/electrum#8001]
I am working on updating the Debian package to the current version of Electrum.  I am not the previous maintainer, but I am willing to become the maintainer of the package going forward.  As such, I am no fully aware of the procedures used by the previous package maintainer, so I apologize if there is something obvious I am missing in the following question.

I am attempting to switch the source tarball from the general release to the new sourceonly tarball (thank you for making that).  However, I have encountered a build error with [Electrum-sourceonly-4.3.2.tar.gz](https://download.electrum.org/4.3.2/Electrum-sourceonly-4.3.2.tar.gz) because it is missing electrum/paymentrequest_pb2.py.  I see that the file is present in the general release [Electrum-4.3.2.tar.gz](https://download.electrum.org/4.3.2/Electrum-4.3.2.tar.gz) tarball.

Was the omission of this file from the source tarball intentional?

**Comment by sorenstoutner** [comment]
Based on the error message it seems like this file can be generated during that package build process.  Is that the recommended procedure?

**Comment by SomberNight** [comment]
> However, I have encountered a build error with [Electrum-sourceonly-4.3.2.tar.gz](https://download.electrum.org/4.3.2/Electrum-sourceonly-4.3.2.tar.gz) because it is missing electrum/paymentrequest_pb2.py. I see that the file is present in the general release [Electrum-4.3.2.tar.gz](https://download.electrum.org/4.3.2/Electrum-4.3.2.tar.gz) tarball.
Was the omission of this file from the source tarball intentional?

Yes, it was intentional. That file is a generated file, and depending on what `protoc` is used to create it, only certain versions of the python `protobuf` package can parse it.
You can generate the file using [`contrib/generate_payreqpb2.sh`](https://github.com/spesmilo/electrum/blob/685f32750ca0d83ae1617198c085285d6a4c398e/contrib/generate_payreqpb2.sh).


related:
https://github.com/spesmilo/electrum/issues/7479
https://github.com/spesmilo/electrum/pull/7594

**Comment by sorenstoutner** [comment]
Thank you.

**Comment by accumulator** [comment]
@sorenstoutner, on IRC someone ran into this issue:

`<gasull[m]> I installed electrum on Debian.  When running it asks me to create `paymentrequest_pb2.py` with `contrib/generate_payreqb2.sh`.   I downloaded `generate_payreqb2.sh` and I get this error running it:... (full message at <https://libera.ems.host/_matrix/media/v3/download/libera.chat/7730ca97309c97c7f0adaa1e2ee168ae8b23bdc8>)
`
