### ISSUE TITLE
[BUG?] The wallet is displayed as 2fa despite 2fa disabled after recreating the wallet with a seed from 2fa wallet

### ISSUE THREAD

**Issue by WhiteBlackGoose** [spesmilo/electrum#8018]
Okay so.
1. I created a 2fa wallet
2. I decided that 2fa wasn't worth the fee so re-created a standard one with the same seed
3. It still displays 2fa

Happens on both android and linux. Is it bug? Or is it due to the nature of the seed, and I have nothing to worry about (and so 2fa is disabled, fees won't be paid)?

**Comment by SomberNight** [comment]
Yes, this is due to the nature of the seed. It is not a "standard" wallet - although the wizard lets you proceed if you select "standard" and enter a 2fa seed to restore, the wallet created will not be "standard", it only lets you proceed for convenience.

"2fa" wallets use fundamentally different Bitcoin "SCRIPT" than "standard" wallets:
- 2fa wallets use 2of3 multisig,
- standard wallets use singlesig

i.e. the difference between the two is visible to blockchain observers for example

"disabling" 2fa like you did is only there to avoid lock-in (to make sure the user can unilaterally move their coins), it is not intended as a long-term mode of operation. In fact 2of3 multisig costs slightly more in mining fees when moving coins, so if you want to avoid that, I suggest you create a standard wallet and move your coins there.
OTOH if you want, you can of course keep using your wallet as-is.

**Comment by WhiteBlackGoose** [comment]
Oh, nice, thanks for the info. But will it cost any fees for 2fa from TrustedCoin if I stay on this wallet with 2fa disabled?

**Comment by SomberNight** [comment]
no, with, the "2fa disabled" TrustedCoin is not contacted or needed at all

**Comment by WhiteBlackGoose** [comment]
Thanks :heart:
