### ISSUE TITLE
TrustedCoin server fails to sign transaction for `2fa_segwit` wallet: "Internal Server Error" (electrum 4.3.3)

### ISSUE THREAD

**Issue by Lokoshepherd** [spesmilo/electrum#8128]
Hi i have latest version Electrum but when i gonna use it send btc i get a messenge TrustedcoinExpection(Internal server error)
What this mean a update or gonna fix server error soon?

**Comment by ecdsa** [comment]
what happens if you click on the TrustedCoin icon in the status bar?
the server works for me.

**Comment by Lokoshepherd** [comment]
I get the i gonna choose 20 or 100 Payment fe

Skickat från Proton Mail mobil

-------- Originalmeddelande --------
Den 5 jan. 2023 17:19, ThomasV skrev:

**Comment by Lokoshepherd** [comment]
Ok so its not any server error do you know inget this Messenge?

Skickat från Proton Mail mobil

-------- Originalmeddelande --------
Den 5 jan. 2023 17:30, Lokoshepherd skrev:

**Comment by Lokoshepherd** [comment]
I have try on my phone to dont work get same error messenge server error

**Comment by Lokoshepherd** [comment]
It was 2fa dont work on my laptop when i disable 2fa all works with electrum

**Comment by Lokoshepherd** [comment]
Its not safe now?

**Comment by badmofo** [comment]
I'm pretty sure this caused by my service (Trustedcoin) puking on some of the 4.3.3 PSBT changes.  I'm in the process of trying to diagnose / remedy and hope to have a fix within 24 hrs.  In the meantime 2FA folks can either wait for a fix, downgrade or restore-from-seed to disable 2FA.

**Comment by SomberNight** [comment]
@badmofo Ah, sorry for that. :/

I can reproduce the server error when trying to sign a tx with a 2fa_segwit seeded wallet.
Signing works with a legacy 2fa wallet (pre-segwit).

Looks like the cause is https://github.com/spesmilo/electrum/commit/d3227d7489fe327bd40e891a517c86bd207227ec (re https://github.com/spesmilo/electrum/issues/8039).
That is, if I revert that, the server can sign.

Like the commit message says, previously for segwit inputs in a PSBT we were only putting `PSBT_IN_NON_WITNESS_UTXO`, but now both `PSBT_IN_NON_WITNESS_UTXO` and `PSBT_IN_WITNESS_UTXO` get included. The latter field can be derived from the former (and the rest of the PSBT):
https://github.com/spesmilo/electrum/blob/a4a2134db523b0e87c9bb8b2165c2dcc0a7c93f1/electrum/transaction.py#L1299-L1302

I am fairly certain you could safely discard the latter field (and require the presence of `PSBT_IN_NON_WITNESS_UTXO` - both old and new versions provide that).

**Comment by Sadbee69** [comment]
Guys pls help. give an information when will the problem with Internal Server Error and trustedcoin be solved. I have no money more and i want to eat but all my money stays on not working btc wallet with this error. I  just want to live please help to decide this problem

**Comment by badmofo** [comment]
Fix applied to the Trustedcoin server.  This bug can be closed.

**Comment by Lokoshepherd** [comment]
Thanks for fix it with one are more save 2fa Google or master key 2fa?
