### ISSUE TITLE
trezor PIN window crashes

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#813]
My trezor was working very well with electrum for a bout a month.
But after I pulled today, I can no longer send funds or sign messages.
All I get, after the trezor showing some processing screens, is "Wrong device or password".
The console stays quiet.

**Comment by MarvinOl** [comment]
This bug is back!

Electrum 2.0 has this same error! I traced it to this commit:
https://github.com/spesmilo/electrum/commit/18d16ba82c8c0a543b71d88c654a3a53d8956281

Starting from that commit when the Trezor pin entry window appears the console is flooded with:
QPixmap: It is not safe to use pixmaps outside the GUI thread
QObject::startTimer: timers cannot be started from another thread
and usually Python crashes.

2.0b3 is working perfectly.

**Comment by MarvinOl** [comment]
Just an update - the re-emergence of the bug is/was wallet related. The same old wallet file works up to the commit I wrote previously but not on a newer one. I got rid of the wallet file and let electrum create a new one for the same trezor and sync it again - this time no problems. When I switched back to the previous wallet file that works on 2.0b3 I got the same error. So it is reproducible but the "fix" is easy too.

**Comment by schulzemic** [comment]
I came across the same issue, not only for PIN but also for the password dialog. As a result, Electrum crashed each time Trezor was plugged in, where it would usually ask for the password. Deleting the old wallet file fixed it.

**Comment by MarvinOl** [comment]
Oh yes, my mistake. Of course I meant the Trezor password input dialog and not the PIN dialog that's used for transactions. Electrum crashes before an operation related to PIN can be performed with the old wallet that works up to 2.0b3. I've been using a cleanly created new wallet file but it looks like I was not the only one with the problem.
