### ISSUE TITLE
Build fail due to unknown commit for python-for-android if it's not latest commit (such as from git tag to test RB)

### ISSUE THREAD

**Issue by emanuelb** [spesmilo/electrum#8162]
Trying to compile latest version 4.3.3 to test for RB as part of WalletScrutiny https://walletscrutiny.com/ project

Resulted in error:

`error: pathspec 'a16a3dd5cf8fe0f846663bce9e248e5432dbbf2d^{commit}' did not match any file(s) known to git`

from: 
https://github.com/spesmilo/electrum/blob/acde8cd0b797dd27492099956b9c7f54b6a4ccb7/contrib/android/Dockerfile#L181-L182

Changing the commit to values from commits in between from tag 4.3.3 to latest commit return the same error. 
`e1111e82b7321d8e555bf67951525bb2381de789` from commit https://github.com/spesmilo/electrum/commit/3129fdb35804d74646fd1ff7d11fab906b7cc81a
`fb8f6fc44ef7465500c534186b0aba2a5e4ddc15` from commit https://github.com/spesmilo/electrum/commit/9704dab68b567f5e5086ccc902b3de5347e35e9d

Only changing to latest currently commit `d33e07ba4c7931da46122a32f3807709a73cb7f6` from did work.

expected result:

each commit in checkout line will work when the same commit is the HEAD of compiled repo using the dockerfile.

commands used:
```shell
git clone https://github.com/spesmilo/electrum
cd electrum/
git checkout 4.3.3
git submodule update --init --recursive
cp contrib/deterministic-build/requirements-build-android.txt contrib/android/
podman build -t electrum-android-builder-img --file contrib/android/Dockerfile $PWD
```

**Comment by SomberNight** [comment]
The problem is that the branch that contained the referenced commit https://github.com/accumulator/python-for-android/commit/a16a3dd5cf8fe0f846663bce9e248e5432dbbf2d was force-pushed, and now the commit is orphaned. GitHub still seems to have the commit, so it might be recoverable if we manage to create a new branch/tag that references the commit, however I don't know how to fetch it (my local clone does not have it).

Going forward, we should make sure we don't orphan commits needed for historical builds.

@accumulator I think instead of force-pushing these referenced branches, it's better to just create new branches. That's why I had this naming convention with the dates - except the date used to stand for the last time we rebased on top of p4a upstream, but since the qt changes we can't do that anymore, so I started adding the letter suffixes :/

**Comment by emanuelb** [comment]
> GitHub still seems to have the commit, so it might be recoverable if we manage to create a new branch/tag that references the commit, however I don't know how to fetch it (my local clone does not have it).

See github refs api to do it, details in:
https://objectpartners.com/2014/02/11/recovering-a-commit-from-githubs-reflog/
https://medium.com/git-tips/githubs-reflog-a9ff21ff765f
https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference

**Comment by SomberNight** [comment]
Thanks. I've pushed a branch that has the commit: https://github.com/SomberNight/python-for-android/tree/electrum_20210421d_v_4_3_x.

Now the historical build for 4.3.3 should work.

-----
for reference:
```
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer SECRET_AUTH_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/SomberNight/python-for-android/git/refs \
  -d '{"ref":"refs/heads/electrum_20210421d_v_4_3_x","sha":"a16a3dd5cf8fe0f846663bce9e248e5432dbbf2d"}'
```
https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference
https://github.com/settings/tokens?type=beta

**Comment by accumulator** [comment]
> @accumulator I think instead of force-pushing these referenced branches, it's better to just create new branches. That's why I had this naming convention with the dates - except the date used to stand for the last time we rebased on top of p4a upstream, but since the qt changes we can't do that anymore, so I started adding the letter suffixes :/

Ah yes.. I tried to be smart and re-apply the P4A commits we keep there on top of the `qt5-wip` branch, thereby destroying the referenced commithashes :-/

I'll keep it in mind for the future.
