### ISSUE TITLE
Bitcoin balance showing in wallet and transaction showing on blockchain but not confirmed after eight hours

### ISSUE THREAD

**Issue by saultryj** [spesmilo/electrum#8175]
I'm on electrum 4.3.4 standard wallet.

I have had several wallets in the past - over 20.

I generated a new receiving wallet this morning but I did not notice that the wallet address was displayed in red.

Someone sent me bitcoin via a purchase from a market. I can see the transaction on the blockchain. My bitcoin wallet shows a balance in line with the transaction, however, the transaction has not been confirmed after eight hours. 

I read something about the gap limit, so I increased the limit and also generated some new wallets. Still, the transaction remained unconfirmed.

I also performed something called a key sweep, which apparently will send the coins to another address in the electrum wallet. That transaction of course also remains unconfirmed.

Any suggestions about what I can do to get my electrum wallet to search for the coins in the wallet that had money sent to it after exeeding the gap limit?

**Comment by SomberNight** [comment]
> I generated a new receiving wallet this morning but I did not notice that the wallet address was displayed in red.

Where is it coloured as red? In the receive tab, red just means the address is already used, so you should not reuse it for privacy reasons. In the addresses tab, it means the address is beyond the gap limit. In either case, money received there is *not* lost.

> My bitcoin wallet shows a balance in line with the transaction, however, the transaction has not been confirmed after eight hours.

So the only problem is that the tx has not been mined yet. Everything else is unrelated.
You can either bump the fee of the stuck tx, CPFP it, or just wait it out. See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

Because of your sweep attempt (which was unnecessary), you already have an unconfirmed child tx (=cpfp), you could right-click>`Increase fee` that, if you are in a hurry.

**Comment by kiwimzki** [comment]
My has a yellow triangle and its been hours now.

Unconfirmend parent it says.

What is wrong?
I Tried to send to diffenret address and now im broke.


HELP PLEASE!!!!

**Comment by BlackHatHacker111** [comment]
> 
Message me on discord so I help you with that immediately my discord is BlackHatHacker111#2333
