### ISSUE TITLE
Error: You cannot pay that invoice using Lightning

### ISSUE THREAD

**Issue by AlistairTB** [spesmilo/electrum#8207]
I was able to figure out that my preferences for lightning network type was set incorrectly, but I figured I would document this "error" for someone else who might encounter it.

The problem was the channel was originally set up for Gossip, but the wallet preferences was set to Trampoline. Changing it back to Gossip and letting it sync resolved the error.

**Comment by ATButteaux** [comment]
Have you created your lightning channel yet? Open Channels tab and create a "New Channel". 

If this is your first time, and aren't sure how lightning works, stop and ask because it works a little differently that on-chain transactions and if you don't open a channel with an idea of how you'll use it, it can be expensive lessons. Lightning payments are limited to the amount you specify when opening your channel, but also limited by the amount you have on either side of the channel. That is, the more you spend, the less you'll be able to spend and need to receive before you can spend more. Think of it like a string with beads on it that can be pushed from one side to another, and you cannot add more beads to the string without opening a new channel or closing the existing one and reopening it with a larger number of beads on it.

**Comment by slrslr** [comment]
@ATButteaux I've never created lightning channel. I have no income in lightning, only mainnet (which you call onchain i guess). At this moment Electrum says I have not enough funds (~$70) to open lightning channel. So the error from this issue title may possibly indicate no lightning channel available, in that case developers should IMO improve error message to be more specific and helpful.

[Reading some guide on lighting channel in Electrum](https://bitcointalk.org/index.php?topic=5259973.msg54732922#msg54732922) not helped me to be confident enough in order to use Lightning feature. Mainly I am uncertain about the costs like mentioned opening channel one and steps needed to ensure payment is issue free. I guess this is out of scope of this issue.
