### ISSUE TITLE
ledger multisig change detection - warning shown by device: "change path is unusual"

### ISSUE THREAD

**Issue by lifeisadvntr** [spesmilo/electrum#8209]
hello, i've created a multisig 2of2 wallet using two ledger hardware wallets. clicking the sign button, ledger device shows "the change path is unusual 48'/0'/0'/2'/1/0". question: is it safe to approve the transaction and send?

thank you so much

wallet info in electrum:
2of2
script type: p2wsh
derivation path: m/48'/0'/0'/2'
"use change addresses" is enabled

**Comment by lifeisadvntr** [comment]
used sparrow wallet for now. no issues with ledger hardware wallet + sparrow

**Comment by SomberNight** [comment]
> clicking the sign button, ledger device shows "the change path is unusual 48'/0'/0'/2'/1/0"
> no issues with ledger hardware wallet + sparrow

Weird that sparrow wallet behaves differently. The warning comes from the ledger firmware, so it should not matter what wallet software you use.
Are you using the same derivation path with sparrow?

**Comment by lifeisadvntr** [comment]
I setup a 2/2 multisig p2wsh wallet on sparrow. defaults to derivation m/48'/0'/0'/2' for both ledger devices. it gave no warnings or issues.

**Comment by SomberNight** [comment]
Maybe sparrow wallet (i.e. HWI) is not marking the multisig change output as "change", in which case the device would treat it as just another external output, in which case the device would prompt you to confirm sending to that address and write out the full change address on screen.

Did the device prompt you to confirm the full change address on its screen (in addition to confirming the external destination address you wanted to send to)?

**Comment by SomberNight** [comment]
btw what kind of ledger device do you have, and what is the "bitcoin" app version installed on it?

**Comment by lifeisadvntr** [comment]
> Did the device prompt you to confirm the full change address on its screen (in addition to confirming the external destination address you wanted to send to)?

it did use the change address. ledger displayed the receive address and the change address also if memory serves and i had to approve both addresses.

**Comment by lifeisadvntr** [comment]
i have nano s and nano s plus both running bitcoin app v 2.0.6

**Comment by SomberNight** [comment]
Right. In that case what Sparrow/HWI is doing is strictly worse than what we are doing. If you installed a compromised/malware copy of Sparrow, it could steal all the coins that are going to your change address (as it could lie about it being a change address).

At least in our case, while you get a warning about the derivation path on the device, which would be nice to fix (but might have to be whitelisted in ledger firmware? or maybe we need to call some additional APIs), the change address is validated by the hardware device and so a compromised electrum could not steal from you.

I'll keep this issue open due to the warning displayed.

**Comment by lifeisadvntr** [comment]
l recognised the change address displayed on ledger as being the same one listed in electrum (show addresses tab). how could sparrow lie if ledger displayed the correct change address?

**Comment by SomberNight** [comment]
Imagine you only used sparrow (and not electrum) to interact with your device.
- You want to pay an invoice for 1 BTC for address A1.
- You only have a single UTXO for worth 5 BTC.
- Sparrow creates a transaction paying 1 BTC to address A1, and 4 BTC to address A2.
- Sparrow shows in its UI that address A2 is a change address that belong to your wallet.
  -  ^ this is the critical point. here you trust sparrow wallet.
- the ledger hw device tells you you are about to sign a tx that sends 1 BTC to address A1 and 4 BTC to address A2. It makes no claim about either address belonging to your wallet.
- you sign the tx and broadcast it.
- turns out address A2 belongs to an attacker who managed to compromise your host PC, and you just lost 4 BTC.

**Comment by lifeisadvntr** [comment]
yes, i'm sure this could  happen. i tried my best to find the right web site and download it then gpg --verify'd the file. i'm just a normal user and not a programmer. i try my best to verify as best i can. thanks for your attention on this issue hopefully electrum can work more smoothly with ledger devices. i've read people using trezor and jade hardware wallets with no issues together with electrum. only ledger gave out warnings. i do not have any other hardware wallets to test.

**Comment by SomberNight** [comment]
My point is that the fact sparrow does not generate the warning is because what they are doing is obviously insecure, and electrum generates the warning because the hardware device is being told about the address being a change address but the hw device is not content with its derivation path - the device will *not* display the change address on-screen but *instead* it displays that warning.

**Comment by lifeisadvntr** [comment]
once i skipped the warning on ledger, ledger+electrum did show both addresses which i approved but did not broadcast the transaction (just testing)

**Comment by SomberNight** [comment]
hmm, ok, in that case what the device is doing is weird.
IIRC there might be a "multisig account registration flow" or similar API in ledger 2.0+ that we could look into; maybe that is what's missing. I don't have time for that now though. Contributions welcome.
Nevertheless, if you ignore the warning on the device, you just regress back to the same security guarantees of using sparrow.

**Comment by SomberNight** [comment]
I have tested now and I don't get any warnings when using "bitcoin" app 2.1.0.
I do get the warnings using "bitcoin" app 1.6.5.

We already do the "multisig account registration flow" (in `>=2.1.0`), except it is done on every spend instead of just once ~globally for the wallet. This is something to improve on.
Besides that, the 2.1.0 flow works as expected and there are no warnings.
