### ISSUE TITLE
Electrum generates Lightning invoice without routing hints

### ISSUE THREAD

**Issue by accumulator** [spesmilo/electrum#8213]
If  a wallet is lightning-enabled, but has no usable channels, creating a payment request creates a lightning invoice without routing hints.

The desktop client mostly avoids the immediate problem due to these lines of code:

https://github.com/spesmilo/electrum/blob/ebb3f90e29196436c17358fdca0e2f740fd0721c/electrum/wallet.py#L2815

https://github.com/spesmilo/electrum/blob/ebb3f90e29196436c17358fdca0e2f740fd0721c/electrum/wallet.py#L2842-L2844

However, once a channel is opened afterwards, the existing LN payment request, without routing hints,  would be shown.

**Comment by ecdsa** [comment]
[Note: the desktop client also checks that the amount is lower than `num_sats_can_receive`, in order to show the invoice. 
I think the QML app should do the same.]

The issue is with invoices generated before any channel was open. A similar issue exists if you generated an invoice when your had only one channel, and you add a new channel later; the invoice will not necessarily have the right routing hints for the requested amount.

Maybe `lnworker` could re-generate invoices with same preimages and updated routing hints, when a channel is added.
(of course the payer would need to rescan it)

**Comment by accumulator** [comment]
> [Note: the desktop client also checks that the amount is lower than `num_sats_can_receive`, in order to show the invoice. I think the QML app should do the same.]

Yes, for QML that's probably sufficient, but it still leaves a gap, e.g. channel open completes while the receive dialog is open, increasing `num_sats_can_receive` (we can ignore `num_sats_can_receive` increases though, while taking into account decreases e.g. when receiving a LN payment while the receive dialog is open)

**Comment by ecdsa** [comment]
Not only channel opening/closures, but also changes in channel liquidity are a reason to update existing lightning invoices.

I am not sure if we really need to store bolt11 invoices in our list of requests; maybe we could replace that field with the payment hash, and regenerate bolt11 invoices whenever needed. Are there use cases in other clients that require stability of the signature?

**Comment by ecdsa** [comment]
Updating invoices while reusing the same preimage should also allow to transition from zero to nonzero amount.
