### ISSUE TITLE
Multisig 2 of 2

### ISSUE THREAD

**Issue by tholzing** [spesmilo/electrum#8244]
I had a multisig wallet 2 of 2.
BTC were transferred by the cosigner only.
How can this be done? 
Is this a security issue?

**Comment by SomberNight** [comment]
In a 2of2, both keys have to sign to be able to spend coins.
Maybe explain in a bit more detail what happened?
Do you control both cosigners, or is it you and a friend, etc.

**Comment by tholzing** [comment]
It was me and a supplier. The supplier just got the whole bunch of money - I don't know how. He had one key - i had the other. Is it possible to crack the electrum wallet?

**Comment by SomberNight** [comment]
Please give more details.
How exactly was the multisig wallet created, step by step.

**Comment by ecdsa** [comment]
First, maybe you could provide a transaction ID so that we can check that you were actually using a multisig wallet, and we do not just have to trust you on that. We don't know you, we have no way of telling how competent you are, and so we have to assume that you are just as competent as the average user.

Secondly, how do you know that the supplier got the money? if they stole it, they would probably not make it obvious that the money went to them, unless they were really dumb.
 
Thirdly, if the supplier really is the person who stole the money, then they only need one seed (yours). in other words, using multisig as escrow does not protect you more than single-signature from the other signer. did this supplier also help you setup the wallet?

**Comment by SomberNight** [comment]
closing. nothing actionable

**Comment by tholzing** [comment]
Sorry - was away for business some days.
I hope and I would appreciate your analysis.

transaction number:
a3c8cf8da7c8b9425e6078a99dfb2e60adf49fe73f68408268b9dfecd5644c74

An yes - the BTC are definitely transferred and not available any more in the wallet.
The BTC were transferred to several different other addresses.
