### ISSUE TITLE
qml: use in-app virtual keyboard for entering seed? unclear if system keyboard is safe.

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8256]
I think we should use an in-app virtual keyboard on the seed-entry screen on Android, in the qml app.
kivy did the same.
At the very least I want a discussion to take place about this, hence this issue :)

<details>
 <summary>pics</summary>

![pic1](https://user-images.githubusercontent.com/29142493/225957325-2ff5d2d7-0a4c-4ac1-a938-a6d1e2201c0a.png)
![pic2](https://user-images.githubusercontent.com/29142493/225957333-d58f1787-4b33-4f74-bec6-7450c01ac99c.png)
</details>

The user might have installed any kind of custom keyboard app (swiftkey/etc), that might exfiltrate entered text either accidentally or maliciously. In general I don't think we can trust the external keyboard app for this.

Alternatively, I wonder if there are flags we can set for Android so that it brings up some trusted barebones default keyboard.

Relatedly, when testing on Android using a keyboard app that has "predictive text" features, I see that on most text fields such as setting a tx label or naming a wallet file the keyboard has predictive text enabled, but on the seed-entry screen the keyboard seems to have predictive text disabled (which is promising). I am curious, how exactly does this work / where is it set?

Re what other wallets are doing, e.g.
Phoenix uses a virtual keyboard,
but bluewallet and SBW use the system keyboard.

**Comment by accumulator** [comment]
Qt can set hints for the virtual keyboard, see https://github.com/spesmilo/electrum/blob/231ea5d03b744957fdfd8a2774cd7bd075d95a0a/electrum/gui/qml/components/controls/SeedTextArea.qml#L80

This is passed to android and eventually to the virtual keyboard implementation. I don't know if or how it is enforced.

**Comment by ecdsa** [comment]
from the Qt docs:
> Qt.ImhSensitiveData - Typed text should not be stored by the active input method in any persistent storage like predictive user dictionary.

I don't think that ensures that the keyboard will not misbehave. 
It would be better if there was a flag that imposes the system's default keyboard, and not a custom one.

**Comment by accumulator** [comment]
Instead of implementing our own in-app keyboard, there's also the [Qt Virtual Keyboard](https://doc.qt.io/qt-5/qtvirtualkeyboard-deployment-guide.html), which if I understand it correctly is pure-Qt and doesn't use the android virtual keyboard. 

Pros:
- user input is kept within the application
- more advanced than we can reasonably implement, e.g. other keyboard layouts, other input methods (?) like chinese, korean, japanese etc

Cons:
- application wide, so we have to use this keyboard for all text input and can't use the android vkbd
- unknown limitations?
