### ISSUE TITLE
Balance shows but i cannot spend or send anything 

### ISSUE THREAD

**Issue by paybtc09** [spesmilo/electrum#8270]
First i had a double spend issue and it was unconfirmed for a long time then i updated electrum and i cannot access my balance.

**Comment by SomberNight** [comment]
More details needed.
For example, at the very least, please share a screenshot of any error you see.

**Comment by paybtc09** [comment]
![electrum snip](https://user-images.githubusercontent.com/128423578/226456704-006c7b9b-d217-4d07-b013-1c32fd32c884.PNG)

**Comment by paybtc09** [comment]
the balance is not available after switching servers and updating

**Comment by paybtc09** [comment]
left ample time for synchronization i think anyway or could this take hours to propogate?

**Comment by paybtc09** [comment]
im connected and if i try to send a transaction it will not send

**Comment by paybtc09** [comment]
ok its very odd, i sent one transaction as a test it did not propagate to the sent or history and on the second one it did. i know this forum is not for questions but could i ask one? why does it keep saying unconfirmed parent?

**Comment by paybtc09** [comment]
why does my balance have a red pie graph to the left of it?

**Comment by paybtc09** [comment]
the main balance of my wallet was confirmed days ago

**Comment by paybtc09** [comment]
it this because i just updated my electrum?

**Comment by SomberNight** [comment]
The pie chart being fully red means all your balance is unconfirmed currently. If you click it, you see more details.
See https://en.bitcoin.it/wiki/Change

Based on the history tab in your picture, you have several unconfirmed (pending) transactions. Whatever error you might have seen originally, might be related to that - no point to guess what it was; next time take a picture of it or write it down. Clearly if you are asking for help due to some error, you should at least provide the error text. :)

**Comment by paybtc09** [comment]
im assuming the pie chart will turn green once confirmed?
