### ISSUE TITLE
February 13 my btc was stolen

### ISSUE THREAD

**Issue by estebanquito19714** [spesmilo/electrum#8279]
February 13 my btc was stolen.  this adress stolen all my btc bc1q5nkxs4dazg8xpmae3dvfvxqqcy8y2y2vr0mnmg.  
I have the latest electrum update loaded on a desktop pc with updated antivirus. I have the seed in a paper, alphanumeric password, etc.  How it could happen? my password was not needed to be able to make the transfer? who takes charge of canceling that operation?
Someone is going to give me a solution or I must go out on all social networks to proclaim that electrum security is a lie!!

**Comment by ecdsa** [comment]
Nobody will cancel that operation. Nobody is in charge of Bitcoin.

A software wallet is only as secure as the operating system on which you are using it. Since you are using an antivirus, I imagine that you are using Windows. If Windows was secure, there would be no need for antivirus.

If you want to use Electrum on an insecure platform, you should use it with a hardware wallet, or a with two factor authentication.

If you want to do something useful, bring your computer to a security specialist who will investigate whether your machine has malware, and whether that malware is specifically targeting Electrum.

**Comment by ian76** [comment]
I think, i have a similar problem. I suppose, i sent too much in a transaction, because i clicked the "Max" Button and didn't realize, that i sent the whole content of the wallet. Now, i must contact the recipient, to send back the overrun.

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by SomberNight** [comment]
closing. nothing actionable
