### ISSUE TITLE
qml: error logged when opening qetxfinalizer

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8330]
To reproduce:
- on qml main screen, click Send
- Paste an onchain address
- enter an amount, and click Pay

An error gets logged:
`221.22 | E | gui.qml.qetxfinalizer | 'NoneType' object has no attribute 'wallet'`

With this simple patch, we can get the full traceback:
```patch
diff --git a/electrum/gui/qml/qetxfinalizer.py b/electrum/gui/qml/qetxfinalizer.py
index 36e129ddae..7ef605ecbb 100644
--- a/electrum/gui/qml/qetxfinalizer.py
+++ b/electrum/gui/qml/qetxfinalizer.py
@@ -311,7 +311,7 @@ class QETxFinalizer(TxFeeSlider):
             self.validChanged.emit()
             return
         except Exception as e:
-            self._logger.error(str(e))
+            self._logger.exception(str(e))
             self.warning = repr(e)
             self._valid = False
             self.validChanged.emit()
```

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qml/qetxfinalizer.py", line 307, in update
    tx = self.make_tx(amount = '!' if self._amount.isMax else self._amount.satsInt)
  File "/home/user/wspace/electrum/electrum/util.py", line 462, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/user/wspace/electrum/electrum/util.py", line 458, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/electrum/gui/qml/qetxfinalizer.py", line 296, in make_tx
    coins = self._wallet.wallet.get_spendable_coins(None)
AttributeError: 'NoneType' object has no attribute 'wallet'
```
The error looks harmless, I guess it gets resolved in a later update() call.

**Comment by accumulator** [comment]
The `finalizer` gets two properties on initialization in WalletMainView, `wallet` and `canRbf`. `canRbf` sets `rbf` property to `True` unconditionally, which triggers an `update()` call. Since the order of setting these two properties is decided by QML, we can get an undefined `wallet` property the moment `update()` is called. Since we know `wallet` will be set after, I think we can simply add a check to `update()` and return when `wallet` is still `None`.
