### ISSUE TITLE
restore_wallet_from_text access from cli to store wallet in memory

### ISSUE THREAD

**Issue by matryosha** [spesmilo/electrum#8373]
I found that [**restore_wallet_from_text**](https://github.com/spesmilo/electrum/blob/57ae933582e44eb775ddbeab278b8e25d9aaf2d4/electrum/wallet.py#L3627) allow path to be None so that a wallet will be restored in memory. But as I can see there is no way to get that behavior from the cli. 

Is this works as intended and I miss something?

**Comment by SomberNight** [comment]
That is correct. IIRC the path=None option was added because a user asked for it and it was trivial to add, and we realised it also comes in handy in tests. Its current use case is to be able to call `restore_wallet_from_text` from python, e.g. when using electrum as a library.

It is not exposed to the CLI atm as that is not so easy. First of all, note that in its current form, it does not make sense to expose it: there is a `restore` command, and there is a `load_wallet` command (which takes a path). You would pretty much need a restore_and_load command if you wanted to create and use a wallet in-memory. Also, the daemon manages wallets internally based on paths, and an in-memory wallet naively does not have one, so some rewriting or hackery would be needed there.

What is your use case?

**Comment by matryosha** [comment]
That answers my question.

My use case goes as follows:
 I interact with electrum via rpc and at deployment time I plan to configure and start the daemon so that it works independently from deployment cycle of my application. 
And at the init stage of the application I want to give a master key to the daemon so that it could be further utilized with the provided wallet. 

So, I was just hoping that using in memory wallet would simplify that init stage by calling close_wallet and then restore one provided by the app. Now I see deployment cycle as my app like this: I should close wallet and remove wallet from its path and then restore by text in case wallet provided by the app has changed. 

Thanks for the quick response. Issue can be closed now
