### ISSUE TITLE
channel_db load_data failure on python3.11

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#8403]
On Python 3.11, channel_db throws the following error:
```
Traceback (most recent call last):
  File "electrum/electrum/sql_db.py", line 56, in run_sql
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "electrum/electrum/util.py", line 470, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "electrum/electrum/util.py", line 465, in do_profile
    o = func(*args, **kw_args)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "electrum/electrum/channel_db.py", line 739, in load_data
    node_info, node_addresses = NodeInfo.from_raw_msg(msg)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "electrum/electrum/channel_db.py", line 191, in from_raw_msg
    return NodeInfo.from_msg(payload_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "electrum/electrum/channel_db.py", line 171, in from_msg
    validate_features(features)
  File "electrum/electrum/lnutil.py", line 1340, in validate_features
    features = LnFeatures(features)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 714, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1128, in __new__
    ve_exc = ValueError("%r is not a valid %s" % (value, cls.__qualname__))
                                                  ^^^^^
ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit
```

The error is thrown because some nodes `features` byte string is very big and contains spaces, something like this:
```
b' \x00\x00...\x00 \x00x00...\x00\x88 \x80\x08\x8ai\x82'
```
Which when ran through `int.from_bytes` returns a huge integer. This huge integer is then passed into LnFeatures constructor, which tries to decode it, finds out-of-range values, and then attempts to construct a ValueError.

In Python 3.10 that worked fine, however in Python 3.11 large integer check [was introduced to prevent DoSes](https://github.com/python/cpython/issues/95778), so now this throws an error.

Some offending node aliases:
```
ergvein-fiatchannels
test-mainnet
arakis
```

I solved it locally with the following patch:
```
diff --git a/electrum/channel_db.py b/electrum/channel_db.py
index 4331a56e5..55b4b8195 100644
--- a/electrum/channel_db.py
+++ b/electrum/channel_db.py
@@ -163,6 +163,8 @@ class NodeInfo(NamedTuple):
     @staticmethod
     def from_msg(payload) -> Tuple['NodeInfo', Sequence['LNPeerAddr']]:
         node_id = payload['node_id']
+        if len(payload["features"]) > 256:
+            raise IncompatibleOrInsaneFeatures(f"len(features) = {len(payload['features'])}")
         features = int.from_bytes(payload['features'], "big")
         validate_features(features)
         addresses = NodeInfo.parse_addresses_field(payload['addresses'])
```

P.S. I see there are a lot of nodes with 253 bytes in their `feature` vectors. Any idea why that could happen?

**Comment by SomberNight** [comment]
Thanks for this report.

> In Python 3.10 that worked fine, however in Python 3.11 large integer check https://github.com/python/cpython/issues/95778, so now this throws an error.

Apparently this change was deemed a security fix and was backported to all supported branches of CPython (going back to 3.7). i.e. it affects ~all versions of python (if sufficiently updated with bugfix patches), not just 3.11

> Some offending node aliases:
> ```
> ergvein-fiatchannels
> test-mainnet
> arakis
> ```

The features bits set by some of these nodes:
```
(1, 7, 8, 11, 13, 14, 17, 19, 23, 27, 45, 32973, 52973)
(1, 7, 8, 11, 13, 14, 17, 19, 23, 27, 39, 45, 55, 32973, 52973)
```

> P.S. I see there are a lot of nodes with 253 bytes in their feature vectors. Any idea why that could happen?

Note that the valid [merged-into-spec features](https://github.com/lightning/bolts/blob/50b2df24a27879e8329712c275db78876fd022fe/09-features.md) currently only go as high as ~51.
However the spec does not specify how to choose feature bits for experimental stuff, so I guess some people are using values in the 50k range. The only limit imposed by the spec on the length of the features bitvector is an implicit one due to the max message size: every msg must be smaller than 65KB, and the features bitvector needs to fit inside the init message, hence it can be up to ~524K bits.
(note that the features are not stored in a sparse representation in the init message and in gossip messages, so if many nodes set such high feature bits, that would noticably impact the size of the gossip).

-----

Anyway, our current implementation of LnFeatures is subclassing IntFlag, and it looks like it does not work well for such large integers. I've managed to make IntFlags reasonably in python 3.11 by overriding __str__ and __repr__ (note that in cpython it is apparently only the base2<->base10 conversions that are slow, power-of-2 conversions are fast, so we can e.g. use `hex()`). However in python 3.10 and older, enum.py itself seems really slow for bigints, e.g. enum._decompose in python 3.10.

Try e.g. this script, which is instant in py3.11 but takes minutes in py3.10:
```py
from enum import IntFlag
class c(IntFlag):
    known_flag_1 = 1 << 0
    known_flag_2 = 1 << 1
    known_flag_3 = 1 << 2
    if hasattr(IntFlag, "_numeric_repr_"):  # python 3.11+
        _numeric_repr_ = hex
    def __repr__(self):
        return f"<{self._name_}: {hex(self._value_)}>"
    def __str__(self):
        return hex(self._value_)


a = c(2**70000-1)
q1 = repr(a)
q2 = str(a)
```

AFAICT we have two options: either we rewrite LnFeatures so that it does not use IntFlag (and enum.py), or, for the short term as workaround, we could just reject very large feature bits.
For now, I've opted to the latter, rejecting feature bits over 10k.

(note that another option is bumping the min required python to 3.11, in which case with the overrides shown above (and added in https://github.com/spesmilo/electrum/commit/c9536180c50c230af43aa75bd22c7bdd97cc70b0), the performance looks perfectly fine)
