### ISSUE TITLE
Debian Snapshot Archive Extremely Slow / Unavailable

### ISSUE THREAD

**Issue by CoryRamsey** [spesmilo/electrum#8496]
I'm on the second day of trying to do a wine build. The snapshot archive has been very slow, to the point of making it impossible to build. I'm on hour 5 of apt update with several timeouts already on my latest attempt. Obviously, I know no one here is in control of the snapshot repo, but I'm wondering if there is a known mirror for snapshots required for Electrum. Specifically, the [debian/20230317T205011Z](https://snapshot.debian.org/archive/debian/20230317T205011Z) archive is what I'm referring to.

**Comment by SomberNight** [comment]
Hi. This is a known issue. :/
Unfortunately `snapshot.debian.org` is often very slow and keeps timing out.
One alternative mirror is `snapshot.notset.fr`, but this does not work for the wine build specifically as it does not mirror the `binary-i386` parts.

First of all, note that if you just want to build for yourself, you don't need to use these snapshot apt sources. You can just switch back to debian upstream. The snapshot mirrors are only needed for the reproducible builds.

If you do want reproducibility, then note that the `ELECBUILD_NOCACHE=1` option is not expected to be needed anymore.
Setting that forces a rebuild of the docker image, which was needed to properly test historical reproducibility in the past, but since we switched to the snapshot apt sources, I expect it's redundant. So you can try without setting that -- and then at least you are only at the mercy of the snapshot apt mirrors once, and then the docker image will get cached.

**Comment by CoryRamsey** [comment]
I figured that was likely the case. I appreciate the response and additional info. That confirms what I thought I had sorted out while having plenty of time to poke around the build scripts and Dockerfile.

It's hard to complain about the snapshot archive. That's a pretty ridiculous thing to host. I think I'll make a local mirror once the load seems to lighten up for them. Thanks again.
