### ISSUE TITLE
Partial signed transaction - qrcode warning

### ISSUE THREAD

**Issue by mmmfreedom** [spesmilo/electrum#8535]
Electrum v 4.4.5  isn't generating correctly the qrcode for a partial signed transaction.

![qr](https://github.com/spesmilo/electrum/assets/139495453/0d2d8e72-3c61-4e2d-9931-8769d14ed7a9)

_Warning: Some data (prev txs / "full utxos") was left out of the QR code as it would not fit. This might cause issues if signing offline. As a workaround, try exporting the tx as file or text instead._

Transaction text has less than 700 characters and qrcodes can support 4.000.

Qrcode content purposefully hidden.
OS: Windows 11.

**Comment by SomberNight** [comment]
The relevant code is here: https://github.com/spesmilo/electrum/blob/1767d26de92fd61726b28a9035abb6b5b7f2d0d4/electrum/transaction.py#L949
Due to limited capacity of qr codes, we don't put full input utxos in qr codes, only witness utxos. For consistency, we do this for each input and always, not just when space would actually run out. Note that it is difficult to scan large qr codes close to the max capacity, so it is not desirable to always try to create qr codes near max capacity.

Hence it is normal that there is space left in the qr code you saw.
