### ISSUE TITLE
Non-default sighash type

### ISSUE THREAD

**Issue by ik105** [spesmilo/electrum#8687]
I created an unsigned transaction in Sparrow wallet with SIGHASH_NONE, then imported the psbt into Electrum and was surprised that Electrum didn't show any warning about the unusual sighash type. It becomes possible to steal coins with malware even from cold or multisig storage. 

Please add a warning when signing a transaction with a non-default sighash type.

**Comment by SomberNight** [comment]
Good point. Do you know how it works/looks in other programs when trying to sign a tx with a non-sighash_all input?

**Comment by ik105** [comment]
Sparrow wallet doesn't warn, but there is an option to select the type of sighash (I don't think it's enough, you can ignore it). Trezor seems to just not accept such transactions. Ledger shows "Non-default sighash - > Reject if you're not sure -> Continue/Reject". Coldcard shows this:

![photo_2023-11-13_20-26-23](https://github.com/spesmilo/electrum/assets/38519936/ec7de082-6bc7-47ea-87a7-2b19decdcc17)

**Comment by ecdsa** [comment]
I guess there is no use case for `sighash_none` at the moment, so we can forbid it.
There are use cases for `sighash_all|anyonecanpay`

**Comment by RobinLinus** [comment]
There is a use case for `sighash_none`: decaying multi-signatures. E.g., if you have a 2-of-3 multisig, signing a `nLocktime` transaction with one of your keys using `sighash_none` effectively decays your 2-of-3 into a 1-of-3 once the locktime opens.

Is there any way to allow it in Electrum?

**Comment by stwenhao** [comment]
> I guess there is no use case for `sighash_none` at the moment, so we can forbid it.

There are use cases for sighash_none, for example funding a puzzle: https://mempool.space/tx/8349df0753e80cce322322f1b76789e1d0fd6693aed2f4de4e49576423081ae7

In this case, bc1q9nw84cph4dn2pw78pnaec68c82h7pxvv55cla8 used SIGHASH_NONE, to fund a puzzle, and bc1qts0jh2d2nesmketmw3thedwrx939k2tqu04gy90x9hd4049g4uhs83ltjx used SIGHASH_ANYONECANPAY, to accept funds from anyone. And that combination is safe, because the signer, who used SIGHASH_NONE, can be 100% sure, that coins won't move anywhere, as long as the puzzle won't be solved. Also, the signer of SIGHASH_ANYONECANPAY can be 100% sure, that if the sponsor will disappear for whatever reason, then other coins can be used, to do the same thing, so grinding the solution from scratch won't be needed.
