### ISSUE TITLE
There should be a way to export private keys on mobile

### ISSUE THREAD

**Issue by danielabrozzoni** [spesmilo/electrum#8705]
Hey,
Sorry if this is not the right place to ask this. Let me know if I should ask somewhere else :)

I'm helping a user with recovering their funds, they have a wallet on Electrum mobile with 3 private keys imported (I suppose WIF keys, they told me it was a legacy paper wallet), they see the funds on the wallet and they were also able to spend part of it some time ago, but right now, at the time of spending, electrum only gives back an unsigned PSBT asking "to show this to the cosigners".
The user doesn't have a backup of the keys anymore.

I'm trying to investigate the problem, I have a few questions:

- This is the wallet details screen, I think the keys are imported since otherwise a "watchonly wallet" label would be shown, is this correct?
![50d3c863-449e-428a-90cb-194925161652](https://github.com/spesmilo/electrum/assets/25042473/b5dcc4f8-4df2-445f-8c5f-117619bb3f41)
- Can I somehow export the private keys? Or, at least, can I export the corresponding public keys? So that I can check if they match the utxos electrum tries to spend from
- I'm not sure how android really works - what if I modified the electrum app to show the private or public keys and ask the user to install it, would we be able to see the wallet, or would android wipe the wallet data, or even block us from installing the modified app?

Any tip would be greatly appreciated, thanks!

**Comment by SomberNight** [comment]
> This is the wallet details screen, I think the keys are imported since otherwise a "watchonly wallet" label would be shown, is this correct?

Yes. The lack of a "watch only" label suggests the wallet has private keys.

> Can I somehow export the private keys? Or, at least, can I export the corresponding public keys?

click top left (wallet name) > "Addresses" > select an address

There should be an item "Private key", and you should see "Tap to show private key" there.
The pubkey is also shown there.

> I'm not sure how android really works - what if I modified the electrum app to show the private or public keys and ask the user to install it, would we be able to see the wallet, or would android wipe the wallet data, or even block us from installing the modified app?

I'm assuming the user installed a "release" build and not a "debug" build. (always the case unless they built their own apk or downloaded it from the CI)  For "debug" builds, you can use adb (the android debugger) and read/write the data directory of the application. For "release" builds, you would need a rooted phone and get root permissions for this -- typically it is not possible to root a phone without wiping it first.

Without root, for a release build application, only the application itself has permissions to access its own data directory (that contains the wallet files among other things).

Re installing a modified electrum, Android uses a TOFU model. Applications have a string id ("package name"), an int version number, and they are signed by the developer's RSA key. If a phone already has an app with a given package name installed, and you are trying to install a new apk with the same package name (because you want access to the same data directory), then the new apk needs to have a >= version code and needs to be signed by the same RSA key.

All that is to say, in practice, only the person who has the original RSA key can publish updates, and you will not be able to access the contents of the data directory without considerable effort.

**Comment by SomberNight** [comment]
>> Can I somehow export the private keys? Or, at least, can I export the corresponding public keys?
>
> click top left (wallet name) > "Addresses" > select an address
> 
> There should be an item "Private key", and you should see "Tap to show private key" there.

Ah sorry, I've just realised this is only on master and has not been released yet. :/
(https://github.com/spesmilo/electrum/pull/8438)

**Comment by ROSAISS81** [comment]
otro lugar
***@***.*** Rosa Isela Pérez Martínez

**Comment by SomberNight** [comment]
There is now a beta release (4.5.0b1) available on the website, on the download page, if you click "Previous releases" at the top.

**Comment by danielabrozzoni** [comment]
Hey @SomberNight, thanks again for your help. We investigated a bit more using the new "show private key" button, we were able to spend some funds, but there's still one utxo for which:
- electrum shows the "imported" label (and no "watchonly" label), as we were saying above
- trying to spend it, electrum creates an unsigned PSBT, and prompts the user to "show this to the cosigners" 
- clicking on "show private keys", nothing is shown

To me, it seems that Electrum doesn't have the private key anymore, but act as if it does. Do you have any tips on how to investigate this? Is there any better channel for this type of issue? Privately, we would be able to share more info about public keys, showing screenshots, etc, but of course continuing the conversation here or in another issue is fine too :)

**Comment by accumulator** [comment]
I can reproduce this behavior when manually removing the private key from the `keypairs` dict within `keystore` in the wallet file (wallet file on desktop, unencrypted)

I remember there was a regression writing keystore after the jsonpatch branch was merged (fixed in 85f13cc6ea23d3410818cd3d6b3488a5d44908ea IIRC), but as far as I know, this regression was never in a released version.

**Comment by accumulator** [comment]
Added logging of any issues retrieving the private key in 9d29e6e03cdab1219983bc03d3487d0bd0c22d26

Note that a missing private key/empty string will manifest as `InvalidPassword`.
