### ISSUE TITLE
Scammer system

### ISSUE THREAD

**Issue by gkhanbey** [spesmilo/electrum#8765]
I opened the channel and after 2 hours it was force closed by itself and I deposited 200 000 satoshi and the money that came back was 88 000 satoshi and it said it was not approved. Be careful of the fraudulent system, they can defraud you too.

**Comment by SomberNight** [comment]
Do you have [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging), so that we can try to find out why the channel got force-closed?
Can you share the channel id or the funding txid/closing txid? Ideally can you share a screenshot of the transaction details (in Electrum) of the closing transaction?

**Comment by gkhanbey** [comment]
When will my money be approved and will the remaining money arrive?

**Comment by gkhanbey** [comment]
nice nice scammer is closed

**Comment by Ericrowlowland** [comment]
Oh yeah is still not late my dear I can help you recover it back and track
the scammer fast….click on the link and send me a text on Facebook massage
thanks


https://www.facebook.com/lucky.715513?mibextid=LQQJ4d

**Comment by SomberNight** [comment]
As long as you don't answer my questions, there is no proof you even had a channel at all.
Also, Electrum is free open source software using the MIT license, i.e. the software is provided as-is.
