### ISSUE TITLE
WE_ARE_TOXIC Lightning channel status

### ISSUE THREAD

**Issue by mysterybear** [spesmilo/electrum#8770]
Hi,

I'm basically having the same issue as #7974 except the person in that issue was able to resolve it without resolving it sorta thing, and I'm not

there's no option to close/recover the channel or anything in the UI

I'd really appreciate some guidance working through this issue in lieu of that!

**Comment by SomberNight** [comment]
More context is needed. What have you done to get your channel(s) into that state?

The reason there is no option to close the channel in the GUI is because it is not safe to close it. If you closed it with that wallet file, it would be considered cheating, and the channel counterparty could take all the money.

The person in the referenced issue got into this state by manually copying the wallet file on the file system, and then using both copies. That is not safe to do. To recover, what they did is to open the other copy, and close the channel there.

**Comment by mysterybear** [comment]
@SomberNight thanks for the quick response!

I rsync'd my home directory from an old laptop to a new laptop D:

**Comment by nzb-tuxxx** [comment]
Had the same problem after a filesystem crash and restoring from a recent backup. Here is how i solved to force-close the channel:

1. Note your seed (backup --> seed)
2. Close electrum and move away .electrum config folder (mv ~/.electrum ~/.electrum_bak)
3. Recover wallet from seed
4. Force-close option is now available for the existing channel

**Comment by mysterybear** [comment]
Thanks @nzb-tuxxx this gives me the option to force-close the channel

If I try to pay an invoice or a Lightning address (without force-closing the channel), it says "You cannot pay that invoice using Lightning"

![image](https://github.com/spesmilo/electrum/assets/50906986/d340642a-5b2f-4c40-add6-8ba8a689c7b3)

not sure why and not sure whether to close this issue now!

**Comment by nzb-tuxxx** [comment]
In my understanding: Thats because static channel backups can only be used to force close channel not to reuse channels again. Either you have the most recent channel state and can reuse the channel or if you have only an old (toxic) state than the only way to get back your money is by giving your channel partner the information to close the channel for you by sending them the force close request.

If you open the channel you will also see this information:

![image](https://github.com/spesmilo/electrum/assets/143939649/aab3c367-1a90-4b80-9629-e2ef7142fc2c)

**Comment by nzb-tuxxx** [comment]
I was able to force close the channel after re-importing the seed and got my money back on-chain but i had to pay high closing fees (about 10$)

**Comment by SomberNight** [comment]
With https://github.com/spesmilo/electrum/pull/8814, the GUI now allows to "request force-close" for WE_ARE_TOXIC channels.
