### ISSUE TITLE
RuntimeError('DataError: bytes overflow')

### ISSUE THREAD

**Issue by MButcho** [spesmilo/electrum#8813]
After updating Electrum to v4.5.0, I am unable to confirm 2/3 multisig transaction with Trezor device, getting error below:
![image](https://github.com/spesmilo/electrum/assets/41790777/6af75274-588b-4181-a08e-3748bca57981)

Workaround was restoring wallet file and use v4.4.6

Logs:
```
20240115T165915.657368Z |    ERROR | gui.qt.main_window.[wallet_1] | on_error
Traceback (most recent call last):
  File "electrum\plugins\trezor\clientbase.py", line 259, in sign_tx
    return trezorlib.btc.sign_tx(self.client, *args, **kwargs)
  File "trezorlib\tools.py", line 308, in wrapped_f
  File "trezorlib\btc.py", line 419, in sign_tx
  File "trezorlib\tools.py", line 308, in wrapped_f
  File "trezorlib\client.py", line 268, in call
trezorlib.exceptions.TrezorFailure: DataError: bytes overflow

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "electrum\gui\qt\util.py", line 1044, in run
  File "electrum\wallet.py", line 2551, in sign_transaction
  File "electrum\plugins\trezor\trezor.py", line 96, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx)
  File "electrum\plugin.py", line 406, in wrapper
  File "electrum\plugin.py", line 399, in run_in_hwd_thread
  File "concurrent\futures\_base.py", line 458, in result
  File "concurrent\futures\_base.py", line 403, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "electrum\plugins\trezor\trezor.py", line 306, in sign_transaction
    signatures, _ = client.sign_tx(self.get_coin_name(),
  File "electrum\plugin.py", line 406, in wrapper
  File "electrum\plugin.py", line 396, in run_in_hwd_thread
  File "electrum\plugins\trezor\clientbase.py", line 258, in sign_tx
    with self.run_flow():
  File "electrum\plugins\trezor\clientbase.py", line 85, in __exit__
    raise RuntimeError(str(e)) from e
RuntimeError: DataError: bytes overflow
```

**Comment by SomberNight** [comment]
I cannot reproduce this.
If it works for you with electrum 4.4.6 but not with 4.5.0, then the relevant change must be upgrading trezorlib from 0.13.4 to 0.13.8.

Could you provide more details about your setup, and how to reproduce?

In menubar>`Wallet`>`Information`,
- what is script type?
- what are the keystores/cosigners listed? I don't need the master public key, just the types, e.g. `hw[trezor]`?

Specifically what trezor model do you use, and what is the version number of the firmware it is running (to find this, click the trezor icon in the bottom right)?

Further, is the transaction you are trying to sign interesting in some way? For example, is it perhaps very large in terms of bytes, due to having lots of inputs/outputs? (or maybe the inputs themselves are large, due to being batched exchange withdrawals/etc)

**Comment by MButcho** [comment]
Here is requested info:
- Scrypt type: p2wsh
- cosigner 1: hw[ledger]
- cosigner 2: hw[jade]
- cosigner 3: hw[trezor] - model one

**Comment by MButcho** [comment]
Updated to v4.5.2 and it works fine 👍🏼

**Comment by SomberNight** [comment]
I don't think anything related was changed between 4.5.0 and 4.5.2 though...

**Comment by MButcho** [comment]
Interesting, but it works, I used Jade and then Trezor Nodel 1 and it worked now.

**Comment by italianbtc1** [comment]
Hi,

I've got the same problem. I can't sign a transaction using my trezor. Have not made a transaction in about 6 months and wanted to test the 2/3 multisig set up and it gives me this error message. RuntimeError('DataError: bytes overflow'

Anyone that could help me?

**Comment by SomberNight** [comment]
@italianbtc1 could you answer the questions in https://github.com/spesmilo/electrum/issues/8813#issuecomment-1898745905 ?

@MButcho was using Windows, based on the file system paths in the traceback. What OS are you using?

Also, could you test if the "show address on Trezor" functionality works for the wallet that produces the error?

**Comment by italianbtc1** [comment]
I'm using a Mac OS. 

It shows the correct adress when asking for receiving funds. 

Trezor model 1, firmware 1.12.1 . Script type p2wsh

The previous transaction I saw trying to send was quite large +800 bytes, but now I'm trying to send another transaction with about 250 bytes, using 4.5.2 and it now showed the correct amount to be sent but failed with the same error message when trying to finalize the transaction. So same error but at different stages.

plugins.get_plugin("trezor").is_bridge_available() - it gives me false on both 4.4.6 and 4.5.2 but I just now was able to send another transaction from 4.4.6 that did not work on 4.5.2

**Comment by Omen336** [comment]
Hello, I have the RuntimeError('DataError: bytes overflow') error now. I upgraded from Electrum v4.4.6 to v4.5.2. I was able to sign transaction before the update. I actually did some transactions a few mins before the update. Please see details below.

OS: Windows
Electrum version: 4.5.2
Wallet: 2/3 MultiSig
HW: Trezor Model One.
HW Firmware: 1.12.1 (I updated to the latest to try to fix it)
plugins.get_plugin("trezor").is_bridge_available() = False
"show address on Trezor" = This does work.

If there is anything else you need to know please let me know. Thanks

**Comment by SomberNight** [comment]
I have tried signing some transactions with a 2of3 p2wsh multisig wallet, with a trezor one cosigner (fw 1.12.1), but I cannot reproduce. I have even tried some fairly large transactions with around 60 inputs.

@matejcik any idea what this could be?

**Comment by Omen336** [comment]
> I have tried signing some transactions with a 2of3 p2wsh multisig wallet, with a trezor one cosigner (fw 1.12.1), but I cannot reproduce. I have even tried some fairly large transactions with around 60 inputs.
> 
> @matejcik any idea what this could be?

My transaction only had 2 UTXOs and is 293 bytes.

**Comment by italianbtc1** [comment]
Could there be a prblem with the wallet file when it is converted?

**Comment by matejcik** [comment]
"Bytes overflow" message is coming from nanopb and it means that a length of some variable-length field exceeded the expected size. This is the relevant list of limits: https://github.com/trezor/trezor-firmware/blob/main/legacy/firmware/protob/messages-bitcoin.options#L32-L77

i was under the assumption that the limits are calculated so that a valid Bitcoin transaction, even multisig, will fit.
esp. if the total tx size is 293 bytes. the only option comes to mind is Electrum stuffing in some data that don't belong? :woman_shrugging:

**Comment by SomberNight** [comment]
@matejcik maybe the inputs (`prev_txes`) themselves are large, due to being batched exchange withdrawals/etc. That would not show up in the byte-size of the transaction, but they are still sent to the device for utxo validation due to how the sighash works. Still, note that these users are saying there is a difference between electrum 4.4.6 and 4.5.x, and I think that translates to a difference between trezorlib 0.13.4 and 0.13.8.

**Comment by SomberNight** [comment]
> Could there be a prblem with the wallet file when it is converted?

Downgrades are not implemented, if that's what you mean -- but the wallet db upgrades should not be related to this issue.

**Comment by matejcik** [comment]
I just went through the commits and there is no difference in btc signing, in fact the file btc.py is barely touched at all. Unless this is a very subtle side effect of, i dunno, changing _some other_ protobuf message, I don't think that's it.
(I'd be curious to see if someone can reproduce it with Electrum 4.5.0 and manually downgraded trezorlib 0.13.4)

> maybe the inputs (`prev_txes`) themselves are large, due to being batched exchange withdrawals/etc

Possible, but the prevouts also get split into individual inputs and outputs. The "bytes overflow" problem must be on a level of a single problematic protobuf message.

There's `trezorlib.log.enable_debug_output(handler=??)` that would be callable in Electrum console. but by default the handler goes to stderr. @SomberNight is there a good place where to direct the log output so that the users can see it?
or @italianbtc1 could you run Electrum from terminal to look at its output?

**Comment by SomberNight** [comment]
>> maybe the inputs (prev_txes) themselves are large, due to being batched exchange withdrawals/etc
>
> Possible, but the prevouts also get split into individual inputs and outputs. The "bytes overflow" problem must be on a level of a single problematic protobuf message.

Could it be due to this line? And one of the prevout txs containing a jpeg in one their inputs :D
https://github.com/spesmilo/electrum/commit/eef9680743e8a7ab6ad760c68ea63c396532bd65#diff-2881a772e94070a1569d653bbbe84089a71ea96168cfc3f8edd5206862620b5fR431

**Comment by matejcik** [comment]
possibly!
not even a jpeg, what I'm reading [here](https://medium.com/coinmonks/on-bitcoin-transaction-sizes-97e31bc9d816) says that the witness size could be 253 bytes for a 2-of-3 multisig. dunno where the 109 limit is coming from.

**Comment by SomberNight** [comment]
Ok, it is that line. I can reproduce. My 2of3 multisig test wallet simply needed UTXOs that are two-levels deep in its own history, previously all utxos were freshly externally sent to it from a singlesig.

```
txin.witness=bytes.fromhex("040047304402207145e41ec9223d37861695b11528cd39cc9cea0fbb5f1bd1839b89413d9251e802206e87965355321575f917eaf92ca4d0d07ad2da6e61f22580476ae07259f49bd80147304402201983c575e7480ee38d58c08db1df93f294539d5ef7e09ded16ddfd1c34722b3c02205d09b7016c59cdb8c9be49c5fe000718c12c0171b9b34b619220f1732bb3e4210169522102065ec18c1f61fe162e6302bf88dc5ee7fa45217013add36b0c47d19ff23d43fd21035238463af2c7a60d026f11748a0a3a414f3a0adae34a9045dd622c8bd42c946c2103b47b3cf3de7ab12b88dbca22a6bf248c1f63c537dcc47796129a56287c0918f653ae")
```
So it is 252 bytes.
Trezor T can sign it ok, but Trezor One errors. (I guess not surprising as you linked to legacy firmware)

**Comment by SomberNight** [comment]
> dunno where the 109 limit is coming from.

That's the upper limit for the witness of p2wpkh.
`<num_witness_items> <len(sig)> <sig> <len(pubkey)> <pubkey>`, it comes out to 3+73(high-S and high-R)+33.

**Comment by italianbtc1** [comment]
So, what should I do so i can make it work on the latest electrum update?

**Comment by SomberNight** [comment]
The fix is on the master branch and will be included in the next release.
If you don't want to run from source, you can wait for the next release, or go back to 4.4.6 for the time being.

**Comment by goodc0re** [comment]
Same issue, RuntimeError('DataError: bytes overflow') Trezor One, no multisig, spending a single segwit utxo, Electrum 4.5.2, MacOS 14.3.1 (23D60) on Apple M3 Max.

**Comment by SomberNight** [comment]
The issue arises if either the tx to be signed has segwit multisig inputs, or one level deeper, if any of the direct parent txs has segwit multisig inputs.

I guess one of the inputs you are trying to spend was created by a transaction (prev_tx/parent_tx) where at least some of the inputs were using segwit multisig. (e.g. someone paid you who was using multisig)
If you are willing to share which UTXO you are trying to spend, I can double-check this is the case and explain it using that specific example.

You can try with the master branch to see if the issue is fixed.

**Comment by italianbtc1** [comment]
Hi, 

Has this issue been fixed? Can I now use the new electrum version?

**Comment by SomberNight** [comment]
4.5.3 and later should have the fix, yes.
