### ISSUE TITLE
Electrum 4.5.0 or higher not starting anymore because of proxy config value

### ISSUE THREAD

**Issue by YorVeX** [spesmilo/electrum#8837]
Just tried updating from 4.4.6 to 4.5.2, but after the installation Electrum doesn't start anymore, nothing happens. Tried 4.5.1 and 4.5.0 too, same problem, then installed 4.4.6 again and Electrum could be started. So I enabled logging there, once more updated to 4.5.2 and now I can see this in the logs:

```
20240120T171446.593475Z |    ERROR | __main__ | 
Traceback (most recent call last):
  File "run_electrum", line 441, in main
  File "run_electrum", line 456, in handle_cmd
  File "electrum\util.py", line 481, in do_profile
  File "electrum\daemon.py", line 418, in __init__
  File "electrum\network.py", line 328, in __init__
  File "electrum\network.py", line 521, in _init_parameters_from_config
  File "electrum\simple_config.py", line 86, in _get_config_value
AssertionError: got None for key='proxy'
```

Checking the config file indeed there is a line `"proxy": none,`, after deleting this line Electrum 4.5.2 is now starting. Given that it wasn't me putting that config value there but the program itself, I am wondering a bit why not more people have this problem, at least I didn't find any matching existing GH issue or anything with Google. I've been using Electrum for many years now, maybe it's a config value from a really old version that I had still in there, so it would only affect users who have been constantly updating their Electrum for a very long time?

**Comment by ralforle** [comment]
Hello, I've got the same problem here. I use the appImage downloaded from electrum.org for quite some time.
But since version 4.5.0 these don't work any more with this AssertionError.
Within the appImage I cannot set any configuration files so this error seems to be within the electrum code itself.
I'm also wondering that there are not more people complaining about this error. 
So far I have to stick to electrum 4.4.6, which is the latest version I can run on my system.

**Comment by SomberNight** [comment]
@ralforle there is no state stored in the appimage. The config file is [in the datadir](https://electrum.readthedocs.io/en/latest/faq.html#where-is-the-electrum-datadir-located).

**Comment by SomberNight** [comment]
> I am wondering a bit why not more people have this problem, at least I didn't find any matching existing GH issue or anything with Google. I've been using Electrum for many years now, maybe it's a config value from a really old version that I had still in there, so it would only affect users who have been constantly updating their Electrum for a very long time?

I suspect to trigger this, one would have had to
- start using electrum before version 3.1 (2018-03)
- change the proxy settings to some proxy
- change the proxy settings to no proxy
- then upgrade to version 3.1 or later, which has commit https://github.com/spesmilo/electrum/commit/04a1809969a24f7fc176aa505b7fed807e55ad4e
- keep using the same data directory since
- upgrade to version 4.5

So yeah, thanks for being a long-time user. :)  I will try to come up with a non-ugly fix.

**Comment by tkedwards** [comment]
I had this problem with the Flatpak-installed version of Electrum. Needed to delete this line from ~/.electrum/config

`"proxy": null,`
