### ISSUE TITLE
Linux Appimage does not work with text interface

### ISSUE THREAD

**Issue by diego-treitos** [spesmilo/electrum#8844]
When launching Electrum Appimage with

```shell
$ electrum gui -g text -w mywallet
  1.43 | W | daemon.Daemon | Ignoring parameter 'wallet_path' for daemon. Use the load_wallet command instead.
  1.46 | E | daemon.Daemon | GUI raised exception: ModuleNotFoundError("No module named 'pyperclip'"). shutting down.
  1.46 | E | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "/tmp/.mount_electrQ3ExrG/usr/bin/electrum", line 458, in handle_cmd
    d.run_gui()
  File "/tmp/.mount_electrQ3ExrG/usr/lib/python3.10/site-packages/electrum/daemon.py", line 614, in run_gui
    gui = __import__('electrum.gui.' + gui_name, fromlist=['electrum'])
  File "/tmp/.mount_electrQ3ExrG/usr/lib/python3.10/site-packages/electrum/gui/text.py", line 9, in <module>
    import pyperclip
ModuleNotFoundError: No module named 'pyperclip'
```

This happens in the current latest version (`4.5.2`) but also in previous versions like `4.4.6` and some more.

**Comment by SomberNight** [comment]
Indeed. commit 43ab4a779afa339c5295aa1bab61c3915d2df2b9 introduced "pyperclip" as a dependency for the prototype "text" gui, and this is not packaged for any of the binaries.

First of all, note that the text gui is just a toy/prototype gui.

Not sure if we really care about having it in the appimage. (It never worked with the win/mac binaries AFAIR.)
Still, we previously decided to include ncurses in the appimage for it (https://github.com/spesmilo/electrum/commit/9117ded1cdbb06823d0304324da1abe11bc638bc), and made it work there.

As pyperclip is a small library, and is pure-python, if we wanted to, we could just vendor it in source. See https://github.com/spesmilo/electrum/commit/9117ded1cdbb06823d0304324da1abe11bc638bc
Alternatively, we would need to list it in `contrib/requirements/requirements-binaries-appimage.txt` -- though that file does not exist yet, due to no prior need for it. (but e.g. `requirements-binaries-mac.txt` exists)

Alternatively we could just ignore this. It is not really important.

**Comment by accumulator** [comment]
Currently it indeed is a toy/prototype and including `pyperclip` doesn't make it a fully functional UI yet.
I don't see us changing that soon due to limited man-hours available.

However I think there's a certain charm to having a text/terminal UI available. Also it can help in refining the front-end/back-end boundary.

As for win/mac support, there's https://github.com/Textualize/textual which looks interesting
