### ISSUE TITLE
Trezor-T fails to sign PSBT after join/combine operations

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#8868]
When doing a join/combine operation on multiple unsigned PSBTs, attempts to sign the resultant PSBT fails with the stacktrace listed below.

## Creation

1. Initialize the Trezor-T hardware wallet as instructed in `mk-psbt.sh` (attached)
2. Create three `testnet` wallet files using Trezor one for P2PKH, P2SH-Segwit, P2WPKH.
3. Load each wallet file ~ 1M sat each
4. Use `payto` to make three PSBTs each with one input and the same output (see `mk-psbt.sh`)
5. Open the P2WPKH wallet file in the Desktop GUI ensuring good connectivity to Trezor
6. From the GUI load the unsigned `segwit.psbt` file created earlier
7. Use the combine operation to join/combine inputs and outputs from the other two PSBTs
8. Attempt to sign the PSBT and note the failure.

## Electrum Log / Stacktrace

```
20240205T002142.104544Z |     INFO | plugin.DeviceMgr | getting client for keystore
20240205T002142.104544Z |     INFO | plugin.DeviceMgr | end client for keystore
20240205T002142.246621Z |     INFO | plugin.DeviceMgr | getting client for keystore
20240205T002142.247621Z |     INFO | plugin.DeviceMgr | end client for keystore
20240205T002142.252620Z |    ERROR | gui.qt.main_window.[slip-14-pp-tz-noln] | on_error
Traceback (most recent call last):
  File "electrum\gui\qt\util.py", line 1047, in run
  File "electrum\wallet.py", line 2550, in sign_transaction
  File "electrum\plugins\trezor\trezor.py", line 96, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx)
  File "electrum\plugin.py", line 406, in wrapper
  File "electrum\plugin.py", line 399, in run_in_hwd_thread
  File "concurrent\futures\_base.py", line 458, in result
  File "concurrent\futures\_base.py", line 403, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "electrum\plugins\trezor\trezor.py", line 304, in sign_transaction
    inputs = self.tx_inputs(tx, for_sig=True, keystore=keystore)
  File "electrum\plugins\trezor\trezor.py", line 361, in tx_inputs
    assert desc
AssertionError
```

## Environment

* OS: Windows 10 22H2 / WSL2 Ubuntu 22.04.2 Jammy
* Electrum: Standalone v4.5.2 / Source v4.5.2
* Hardware: Trezor-T firmware v2.6.4
* Attachment: [psbt-error.tar.gz](https://github.com/spesmilo/electrum/files/14160039/psbt-error.tar.gz)

**Comment by SomberNight** [comment]
related https://github.com/spesmilo/electrum/issues/8325

**Comment by SomberNight** [comment]
Just pushed https://github.com/spesmilo/electrum/commit/87214c004ef06579e1ddc81e1d20fae1b13a40f9, now you get a better error message :P
`RuntimeError: ProcessError: Unverifiable external input.`
I guess it is coming from the firmware.

**Comment by matejcik** [comment]
Yup that's #8325 all right. Trezor will refuse to sign its input unless the other inputs are already signed, or have ownership proof. Thus leading to a chicken-and-egg problem.

**Comment by SomberNight** [comment]
Ok, then I will close this as duplicate.

**Comment by brianddk** [comment]
> Ok, then I will close this as duplicate.

I may have made my case poorly.  I was able to find a way to get the firmware to sign the TXN, just not using Electrum.  Attached is a python script using the trezor python library to do it.

@matejcik Is there a better wording you think I can use?

* Attachments: [sign_tx.py.gz](https://github.com/trezor/trezor-firmware/files/14183970/sign_tx.py.gz)

**Comment by SomberNight** [comment]
- The trezor firmware enforces that all inputs that belong to the same bip32 root seed are signed in the same signing session.
- If you want to sign external inputs, you need to provide proofs to the device that they do not belong to the same bip32 root seed.

> Attached is a python script using the trezor python library to do it.

That script can work because all inputs belong to the same bip32 root seed and they are all marked as such and provided in a single signing session to the device.

In the OP, when using Electrum, you tried to sign a 3-input tx where only one of the inputs is shown to the device as belonging to the bip32 seed, and the other two inputs are external (technically they too belong to the same bip32 seed but the electrum wallet you are trying to sign with does not know this, so it tells the device firmware that they are external inputs (what you would see in e.g. a coinjoin)).

To support signing with external inputs, https://github.com/spesmilo/electrum/issues/8325 is needed. i.e. Electrum needs to provide proofs to the device firmware that the external inputs do not belong to the same bip32 seed.
However, note that in the OP, in your example, these inputs actually do belong to the same bip32 seed, so valid proofs cannot be constructed.

To do what you want with Electrum, we would need to support the creation of a single wallet file that includes and recognises as is-mine all these addresses at the various derivation paths with their mixed script types. Hopefully this will be possible in the future but atm it is not.
