### ISSUE TITLE
Password protected Electrum wallet that says "Not encrypted''

### ISSUE THREAD

**Issue by Multibituser** [spesmilo/electrum#902]
My Electrum default_wallet (that I had no idea was password protected) has a password on it that I cannot figure out. But, when you click on the lock in the lower right-hand corner, it says "Your keys are not encrypted". However, I cannot send anything out of the wallet because it says "wrong password". I don't even get a prompt to input a password--even if I knew what it was! 

![screenshot of whole wallet 2014-10-27 14 jpeg](https://cloud.githubusercontent.com/assets/5903234/4792864/c3306cc2-5de9-11e4-8c6c-1f2b732409d7.png)

![screenshot when clicking on the lock 2014-10-27 14 jpeg](https://cloud.githubusercontent.com/assets/5903234/4792866/c613a490-5de9-11e4-8a3e-42c8111eee9f.png)

![screenshot when trying to send 2014-10-27 14 jpeg](https://cloud.githubusercontent.com/assets/5903234/4792871/c97c08c0-5de9-11e4-9736-5d852052c56e.png)

**Comment by paulmadore** [comment]
So I had a very similar problem, except I had been using a password with an unencrypted wallet all along. For whatever reason my false had been changed to true, and I was unable to do anything. After I changed it back to false, the problem was solved. But I was definitely freaking out for a minute. A large number of my addresses are now highlighted red.
