### ISSUE TITLE
No prompt for seed extension when restoring old 2fa wallet

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#9088]
This was reported [on the forum](https://bitcointalk.org/index.php?topic=5499322.msg64190438#msg64190438). When restoring a wallet with an old style p2sh 2fa seed, clicking on the options button and checking the box to extend the seed with custom words you expect to be prompted to enter the seed extension but that does not happen. Therefore there is no way to restore the wallet. This bug was introduced in version 4.5.3.

Example seed:

`buffalo valley divorce pumpkin gossip bracket bullet page walnut immune crazy pumpkin`

**Comment by SomberNight** [comment]
Ahh.. this is ultimately because of confusion from there being two types of seed overloaded with the "2fa" type,
- pre-2.7 "2fa"
- post-2.7 "2fa"

(and there is also "2fa_segwit" as a third thing)

It is only the first type that cannot have a seed extension. Your example is type2, so yes the wizard should offer it.

The regression is from https://github.com/spesmilo/electrum/pull/8906, where I forgot about this "2fa"-type-overload... (though there was a different less problematic bug in all versions before that, where instead the wizard offered setting a seed extension for both types, and then errored at the very last step when trying to create the wallet file in case of type1)

Thanks a lot for reporting this.
