### ISSUE TITLE
Transfer Did Not Go Through

### ISSUE THREAD

**Issue by joneil907** [spesmilo/electrum#9328]
I received bitcoin from a paper wallet into Electrum and then sent the balance to my Coinbase account but it never went through.  Trying to figure out what happened.

**Comment by consensys-mod** [comment]
> I received bitcoin from a paper wallet into Electrum and then sent the balance to my Coinbase account but it never went through. Trying to figure out what happened.

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Electrum Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by Jerometh-wq** [comment]
Have you able to resolved your issues yet?

**Comment by Direnyy** [comment]
Hello @joneil907  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
