### ISSUE TITLE
BTChip change adresses 

### ISSUE THREAD

**Issue by pecompl** [spesmilo/electrum#957]
In BTChip hardware wallet, after transacion is being made change is going to adresses which isnt visible in change adresses or doesnt belong to wallet.

**Comment by btchip** [comment]
ok, sorry just checked that bug, that one was fun (for some definition of fun) - it happens when you use the hidapi variant of the Python library, which has a special surprise behavior if the first byte of the data being sent is 0. 

TLDR to recover your funds, derive the seed to 44'/128'/0/256/0 and following

Will be fixed in the Python API
