### ISSUE TITLE
cant send money error code U'message :U U Code: -25

### ISSUE THREAD

**Issue by electrumuser** [spesmilo/electrum#962]
what should i do to fix it ?

**Comment by sigmike** [comment]
I get this error on all the servers I tried.

**Comment by ldurback** [comment]
I'm getting the same error.  Also on all servers.

**Comment by ldurback** [comment]
I've tried 20 different servers.  All of them give this error...

**Comment by dabura667** [comment]
This is a generic error.

The likelyhood of everyone here having the same cause is slim to none.

If you want more detailed assistance, post details of the transaction.

**Comment by ldurback** [comment]
How do I get a more detailed error message?

**Comment by ecdsa** [comment]
as @dabura667 said, it's a generic error. if you tried 20 servers without success, then I don't think that the fact it finally worked has anything to do with the server.

**Comment by sigmike** [comment]
My transaction had nothing special as far as I know. The coins originated from an imported private key.

Is there any way for us to provide more information about the transaction?

Can't the generic error message be changed to something more useful?

**Comment by Technologov** [comment]
+1
same problem here !
Can't use my Bitcoins now...

**Comment by ecdsa** [comment]
can someone publish a transaction that causes this error?

**Comment by Technologov** [comment]
Unfortunately I cannot reproduce it today (15.Jan.2015). It was broken yesterday.

**Comment by ecdsa** [comment]
do you know if you used the same server today and yesterday?

**Comment by ecdsa** [comment]
also, was it the same transaction (same recipient, same amount) today and yesterday?

**Comment by Technologov** [comment]
I use "auto-server" today, and tried several servers yesterday and auto. Yesterday nothing worked. But I did not write down which servers I tried to connect to.
And yes, same wallet and same destination BTC address.

**Comment by EagleTM** [comment]
If it happens again, please use electrum.no-ip.org as a server. It has a newer version of bitcoin core running and should possibly give you a more detailled error message than just code -25.

**Comment by alfoncer** [comment]
i used electrum.no-ip.org on osx, same error, nothing detailed.
error: {u'message': '', u'code': -25}

**Comment by EagleTM** [comment]
OK, indeed it seems there is no built in explanation in bitcoind for the error message. Also I couldn't trace the tx in the debug.log (the default log level for debug is less high in 0.10.0)

**Comment by EagleTM** [comment]
The best pointer I could find here is http://bitcoin.stackexchange.com/questions/36104/why-is-my-raw-transaction-non-canonical-getting-error-25-and-being-rejected

There is a note about "You get that obscure RPC error when your tx is using outputs that bitcoind never heard of.". Are people experiencing this error trying to spent relatively new (no confirmation) outputs as inputs for the next transaction?

Other than that, according to that stackexchange post it might be signing problem with (imported?) compressed key, which might be an implementation bug in electrum. It should persists (and not suddenly start to work a day later) - unless of course there's something up with deterministic signing.

**Comment by EagleTM** [comment]
Other than that I've applied the pull-request [Report missing inputs in sendrawtransaction](https://github.com/bitcoin/bitcoin/pull/5418) to electrum.no-ip.org's bitcoind and I get a lot of {u'message': u'Missing inputs', u'code': -26}; while u'code': -25 never gives this error explanation

**Comment by EagleTM** [comment]
To do more debugging please use https://blockchain.info/pushtx and see the error message it gives.

I've tested a dozen error tx u'code': -25 from the past week and got:

Non-canonical signature: unknown hashtype byte 71 (reported once)
An outpoint [sic!] is already spent in [7....]   (all but two errors) 
Attempted OP_DUP on an empty stack (reported once)

Now I cannot tell whether these outputs have eventually been spent or whether this was the error message to begin with, so it would be helpful to debug new -25 errors with blockchain's pushtx

**Comment by sigmike** [comment]
> To do more debugging please use https://blockchain.info/pushtx and see the error message it gives.

How can we make electrum display the raw transaction it tries to send?

I now get the `{u'message': u'Missing inputs', u'code': -26}` error when I use electrum.no-ip.org, and the -25 error on the few other servers I tried.

I'm sending from an imported private key.

**Comment by ecdsa** [comment]
select 'show before broadcast' in your preferences, and you can save the raw tx before sending it

**Comment by EagleTM** [comment]
Apparently "missing inputs" means the longest chain does not know about one of the inputs of the tx, possibly because there has been a re-org or because it's not in the memorypool. Not in the memorypool could be because it has never propaged the network and is in fact unconfirmed (dust for example). Not sure how we'd go about re-org issues - it'd be news to me, but definitely something to look out for.

@sigmike: blockchain pushtx says "An outpoint is already spent in [5....]". I'm not sure how confidential you need to keep this tx or whether it can be published for debugging purposes.

**Comment by sigmike** [comment]
> select 'show before broadcast' in your preferences, and you can save the raw tx before sending it

I don't have this option in the preferences dialog. I'm running 1.9.8. I tried to run 2.0 but I could not install all the dependencies.

> I'm not sure how confidential you need to keep this tx or whether it can be published for debugging purposes.

I'd rather keep it confidential. Since you have many errors like this one I guess most of them are legit requests from electrum clients that thinks these outputs are not spent. So maybe there's enough material to investigate why electrum builds transactions with spent outputs? I have to spend these coins so I'll use another method for now.

**Comment by EagleTM** [comment]
You can grab 2.0 from https://electrum.org/beta/ for the time being (binaries should be released soon). However I'm guessing you'll get the same error "An outpoint is already spent in [5....]" on pushtx, which isn't really helpful at least not for me, because spent outputs (outpoints is just a spelling issue?) should be a different error message in bitcoin core.

**Comment by ecdsa** [comment]
from my server's log, I found several multisig transactions where the input was not signed.
@sigmike  was yout transaction spending a multisig output?

**Comment by sigmike** [comment]
No. I imported a standard private key and tried to spend some coins.

**Comment by ecdsa** [comment]
does the problem still occur with recent versions? 2.0.2

**Comment by sigmike** [comment]
I tried on a new system with electrum 2.0.2 and another private key (the previous one doesn't have any coin left now) and it worked fine.

**Comment by sigmike** [comment]
I haven't had any error since I upgraded to 2.0.2. I guess it's solved.
